### ISSUE TITLE
Does `GPEI` use marginal likelihood maximization or MCMC by default?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1000]
I'm guessing marginal likelihood maximization, but I wanted to be sure since I'm responding to reviewer feedback on https://doi.org/10.26434/chemrxiv-2022-nz2w8.

**Comment by eytan** [comment]
Yes, by default we use MAP on the MLL.  If using SAASBO we do MCMC using NUTS, and an "MCMC" version of EI.

**Comment by eytan** [comment]
By default we use MAP estimation using the MLL.  We only use MCMC inference
(and "MCMC acquisition functions", ala Snoek et al.) for SAASBO models (
https://botorch.org/tutorials/saasbo, where we use NUTS, in particular).
For lower dimensional problems, the GP HPs typically converge pretty
quickly as long as you have a reasonable amount of data, so MAP works
fine.  MCMC with EI with a vanilla RBF/Matern kernel with ~ < 12ish inputs
won't make much of a difference if you've got a halfway reasonable number
of initialization points (e.g., 2*input_dims).

e
