### ISSUE TITLE
"Storage" docs for JSON saving rely on function that doesn't exist

### ISSUE THREAD

**Issue by berkgercek** [facebook/Ax#1002]
As the title says, [this page](https://ax.dev/docs/storage.html) references a function "save" that exists in the ax top level namespace. When I try to run the first line with Ax version 0.2.5.1 I get `ImportError: cannot import name 'save' from 'ax'`

What is the actual way to save an experiment in JSON format?

**Comment by berkgercek** [comment]
Ok, so I've found `ax.storage.json_store.save_json` which seems to be the right method. However if possible I'd like to know how to save an experiment and the model associated with it, along with the data involved in fitting.

**Comment by mpolson64** [comment]
Hi Berk- thanks for bringing this to our attention, and sorry our docs we're out of date! We will get those updated straight away.
As far as saving, please refer to this section of the Service API tutorial for a method of saving your AxClient to json https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL . Upon loading, the model inside will be refit using the data contained within the experiment. If you are using the Developer API, you may follow the instructions in this tutorial instead https://ax.dev/tutorials/gpei_hartmann_developer.html#9.-Save-to-JSON-or-SQL and the same will be true about model re instantiation and fitting. Let me know if you have any other questions.

**Comment by berkgercek** [comment]
Oh excellent, thanks for pointing me to the service tutorial. I didn't see that bit and it's indeed what I'm using. Cheers and thanks for the fast response.
