### ISSUE TITLE
Ax installation issue in macOS

### ISSUE THREAD

**Issue by Sayantan-1996** [facebook/Ax#1011]
I am trying run the custom BOTORCH with Ax. I tried using `conda` method for Ax installation given as:

`conda install pytorch torchvision -c pytorch`

It installs with no error.

When I again run the code it gives:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/bt/kqf88mw53h55m9mj35rkwt6h0000gn/T/ipykernel_52027/3312530531.py in <module>
      2 from contextlib import contextmanager
      3 
----> 4 from ax.utils.testing.mock import fast_botorch_optimize_context_manager
      5 import plotly.io as pio
      6 # Ax uses Plotly to produce interactive plots. These are great for viewing and analysis,

ModuleNotFoundError: No module named 'ax'

```
What am I missing? Thanks.

**Comment by Sayantan-1996** [comment]
When doing 

`pip3 install ax-platform`

`There is a requirement already satiesfied`

```
Requirement already satisfied: ax-platform in ./opt/miniconda3/lib/python3.9/site-packages (0.2.4)
Requirement already satisfied: scikit-learn in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (1.0.2)
Requirement already satisfied: pandas in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (1.4.2)
Requirement already satisfied: typeguard in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (2.13.3)
Requirement already satisfied: jinja2 in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (3.1.1)
Requirement already satisfied: botorch==0.6.2 in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (0.6.2)
Requirement already satisfied: plotly in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (5.7.0)
Requirement already satisfied: scipy in ./opt/miniconda3/lib/python3.9/site-packages (from ax-platform) (1.8.0)
Requirement already satisfied: gpytorch>=1.6 in ./opt/miniconda3/lib/python3.9/site-packages (from botorch==0.6.2->ax-platform) (1.6.0)
Requirement already satisfied: torch>=1.9 in ./opt/miniconda3/lib/python3.9/site-packages (from botorch==0.6.2->ax-platform) (1.11.0)
Requirement already satisfied: multipledispatch in ./opt/miniconda3/lib/python3.9/site-packages (from botorch==0.6.2->ax-platform) (0.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./opt/miniconda3/lib/python3.9/site-packages (from jinja2->ax-platform) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.1 in ./opt/miniconda3/lib/python3.9/site-packages (from pandas->ax-platform) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./opt/miniconda3/lib/python3.9/site-packages (from pandas->ax-platform) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in ./opt/miniconda3/lib/python3.9/site-packages (from pandas->ax-platform) (1.22.3)
Requirement already satisfied: six in ./opt/miniconda3/lib/python3.9/site-packages (from plotly->ax-platform) (1.16.0)
Requirement already satisfied: tenacity>=6.2.0 in ./opt/miniconda3/lib/python3.9/site-packages (from plotly->ax-platform) (8.0.1)
Requirement already satisfied: joblib>=0.11 in ./opt/miniconda3/lib/python3.9/site-packages (from scikit-learn->ax-platform) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./opt/miniconda3/lib/python3.9/site-packages (from scikit-learn->ax-platform) (3.1.0)
Requirement already satisfied: typing_extensions in ./opt/miniconda3/lib/python3.9/site-packages (from torch>=1.9->botorch==0.6.2->ax-platform) (4.1.1)
```

May be some issue with versions.

**Comment by Sayantan-1996** [comment]
Also, another related issue is that when I run this snippet form the BOTORCH with Ax example:

```
from botorch.models.gpytorch import GPyTorchModel
from botorch.utils.containers import TrainingData
from gpytorch.distributions import MultivariateNormal
from gpytorch.kernels import RBFKernel, ScaleKernel
from gpytorch.likelihoods import GaussianLikelihood
from gpytorch.means import ConstantMean
from gpytorch.models import ExactGP


class SimpleCustomGP(ExactGP, GPyTorchModel):

    _num_outputs = 1  # to inform GPyTorchModel API

    def __init__(self, train_X, train_Y):
        # squeeze output dim before passing train_Y to ExactGP
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        self.mean_module = ConstantMean()
        self.covar_module = ScaleKernel(
            base_kernel=RBFKernel(ard_num_dims=train_X.shape[-1]),
        )
        self.to(train_X)  # make sure we're on the right device/dtype

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)

    @classmethod
    def construct_inputs(cls, training_data: TrainingData, **kwargs):
        r"""Construct kwargs for the `SimpleCustomGP` from `TrainingData` and other options.

        Args:
            training_data: `TrainingData` container with data for single outcome
                or for multiple outcomes for batched multi-output case.
            **kwargs: None expected for this class.
        """
        return {"train_X": training_data.X, "train_Y": training_data.Y}
```

It gives:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/bt/kqf88mw53h55m9mj35rkwt6h0000gn/T/ipykernel_52027/3589040403.py in <module>
----> 1 from botorch.models.gpytorch import GPyTorchModel
      2 from botorch.utils.containers import TrainingData
      3 from gpytorch.distributions import MultivariateNormal
      4 from gpytorch.kernels import RBFKernel, ScaleKernel
      5 from gpytorch.likelihoods import GaussianLikelihood

ModuleNotFoundError: No module named 'botorch'
```

But when in my terminal I open python3 command line:

```
(base) Sayantans-MacBook-Air:~ sayantanmandal$ python3
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:27:05) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import botorch
>>> 
```
It means the botorch is installed. I dont understand what is causing this issue.

**Comment by danielcohenlive** [comment]
Are you using a virtual env?  It looks like the python3 command line is not executing in the same environment as your python file.  Can you in both the command line, and a python file where you're failing to import ax/botorch run this and tell me if the results are the same?
```python
import os
print(os.environ['PATH'])
```
Also, are you executing the python file from the same directory you're executing the command line with `python3`?

> But when in my terminal I open python3 command line: ... It means the botorch is installed.

I assume the same is true for ax, right?

**Comment by Sayantan-1996** [comment]
Hi, @danielcohenlive . Very thank you for your reply. When I run:

```
import os
print(os.environ['PATH'])
```

in a terminal python3 command line, in the same directory as the original custom BOTORCH with Ax code, the resultant path is:

`/Users/sayantanmandal/opt/miniconda3/bin:/Users/sayantanmandal/opt/miniconda3/condabin:/usr/local/opt/gettext/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin`

And when I open the BOTORCH with Ax code in jupyter and run the above set of commands, the resultant address is same.

I am not using any activated environment for this, and yes its true for Ax as well.

**Comment by Sayantan-1996** [comment]
> > Also, are you executing the python file from the same directory you're executing the command line with python3?
> 
> One further thought on this, can you share the exact command you execute the python file with? There are some differences in behavior between `python path/to/file.py` and `python -m path.to.file`

I am using it from jupyter

**Comment by Sayantan-1996** [comment]
Let me give the output of when I run :

`python3 custom_botorch_model_in_ax.py` in terminal

Output:

`Traceback (most recent call last):
  File "/Users/sayantanmandal/Downloads/custom_botorch_model_in_ax.py", line 136, in <module>
    from ax import SimpleExperiment
ImportError: cannot import name 'SimpleExperiment' from 'ax' (/Users/sayantanmandal/opt/miniconda3/lib/python3.9/site-packages/ax/__init__.py)`

**Comment by danielcohenlive** [comment]
We deprecated `SimpleExperiment` and removed it a few versions ago.  So _that_ error is expected unless you're using an older version of ax.  I looks like it _does_ have `ax/__init__.py` though.  You should be able to do `from ax import Experiment` in custom_botorch_model_in_ax.py (though you'll have to change the code).  It sounds like the problem only exists in Jupyter?  Can you confirm that you still can't `from ax import Experiment` in Jupyter?

**Comment by danielcohenlive** [comment]
So it sounds like ax _is_ installed in jupyter.  Is there anywhere it still doesn't work?

**Comment by danielcohenlive** [comment]
Sure!  I would probably recommend starting with the [Service API](https://ax.dev/tutorials/gpei_hartmann_service.html) instead of using core ax components (like `Experiment`), which we refer to as the developer API.  But I know nothing about what you're trying to do, so it's hard to give further recommendations.  Is this a field experiment you're running on real users?  Is it something you can run without a human in the loop?  Is there a chance that the same parameters/inputs could give different results at different times?  Could you just include a general description of what you want to do?

Also, as far as I know `SimpleExperiment` was removed from our docs several months ago and you sound either new to Ax, or maybe you're just on a new machine.  Where did you get `SimpleExperiment` from?  Just want to make sure we're not missing something.  🙏🙏

**Comment by Sayantan-1996** [comment]
Well, what I am trying to do is run a numerical glacier model. Since it is numerical it involves differential equations translated in the code in algebraic form. There are three parameters which acts as decision variables. These will be up in the parameter search space definition. Basically I am modifying the `branin` function in `custom_botorch_model_in_ax.py`, to take `y=rmse(modelled_out-observed). Earlier in 2021 the older version of `custom_botorch_model_in_ax.py` was used by me to achieve this. And yes now my machine is different and even during earlier usage I didnt go much into `ax` working and documentation. So its both.

No human is required in the loop. 

Yes the model can give different output with same parameters as it is heavily depended on what input guess values we provide it. 

`SimpleExperiment` was in the earlier versions of `custom_botorch_model_in_ax.py`

**Comment by Sayantan-1996** [comment]
Let me narrow down my problem even further more consider the below lines:

`from botorch.models.gpytorch import GPyTorchModel
from botorch.utils.containers import TrainingData
from gpytorch.distributions import MultivariateNormal
from gpytorch.kernels import RBFKernel, ScaleKernel
from gpytorch.likelihoods import GaussianLikelihood
from gpytorch.means import ConstantMean
from gpytorch.models import ExactGP


class SimpleCustomGP(ExactGP, GPyTorchModel):

    _num_outputs = 1  # to inform GPyTorchModel API

    def __init__(self, train_X, train_Y):
        # squeeze output dim before passing train_Y to ExactGP
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        self.mean_module = ConstantMean()
        self.covar_module = ScaleKernel(
            base_kernel=RBFKernel(ard_num_dims=train_X.shape[-1]),
        )
        self.to(train_X)  # make sure we're on the right device/dtype

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)

    @classmethod
    def construct_inputs(cls, training_data: TrainingData, **kwargs):
        r"""Construct kwargs for the `SimpleCustomGP` from `TrainingData` and other options.

        Args:
            training_data: `TrainingData` container with data for single outcome
                or for multiple outcomes for batched multi-output case.
            **kwargs: None expected for this class.
        """
        return {"train_X": training_data.X, "train_Y": training_data.Y}

from ax.models.torch.botorch_modular.model import BoTorchModel
from ax.models.torch.botorch_modular.surrogate import Surrogate


ax_model = BoTorchModel(
    surrogate=Surrogate(
        # The model class to use
        botorch_model_class=SimpleCustomGP,
        # Optional, MLL class with which to optimize model parameters
        # mll_class=ExactMarginalLogLikelihood,
        # Optional, dictionary of keyword arguments to model constructor
        # model_options={}
    ),
    # Optional, acquisition function class to use - see custom acquisition tutorial
    # botorch_acqf_class=qExpectedImprovement,
)

from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models


gs = GenerationStrategy(
    steps=[
        # Quasi-random initialization step
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
        ),
        # Bayesian optimization step using the custom acquisition function
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            # For `BOTORCH_MODULAR`, we pass in kwargs to specify what surrogate or acquisition function to use.
            model_kwargs={
                "surrogate": Surrogate(SimpleCustomGP),
            },
        ),
    ]
)

import torch
from ax.service.ax_client import AxClient
from ax.service.utils.instantiation import ObjectiveProperties
#from botorch.test_functions import Branin


# Initialize the client - AxClient offers a convenient API to control the experiment
ax_client = AxClient(generation_strategy=gs)
# Setup the experiment
ax_client.create_experiment(
    name="branin_test_experiment",
    parameters=[
        {
            "name": "x1",
            "type": "range",
            # It is crucial to use floats for the bounds, i.e., 0.0 rather than 0.
            # Otherwise, the parameter would be inferred as an integer range.
            "bounds": [-5.0, 10.0],
        },
        {
            "name": "x2",
            "type": "range",
            "bounds": [0.0, 15.0],
        },
        {
            "name": "x3",
            "type": "range",
            "bounds": [0.0, 15.0],
        }
       
    ],
    objectives={
        "branin": ObjectiveProperties(minimize=True),
    },
)
`
Output:

`[INFO 06-24 17:10:59] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 06-24 17:10:59] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x1. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-24 17:10:59] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x2. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-24 17:10:59] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x3. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 06-24 17:10:59] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='x1', parameter_type=FLOAT, range=[-5.0, 10.0]), RangeParameter(name='x2', parameter_type=FLOAT, range=[0.0, 15.0]), RangeParameter(name='x3', parameter_type=FLOAT, range=[0.0, 15.0])], parameter_constraints=[]).`

Next lines of codes:

`def glacier(parameterization, *args):
#def glacier(parameterization):
         x1, x2, x3 = parameterization["x1"], parameterization["x2"], parameterization["x3"]
     #y = (x2 - 5.1 / (4 * np.pi ** 2) * x1 ** 2 + 5 * x1 / np.pi - 6) ** 2
     #y += 10 * (1 - 1 / (8 * np.pi)) * np.cos(x1) + 10
         with open('params.txt', 'r') as f:
                 h = f.readlines()[0].split()
                 f.close()
         open('params.txt', 'w').close()
         with open('params.txt', 'w') as f:
                 f.write(" ".join([h[0], h[1], h[3],str(x1), str(x2), str(x3)]))
                 f.close()
         print('A wait time of 40 seconds...')
         sleep(40)
         eng = matlab.engine.start_matlab()
         eng.gepangath_semi_explicit(nargout=0)
         eng.quit()
         print('Matlab run is complete')
         print('A wait time of 50 seconds...')
         sleep(50)
         y = mr.RmSe()
         print(f"y is:{y}")
 #let's add some synthetic observation noise
     #y += random.normalvariate(0, 0.1)
         return {"branin": (y, 0.0)}

branin = glacier()`

Output:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [26], in <cell line: 1>()
----> 1 branin = glacier()

TypeError: glacier() missing 1 required positional argument: 'parameterization'`

For convenience sake I have am calling my function glacier (which is calling the matlab code) and storing its value in branin.

**Comment by danielcohenlive** [comment]
everything looks good up until the line `branin = glacier()`.  It looks like `glacier` is basically your evaluator.  So you can substitute it in to the code in the [Run optimization loop](https://ax.dev/tutorials/gpei_hartmann_service.html#4.-Run-optimization-loop) section, and it would look like:
```
for i in range(25):  # 25 or whatever number of iterations you want
    parameters, trial_index = ax_client.get_next_trial()
    # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=glacier(parameters)) # 'glacier' instead of 'evaluate'
```

**Comment by Sayantan-1996** [comment]
Great, @danielcohenlive , its working fine, Thanks for your patience with me. I will close this issue now. Thanks again.

**Comment by danielcohenlive** [comment]
I'm going to close this issue.  Feel free to reopen it or create another issue if you need more help!
