### ISSUE TITLE
Batch (Multi-trials) evaluation in Service API performance 

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#1019]
Hello, 

As proposed in a precedent issue, I'm using 
parameters, trial_index = ax_client.get_next_trials(max_trials=5)
in Service API to get 5 trials at the same time and evaluate them (the generation strategy is set to Models.GPEI).

Is it equivalent to using batch Expected Improvement in BOTorch in terms of performance (convergence speed of the optimization) ? (Reading the comments in the BOTorch tutorial, it seems not )
 If not, how can I use batch Expected Improvement in Service API ?
 
Thanks

**Comment by eytan** [comment]
Yes, batch EI is used under the hood when doing parallel optimization in
ax. In particular, we use qNEI from BoTorch.

**Comment by Kh-im** [comment]
That's great ! Thanks for your answer

**Comment by Balandat** [comment]
The default in the service API is actually to use EI with sequential conditioning rather than solving the full `d * q` (where `q` is the number of trials) dimensional problem as in qNEI. This has regret guarantees and usually works better in practice due the optimization problem being easier.

**Comment by lena-kashtelyan** [comment]
This seems resolved; please reopen if you have any follow-ups, @Kh-im!
