### ISSUE TITLE
what is status quo? and why is it necessary if we set objective threshold in Multi objective setting?

### ISSUE THREAD

**Issue by ayushi-3536** [facebook/Ax#1043]

**Comment by ayushi-3536** [comment]
Is it ok if we generate any random sample over the search space and set it as default? How does it impact optimization?
I am mainly targeting qehvi, qNEHVI and QNpargo

**Comment by mpolson64** [comment]
Thank you for reaching out. In the context of multi objective optimization the objective thresholds and status quo can often be seen as equivalent concepts. You should only need to provide objective thresholds to use Ax for MOO.

Could you provide a little more context on the problem you're trying to solve, and what your code looks like (snippets, link to tutorial your basing your code off, etc)?

**Comment by ayushi-3536** [comment]
Hey, Thanks for getting back quickly. I realize the problem was using non-relative threshold. will close this issue. Have an another question: Does qehvi, qnehvi handle hierarchical space?

**Comment by mpolson64** [comment]
I have answered in [the original thread](https://github.com/facebook/Ax/issues/1042) to help keep things searchable. Closing this issue out for now, we can discuss further in the other Issue :)
