### ISSUE TITLE
Must the comparison for outcome constraint always be <= ?

### ISSUE THREAD

**Issue by hsm207** [facebook/Ax#107]
In the [Service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html), it is mentioned that:

> outcome_constraints should be a list of strings of form "constrained_metric <= some_bound".

But in the [outcome_constraint_from_str](https://github.com/facebook/Ax/blob/4bff1bba558aa0b92763f23ab019d245108f37a0/ax/service/utils/instantiation.py#L214-L231) function we have this assertion:

```
   assert len(tokens) == 3 and tokens[1] in COMPARISON_OPS, (
        "Outcome constraint should be of form `metric_name >= x`, where x is a "
        "float bound and comparison operator is >= or <=."
    )
```
Does this mean the comparison operator for an outcome constraint can be either >= or <= and that the tutorial is outdated?

**Comment by sdsingh** [comment]
The tutorial is outdated, you should be able to use either '>=' or '<=' as the comparison operator--will update.
