### ISSUE TITLE
Flaky failures in building scheduler tutorial in nightly cron due to plotting with callback

### ISSUE THREAD

**Issue by esantorella** [facebook/Ax#1074]
We have seen the nightly cron sometimes fail and sometimes not lately. I ran it with more informative errors ([results](https://github.com/facebook/Ax/runs/7867439449?check_suite_focus=true)) and found that this happens when we attempt to make a plot during ongoing optimization when there isn't yet data to plot with. This is kind of like a race condition. I have a PR to fix this incoming shortly.

Proposed fix:
- When we generate the callback [here](https://github.com/facebook/Ax/blob/40714956c1849ac11350fcbf7a72a2aa41f939a4/ax/service/utils/report_utils.py#L662), put the call to `plot_fn` inside of a try/except, catching `RuntimeError`s. If it fails, log the warning and proceed without updating the plot. In general, we probably don't to kill optimization just because of an issue with plotting.
- In the plotting function defined in the tutorial notebook `scheduler.ipynb`, raise a `RuntimeError` if there is no data to plot with.

**Comment by Balandat** [comment]
Thanks for catching this. A larger though there is that since the callback can come from anywhere, it may be quite risky to always fail the full scheduled loop if the callback fails. So another option would be to give the `Scheduler` an option (say `fail_on_callback_error`) to always call `try/except` on the callback calls that way. Wdyt?

**Comment by esantorella** [comment]
Yeah, currently it will continue optimizing if it gets a `RuntimeError` but not if it gets any other kind of error, which is pretty arbitrary. I think having a `fail_on_callback_error` option that allows `try/except` on any error makes sense.

**Comment by Balandat** [comment]
One could potentially be more granular and allow catching only specific failures (e.g. by providing a tuple of exception classes or even some regex exception parsing stuff- I think @bernardbeckerman has done similar things in the past). But that might be overkill for now and we can stick with something simple. 

Maybe sth like the following is a good compromise:
```
# this would be a part of `SchedulerOptions`
catch_callback_errors: Tuple[type, ...] = (),  # could also do # (Exception,) as the default
```

and then in the scheduler loop we do sth like
```
try:
    callback()
except scheduler_options.catch_callback_errors as e:
    warnings.warn(f"Callback raised exception: {str(e)}.")
```
