### ISSUE TITLE
Import Error using Azure DataBricks

### ISSUE THREAD

**Issue by sennettleung** [facebook/Ax#1107]
Hi there,

I am trying to use ax-client to find the best hyperparameters for my neural network model, and I encountered this import error as shown in the link below. I used to be able to access the package okay, but it's not working now. I have installed all the dependency libraries onto the cluster, so am unsure why I'm still running into this error, using the pip install bleeding edge version of the package also didn't help resolve the issue. Any help is much appreciated, thank you!

Screenshot of the dependencies I have installed:
![image](https://user-images.githubusercontent.com/99122662/188015808-f45d54d4-fc8e-4697-b230-e50ac32a9376.png)

Screenshot of the error I encountered whilst trying to import the package (both lines output the same error message):
![image](https://user-images.githubusercontent.com/99122662/188015460-96a9b742-fb5b-4052-bac8-202a88483295.png)

**Comment by saitcakmak** [comment]
Hi @sennettleung! I assume you're using gpytorch 1.9.0 here? That is currently not supported in Ax/BoTorch (will be supported in next release). If you downgrade to GPyTorch 1.8.1 things should work again.

**Comment by Balandat** [comment]
Related botorch issue: https://github.com/pytorch/botorch/issues/1370

I am planning to release a version early next week to to fix this.

**Comment by sennettleung** [comment]
Hi there,

Thank you both for the update and solution, I've tried to run this command
'pip install torch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1 torchtext==0.9.1'
 (please correct me if I'm wrong), but I'm now encountering another error in which one of the solutions is to upgrade pytorch? 

Please find screenshot of the error I'm seeing below: 

![image](https://user-images.githubusercontent.com/99122662/188090379-3acfd357-08f9-4970-b45d-2f9eff3526cf.png)

Not sure if I'm going in circles here, thank you for your support in advance!

**Comment by sennettleung** [comment]
Hi both,

That's great, downgrading seemed to have worked, thank you for the update and workaround! :)

**Comment by lena-kashtelyan** [comment]
We're looking into cutting new version now, which should address this.

**Comment by saitcakmak** [comment]
This should be resolved in the just-released 0.2.7 version.
