### ISSUE TITLE
MySQL vs. MongoDB

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1124]
I have some basic familiarity with MongoDB, but practically none with SQL. The context is creating an example that stores experimental data from [SDL-Demo](https://github.com/sparks-baird/self-driving-lab-demo) via [an additional example notebook](https://github.com/sparks-baird/self-driving-lab-demo/blob/main/notebooks/README.md). I've been using Ax for some of the examples (e.g. https://github.com/sparks-baird/self-driving-lab-demo/blob/main/notebooks/3.1-random-vs-grid-vs-bayesian.ipynb), and I remember that Ax has some database integration. Would you recommend learning MySQL / SQLite to use the built-in functionality or creating a custom storage system that utilizes MongoDB? If I chose the latter, any recommendations on how to approach this?

**Comment by danielcohenlive** [comment]
Thanks for the question @sgbaird!  Ax's storage works pretty out of the box without you having to learn any SQL or SQLAlchemy.  So I'd suggest just using that.  The Service API handles saving and loading to the database for you, provided you give it a [DBSetting](https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL) and the developer api works through [`save_experiment()` and `load_experiment()`](https://ax.dev/tutorials/gpei_hartmann_developer.html#9.-Save-to-JSON-or-SQL).  It stores experiments, trials, generation strategies, aggregated data on the trial, etc...  What it does not store is individual data points, so if you need to store those you probably want to design your own system around that.

If you need to inspect ax's database or have another application interact with it, my personal bias is that SQL isn't _that_ bad, but I'll leave the decision of whether to use it up to you.

**Comment by danielcohenlive** [comment]
I'm going to close this for now, but feel free to follow up

**Comment by sgbaird** [comment]
> Thanks for the question @sgbaird! Ax's storage works pretty out of the box without you having to learn any SQL or SQLAlchemy. So I'd suggest just using that. The Service API handles saving and loading to the database for you, provided you give it a [DBSetting](https://ax.dev/tutorials/gpei_hartmann_service.html#7.-Save-/-reload-optimization-to-JSON-/-SQL) and the developer api works through [`save_experiment()` and `load_experiment()`](https://ax.dev/tutorials/gpei_hartmann_developer.html#9.-Save-to-JSON-or-SQL). It stores experiments, trials, generation strategies, aggregated data on the trial, etc... What it does not store is individual data points, so if you need to store those you probably want to design your own system around that.

Thanks for clarifying this! That's good to know that Ax abstracts some of the SQL-specific knowledge away. The kind of information you mentioned sounds great and I think would be plenty for me, especially considering the underlying datapoints will be available by accessing the trial information. Related to this, do you know if there's a way of attaching arbitrary dictionaries (e.g. that contain mixtures of floats and strings as values) to one of those objects in a way that it will be saved? Or even just a few extra string values. Technically I could probably use the experiment name. Sort of like adding extra metadata, though maybe that fits into the category of designing my own system like you mentioned.

> If you need to inspect ax's database or have another application interact with it, my personal bias is that SQL isn't _that_ bad, but I'll leave the decision of whether to use it up to you.

The ability to store arbitrary JSON data in MongoDB is still compelling to me based on my background and familiarity, but later on, I might explore SQL a bit more. For now, I'll probably stick with Ax's built-in storage.

**Comment by danielcohenlive** [comment]
> Related to this, do you know if there's a way of attaching arbitrary dictionaries (e.g. that contain mixtures of floats and strings as values) to one of those objects in a way that it will be saved?

The ax [experiment](https://github.com/facebook/Ax/blob/main/ax/core/experiment.py#L107) and [trial](https://github.com/facebook/Ax/blob/main/ax/core/base_trial.py#L258) objects have an `_properties` field which is that arbitrary dictionary you're looking for.  They will both save to their respective `properties` columns in their database tables.

**Comment by danielcohenlive** [comment]
I'm going to close this again, but, again, feel free to follow up : )

**Comment by sgbaird** [comment]
@danielcohenlive do you know of any SQL options similar to [MongoDB Atlas](https://www.mongodb.com/docs/atlas/tutorial/deploy-free-tier-cluster/) that offers a free tier cluster? (i.e. something compatible with Ax)

**Comment by danielcohenlive** [comment]
Sorry for the late response @sgbaird... Ax should be compatible with any db SQAlchemy is compatible with (see https://www.sqlalchemy.org/features.html#:~:text=Supported%20Databases,of%20which%20support%20multiple%20DBAPIs.). Clever cloud and ElephantSQL look promising as Ax usually doesn't need a lot of concurrent connections, unless you're building some huge app on top of it.

**Comment by lena-kashtelyan** [comment]
@sgbaird, please do reopen issues if you follow up : ) Very hard to find/notice the follow-ups otherwise.
