### ISSUE TITLE
"Ax must be installed!" although it has been installed already.

### ISSUE THREAD

**Issue by HNossrati** [facebook/Ax#1126]
Trying to use Ray[Tune] with Ax-platform getting this error, even when running Ray's official example for the Ax. 
Please tell me if you need any more details about the system setup and code. 

![Capture](https://user-images.githubusercontent.com/22433913/189886201-7c788017-4192-4c3f-b458-8efb2751774e.PNG)
![Capture1](https://user-images.githubusercontent.com/22433913/189886230-9150b90f-5b2d-4fd8-961e-5a93d5739bec.PNG)

**Comment by HNossrati** [comment]
Solved 
gpytorch version must be 1.8.1
but "pip install ax-platform" installs 1.9.0, which conflicts with the ax library.

**Comment by Balandat** [comment]
This is not an issue with raytune, it's that the botorch version that Ax is pinned to is not pinned to a gpytorch version but gpytorch 1.9.0 (the latest release) is not compatible with that botorch version (but it is with the latest botorch version) so during installation we end up with a version incompatibility between botorch and gpytorch. That raises an import error that is masked by the try/except. The solution is to release a new Ax version that pins to a botorch version compatible with gpytorch 1.9.0.

**Comment by danielcohenlive** [comment]
> The solution is to release a new Ax version that pins to a botorch version compatible with gpytorch 1.9.0.

@Balandat so a botorch release needs to happen first?

**Comment by saitcakmak** [comment]
> a botorch release needs to happen first?

It happened last week :) https://github.com/pytorch/botorch/releases/tag/v0.7.0

**Comment by Martin-Molinero** [comment]
Hello! saw 0.2.7 was released on gh but it's not on released on `pip` yet. Curious if it will be? and if there's an ETA, thanks!

**Comment by saitcakmak** [comment]
Version 0.2.7(.2 to be precise) is now available on pypi!
