### ISSUE TITLE
Incompatibility between Ax and latest `pandas` (`ValueError: columns cannot be a set`)

### ISSUE THREAD

**Issue by lambertsbennett** [facebook/Ax#1153]
I am new to Ax and trying to run the tutorial examples on the webpage however I keep getting the same error: 

[INFO 09-20 15:06:48] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x2. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 09-20 15:06:48] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x3. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 09-20 15:06:48] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x4. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 09-20 15:06:48] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x5. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 09-20 15:06:48] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x6. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 09-20 15:06:48] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='x1', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='x2', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='x3', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='x4', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='x5', parameter_type=FLOAT, range=[0.0, 1.0]), RangeParameter(name='x6', parameter_type=FLOAT, range=[0.0, 1.0])], parameter_constraints=[ParameterConstraint(1.0*x1 + 1.0*x2 <= 20.0)]).
[INFO 09-20 15:06:48] ax.modelbridge.dispatch_utils: Using Bayesian optimization since there are more ordered parameters than there are categories for the unordered categorical parameters.
[INFO 09-20 15:06:48] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 12 trials, GPEI for subsequent trials]). Iterations after 12 will take longer to generate due to  model-fitting.
[INFO 09-20 15:06:48] ax.service.managed_loop: Started full optimization with 30 steps.
[INFO 09-20 15:06:48] ax.service.managed_loop: Running optimization trial 1...
[ERROR 09-20 15:06:48] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "c:\Users\__\Anaconda3\envs\ax\lib\site-packages\ax\service\managed_loop.py", line 227, in full_run
    self.run_trial()
  File "c:\Users\__\Anaconda3\envs\ax\lib\site-packages\ax\utils\common\executils.py", line 161, in actual_wrapper
    return func(*args, **kwargs)
  File "c:\Users\__\Anaconda3\envs\ax\lib\site-packages\ax\service\managed_loop.py", line 201, in run_trial
    trial = self._get_new_trial()
  File "c:\Users\__\Anaconda3\envs\ax\lib\site-packages\ax\service\managed_loop.py", line 159, in _get_new_trial
    generator_run=self.generation_strategy.gen(
  File "c:\Users\___\Anaconda3\envs\ax\lib\site-packages\ax\modelbridge\generation_strategy.py", line 334, in gen
    return self._gen_multiple(
  File "c:\Users\___\Anaconda3\envs\ax\lib\site-packages\ax\modelbridge\generation_strategy.py", line 457, in _gen_multiple
    self._fit_or_update_current_model(data=data)
  File "c:\Users\___\Anaconda3\envs\ax\lib\site-packages\ax\modelbridge\generation_strategy.py", line 513, in _fit_or_update_current_model
...
    self._df = pd.DataFrame(columns=self.required_columns())
  File "c:\Users\___\Anaconda3\envs\ax\lib\site-packages\pandas\core\frame.py", line 639, in __init__
    raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?014a3a59-3b6a-46a9-923b-8bc09868c3f5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [3], line 1
----> 1 best_parameters, values, experiment, model = optimize(
      2     parameters=[
      3         {
      4             "name": "x1",
      5             "type": "range",
      6             "bounds": [0.0, 1.0],
      7             "value_type": "float",  # Optional, defaults to inference from type of "bounds".
      8             "log_scale": False,  # Optional, defaults to False.
      9         },
     10         {
     11             "name": "x2",
     12             "type": "range",
     13             "bounds": [0.0, 1.0],
     14         },
     15         {
     16             "name": "x3",
     17             "type": "range",
     18             "bounds": [0.0, 1.0],
     19         },
     20         {
     21             "name": "x4",
     22             "type": "range",
...
    641 if copy is None:
    642     if isinstance(data, dict):
    643         # retain pre-GH#38939 default behavior

ValueError: columns cannot be a set

This error happens in two different conda environments that I have tried with. One with Python 3.8.0 and torch 1.12.1. The other is Python 3.10.4 and torch 1.12.1. I have a feeling it is something simple that I don't quite understand. 

Thanks for any help!

**Comment by lambertsbennett** [comment]
Thanks, downgrading to pandas 1.4.0 seems to have done the trick.

**Comment by Pedrexus** [comment]
I am still facing this issue on the latest ax-platform build with python 3.11 while working on this https://github.com/facebookresearch/hydra/pull/2489#issuecomment-1774194949

Any updates?
