### ISSUE TITLE
Is there a tutorial or doc on using the GP in TorchModelBridge outside of optimization loop?

### ISSUE THREAD

**Issue by acb-code** [facebook/Ax#1165]
Hi, I'm trying to compare the model predictions to a true analytic function at the end of a bayesian optimization loop.

When I use: `out = get_standard_plots(exp, model_bridge_with_GPEI)` I get a plot that looks as expected for `out[1]`

However, for working in more detail with plotting I'd like to access and use the GP model directly to make predictions. When I use
```
# test data inputs
x_test = torch.linspace(0,1,200)

# predictions
final_model = model_bridge_with_GPEI.model
mu_test, cov_tes

t = final_model.predict(x_test)
```
 to try and get predictions, and plot via 
```
f, ax = plt.subplots(1, 1, figsize=(4, 3))
# mean prediction from surrogate
ax.plot(x_test.numpy(), mu_test.numpy())
```
I get a plot that is scaled differently to the slice plot from the `standard_plots` output. 

Is there a normalization/scaling layer that needs to be exported from the experiment as well?

I've included the plotting differences below
![output](https://user-images.githubusercontent.com/69542078/192067557-f1c70d80-ab6a-4f05-a2ff-f759461ebac0.png)
![ax_al_attempt](https://user-images.githubusercontent.com/69542078/192067206-403fc79a-1f7d-4b2f-b5e4-1a4622dbb7a7.png)
Thanks!

**Comment by saitcakmak** [comment]
Hi @acb-code. `model_bridge_with_GPEI.model.model` should get you the BoTorch `Model`. For GPEI, this will be a `FixedNoiseGP` or a `SingleTaskGP`, which are both defined in https://github.com/pytorch/botorch/blob/main/botorch/models/gp_regression.py. To get the predictions from these models, you need to use the `posterior` call, which is defined here: https://github.com/pytorch/botorch/blob/main/botorch/models/gpytorch.py#L307-L314.

**Comment by saitcakmak** [comment]
Re the two plots being on different scales: The reason for this is `TorchModelBridge` standardizes the observations before fitting the model. When you call `final_model.predict(x_test)`, you're accessing the standardized predictions. To get the unstandardized predictions, you should use `model_bridge_with_GPEI.predict` instead: https://github.com/facebook/Ax/blob/main/ax/modelbridge/base.py#L494

**Comment by acb-code** [comment]
I see! Thank you for the quick response!

**Comment by acb-code** [comment]
Actually, @saitcakmak, a quick follow up. The `model_bridge_with_GPEI.predict` call asks for observation features as the input type. Looking in the documentation for `ObservationFeatures`, it's not clear to me what the constructor process would be for this prediction case.

How do I construct an `ObservationFeatures` object starting with the simple test values of `torch.linspace(0,1,100)`? 

Otherwise, using `model_bridge_with_GPEI.model.surrogate.posterior(x_test)` I still get the scaled response, so for that approach it seems I need to export the scaler.

**Comment by saitcakmak** [comment]
For getting the predictions, you just need to initialize the `ObservationFeature` with a parameterization, which is a dict mapping the parameter name to the value. So, in your case, something like this should work.
```
obs_feats = [ObservationFeature(parameters={"x0": value.item()}) for value in torch.linspace(0,1,100)]
model_bridge_with_GPEI.predict(observation_features=obs_feats)
```

> Otherwise, using model_bridge_with_GPEI.model.surrogate.posterior(x_test) I still get the scaled response, so for that approach it seems I need to export the scaler.

Yeah, you'd need to look at the transforms on `model_bridge_with_GPEI` and untransform according to the scaling stored in the `StandardizeY` transform.

**Comment by acb-code** [comment]
Perfect! Thanks for the help!
