### ISSUE TITLE
Feature request for subplots.

### ISSUE THREAD

**Issue by john-michaelburke** [facebook/Ax#1176]
We have been working with the plot_pareto_frontier feature to generate 3x 2D Pareto Frontier plots which get rendered on different pages in a browser via the render function. We wanted to merge these to be rendered on a single page and share a color scale based on the Arm major integer. This required a lot of manual hacking away at the AxPlotConfig data to feed to plotly to generate a figure which could then be used to generate a new AxPlotConfig GENERIC type. Although something specific to our case would be an appreciated feature, I could see a lot of value in adding a generic way for embedding AxPlotConfigs into subplots.

**Comment by mpolson64** [comment]
Thank you for the suggestion! You're right -- there is some work we could do to make our plotting a little more friendly. I am going to mark this Issue as a wishlist item for now and we'll do our best to get this done :)
