### ISSUE TITLE
How can I use HeteroskedasticSingleTaskGP with AxClient?

### ISSUE THREAD

**Issue by Song-Hyeong-Yun** [facebook/Ax#1188]
I want to use `HeteroskedasticSingleTaskGP` instead `SingleTaskGP`.
However, An error occurred when `HeteroskedasticSingleTaskGP` was inserted instead of `SingleTaskGP.`
I have already questioned this issue in #1077, but it seems that I couldn't get an answer because I couldn't reopen the issue.
I'll rewrite the error here.

I attached and completed trials like this.
`[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 170, 'CT': 700} as trial 0.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 0 with data: {'yield': (208.8, 15.061374)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 170, 'CT': 700} as trial 1.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 1 with data: {'yield': (230.1, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 115, 'CT': 700} as trial 2.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 2 with data: {'yield': (170.4, 1.979899)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 115, 'CT': 700} as trial 3.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 3 with data: {'yield': (167.6, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 150, 'CT': 700} as trial 4.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 4 with data: {'yield': (197.1, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 190, 'CT': 700} as trial 5.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 5 with data: {'yield': (191.4, 2.404163)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 190, 'CT': 700} as trial 6.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 6 with data: {'yield': (188.0, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 210, 'CT': 700} as trial 7.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 7 with data: {'yield': (200.1, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 250, 'CT': 700} as trial 8.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 8 with data: {'yield': (167.8, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 170, 'CT': 450} as trial 9.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 9 with data: {'yield': (110.9, 10.0)}.

[INFO 10-04 10:24:48] ax.service.ax_client: Attached custom parameterization {'wt': 25, 'DT': 170, 'CT': 300} as trial 10.
[INFO 10-04 10:24:48] ax.service.ax_client: Completed trial 10 with data: {'yield': (123.7, 10.0)}.`

However, the problem occurs when I use:

parameters, trial_index = ax_client.get_next_trial()

The error message says this:
`---------------------------------------------------------------------------
TypeError Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16124\518108282.py in
1 for i in range(2):
----> 2 parameters, trial_index = ax_client.get_next_trial()

~.conda\envs\BoTorch\lib\site-packages\ax\utils\common\executils.py in actual_wrapper(*args, **kwargs)
145 )
146 time.sleep(wait_interval)
--> 147 return func(*args, **kwargs)
148
149 # If we are here, it means the retries were finished but

~.conda\envs\BoTorch\lib\site-packages\ax\service\ax_client.py in get_next_trial(self, ttl_seconds, force)
464 try:
465 trial = self.experiment.new_trial(
--> 466 generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
467 )
468 except MaxParallelismReachedException as e:

~.conda\envs\BoTorch\lib\site-packages\ax\service\ax_client.py in _gen_new_generator_run(self, n)
1553 n=n,
1554 pending_observations=self._get_pending_observation_features(
-> 1555 experiment=self.experiment
1556 ),
1557 )

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\generation_strategy.py in gen(self, experiment, data, n, pending_observations, **kwargs)
336 n=n,
337 pending_observations=pending_observations,
--> 338 **kwargs,
339 )[0]
340

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\generation_strategy.py in _gen_multiple(self, experiment, num_generator_runs, data, n, pending_observations, **kwargs)
453 self.experiment = experiment
454 self._maybe_move_to_next_step()
--> 455 self._fit_or_update_current_model(data=data)
456
457 # Make sure to not make too many generator runs and

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\generation_strategy.py in _fit_or_update_current_model(self, data)
509 self._update_current_model(new_data=new_data)
510 else:
--> 511 self._fit_current_model(data=self._get_data_for_fit(passed_in_data=data))
512 self._save_seen_trial_indices()
513

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\generation_strategy.py in _fit_current_model(self, data)
655 logger.debug(f"Fitting model with data for trials: {trial_indices_in_data}")
656
--> 657 self._curr.fit(experiment=self.experiment, data=data, **model_state_on_lgr)
658 self._model = self._curr.model_spec.fitted_model
659

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\generation_node.py in fit(self, experiment, data, search_space, optimization_config, **kwargs)
131 search_space=search_space,
132 optimization_config=optimization_config,
--> 133 **kwargs,
134 )
135

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\model_spec.py in fit(self, experiment, data, **model_kwargs)
128 experiment=experiment,
129 data=data,
--> 130 **combined_model_kwargs,
131 )
132

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\registry.py in call(self, search_space, experiment, data, silently_filter_kwargs, **kwargs)
345 data=data,
346 model=model,
--> 347 **bridge_kwargs,
348 )
349

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\torch.py in init(self, experiment, search_space, data, model, transforms, transform_configs, torch_dtype, torch_device, status_quo_name, status_quo_features, optimization_config, fit_out_of_design, objective_thresholds, default_model_gen_options)
108 status_quo_features=status_quo_features,
109 optimization_config=optimization_config,
--> 110 fit_out_of_design=fit_out_of_design,
111 )
112

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\base.py in init(self, search_space, model, transforms, experiment, data, transform_configs, status_quo_name, status_quo_features, optimization_config, fit_out_of_design, fit_abandoned)
181 search_space=search_space,
182 observation_features=obs_feats,
--> 183 observation_data=obs_data,
184 )
185 self.fit_time = time.time() - t_fit_start

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\torch.py in _fit(self, model, search_space, observation_features, observation_data)
134 search_space=search_space,
135 observation_features=observation_features,
--> 136 observation_data=observation_data,
137 )
138

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\array.py in _fit(self, model, search_space, observation_features, observation_data)
106 search_space_digest=search_space_digest,
107 metric_names=self.outcomes,
--> 108 candidate_metadata=candidate_metadata,
109 )
110

~.conda\envs\BoTorch\lib\site-packages\ax\modelbridge\torch.py in _model_fit(self, model, Xs, Ys, Yvars, search_space_digest, metric_names, candidate_metadata)
202 search_space_digest=search_space_digest,
203 metric_names=metric_names,
--> 204 candidate_metadata=candidate_metadata,
205 )
206

~.conda\envs\BoTorch\lib\site-packages\ax\models\torch\botorch_modular\model.py in fit(self, Xs, Ys, Yvars, search_space_digest, metric_names, target_fidelities, candidate_metadata, state_dict, refit)
202 candidate_metadata=candidate_metadata,
203 state_dict=state_dict,
--> 204 refit=refit,
205 )
206

~.conda\envs\BoTorch\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py in fit(self, training_data, search_space_digest, metric_names, candidate_metadata, state_dict, refit)
276 training_data=training_data,
277 metric_names=metric_names,
--> 278 **dataclasses.asdict(search_space_digest),
279 )
280 if state_dict:

~.conda\envs\BoTorch\lib\site-packages\ax\models\torch\botorch_modular\surrogate.py in construct(self, training_data, **kwargs)
226
227 # pyre-ignore [45]
--> 228 self._model = self.botorch_model_class(**formatted_model_inputs)
229
230 def fit(

TypeError: init() missing 1 required positional argument: 'train_Yvar'`

I don't know why this error occurs because it seems that noise is properly included in the completed trial.
How can I fix this problem?
Please help me.
Thank you so much in advance!

**Comment by bernardbeckerman** [comment]
Hi @Song-Hyeong-Yun, thanks for raising this! I've re-opened your original issue and am closing this one out to keep discussion all in one place. Please comment there.
