### ISSUE TITLE
No pip install for Windows

### ISSUE THREAD

**Issue by bash-j** [facebook/Ax#119]
If I run `pip install ax-platform` on Windows, it installs version 0.0.0. Can we please have whl files for Windows users who don't have build tools installed on their machines?

**Comment by kkashin** [comment]
Thanks for raising this issue @bash-j, and sorry about the lack of Windows wheels. We're going to discuss this early next week & let us circle back around to you with ETA for having this up.

**Comment by sdsingh** [comment]
@bash-j, you should see a 0.1.3 `whl` file present now, for Python 3.7! Please try running `pip install ax-platform` now :) 

If you need Python 3.6, that should be out later today.

**Comment by bash-j** [comment]
Thank you @sdsingh

I was able to install it today in a 3.7 environment.
