### ISSUE TITLE
`AxClient.get_best_trial(use_model_predictions=False)` never finds point satisfying outcome constraints

### ISSUE THREAD

**Issue by olivierkeke** [facebook/Ax#1225]
This problem seems to be solved when replacing 
https://github.com/facebook/Ax/blob/b0fe0c52179e417e1b34b55131a23d9297afd4e4/ax/service/utils/best_point.py#L697
by
```
 return ~name_match_mask | (observed_upper_bound > oc.bound)
```
and
https://github.com/facebook/Ax/blob/b0fe0c52179e417e1b34b55131a23d9297afd4e4/ax/service/utils/best_point.py#L699
by
```
 return ~name_match_mask | (observed_lower_bound < oc.bound)
```

**Comment by bernardbeckerman** [comment]
Closing this out since the PR is now closed. Thanks for identifying this issue!
