### ISSUE TITLE
'ChoiceParameter' is not iterable

### ISSUE THREAD

**Issue by AndrewFalkowski** [facebook/Ax#1229]
Trying to optimize from a series of choice parameters and keep getting an error that these choice parameters are not iterable. My parameter structure appears to be in line with what I have seen in these [examples](https://ax.dev/versions/0.1.0/tutorials/building_blocks.html), so I am not sure where the issue is coming from. 

Analogous dummy code provided below:

```
from ax.service.managed_loop import optimize
from ax.utils.notebook.plotting import render, init_notebook_plotting
from ax.core import ChoiceParameter, ParameterType
from ax.service.utils.instantiation import ObjectiveProperties
from ax.service.ax_client import AxClient

ax_client = AxClient()

materials_param = ChoiceParameter(name="materials_input", values=["config1", "config2", "config3"], parameter_type=ParameterType.STRING)

size_param1 = ChoiceParameter(name="size1", values=[0,20,30,40,45], parameter_type=ParameterType.INT)
size_param2 = ChoiceParameter(name="size2", values=[0,20,30,40,45], parameter_type=ParameterType.INT)
size_param3 = ChoiceParameter(name="size3", values=[0,20,30,40,45], parameter_type=ParameterType.INT)

ax_client.create_experiment(
    name="dummy_optimization",
    parameters=,
    objectives={"outcome": ObjectiveProperties(minimize=False)},
    overwrite_existing_experiment=True,
)

best_parameters, values, experiment, model = optimize(
    parameters=[materials_param, size_param1, size_param2, size_param3],
    evaluation_function=evaluateMaterial,
    objective_name='mean_SS',
    minimize=True,
    total_trials=30,
)

```

**Comment by danielcohenlive** [comment]
Hi @AndrewFalkowski , thanks for posting your question.  Your code is combining 2 of our paradigms, the [dev api](https://ax.dev/versions/0.1.0/tutorials/gpei_hartmann_developer.html) and [service api](https://ax.dev/versions/0.1.0/tutorials/gpei_hartmann_service.html).  

`ax_client.create_experiment()` actually wants a list of dictionaries for `parameters`.  I would recommend using the service api.  You can check out the [**Set up experiment** section](https://ax.dev/versions/0.1.0/tutorials/gpei_hartmann_service.html#2.-Set-up-experiment) for more details.

**Comment by AndrewFalkowski** [comment]
Thank you @danielcohenlive, that was where I was going wrong. However, I seem to have encountered a few other issues in the use of choice params during optimization.

I am consistently getting a warning that `ax.modelbridge.transforms.int_to_float is unable to round my parameterization to meet the constraints of the search space`. This only seems to occur when a SOBOL generated point violates a parameter constraint. This may not be an issue in the grand scheme of the optimization, however. Is there a way to apply a parameter constraint to the initial point generation procedure?

Additionally, I am consistently having optimizations fail due to a `KeyError` that I am not sure how to resolve. This only occurs during the SOBOL trials, and at random points. If the model makes it to the GPEI stage, then it will run as expected. Any insight into why this might be occurring?
```
KeyError                                  Traceback (most recent call last)
c:\Users\Andrew~~ in line 90
     88 for i in range(50):
     89     print(f"Running trial {i+1}/50...")
---> 90     parameters, trial_index = ax_client.get_next_trial()
     91      # Local evaluation here can be replaced with deployment to external system.
     92     ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))

File c:\Users\Andrew~~\lib\site-packages\ax\utils\common\executils.py:161, in retry_on_exception.<locals>.func_wrapper.<locals>.actual_wrapper(*args, **kwargs)
    157             wait_interval = min(
    158                 MAX_WAIT_SECONDS, initial_wait_seconds * 2 ** (i - 1)
    159             )
    160             time.sleep(wait_interval)
--> 161         return func(*args, **kwargs)
    163 # If we are here, it means the retries were finished but
    164 # The error was suppressed. Hence return the default value provided.
    165 return default_return_on_suppression

File c:\Users\Andrew~~\lib\site-packages\ax\service\ax_client.py:480, in AxClient.get_next_trial(self, ttl_seconds, force)
    476         raise OptimizationShouldStop(message=global_stopping_message)
    478 try:
    479     trial = self.experiment.new_trial(
--> 480         generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
    481     )
...
    117             pval: int = obsf.parameters[p_name]
--> 118             obsf.parameters[p_name] = reverse_transform[pval]
    119 return observation_features

KeyError: 3

```

Finally, I get a number of optimization failures resulting from  a `scipy.minimize` error (see below).
```
Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 9.')]
Trying again with a new set of initial conditions.
```
I believe this may be the result of categorical variables that produce plateaus in the observation landscape, which generally hinder solvers. Wondering if you have any experience in mitigating this issue?

**Comment by danielcohenlive** [comment]
Can you post your code again?  It's a little hard to tell what's going on with out seeing that
