### ISSUE TITLE
Metric Registry Question (Hash changes between environments)

### ISSUE THREAD

**Issue by AustinGomez** [facebook/Ax#1235]
Hi, I'm looking to save an experiment with a custom Metric to SQL. I've registered the metric, saved it, and it's been saved in the DB with `metric_type = 74810`.

I'm creating my SQAConfig like so:
```
bundle = RegistryBundle(
    metric_clss={MyMetric: None},
    runner_clss={MyRunner: None},
)

config = SQAConfig(
    json_encoder_registry=bundle.encoder_registry,
    json_decoder_registry=bundle.decoder_registry,
    metric_registry=bundle.metric_registry,
    runner_registry=bundle.runner_registry,
)
```

When I try to load my experiment I getting the following error: 

```
ax.exceptions.storage.SQADecodeError: Cannot decode SQAMetric because 74810 is an invalid type. ATTENTION: There have been some recent changes to Metric/Runner registration in Ax. Please see https://ax.dev/tutorials/gpei_hartmann_developer.html#9.-Save-to-JSON-or-SQL for the most up-to-date information on saving custom metrics.

```
It seems that the hash has changed, because the `config.reverse_metric_registry` contains  `{59305: <class 'mymodule.MyMetric'>, 1: <class 'ax.core.metric.Metric'>}`.

If I'm understanding correctly, to fix this I can either manually set the hash seed (which doesn't scale well across environments), or I can set the type manually when creating the registry. Is the latter approach ok? I'm scared there may be "gotchas" down the road if I set manually. 

I.E.:
```
bundle = RegistryBundle(
    metric_clss={MyMetric: 2, ...},
    runner_clss={MyRunner: 2,  ...},
)

config = SQAConfig(
    json_encoder_registry=bundle.encoder_registry,
    json_decoder_registry=bundle.decoder_registry,
    metric_registry=bundle.metric_registry,
    runner_registry=bundle.runner_registry,
)
```

Thanks in advance

**Comment by bernardbeckerman** [comment]
@AustinGomez thank you for raising this here, and sorry for taking so long to get back to you! Would you please provide the code used to load the experiment as well? Thank you!

**Comment by mpolson64** [comment]
Hi @AustinGomez. Go ahead and set that int manually, so you'll wind up with:
```
bundle = RegistryBundle(
    metric_clss={MyMetric: 74810},
    runner_clss={MyRunner: 12345},
)
```

Manually setting is actually the preferred (and safer!) way to go about things, so no need to be worried about gotchas down the line. By setting manually you're protecting yourself from changes to the hash -- providing `None` and using the classes hash is just a shortcut some of our users requested when we implemented this feature.

Also, feel free to use `bundle.sqa_config` instead of manually constructing your `SQAConfig` from the bundle contents; they are equivalent.

**Comment by AustinGomez** [comment]
Glad to hear it won't cause any problems, and thanks for the SQAConfig tip (that was taken from the registry example in the docs btw)
