### ISSUE TITLE
Plotting Acquisition Function

### ISSUE THREAD

**Issue by yyexela** [facebook/Ax#1236]
Hello, I'm getting acquainted with using Ax's Modular BOTorch capabilities for my research project and was wondering if there is a way to plot the acquisition function after some observations for my model? There doesn't seem to be an option for it in [ax.plot](https://ax.dev/api/plot.html). Thanks!

**Comment by yyexela** [comment]
Further, there is [this notebook](https://botorch.org/tutorials/GIBBON_for_efficient_batch_entropy_search) from BoTorch's tutorials which plots various acquisition functions but I'm unable to get it to work from Ax's classes. Thanks again!

**Comment by yyexela** [comment]
Here's a simple example of plotting expected improvement on some dummy data:

```python
# Imports
import numpy as np
import matplotlib.pyplot as plt
import torch

from botorch.acquisition import ExpectedImprovement
from botorch.models import FixedNoiseGP

# We know that the best f is 0
best_f = 0

# Set up parameters to EI
train_X = torch.rand(200, 1)
train_Y = torch.sin(train_X).sum(dim=1, keepdim=True)
train_Yvar = torch.full_like(train_Y, 0.2)

# Define our model
model = FixedNoiseGP(train_X, train_Y, train_Yvar)

# Define acquisition function
EI = ExpectedImprovement(model, best_f=best_f, maximize=False)

# Define points at which we'll evaluate the acquisition function
x_eval = np.linspace(0,1,101)

# Transform input to something EI expects
EI_x_eval = torch.tensor(np.expand_dims(np.expand_dims(x_eval,1),1), dtype=torch.float)
y_eval = EI(EI_x_eval)

# Make y_eval plot-able
y_eval = y_eval.detach().numpy()

# Make our plots
fig, ax = plt.subplots(1,2, figsize=(7,4))

ax[0].plot(x_eval, y_eval, color='black')
ax[0].set_title("EI")
ax[1].plot(train_X, train_Y, marker='x', linestyle='none', color='black')
ax[1].set_title("Data")
plt.show()
```

What I want to do is take my BoTorchModular model:

```python
    model = BoTorchModel(
        # Optional
        botorch_acqf_class=qExpectedImprovement,
        #botorch_acqf_class=qKnowledgeGradient
        surrogate=Surrogate(
            botorch_model_class=FixedNoiseGP,
        )
    )
```

and somehow extract the inner acquisition function and plot it similar to the above example.

**Comment by yyexela** [comment]
Okay! So I have something working:
I define a point I want to get evaluate the acquisition function at as follows:

```python
a = arm.Arm({'x': x_eval[i]})
b = observation.ObservationFeatures.from_arm(a)
```

And then I can get the acquisition function evaluation at that point as follows:

```python
My_model_bridge.evaluate_acquisition_function([b])[0]
```

As such, I'm now able to make a plot of the acquisition function. So, I'm now wondering if this is the correct way to do this? Furthermore, are there any plans to make plotting the acquisition function a default feature with/without Plotly? Thanks a lot for all of your hard work in Ax/BoTorch! (I have attached my notebook to this comment if anyone wants to take a deeper look into this!)

[modular.zip](https://github.com/facebook/Ax/files/9924243/modular.zip)

**Comment by yyexela** [comment]
Figured this out as well! Though I am still interested in someone's thoughts as to how end-users are expected to access low-level information from Bayesian Optimization with Ax. Thanks!

[modular.zip](https://github.com/facebook/Ax/files/10119011/modular.zip)

**Comment by bernardbeckerman** [comment]
`ModelBridge.evaluate_acquisition_function` is the right way to go and should allow users to access EI from Ax. As of now there is no plan to automate the plotting of EI, but I believe you have everything you need to plot it now, is that correct? Closing this out for now but please let us know if you require further followup!
