### ISSUE TITLE
Register custom GP class to registry for saving to json

### ISSUE THREAD

**Issue by thschaer** [facebook/Ax#1245]
I have a simple custom GP class, similar to the tutorial

```
#Custom GP class, inherits from a general GPyTorch model from BoTorch and the ExactGP model from GPyTorch
class SimpleCustomGP(ExactGP, GPyTorchModel):
    _num_outputs = 1  # to inform GPyTorchModel API
    def __init__(self, train_X, train_Y):
        # squeeze output dim before passing train_Y to ExactGP
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        self.mean_module = ConstantMean()
        #Kernel can be customised
        self.covar_module = ScaleKernel(
            base_kernel=MaternKernel(nu=2.5),
        )
        self.to(train_X)  # make sure we're on the right device/dtype
    #returns multivariatenormal with prior mean and covariance evaluated at x
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)
```

and would like to save my ax_client to json with `ax_client.save_to_json_file("test.json")`, however I get the ValueError 

```
Class "SimpleCustomGP" not in Type[Model] registry, please add it. BoTorch object registries are located in "ax/storage/botorch_modular_registry.py".
```

What is the proper procedure for adding my custom class to the registry?
Thank you for your help

**Comment by thschaer** [comment]
The solution that I have come to so far is:

```
from ax.storage.botorch_modular_registry import MODEL_REGISTRY
from ax.storage.botorch_modular_registry import REVERSE_MODEL_REGISTRY

MODEL_REGISTRY.update({SimpleCustomGP:"SimpleCustomGP"})
REVERSE_MODEL_REGISTRY.update({"SimpleCustomGP":SimpleCustomGP})
ax_client.save_to_json_file()
```

And to load:
`ax_client = AxClient().load_from_json_file()`

Is this the best way? It requires me to have initialised the SimpleCustomGP before loading which is a bit suboptimal. Did I miss documentation on this somewhere?

Thank you and best regards

**Comment by bernardbeckerman** [comment]
Hi @thschaer and thank you for raising this here! Let me follow up internally to see the best person to ask about this.

**Comment by mpolson64** [comment]
Hi @thschaer -- what you have is actually exactly right. Storage of custom torch components is a difficult task and improving this flow has been on the team's wishlist for a while now. For now what you have is the best way to do things, and we hope to continue making Ax easier to use for both simple and complex use cases in the future :)
