### ISSUE TITLE
Announcement: Changes to Metric API

### ISSUE THREAD

**Issue by mpolson64** [facebook/Ax#1253]
In Ax 0.2.9 we made some major changes to the way Metrics fetch data. [Taking inspiration from Rust](https://doc.rust-lang.org/std/result/), `Metric.fetch_trial_data()` not returns a `MetricFetchResult`, which can encode either Data or a python Exception. You can read more in the release notes.

This change allows us to defer raising exceptions until the Results are "unwrapped" at usage time. For example, in the Scheduler we unwrap results before generating new candidates, and if there was an error in fetching we either mark the offending trial as FAILED or keep going (depending on the importance of the metric) rather than halting the entire experiment. While the Data is still "wrapped" in the Result we can still do many operations like (mapping)[https://github.com/facebook/Ax/blob/main/ax/utils/common/result.py#L47] or put the Results into containers like Lists and Dicts, as we do in the Metric itself for `fetch_experiment_data`, `fetch_trial_data_multi`, etc.

The easiest way to update your own custom metrics to be compatible with v0.2.9 is by wrapping the returned Data object with Ok from `ax.utils.common.result`, but if you would like to take advantage of the more sophisticated exception deferral you will need to use try/except blocks and Errs. You can see the (Scheduler tutorial)[https://ax.dev/tutorials/scheduler.html] on our website for details.

If you have any questions about this change please do not hesitate to ask them under this issue.

**Comment by alxfed** [comment]
Bad idea. Wrong architectural decision. I'm rolling back to the older version.
