### ISSUE TITLE
feature request: Teaching materials

### ISSUE THREAD

**Issue by chanansh** [facebook/Ax#1262]
Hi,
I would like to teach people to use Ax.
Is there a ready class/workshop/video/deck I can use on top of the documentation ?

**Comment by pcanaran** [comment]
@chanansh - Thank you for reaching out. I don't think we have something readily available. We'll review and get back to you.

**Comment by chanansh** [comment]
Thanks, while you are at it, how do I choose which algorithm it uses? Can we have a discord channel for usage questions?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pcanaran** [comment]
@chanansh - Sure, no problem.

Re: which algorithm to use

- For details on models, please refer to https://ax.dev/docs/models.html.
- The optimization algorithms are specified using the GenerationStrategy abstraction. For details on this refer to https://ax.dev/tutorials/generation_strategy.html.
- For any class mentioned in these docs, you can refer to the [API reference](https://ax.dev/api/) for details.

Re: Usage questions

Primarily we use github issues for usage questions. Please feel free to create issues as needed. I recommend separate issues for distinct issues as it would make managing them easier.

**Comment by sgbaird** [comment]
Incidentally, I'm preparing a recorded set of Ax tutorials to be used as teaching materials. While I have some of my own content, much of it comes directly from the [Ax tutorials](https://ax.dev/tutorials/) and [BoTorch tutorials](https://botorch.org/tutorials/). If you can wait up to a couple of days, I'm planning to complete it and have it uploaded very soon👍

**Comment by Balandat** [comment]
> I'm preparing a recorded set of Ax tutorials from a physical sciences perspective to be used as teaching materials

^This is awesome, looking forward to seeing those! 

Last year I gave a [talk about Ax/BoTorch](https://www.youtube.com/watch?v=X_-npBRGRX4&list=PLZ_xn3EIbxZHjt6mOPbvtHzZkWeDL5pHW&ab_channel=GaussianProcessSummerSchool) at the Gaussian Process Summer School: - this isn't really a tutorial but more an overview of how stack came to be, what the main goals and design considerations behind it are, and how we think about it accelerating our research-to-production pipeline. May still be useful and / or interesting.

**Comment by sgbaird** [comment]
@Balandat 

> > I'm preparing a recorded set of Ax tutorials from a physical sciences perspective to be used as teaching materials
> 
> ^This is awesome, looking forward to seeing those!

Thanks! I'll post back when it's ready.

> Last year I gave a [talk about Ax/BoTorch](https://www.youtube.com/watch?v=X_-npBRGRX4&list=PLZ_xn3EIbxZHjt6mOPbvtHzZkWeDL5pHW&ab_channel=GaussianProcessSummerSchool) at the Gaussian Process Summer School: - this isn't really a tutorial but more an overview of how stack came to be, what the main goals and design considerations behind it are, and how we think about it accelerating our research-to-production pipeline. May still be useful and / or interesting.

Thanks for the great resource! I've been going through it 😄 Really nice to get a condensed view of the evolution of the Ax and BoTorch frameworks and specific design decisions that go along with them.

**Comment by lena-kashtelyan** [comment]
> Thanks, while you are at it, how do I choose which algorithm it uses?

This is the function we use to pick the algorithm in Ax Service API (`AxClient`): https://ax.dev/tutorials/generation_strategy.html#1B.-Auto-selected-generation-strategy. Currently looking at its code is probably the best source of info about this auto-selection... https://github.com/facebook/Ax/blob/070f3a6ab064edb96526e68eca3b6322e3664406/ax/modelbridge/dispatch_utils.py#L217. We are aware of the sore need for better documentation on this though and will work on it in 2023.

**Comment by chanansh** [comment]
@Balandat can you share the slides from the talk? I am giving the tutorial tomorrow so if you have last minute tips on what should someone be aware of before using ax.dev please let me know

**Comment by sgbaird** [comment]
@chanansh feedback welcome! Here is [the recording (~3 h)](https://drive.google.com/file/d/1D-BQ0h7INpODkhVUGK5uCS-fqfYzZ-c9/view?usp=sharing) and [slides](https://docs.google.com/presentation/d/1Aw0YwM2IHwRIwzs7aD_DWdpGbJKMWT0g/edit?usp=sharing&ouid=111618553007371874901&rtpof=true&sd=true). Feel free to reuse slides if it makes sense for you, preferably with attribution 😉. Note that the links to Jupyter Notebooks shouldn't work because those were hardcoded on my local filepath system.

**Comment by sgbaird** [comment]
Also, here are the corresponding notebooks:
- https://github.com/sparks-baird/self-driving-lab-demo/tree/main/notebooks/escience

**Comment by chanansh** [comment]
Thanks @sgbaird but I think your material is too advanced. I need some for beginners

**Comment by sgbaird** [comment]
@chanansh thanks for the feedback. When I was first learning, the [simplified API examples](https://ax.dev/docs/api.html) were very useful for me to reference. One possibility would be to take that example and show how to convert it to a different task that either you or the audience is more familiar with.

**Comment by Balandat** [comment]
@chanansh sorry I missed that - hope the tutorial went well. 

Here are the slides from that talk: [20210916 - GPSS Software for Gaussian processes workshop.pdf](https://github.com/facebook/Ax/files/10150647/20210916.-.GPSS.Software.for.Gaussian.processes.workshop.pdf)

**Comment by sgbaird** [comment]
@chanansh interested to see the slide deck / recording if available for the tutorial you gave recently! Would you be willing to share? (see my profile page for my email if you don't want it to be public)

**Comment by bernardbeckerman** [comment]
@chanansh was just reading through this thread and agree, I'd love to see a slide deck, recording, or any other materials you thought were good for beginners! Thanks @sgbaird and @Balandat for sharing your teaching materials as well!

**Comment by chanansh** [comment]
Hi @bernardbeckerman and @sgbaird , thank you for your interest :-)  See enclosed.
[ax.dev intro - public version.pdf](https://github.com/facebook/Ax/files/10318380/ax.dev.intro.-.public.version.pdf)

**Comment by sgbaird** [comment]
@chanansh just went through the slides. Great resource!

**Comment by pcanaran** [comment]
It looks like a number of resources have already been shared on this issue. I'll go ahead an close it. Thanks.
