### ISSUE TITLE
Loop API: optimize

### ISSUE THREAD

**Issue by guocheng2018** [facebook/Ax#127]
What does the wait_time parameter do in optimize function of loop api?

**Comment by lena-kashtelyan** [comment]
@guocheng2018, nothing at the moment, unfortunately –– it is a scheduling option we are planning to add to make the loop wait for a given amount of time after every iteration. It doesn't do anything right now, however, and I'll remove it from the API until it's actually used. Thank you for bringing this up!

**Comment by lena-kashtelyan** [comment]
The `wait_time` kwarg is now removed on master.

**Comment by lena-kashtelyan** [comment]
The `wait_time` kwarg is now removed in the latest stable version, 0.1.5.
