### ISSUE TITLE
how to set tracking_metric_names dynamically

### ISSUE THREAD

**Issue by chanansh** [facebook/Ax#1272]
I have a function `y=objective(x)` which returns a dictionary of metrics `y`, one of which is the metric to optimize and the others are metadata.
I understand I need to tell the experiment class to track those using `tracking_metric_names`. 
However, now every time I update `objective(x)` I need to update the variable `tracking_metric_names`. 
Is there a way to use the output of the first call to `y=objective(x)` to see the output keys and set the `tracking_metric_names=[y.keys()]` accordingly (after experiment was created)? I tried to read the source code but it seems not very accessible to do so, it's not as simple as setting the class property. 

Moreover, it's not clear what `metric_definitions` param does, the documentation is very limited. 

Thanks.

**Comment by danielcohenlive** [comment]
Hi @chanansh, thanks for the question.  Are you following along with our [service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html)?  That's the one I'd recommend unless you're trying to build an application leveraging Ax.

You are going to need a way to give the client a dict with consistent key for your metric when you call `ax_client.complete_trial()`.  Is it possible to wrap your `objective(x)` function in another function which does this?  I'm not entirely clear on what you're running into though, so it might help if you shared the code you're currently running.

> Moreover, it's not clear what metric_definitions param does, the documentation is very limited.

This is likely not applicable to you.  It's for passing key word arguments to special metric classes, which `AxClient` doesn't have by default.

**Comment by chanansh** [comment]
Let me explain:

See code based on the tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html where I added another key to the result of the `evaluate` method.

```
import numpy as np
def evaluate(parameters):
    x = np.array([parameters.get(f"x{i+1}") for i in range(6)])
    # In our case, standard error is 0, since we are computing a synthetic function.
    return {"hartmann6": (hartmann6(x), 0.0), "l2norm": (np.sqrt((x ** 2).sum()), 0.0), "the_ultimate_question_of_life_the_universe_and_everything": 42}
```

When running the optimization loop, one get:
> [INFO 11-22 12:45:52] ax.service.ax_client: Data was logged for metric the_ultimate_question_of_life_the_universe_and_everything that was not yet tracked on the experiment. Please specify `tracking_metric_names` argument in AxClient.create_experiment to add tracking metrics to the experiment. Without those, all data users specify is still attached to the experiment, but will not be fetched in `experiment.fetch_data()`, but you can still use `experiment.lookup_data_for_trial` to get all attached data.

So, one need to add `"the_ultimate_question_of_life_the_universe_and_everything"` to `tracking_metric_names`.
However, I want to do it dynamically, e.g. run the `evaluate` method once and get a result from which I will save the keys `tracking_metric_names = result.keys()`. However, to do so, I need already to start the experiment, since it is an argument of the AxClient.create_experiment function. I would like to update `tracking_metric_names` *after* the experiment has started.

**Comment by danielcohenlive** [comment]
Got it!  We don't have that in the service api, but the good news is you can easily drop into the dev api for that and use [`Experiment.add_tracking_metrics()`](https://github.com/facebook/Ax/blob/main/ax/core/experiment.py#L380).  So this would look something like:
```python
from ax.core import Metric

for i in range(25):
    parameters, trial_index = ax_client.get_next_trial()
    # Local evaluation here can be replaced with deployment to external system.
    result = evaluate(parameters)
    ax_client.complete_trial(trial_index=trial_index, raw_data=result)

    # now we're in the dev API
    new_metrics = [Metric(k) for k in result if k not in ax_client.metric_names]
    ax_client.experiment.add_tracking_metrics(new_metrics)
```

**Comment by chanansh** [comment]
@danielcohenlive  is this published in a version?

**Comment by chanansh** [comment]
@danielcohenlive unfortunately it does not work:
> AttributeError: 'AxClient' object has no attribute 'metric_names'

**Comment by danielcohenlive** [comment]
Sorry, I missed your question @chanansh.  It is in 0.2.10 (https://github.com/facebook/Ax/blob/c6c67d8ab23f1f723622400a5bfc033867f0568a/ax/service/ax_client.py).  Is that the version you're on?  It was added ~2 months ago, so if you're on an older version that might be it.  If you can't update for any reason, you could rewrite the line as 
```
    ax_client.add_tracking_metrics([k for k in result if k not in ax_client.experiment.metrics])
```

**Comment by lena-kashtelyan** [comment]
@chanansh , please do reopen issues if you follow up : ) Very hard to find/notice the follow-ups otherwise.
