### ISSUE TITLE
Optimization failed within `scipy.optimize.minimize` with status 9.

### ISSUE THREAD

**Issue by tanguyen77** [facebook/Ax#1282]
Whenever I run my MOBO script, I get the following warning only after the very last MOBO iteration:

Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 9.')]
Trying again with a new set of initial conditions.

I am not sure what it means but I am guessing the code tries to generate a new set of parameters to try next but fails to do so?
I find it a bit weird that I always get this message only after the very last MOBO run, where I am not expecting a new set of parameters to be proposed. Can anyone help in understanding what this warning means? Thanks in advance!

**Comment by Balandat** [comment]
> I find it a bit weird that I always get this message only after the very last MOBO run, where I am not expecting a new set of parameters to be proposed

I am not sure I understand - could you please post a repro-able example or at least the script that is giving you this error (and the exact error)?

**Comment by lena-kashtelyan** [comment]
@tanguyen77, please follow up with repro of the issue that we can run –– it's not possible for us to debug this without seeing what code you are running.

**Comment by lena-kashtelyan** [comment]
Closing as inactive.
