### ISSUE TITLE
contextual optimization f(x, context)

### ISSUE THREAD

**Issue by chanansh** [facebook/Ax#1298]
let's say I have f(x, context) I would like to find the optimal settings per context, where context is not controlled. context can be controlled is simulation but not in the live system. What would be the best practice approach?

**Comment by bernardbeckerman** [comment]
Hi there, I was able to follow up with some of our researchers on this internally, who pointed me to https://github.com/facebookresearch/ContextualBO, which contains some code to reproduce the results in the linked paper. Please take a look and let me know if this is what you're looking for. Thanks @bletham for the pointer : )

**Comment by lena-kashtelyan** [comment]
Some more potentially useful code for this:

1. Set up a generation strategy:
```
from ax.modelbridge.registry import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=1,
            min_trials_observed=1,
        ),
        GenerationStep(
            model=Models.CONTEXT_SACBO,
            num_trials=-1,
            model_kwargs={"decomposition": {"context1": {"x1_c1": "x2_c1"}, "context2": {"x1_c2": "x2_c2"}}},
        ),
    ]
)
```
2. Use it in place of model in this flow: https://ax.dev/tutorials/gpei_hartmann_developer.html, with minor changes to section 5 (https://ax.dev/tutorials/gpei_hartmann_developer.html#5.-Perform-Optimization):
    <img width="963" alt="image" src="https://user-images.githubusercontent.com/17101234/204872406-94dee92d-5fcc-4e19-87c7-83b2d0b049c1.png">
     a. instead of calling `Models.MODEL.gen`, you will now call `gs.gen`, having defined the generation strategy like in 1) above.
    b. Instead of calling `gen(n=1)`, call `gen(n=num_contexts)` (to get parameterizations to use in each of the contexts).
    c. Instead of calling `new_trial`, you will call `new_batch_trial` (to add all parameterizations for different contexts to one trial).
3. You will also need to make sure your runner and metric work for `BatchTrial`, which contains multiple arms. Let us know if you need help with this part. Examples here might be useful: https://ax.dev/tutorials/scheduler.html#2.-Set-up-a-mock-external-execution-system (while these work for single-arm `Trial`-s, they should extend to `BatchTrial`-s with multiple arms in a fairly straightforward way).

**Comment by lena-kashtelyan** [comment]
Closing this as inactive as it seems answered. Feel free to reopen if you have follow-up questions, @chanansh!
