### ISSUE TITLE
pip install is outdated?

### ISSUE THREAD

**Issue by priyankclarifai** [facebook/Ax#131]
the `pip3 install ax-platform` seems to be outdated. 
e.g. in `ax/utils/tutorials/cnn_utils.py` has different `train` and `load_mnist` functions compared to whats there on this github
```
def train(
    train_loader: DataLoader,
    parameters: Dict[str, float],
    dtype: torch.dtype,
    device: torch.device,
) -> nn.Module:
```

will throw error ```*** TypeError: train() got an unexpected keyword argument 'net' ``` if I follow the tutorial on https://ax.dev/versions/latest/tutorials/tune_cnn.html
```net = train(net=net, train_loader=train_loader, parameters=parameterization, dtype=dtype, device=device)```

Similarly ```train_loader, valid_loader, test_loader = load_mnist(batch_size=BATCH_SIZE)```
will also throw error

**Comment by Balandat** [comment]
The pip version is always the latest release and not meant to be up to date with the github master. You can find the tutorial for the current pip version here: https://ax.dev/versions/0.1.2/tutorials/tune_cnn.html

If you want to live on the bleeding edge and run the tutorial off master, you need to install Ax from the github master.

**Comment by sdsingh** [comment]
@priyankclarifai, one thing to clarify, the current pip version is not 0.1.2, but is the "stable" version on the Ax site (0.1.3).

**Comment by priyankclarifai** [comment]
Understood thanks a lot,

**Comment by kkashin** [comment]
To add onto this conversation, we do have a bug at the moment with the site where it's easy to be redirected to the latest tutorial (bleeding edge) even though you think you're looking at the stable tutorials. This can happen, for example, if you use the left-hand side nav on the tutorials page. We will fix this shortly.

In the meantime, please use the following link directly as the stable (0.1.3) tutorial: https://ax.dev/tutorials/tune_cnn.html.

**Comment by kkashin** [comment]
Website versioning is fixed now, closing out the task.
