### ISSUE TITLE
How does `plot_objective_vs_constraints` work?

### ISSUE THREAD

**Issue by chanansh** [facebook/Ax#1346]
The model seems to fail learning simple linear relationship between metrics:
ntrials = 200. # params 7, all ints.

![newplot (24)](https://user-images.githubusercontent.com/5981644/209854091-eef899d2-9079-49f9-b33e-d5d2bdfd54da.png)
![newplot (25)](https://user-images.githubusercontent.com/5981644/209854094-02c94b71-96fe-4c68-b78f-c0b7e41080be.png)
![newplot (26)](https://user-images.githubusercontent.com/5981644/209854097-d11603bf-da22-4fe5-9ed5-2c81dc5572de.png)
![newplot (27)](https://user-images.githubusercontent.com/5981644/209854098-db08295a-82ab-421a-9bba-549866c0bc65.png)

**Comment by bernardbeckerman** [comment]
@chanansh from what you've posted, it looks like you're using [tradeoff plots](https://ax.dev/versions/v0.1.20/tutorials/visualizations.html#3.-Tradeoff-plots), which show two metrics plotted against one another. Ax models generally capture the dependency of metrics on parameters (rather than metrics on other metrics), and therefore the tradeoff plots generally don't show the modeled relationships between metrics. Is that what you're looking for?

**Comment by chanansh** [comment]
I was expecting that the standard figure method `plot_objective_vs_constraints` will make sense, but now I understand it is useless since the other metrics are not modeled. This suppose to be some kind of pareto front but when only one axes is modeled I don't see why is this useful.

**Comment by lena-kashtelyan** [comment]
> This suppose to be some kind of pareto front but when only one axes is modeled I don't see why is this useful.

This is not correct. Both axes are modeled, just not with respect to each other. The utility here is that when metric observations are subject to uncertainty, the model-based prediction of a metric’s value can be more accurate than its raw observed value. The dropdown allows you to toggle between modeled and raw values if you would prefer the latter.

In general, we ask that you keep the tone of your messages in this project kind and professional, and avoid terms that are unnecessarily harsh like "useless." While we welcome constructive criticism, there is no need for denigrating language. Our code of conduct can be found here: https://github.com/facebook/Ax/blob/main/CODE_OF_CONDUCT.md; violating it may lead to a limit on your ability to post in this project.

**Comment by lena-kashtelyan** [comment]
Closing this as inactive.
