### ISSUE TITLE
UserWarning: `sort_values` is not specified for `ChoiceParameter`

### ISSUE THREAD

**Issue by YoungJaeBae** [facebook/Ax#1355]
I got a warning message below,
` 
``sort_values`` is not specified for ``ChoiceParameter`` "my_param". Defaulting to ``True`` for parameters of ``ParameterType`` INT. To override this behavior (or avoid this warning), specify ``sort_values`` during ``ChoiceParameter`` construction. 
`
despite the  `sort_values` being specified during the construction of the choice parameter as below.
`
ChoiceParameter( 
    name="my_param",
    parameter_type=ParameterType.INT,
    values=[0, 1],
    is_ordered=False,
    sort_values=True,
)
`
The above warning message occurred while following [Tutorial of Developer API](https://ax.dev/tutorials/gpei_hartmann_developer.html#1.-Create-Search-Space) by changing the parameter type(range to choice) and custom metrics.

Using,
python: 3.7.13
ax: 0.2.6
botorch: 0.6.6

Thank you.

**Comment by danielcohenlive** [comment]
Hi @YoungJaeBae , thanks for the question.  Happy to help!  I ran this minimal repro on ax 0.2.6 and myself didn't get that warning, the minimal repro being:
```
from ax import ChoiceParameter, ParameterType
ChoiceParameter(  name="my_param", parameter_type=ParameterType.INT, values=[0, 1], is_ordered=False, sort_values=True, )
```
I doubt that the other versions are causing the problem (though I could be wrong about the python version) .  Could you confirm my minimal repro causes the error in your environment (assuming I understood your problem correctly).  If not, could you post all of your code with any sensitive info redacted?  I'd like to eliminate the possibility that the warning is actually coming from another choice parameter.

**Comment by danielcohenlive** [comment]
I'm having a little trouble getting 0.2.6 working fully.  Just wondering if it's a option to update to 0.2.10 and see if you still have the issue?  It's not replicating on the latest for me.

**Comment by YoungJaeBae** [comment]
To confirm that I have an issue on python >= 3.8 and ax 0.2.10. I ran the aforementioned code on colab.
I still have the same issue.
```
Running Sobol initialization trials...
Running GP+EI optimization trial 6/20...
/usr/local/lib/python3.8/dist-packages/ax/core/parameter.py:481: UserWarning:

`sort_values` is not specified for `ChoiceParameter` "x5". Defaulting to `True` for parameters of `ParameterType` INT. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.

/usr/local/lib/python3.8/dist-packages/ax/models/torch/botorch_modular/surrogate.py:216: AxWarning:

Provided model class <class 'botorch.models.gp_regression_mixed.MixedSingleTaskGP'> does not accept `train_Yvar` argument, but received `FixedNoiseDataset`. Ignoring variance observations and converting to `SupervisedDataset`.

```

```
from platform import python_version
>>3.8.16
!pip show ax-platform
>>Name: ax-platform
>>Version: 0.2.10
>>Summary: Adaptive Experimentation
>>Home-page: https://github.com/facebook/Ax
>>Author: Facebook, Inc.
>>Author-email: 
>>License: MIT
>>Location: /usr/local/lib/python3.8/dist-packages
>>Requires: botorch, ipywidgets, jinja2, pandas, plotly, scikit-learn, scipy, typeguard
>>Required-by: 
```

**Comment by danielcohenlive** [comment]
I apologize because I just realized there is something particular about our notebook environment that's hiding that warning.  So it's not your version, it's a problem on the bleeding edge latest and I'm looking into it.

**Comment by danielcohenlive** [comment]
@YoungJaeBae I'm shipping a fix to this.  I can't tell you to build from master because it's in a bad state, but there is good news.  I'm noticing you're setting `sort_values=True`, and the warning says "Defaulting to `True` for parameters of `ParameterType` INT."  So this should not be affecting your experiment.

**Comment by YoungJaeBae** [comment]
Thank you @danielcohenlive .
In addition, does Ax currently support 
- Inheriting GenericNoisyFunctionMetric class with custom class methods?
- BoTorch optimization functions for optimizaing surrogate model?

**Comment by YoungJaeBae** [comment]
Oh, I have fixed it. Really appreciate for the responses!

**Comment by danielcohenlive** [comment]
Great!  I'm closing this, but feel free to reopen it if you further questions

**Comment by lena-kashtelyan** [comment]
Sounds like this was meant to be closed, so I'm going to close this. @YoungJaeBae, if you still need help with these two, please open separate issues for them with a description of what you are looking to do and what issues you are facing:

> Inheriting GenericNoisyFunctionMetric class with custom class methods?
> BoTorch optimization functions for optimizing surrogate model?

Thank you!
