### ISSUE TITLE
`optimization_options` not being passed to `botorch.optim.optimize_acqf()`

### ISSUE THREAD

**Issue by NeptuneProjects** [facebook/Ax#1376]
I am trying to shift my workflow from BoTorch over to Ax. In BoTorch, I use qEI and in `optimize_acqf` can easily specify `q`, `num_restarts`, and `raw_samples`. However, when I pass these parameters via the following generation strategy, I'm only getting the default values back when I print them from [this line](https://github.com/pytorch/botorch/blob/3596b125ffad5482eb113ef55f32375ec66ff0ec/botorch/optim/optimize.py#L136) in  `botorch.optim.optimize_acqf`:
```python
from ax.models.torch.botorch_modular.surrogate import Surrogate
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models
from ax.utils.measurement.synthetic_functions import branin
from botorch.acquisition.monte_carlo import qExpectedImprovement
from botorch.models.gp_regression import SingleTaskGP
import numpy as np

N_WARMUP = 5
q = 4
N_TOTAL = N_WARMUP + 5
N_RESTARTS = 10
N_SAMPLES = 256

def evaluate(parameters):
    x = np.array([parameters.get(f"x{i+1}") for i in range(2)])
    return {"branin": (branin(x), None)}

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=N_WARMUP,
            min_trials_observed=N_WARMUP,
            max_parallelism=N_WARMUP,
            model_kwargs={"seed": 2023},
            model_gen_kwargs={}
        ),
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,
            max_parallelism=None,
            model_kwargs={
                "surrogate": Surrogate(
                    botorch_model_class=SingleTaskGP,
                    mll_class=ExactMarginalLogLikelihood
                ),
                "botorch_acqf_class": qExpectedImprovement,
                "acquisition_options": {
                    "optimizer_options": {
                        "q": q,
                        "num_restarts": N_RESTARTS,
                        "raw_samples": N_SAMPLES
                    }
                }
            }
        )
    ]
)

ax_client = AxClient(generation_strategy=gs)
ax_client.create_experiment(
    name="branin_test_experiment",
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [-5.0, 10.0],
            "value_type": "float",
            "log_scale": False
        },
        {
            "name": "x2",
            "type": "range",
            "bounds": [0.0, 15.0],
            "value_type": "float",
            "log_scale": False
        }
    ],
    objectives={"branin": ObjectiveProperties(minimize=True)}
)

for i in range(N_TOTAL):
    parameters, trial_index = ax_client.get_next_trial()
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))
```
Since `optimize_acqf` is at the heart of the acquisition function optimization, I would expect to see:
`(q, num_restarts, raw_samples) = (4, 10, 256)`  
Instead, what I'm seeing are the Ax default parameters:
`(q, num_restarts, raw_samples) = (1, 40, 1024)`

I've been trying to trace where these parameters are getting passed through the various modules but with no luck so far. Any pointers would be greatly appreciated, as I suspect this is a gross conceptual error on my part!

**Comment by pcanaran** [comment]
@NeptuneProjects Thank you for reaching out. Let me find someone who is more familiar with this flow and can advise on how to pass these parameters downstream.

**Comment by saitcakmak** [comment]
Hi @NeptuneProjects. The optimizer options should be passed in as part of the `model_gen_kwargs` to the `GenerationStep`.

```
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,
            max_parallelism=None,
            model_kwargs={
                "surrogate": Surrogate(
                    botorch_model_class=SingleTaskGP,
                ),
                "botorch_acqf_class": qExpectedImprovement,
            },
            model_gen_kwargs={
                "model_gen_options": {
                    "optimizer_kwargs": {
                        "num_restarts": N_RESTARTS,
                        "raw_samples": N_SAMPLES,
                    },
                }
            },
        ),
```

The `q` part works a bit differently in Ax. You request `n` candidates from `gen` converts that into `q` under the hood. In the case of `AxClient`, `ax_client.get_next_trial()` does not support `n > 1`. You can pass `n=q` to `ax_client._gen_new_generator_run(n=q)`, which will give you a `GeneratorRun` containing `q` arms. You'd then have to make these into trials and attach them to the experiment.

**Comment by Balandat** [comment]
To be clear, calling `ax_client.get_next_trial()` repeatedly without completing trials to generate a batch of candidates is totally fine and the generation will take into account that previous trials have been generated but not completed.

**Comment by NeptuneProjects** [comment]
Team - thank you so much! Confirmed this is working now. Thank you for the clarification regarding how `q` is handled, this was going to be a follow-on question.

Just so I don't get this wrong in my implementation:
- Is it correct to say that, if I call `ax_client.get_next_trial()` repeatedly (or `ax_client._gen_new_generator_run(n=q)`), this is essentially "sequential greedy batch optimization" as discussed in App. F.2 from your [paper](https://arxiv.org/abs/1910.06403)?
- Is there currently a way in Ax to implement the approach in App. F.1 (i.e., the `q`x`d` optimization problem, which appears to be the default in BoTorch)? Or would I need to construct the heuristic manually?

I understand that sequential greedy optimization is the preferred method, but since I was using the `q`x`d` optimization in BoTorch, if possible I'd like to replicate my BoTorch workflow in the Ax framework before I start changing my optimization strategy.

**Comment by saitcakmak** [comment]
Calling `ax_client.get_next_trial()` repeatedly is the "sequential greedy batch optimization". At least with the `BOTORCH_MODULAR` generation step, `ax_client._gen_new_generator_run(n=q)` will solve the `q x d` optimization problem under the hood (see [here](https://github.com/facebook/Ax/blob/main/ax/models/torch/botorch_modular/acquisition.py#L409-L417)). The `GeneratorRun` returned by this will include `q` arms that are generated jointly. You can make them into `Trial`s and attach those to the experiment to replicate the BoTorch behavior.

**Comment by saitcakmak** [comment]
Alternatively, if you use the developer API ([tutorial](https://ax.dev/tutorials/gpei_hartmann_developer.html)), you can pass `n=q` to `gen` calls directly. This is currently only a limitation of `AxClient`.

**Comment by NeptuneProjects** [comment]
@saitcakmak thank you very much!
