### ISSUE TITLE
Poor model fit on synthetic function when not specifying noise data

### ISSUE THREAD

**Issue by jultou-raa** [facebook/Ax#1385]
Hi,

I tried a basic function optimization $\min_{x\in\[0,100\]} x \sin x$.

This is the code I used:

```python
from ax import optimize
import numpy

best_parameters, best_values, experiment, model = optimize(
        parameters=[
          {
            "name": "x",
            "type": "range",
            "bounds": [0.,100.],
          },
        ],
        evaluation_function=lambda p: p["x"] * numpy.sin(p["x"]),
        minimize=True,
        total_trials=100,
        objective_name="P",
    )
```

If I want to plot the slice to see how well the surrogate model fits, this is what I see:

![$x\sin x$](https://user-images.githubusercontent.com/64092886/213939313-beb2bd56-de83-49b8-bd24-8f8ef8fe9168.png)

Why does it fit so badly? Am I missing a hypothesis?

Thank you for your explanation.

**Comment by Balandat** [comment]
A few points: 
- The function is highly oscillatory over the domain [0, 100], and will be challenging to model exactly with only 100 observations no matter the model (unless there is prior (potentially parametric) information included).
- You are not passing any information about the observation noise; so the model is inferring a Gaussian noise level on the observations.
- We do have priors on both the lenghtscales and the observation noise of the underlying Gaussian Process model to avoid severely overfitting in the low data regime. 
- Under those priors it's highly unlikely for the model that the data is generated from a noiseless highly oscillatory function.
- If you do want to inform Ax that these observations are indeed noiseless, you can do that by explicitly passing a zero noise level as part of the evaluation function, see the tutorial here: https://ax.dev/tutorials/gpei_hartmann_loop.html#1.-Define-evaluation-function
- (Finally, and more of a side note, you're *optimizing* the function and are not trying to learn it across the whole domain - here you seem to have nice coverage, but in general you can't expect the model to be very good across the whole domain [though ideally it's good where it matters, i.e. near the optimum])

Can you also share how exactly you created the slice plot here?

**Comment by jultou-raa** [comment]
Hi @Balandat and thank you so much for your detailed answer.

To render the plot I used :

```python
from ax.utils.notebook.plotting import render, init_notebook_plotting

init_notebook_plotting()

render(plot_slice(model, "x", "P"))
```

Actually, I hadn't thought of setting the noise estimate to 0. I don't know why, but in my head it was the default behaviour...

The model fits much better! Thank you :)

![x sin x with 0 noise](https://user-images.githubusercontent.com/64092886/213993701-d32b70a5-a01f-4aa8-b806-246ca0596500.png)

**Comment by lena-kashtelyan** [comment]
@jultou-raa, did @Balandat get to all your questions or are any outstanding? : )

**Comment by jultou-raa** [comment]
@lena-kashtelyan yes it is good for me.
Thank you again @Balandat I close this thread.
