### ISSUE TITLE
Instantiating a new AxClient using the `parameters` from an existing AxClient (Service API)

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1398]
I've run into the situation a few times where I want to instantiate a new AxClient using `parameters` from one that has been loaded from a file. For example:
```python
ax_client = AxClient.load_from_json_file(filepath=fpath)
ax_client_tmp = AxClient(generation_strategy=ax_client.generation_strategy)
```
However, AFAIK the file doesn't store the JSON version of `parameters`, and I can't pass `ax_client.experiment.parameters` because it's already been converted to Developer API objects (`ax_client.create_experiment(...)` doesn't support that). I know there's a [`parameter_from_json`](https://ax.dev/api/service.html#ax.service.utils.instantiation.InstantiationBase.parameter_from_json) function, but I don't think there's an inverse of this, and I'm not sure it would make sense to have one anyway.

For now, I'll probably do what I've done before and just remake the list of JSON-style parameters.

For context, I'm working on a response to reviewers for a manuscript, and one reviewer mentioned that some of the comparisons I was making may be less interesting because the optimization trace may be too converged. The reviewer suggested that I take a look at an earlier point in the optimization. So, for my immediate use case, I want to "rewind" the AxClient to a previous state (about halfway back). I'm planning to work around this by creating a fresh AxClient and attaching around half of the trial data that was present in the existing AxClient.

EDIT: I think the following might work for deleting trials (not sure if this will have unintended side-effects):
```python
[ax_client.experiment._trials.pop(i) for i in range(50, 100)]
ax_client.fit_model() # e.g., for feature importance plots
```

**Comment by mpolson64** [comment]
Thanks for this. There's no better way than what you're doing now to create a "clean" copy of an AxClient using the same SearchSpace/OptimizatioConfig/etc but without any of the data, but I could imagine this being very useful to many of our users.

I'll tag this issue as an "enhancement" and post a new comment here if we're able to add this to Ax in the future :)
