### ISSUE TITLE
Is there a way to control the CPU number for Models.FULLYBAYESIAN()? 

### ISSUE THREAD

**Issue by Ted12345678** [facebook/Ax#1408]
So far I can see it tries to use all the available CPUs.

Thanks,

Ted

**Comment by mpolson64** [comment]
Hi, unfortunately there is no way to directly control the number of CPUs an Ax model uses. Instead however you may use [torch.set_num_trheads()](https://pytorch.org/docs/stable/torch.html#torch.set_num_threads) to set the total number of cores pytorch has access to under the hood and in turn limit the number of Ax will be able to use. Would this be sufficient for your use case? cc @saitcakmak

**Comment by saitcakmak** [comment]
Here's some discussion on this from PyTorch docs: https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html. In general, just using `torch. set_num_threads()` should handle most torch operations (such as matmul) that happen under the hood. If you still see high CPU usage, you can also try `torch.set_num_interop_threads()` as well (I don't fully understand this one).

**Comment by esantorella** [comment]
Another option would be to set the % of CPU capacity used by the entire process via a command-line utility. See examples [here](https://superuser.com/questions/442970/limit-a-processes-cpu-usage-methods).

**Comment by Ted12345678** [comment]
Thank you all for the comments. torch.set_num_threads() should be enough. Hence close the question here.
