### ISSUE TITLE
Allow skipping model fitting for tracking metrics

### ISSUE THREAD

**Issue by Balandat** [facebook/Ax#1416]
Currently, models are fit on all tracking metrics during the optimization, even though (by definition) the tracking metrics aren't used for the optimization. 

This slows down optimization and can also cause orthogonal issues (see https://github.com/facebook/Ax/issues/1089#issuecomment-1426881700). 

We should add a `fit_tracking` option that will avoid fitting models to tracking metrics.

**Comment by ClaasRostock** [comment]
I much support the idea of adding a `fit_tracking` option, which allows to have a model run fit() on only a subset of the metrics tracked.  In my case, for instance, I track 5 metrics, but the motivation to track them is mostly monitoring. I do not need the ability of the model to predict all metrics. Fitting a subset of the tracked models would be enough.  If I could do that, it would in my case significantly boost performance.  Especially in cases where you have metrics that are nonlinear and not differentiable in nature, fit() has a hard job will take a looooong time, which could be avoided with a distinct `fit_tracking` option.

**Comment by ClaasRostock** [comment]
'Just shouting out an idea:  The GenerationStrategy could be given a list of metrics to be be opted out, i.e. excluded from fit / gen / predict.  As the GenerationStrategy class actively looks up the data it uses for fit / update, it seems the right place to also hold responsibility to in turn _exclude_ certain metrics from that data (rather than placing that responsibility in Experiment). 

I started a small test implementation.  If it looks clean and works well I will report.

**Comment by Balandat** [comment]
That could work, curious to see your test implementation. 

One thing to not is that in general we think of the GenerationStrategy to only be relevant for the metrics that appear in the objective (either as actual objective(s) or as constraints). So I'm not sure GenerationStrategy is the most logical place for this to live. The reason why we fit non-optimization metrics is for things like inspection and reporting (especially automated reporting). Maybe some more structured notion of that could be a place where those settings could live.

**Comment by ClaasRostock** [comment]
Thank you, @Balandat  
Ok, I see.  Maybe it pinpoints a more general issue then, i.e. may be it is necessary to handle more explicitely the reason(s) why a model is trained. The core purpose, and the one that likely marks the core responsibility of GenerationStrategy as you outline, is that training on all objectives is needed for subsequent generation of new candidates. Beside that core purpose, users likely have other reasons to train (or not train) a model on specific metrics. In many cases this will be a need to use the trained model for prediction, for instance as a surrogate model. And these two needs are likely mixed in a bit non-transparent way currently by users. If you want to build upon a trained model beyond its primary purpose to generate candidates, the GenerationStrategy framework is the part in Ax to look into, currently. But maybe that is not optimal and we I squeeze two responsibilities into GenerationStrategy which should maybe be separated.

**Comment by Balandat** [comment]
Resolved by #1735

**Comment by sgbaird** [comment]
- Is this resolving something different from https://github.com/facebook/Ax/issues/205#issuecomment-562736478 ?

**Comment by saitcakmak** [comment]
> Is this resolving something different from https://github.com/facebook/Ax/issues/205#issuecomment-562736478 ?

Yes. The tracking metrics were being fit but not being passed to the acquisition functions. The issue pointed out by #205 is that the models for tracking metrics would have been needlessly evaluated and their outputs discarded without use within the acquisition functions. For quite some time, the models were being subset to only the outputs needed in the acquisition function before being passed in, avoiding the overhead outlined there (ex: https://github.com/facebook/Ax/blob/main/ax/models/torch/botorch_modular/acquisition.py#L194-L206).

What this does is to avoid creating those models in the first place. With #1735, if `fit_tracking_metrics=False`, Ax will only fit models for the metrics that appear in the `OptimizationConfig` and ignore the rest.
