### ISSUE TITLE
Feature: Add support for (de)serializing fuctions

### ISSUE THREAD

**Issue by madeline-scyphers** [facebook/Ax#1435]
## Summary
# Problem

The current `CORE_DECODER_REGISTRY` and `CORE_ENCODER_REGISTRY` does not include `pathlib.Path` instances which people often store paths as. I am trying to encode and decode some custom Ax Metrics and other subclasses that include me sometime storing paths. A problem with the current encoding and decoding options is that they need to be classes (instead of a function) because of this line in `object_from_json`
``` python
elif issubclass(_class, SerializationMixin):
```
Which doesn't work with `pathlib.Path` since it also only takes position arguments that get splatted/unpacked. It would be easy to to make it accept functions functions by making the check `elif isclass(_class) and issubclass(_class, SerializationMixin):` which happens for other similar checks a dozen or so lines above this line.

Doing so would also allow encoders and decoders that are `classmethods` which are often used as alternative constructors (Something.from_json, Something.to_json, etc.) 

# Proposed Solution

I have opened a PR #1418 to add this functionality and add support for (de)serializing pathlib paths.

**Comment by mpolson64** [comment]
Thank you for submitting this PR and contributing to Ax! I will make sure this gets reviewed soon -- hopefully this week :)
