### ISSUE TITLE
Use of seed for `get_sobol` not producing identical sets when repeated

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1439]
modifying the snippet from https://github.com/facebook/Ax/issues/1437
```python
SEED = 10
parameters = [
    {"name": "mu1", "type": "range", "bounds": [1.0, 5.0], "value_type": "float"},
    {"name": "mu2", "type": "range", "bounds": [1.0, 5.0], "value_type": "float"},
    {"name": "mu3", "type": "range", "bounds": [1.0, 5.0], "value_type": "float"},
    {"name": "std1", "type": "range", "bounds": [0.1, 1.0], "value_type": "float"},
    {"name": "std2", "type": "range", "bounds": [0.1, 1.0], "value_type": "float"},
    {"name": "std3", "type": "range", "bounds": [0.1, 1.0], "value_type": "float"},
    {"name": "comp1", "type": "range", "bounds": [0.0, 1.0], "value_type": "float"},
    {"name": "comp2", "type": "range", "bounds": [0.0, 1.0], "value_type": "float"},
    {"name": "comp3", "type": "range", "bounds": [0.0, 1.0], "value_type": "float"},
    {"name": "num_particles", "type": "range", "bounds": [100, 1000]},
    {"name": "safety_factor", "type": "range", "bounds": [1.0, 2.5]},
]
ax_client = AxClient()
ax_client.create_experiment(
    name="boppf_sobol",
    parameters=parameters,
    objective_name="packing_fraction",
    minimize=False,
    parameter_constraints=["std1 <= std2", "std2 <= std3"],
)
search_space = ax_client.experiment.search_space
m = get_sobol(search_space, fallback_to_sample_polytope=True, seed=SEED)
gr = m.gen(n=num_samples)
param_df = pd.DataFrame([arm.parameters for arm in gr.arms])

print(param_df.shape[0])
# 65536

m2 = get_sobol(search_space, fallback_to_sample_polytope=True, seed=SEED)
gr2 = m2.gen(n=num_samples)
param_df2 = pd.DataFrame([arm.parameters for arm in gr2.arms])
```

After merging the two repeat datasets, there are no duplicates.
```python
print(pd.concat((param_df, param_df2)).drop_duplicates().shape[0])
# 131072
```

Even with aggressive rounding, only a couple hundred repeats out of over 100k entries are present.
```python
print(pd.concat((param_df2.round(3), param_df3.round(3))).drop_duplicates().shape[0])
# 130900
```

Not sure if this is relevant, but I do get:
```python
[INFO 02-21 14:22:57] ax.models.random.base: Rejection sampling exceeded specified maximum draws.Falling back on polytope sampler
```

Same behavior if I use `model_gen_options`:
```python
...
m = get_sobol(search_space, fallback_to_sample_polytope=True, seed=SEED)
gr = m.gen(n=num_samples, model_gen_options={"seed": SEED})
...
```

**Comment by sgbaird** [comment]
A workaround is to call `torch.manual_seed(...)` prior to `m.gen(...)` per the comment by @bletham in https://github.com/facebook/Ax/issues/95#issuecomment-494480113:
```python
m = get_sobol(search_space, fallback_to_sample_polytope=True, seed=SEED)
torch.manual_seed(SEED)
gr = m.gen(n=num_samples)
```

**Comment by mpolson64** [comment]
cc @saitcakmak @esantorella who have both recently been hunting down nondeterminism in Ax

**Comment by saitcakmak** [comment]
Hi @sgbaird. 

> Not sure if this is relevant, but I do get:
```
[INFO 02-21 14:22:57] ax.models.random.base: Rejection sampling exceeded specified maximum draws.Falling back on polytope sampler
```

This is indeed very relevant. This is saying that Sobol couldn't produce the samples you needed using Sobol + rejection sampling and it is instead using `HitAndRunPolytopeSampler` to produce the samples. It is not passing in the `seed` to `HitAndRunPolytopeSampler`, which leads to the non-determinism you observe. 

One option would be to pass in the `seed` [here](https://github.com/facebook/Ax/blob/main/ax/models/random/base.py#L151). I don't know what randomness property the resulting samples would satisfy if we did this twice with the same seed though. It is possible that they'd be different since `_get_last_point(self)` should return a different point but it might be safer to just pass in something like `seed + num_generated` instead.

@Balandat any thoughts on this?

**Comment by sgbaird** [comment]
@saitcakmak thank you for clarifying this. For some reason I made the naive assumption that the fallback behavior was still a form of Sobol. It's clear to me now that's not the case.
