### ISSUE TITLE
Nested / referenced parameters in search space

### ISSUE THREAD

**Issue by pezosanta** [facebook/Ax#1454]
Hi,

We are trying to use Ax for a Neural Architecture Search task where we want the Hyperparameter Tuning algorithm to suggest us how many layers (of each layer type) should the DNN contain and what should be their kernel sizes. Currently, we are using the Hyperopt (TPE) library/tool for this task, but we want to try other hyperparameter tuning tools as well.

In Hyperopt, we can build this "complicated" parameter space with nested parameters in the following way:

```
from hyperopt import hp

...

param_space = {
    "conv_layers": 
        hp.choice(
            "num_conv_layers",
            [
                {
                    "kernel_sizes": [
                        hp.choice(f"kernel_{num_conv_layers}_{i}", [1, 5, 10, 20, 50]) for i in range(num_conv_layers)
                    ],
                } for num_conv_layers in [5, 10, 15, 20, 25]
            ]
        )
    ...
} 

...

```

Here, the list [5, 1, 10, 20, 1] can be a sampled value for the `conv_layers` named hyperparameter which would mean that we will have all in all 5 consecutive conv layers (`len(conv_layers)`) with 5, 1, 10, 20, 1 kernel sizes respectively.

Any idea on how to implement such parameter space structure/logic in Ax ? Based on the docs I am not sure whether nesting parameters (just like above) or referencing other parameters in the same parameter space is possible at all. (E.g.: param1 decides the number of layers and after it is sampled, param1 number of kernel sizes are sampled as well.)

Another idea of mine (see below) is to 
- always sample the maximum number of kernel sizes (`"kernel_size_of_layer_{i+1}"` parameters)
- sample the number of conv layers to use in a separate parameter (`"num_conv_layers_to_use"`)
-  use the first `num_conv_layers_to_use` number of `kernel_size_of_layer_{i+1}` kernel sizes to build the model
```
max_conv_layers_to_use = 25

param_space = [
    {
        "name": "num_conv_layers_to_use",
        "type": "choice",
        "values": [5, 10, 15, 20, max_conv_layers_to_use]
    },
    
    {
        "name": f"kernel_size_of_layer_{i+1}",
        "type": "choice",
        "values": [1, 5, 10, 20, 50]
    }
    for i in range(max_conv_layers_to_use)
]
```
However, this way, I don't know how confusing would it be for Ax Search that some sampled kernel sizes most often would not contribute to the reported metric. 

Note that we are using Ray Tune for hyperparameter tuning the models at scale on our GPU cluster, so the solution (if any) should be compatible with it.

**Comment by mpolson64** [comment]
Hi Peter -- yes we do support search spaces like this and you can see an example as well as substantial discussion on the topic in this issue here https://github.com/facebook/Ax/issues/140#issuecomment-1009015750 . Methods for optimizing hierarchical search spaces like the one you describe is an active area of research on our team and we hope to provide some more substantial support (along with a blog post and tutorial) in the future. Let me know if you have any questions.

**Comment by lena-kashtelyan** [comment]
I believe this is resolved, so closing it. If you still need help with this, please reopen the issue, @pezosanta!
