### ISSUE TITLE
pip not install 

### ISSUE THREAD

**Issue by yiyinying** [facebook/Ax#147]
ubuntu 19.04
conda python=3.7.4
pytorch 1.2.1
botorch 

(py37) yiyin@yiyin-ThinkPad-T460p:~$ pip uninstall ax-platform
8.3.0
Uninstalling ax-platform-0.0.0:
  Would remove:
    /opt/miniconda3/envs/py37/lib/python3.7/site-packages/ax_platform-0.0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled ax-platform-0.0.0
(py37) yiyin@yiyin-ThinkPad-T460p:~$ pip install ax-platform
8.3.0
Collecting ax-platform
  Using cached https://files.pythonhosted.org/packages/89/b4/a51b618c99ea757d051cb1fcf89996ebd3c92acfce82806040c25b54b43f/ax_platform-0.0.0-py3-none-any.whl
Installing collected packages: ax-platform
Successfully installed ax-platform-0.0.0

**Comment by kkashin** [comment]
It appears as though pip is using a cached version of Ax. Could you either:

1) Install without using the cache: `pip install ax-platform --no-cache-dir`

2) Install version 0.1.3 explicitly: `pip install ax-platform==0.1.3`


Can you let me know if either of these works?

Thanks!

**Comment by yiyinying** [comment]
pip uninstall ax-platform --no-cache-dir
8.3.0
Uninstalling ax-platform-0.0.0:
  Would remove:
    /opt/miniconda3/envs/py37/lib/python3.7/site-packages/ax_platform-0.0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled ax-platform-0.0.0

pip install ax-platform==0.1.3
8.3.0
Collecting ax-platform==0.1.3
  ERROR: Could not find a version that satisfies the requirement ax-platform==0.1.3 (from versions: 0.0.0)
ERROR: No matching distribution found for ax-platform==0.1.3




Still not installed successfully。 ubuntu 19.04

**Comment by kkashin** [comment]
@yiyinying - hmm, OK. Not sure off the top of my head why pip is not using the [`manylinux1`](https://www.python.org/dev/peps/pep-0513/) wheel that we provide for Python 3.7: https://files.pythonhosted.org/packages/1e/32/fe7b32395a8e2075369ffa826ab3d0e4e71ef13086f6b09fad7104132dc8/ax_platform-0.1.3-cp37-cp37m-manylinux1_x86_64.whl.

If you could try running the `is_manylinux1_compatible` function from https://www.python.org/dev/peps/pep-0513/#platform-detection-for-installers and see why your system is not eligible for `manylinux1`, that would be helpful. 

If you could provide outputs for specific checks, that would be useful too, e.g. what do you get if you run the following command:
```
python3 -c "from distutils.util import get_platform; print(get_platform());"
```

We will investigate this further, but in the meantime you should be able to install the bleeding edge version directly from Git: https://ax.dev/versions/latest/docs/installation.html#installing-from-git.

**Comment by yiyinying** [comment]
(py37) yiyin@yiyin-ThinkPad-T460p:~$ python3 -c "from distutils.util import get_platform; print(get_platform());"
linux-x86_64

**Comment by yiyinying** [comment]
is_manylinux1_compatible()  true
have_compatible_glibc('ubuntu','19.04')

**Comment by yiyinying** [comment]
Should I change to ubuntu 18.04?

**Comment by yiyinying** [comment]
https：//files.pythonhosted.org/packages/1e/32/fe7b32395a8e2075369ffa826ab3d0e4e71ef13086f6b09fad7104132dc8/ax_platform-0.1.3-cp37-cp37m- manylinux1_x86_64.whl。


pip install ax_platform-0.1.3-cp37-cp37m-manylinux1_x86_64.whl 
8.3.0
ERROR: ax_platform-0.1.3-cp37-cp37m-manylinux1_x86_64.whl is not a supported wheel on this platform.

**Comment by yiyinying** [comment]
ERROR: Command "git clone -q ssh://git@github.com/facebook/Ax.git /tmp/pip-req-build-9ufn0ckd" failed with error code 128 in None

**Comment by yiyinying** [comment]
Git installation also failed

**Comment by kkashin** [comment]
Re: `have_compatible_glibc`, you want to pass the major and minor version of glibc (see example in https://www.python.org/dev/peps/pep-0513/#platform-detection-for-installers). What's the version you have?

Re: the error you're getting cloning the repo (`"failed with error code 128 in None"`), it seems like that can happen due to a variety of reasons (some authentication related), but it shouldn't be specific to our library. See for example, https://github.com/zulip/zulip/issues/126.

Make sure you have an up-to-date pip and that your GitHub certs are in order, and then try:

```
pip3 install cython numpy  # needed for compiling Cython code
pip3 install git+ssh://git@github.com/facebook/Ax.git#egg=Ax
```

**Comment by yiyinying** [comment]
Python 3.6 installed successfully。

**Comment by kkashin** [comment]
Great, closing the issue then.
