### ISSUE TITLE
typeguard 3.x release breaking changes for type validation in ax utils module

### ISSUE THREAD

**Issue by BenWilson2** [facebook/Ax#1509]
A heads-up: typeguard released 3.0.0 last night on 3/14/23 with a breaking change to its `check_type()` API. 
The following line throws with the unguarded import of typeguard: https://github.com/facebook/Ax/blob/3f36e59c3874ab6fd74679c34f2a2214d0aee34b/ax/utils/common/typeutils.py#L86

Here's the top-level stack trace for the error:

```
Traceback (most recent call last):
  File "/home/runner/.myenv/envs/env-0970aad0277769059cafdf501428fc3782d89a0d/lib/python3.8/site-packages/ax/utils/common/typeutils.py", line 83, in checked_cast_complex
    check_type("val", val, typ)
TypeError: check_type() takes 2 positional arguments but 3 were given
```

**Comment by Balandat** [comment]
Thanks for flagging - yes we're aware, see #1508. In fact, we're probably going to get rid of typeguard altogether since its value add is questionable given how we use it.

**Comment by mpolson64** [comment]
Thanks for the catch. We have a fix ready here https://github.com/facebook/Ax/pull/1510 and will be releasing a new Ax version ASAP to help all affected users.

**Comment by BenWilson2** [comment]
Awesome! Thanks for the proactive fix :)

**Comment by mpolson64** [comment]
There has been a minor change of plans and we decided to pin typeguard to version 2.13.3. The team is continuing to look into the best way to move forward without having any regression in runtime safety, but wanted to get a new version of Ax out as soon as possible to avoid forcing our users to have to manually downgrade typeguard.

Users using [Ax v0.3.1](https://github.com/facebook/Ax/releases/tag/0.3.1) or newer will not be affected by this bug.
