### ISSUE TITLE
plotting Pareto frontier based on model posterior

### ISSUE THREAD

**Issue by tanguyen77** [facebook/Ax#1519]
Hi,

using the following code from one of the tutorials, I can get the pareto frontier based on the model posterior:

```
filename = f'./trials/{date}/ax_client_snapshot0.json'
restored_ax_client = AxClient.load_from_json_file(filepath=filename)
objectives = restored_ax_client.experiment.optimization_config.objective.objectives
frontier = compute_posterior_pareto_frontier(
    experiment=restored_ax_client.experiment,
    data=restored_ax_client.experiment.fetch_data(),
    primary_objective=objectives[0].metric,
    secondary_objective=objectives[1].metric,
    absolute_metrics=["constraint satisfaction", "efficiency"],
    num_points=50,
)
render(plot_pareto_frontier(frontier, CI_level=0.9))
```

When using "compute_posterior_pareto_frontier" I get the following warning multiple times:

```
Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 9.')]
Trying again with a new set of initial conditions.
C:\Users\ng\Miniconda3\envs\py39\lib\site-packages\botorch\optim\optimize.py:298: RuntimeWarning:
Optimization failed on the second try, after generating a new set of initial conditions.
```

Can someone help me in figuring out, what this means? Thanks in advance.

**Comment by Balandat** [comment]
Depending on the data, computing the Pareto frontier based on the model predictions can be a pretty challenging numerical optimization problem. These warnings are telling you that some of the underlying optimizations that are running are having a hard time finding solutions. This may be quite benign if this occurs only occasionally for some corners of the Pareto frontier, but it could also be a sign of a bigger issue. 

How do the results you're getting from this look like? Is there any reason to think that they're not reasonable?

Also could you share the `ax_client_snapshot0.json` file with us? Without the data it's hard to diagnose what's going wrong.

**Comment by tanguyen77** [comment]
Hi @Balandat, thanks for answering. Yes, I can share the data with you.
RIght now, it is hard for me to tell whether the results are reasonable or not. I will provide the estimated as well as observed pareto frontier here and the convergence. It seems like the problem has not fully converged and the observed pareto frontier does not have good coverage in some areas. Is there something you can recognize or know of?

![grafik](https://user-images.githubusercontent.com/56732601/226208182-cb52fe89-97b9-439f-920f-caa2d20b714f.png)
![grafik](https://user-images.githubusercontent.com/56732601/226208198-1c37c521-3b7b-46c8-971e-fb068ad9018a.png)
![grafik](https://user-images.githubusercontent.com/56732601/226208222-211bc3df-9d16-498c-a405-01b266850123.png)




[ax_client_snapshot0.zip](https://github.com/facebook/Ax/files/11012259/ax_client_snapshot0.zip)

**Comment by Balandat** [comment]
It's hard to tell. Is there any reason you can think of for the many points clustered at around (0.8, 0.495)?

Did you specify objective thresholds for the multi-objective optimization? If the threshold for efficiency is too high this could potentially explain that behavior.  

This behavior of a relatively sparse empirically observed frontier in the center (with observations clustering at the edges) could also be due to the function just being quite flat in the two objectives in large parts of the search space with only a small region where there is meaningful change in both metrics simultaneously.

**Comment by tanguyen77** [comment]
I cannot think of any reason as of now for why there are many points clustered around 0.8 and 0.495.
I did specify thresholds, which are 0 for the efficiency and -3 for the constraint satisfaction.

To be honest, I don't know whether the function is rather flat or not. I ran the optimization again with more closed loop simulations/ trials but got quite similar results.

![grafik](https://user-images.githubusercontent.com/56732601/227927978-0012ab5c-073b-4313-a963-5124ee1d0d70.png)

And I still get the same warning multiple times: Optimization failed in `gen_candidates_scipy` with the following warning(s):
[OptimizationWarning('Optimization failed within `scipy.optimize.minimize` with status 9.')]
Trying again with a new set of initial conditions.

**Comment by Balandat** [comment]
Hmm it may just be that this is a relatively hard problem when it comes to getting good coverage of "belly" of the Pareto frontier. The iteration coloring suggests that there is indeed decent progress being made as the exploration continues. cc @sdaulton if he has any additional thoughts here. 

> And I still get the same warning multiple times: Optimization failed in gen_candidates_scipy with the following warning(s): [OptimizationWarning('Optimization failed within scipy.optimize.minimize with status 9.')]

Is still still happening during the call to `compute_posterior_pareto_frontier` (rather than during the actual optimization loop)?

**Comment by tanguyen77** [comment]
Yes, it happens when I call compute_posterior_pareto_frontier.

**Comment by lena-kashtelyan** [comment]
This has been inactive for a while. @tanguyen77, please reopen this issue if you still need help. Please don't comment on the closed issue though as we are unlikely to see the comment that way –– reopen if you do follow up. Thank you!
