### ISSUE TITLE
weird error(ArgumentError('Type annotation for "SQAGeneratorRun.arms" can\'t be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic  type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legac y annotations which don\'t use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class.'))

### ISSUE THREAD

**Issue by Shu1999-07** [facebook/Ax#1539]
I am new to Ax and trying to run the tutorial examples on the webpage however I keep getting the same error:
[2023-03-22 19:58:35,259][HYDRA] NumExpr defaulting to 4 threads.
Error in call to target 'hydra_plugins.hydra_ax_sweeper.ax_sweeper.AxSweeper':
ArgumentError('Type annotation for "SQAGeneratorRun.arms" can\'t be correctly interpreted for Annotated Declarative Table form.  ORM annotations should normally make use of the ``Mapped[]`` generic type, or other ORM-compatible generic
 type, as a container for the actual type, which indicates the intent that the attribute is mapped. Class variables that are not intended to be mapped by the ORM should use ClassVar[].  To allow Annotated Declarative to disregard legac
y annotations which don\'t use Mapped[] to pass, set "__allow_unmapped__ = True" on the class or a superclass this class.')
full_key: hydra.sweeper

**Comment by mpolson64** [comment]
Sorry to hear you're running into this issue. Before we look into this more deeply, could you provide a `pip freeze` so we can see what package versions are being run when you encounter this error?

**Comment by sonisparky** [comment]
> Ahhhhh, I have already fixed this error. I think this error is caused by some packages, such as sqlalchemy.. Thanks for your quick reply!

Hi @Shu1999-07 can I know how you resolved this issue, as i updated the sqlalchemy package from 1.4.47 to 2.0 and facing this error

**Comment by Shu1999-07** [comment]
Hello,
I just removed this package cause I don't need it. Maybe you can try downgrade it to the orignal version?
