### ISSUE TITLE
DocString incorrect: utils.measurement.synthetic_functions SyntheticFunction

### ISSUE THREAD

**Issue by ClaasRostock** [facebook/Ax#1545]
In class SyntheticFunction, the DocString of method _f() does not seem to be correct. It was apparently copied from method f().
However, while f() works on an input matrix and returns a vector,  _f() works on a single observation, i.e. vector, and returns a float.

Proposal:
def _f(self, X: np.ndarray) -> float:
    ...
    Args:
        X (numpy.ndarray): 1-dimensional input vector with d elements, where d is the             dimensionality of the inputs.
    Returns:
        float: the function value

**Comment by ClaasRostock** [comment]
further observation:   _f() is declared as class method, but has 'self' as first parameter.  I suspect the @classmethod decorator is wrong and should be removed, unless _f() is really used somewhere as class method.

**Comment by esantorella** [comment]
Closed by #2329 .
