### ISSUE TITLE
[Question] How to use advanced Acquisition-Functions in model_bridge_with_GPEI

### ISSUE THREAD

**Issue by Meganton** [facebook/Ax#1550]
I want to compare the performance of many acquisition-functions and therefore generate the data all with the same program, just iterating over the Acqu-Functs (with SingleTaskGP as surrogate-model). This works fine for many simple Acquisition-functions like the analytic and monte carlo-methods, but when using more complex like qPredictiveEntropySearch, i get the Error:
`Exception has occurred: RuntimeError
Input constructor for acquisition class "qPredictiveEntropySearch" not registered. Use the "@acqf_input_constructor" decorator to register a new method.`

My Code is (after i defined the experiment on the Branin-metric:

```
for b_round in range(numberOfBotorchRounds):
        model_bridge_with_GPEI = Models.BOTORCH_MODULAR(
                experiment=exp,
                data=exp.fetch_data(),
                surrogate=Surrogate(SingleTaskGP),
                botorch_acqf_class=qPredictiveEntropySearch)
        generator_run = model_bridge_with_GPEI.gen(1)
        #Here the Error occurs
        trial = exp.new_trial(generator_run=generator_run)
        trial.run()
        trial.mark_completed()
```

Are these functions available for this model_bridge or did i just miss something? 

Thanks in advance!

**Comment by Balandat** [comment]
Hi @Meganton, for Ax to know how to generate the inputs to the BoTorch acquisition function constructors, we need to register a method that can tell it how to do that in a programmatic fashion (the main reason is that acquisition functions range from very simple to highly complex, and so standardizing the arguments in a way that doesn't add a ton of red tape on the BoTorch end isn't straightforward). This is the place where this is called in the Ax code: https://github.com/facebook/Ax/blob/ce9e6ee47db7d4e9bb330c3a7cbdb25139739c69/ax/models/torch/botorch_modular/acquisition.py#L287-L309 

It looks like `qPredictiveEntropySearch` is just not registered at this point. To do that you'll have to write some helper function that takes in a set of standardized arguments and spits out the inputs to the BoTorch `qPredictiveEntropySearch` constructor. You can see an example for `qMaxValueEntropySearch` here: https://github.com/pytorch/botorch/blob/9302055f36981e3413e8dce08ae050bd701f5e7a/botorch/acquisition/input_constructors.py#L850-L876

You can do that locally (outside of the BoTorch code base) by importing the [`acqf_input_constructor`](https://github.com/pytorch/botorch/blob/9302055f36981e3413e8dce08ae050bd701f5e7a/botorch/acquisition/input_constructors.py#L180) decorator. But it would be great to also add this to BoTorch to make this available to other folks as well - would you be willing to create a PR for this?

**Comment by Meganton** [comment]
Thanks a lot for the detailed answer, i will try doing this. But as I'm still a beginner i don't think it will be clean and safe enough to really work as a public solution.
