### ISSUE TITLE
Warm-start from an existing AxClient

### ISSUE THREAD

**Issue by acse-itk22** [facebook/Ax#1558]
Hello, 
I ran a multi-objectivie optimization with Ax Service API and discovered that it has not converged to a satisfactory Pareto front. Because of this, I would like to continue the simluation based on an AxClient saved in a JSON files. I've read about the attach_trial and complete_trial methods but I cannot figure out how to extract the inputs for these function from and old Ax Client. Could you please help?

**Comment by mpolson64** [comment]
Once you have reloaded an AxClient from JSON you may continue to call `ax_client.get_next_trial()` etc and continue with your experiment as long as you would like.

That being said, if there is a need to use a fresh AxClient you will need to transfer all the Trials and their results from the old client to the new one. The following snippet should be sufficient if you replace the `...`s with the appropriate values for your setup :)

```
ax_client = AxClient.load_from_json_file(...)

new_client = AxClient()
new_client.create_experiment(...)

data_df = ax_client.experiment.fetch_data().df

for index, trial in ax_client.experiment.trials.items():
    paramerization = trial.arm.parameters
    raw_data = {row["metric_name"]: (row["mean"], row["sem"]) for _index, row in data_df[data_df["trial_index"] == index].iterrows()}

    _parameterization, new_index = new_client.attach_trial(parameters=paramerization)
    new_client.complete_trial(trial_index=new_index,raw_data=raw_data)
```

Let me know if this doesn't work or if you have any follow up questions.

**Comment by acse-itk22** [comment]
Thank you for the quick response @mpolson64. The setup above works for me and it seems like I have overlooked the easy solution to my problem. Feel free to close this :)

**Comment by marios1861** [comment]
> Once you have reloaded an AxClient from JSON you may continue to call `ax_client.get_next_trial()` etc and continue with your experiment as long as you would like.
> 
> That being said, if there is a need to use a fresh AxClient you will need to transfer all the Trials and their results from the old client to the new one. The following snippet should be sufficient if you replace the `...`s with the appropriate values for your setup :)
> 
> ```
> ax_client = AxClient.load_from_json_file(...)
> 
> new_client = AxClient()
> new_client.create_experiment(...)
> 
> data_df = ax_client.experiment.fetch_data().df
> 
> for index, trial in ax_client.experiment.trials.items():
>     paramerization = trial.arm.parameters
>     raw_data = {row["metric_name"]: (row["mean"], row["sem"]) for _index, row in data_df[data_df["trial_index"] == index].iterrows()}
> 
>     _parameterization, new_index = new_client.attach_trial(parameters=paramerization)
>     new_client.complete_trial(trial_index=new_index,raw_data=raw_data)
> ```
> 
> Let me know if this doesn't work or if you have any follow up questions.

Is `new_client.experiment.warm_start_from_old_experiment(ax_client.experiment)` not the same? I have a client that has 30 completed Sobol trials, and after doing this, it starts the exact same sobol trials again 
(having the same random_seed). I would just use the same ax_client, but some times I want to change some parameter ranges etc. I don't understand why it is ignoring the already run Sobol runs. With `ax_client.get_trials_data_frame()`, I see that the new sobol trials have the exact same arm name.
