### ISSUE TITLE
Question regarding transformation of GP hyperparameter constraints

### ISSUE THREAD

**Issue by NeptuneProjects** [facebook/Ax#1601]
I have a use case in which GP hyperparameters should be constrained to a range determined by a physics model; specifically, the expected length scales for an RBF or Matern kernel are related to the characteristics of a wave propagating in a certain environment. My custom covariance module for this two-dimensional spatial application is defined as:
```python
from gpytorch.constraints import Interval, Positive
from gpytorch.kernels import RBFKernel, ScaleKernel

covar_module = ScaleKernel(
    base_kernel = (
        RBFKernel(
            active_dims=[0],
            lengthscale_constraint=Interval(1, 10) # <- Untransformed domain values
        )
        * RBFKernel(
            active_dims=[1],
            lengthscale_constraint=Interval(100, 1000) # <- Untransformed domain values
        )
    ),
    outputscale_constraint=Postive()
)
```
I'm having trouble understanding how the hyperparameter constraints I specify are related to the transformation pipeline in Ax. If I know the length scale should be between 1-10 meters in one dimension of the parameter domain and 100-1000 m in another dimension, what values do I specify for the `lengthscale_constraint`? My working assumption is that the `lengthscale_constraint` would be specified in the transformed domain; if this is the case, is there a straightforward way to convert my physical lengths into the correctly transformed domain?

I am using the Service API.

**Comment by saitcakmak** [comment]
Hi @NeptuneProjects. 

> My working assumption is that the lengthscale_constraint would be specified in the transformed domain

That is correct. Your parameters would be transformed in Ax by default and the lengthscale constraints would apply in the transformed space.

> is there a straightforward way to convert my physical lengths into the correctly transformed domain?

This depends on what your parameters are. If you're using range parameters, this should be straightforward. Most out of the box generation strategies in Ax will standardize the range parameters to [0, 1]. So, if your original parameter is a range parameter in [10, 20], a length-scale of 10 in the raw space would correspond to a length-scale of 1 (=10/(20-10)) in the standardized space. 

If you're using choice parameters, this might be a bit more complicated. Unordered choice parameters would be one-hot encoded, so this wouldn't really work out. For ordered choice parameters, the default generation strategies will eventually map them to [0, 1] as well. The transform might not be a linear transform (depending on the values of the choice parameter), so a transform like above might only be a crude approximation.

**Comment by NeptuneProjects** [comment]
Thanks for the information, this is very helpful and thankfully my parameters are range parameters!

**Comment by Balandat** [comment]
Sounds like a cool application, @NeptuneProjects - would love to learn more about it. Do you have any related papers that you could share?

**Comment by NeptuneProjects** [comment]
@Balandat thanks for your interest, working on an acoustic localization/model inversion problem. We are quite close to submitting our first paper on the topic, I'll post a link when we do!

**Comment by Balandat** [comment]
Great, looking forward to it!

**Comment by NeptuneProjects** [comment]
@Balandat wanted to follow up - [our paper](https://doi.org/10.1121/10.0020839) using BO came out today. Many thanks to you and your team for an excellent library and for being so responsive to questions/feedback. Essentially, I used BO to speed up matched field processing, a technique used in underwater acoustics to localize a source. The objective function is the correlation between a measured acoustic field and a predicted one. In trying to be a good Bayesian, I was interested in incorporating what we know about the physics of waveguides to constrain the kernel function hyperparameters; i.e., given the geometry of the waveguide and the source frequency, we have theoretical and empirical expectations of the structure of the objective function surface. In the end, the defaults coincided with what we could expect from the physics.

Our next step is to increase the parameter space to estimate additional geoacoustic properties (e.g., speed of sound in the seabed). These inversions are typically performed with MCMC, so it will be quite satisfying to be able to actually incorporate the physics of the waveguide into the optimization.

**Comment by Balandat** [comment]
@NeptuneProjects Awesome, thanks for the update! I love everything ocean, so I'm happy to see our tools getting used in that context.
