### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'name'

### ISSUE THREAD

**Issue by SamirLamin** [facebook/Ax#1604]
Hello. I tried to implement AX for my multiobjective Bayesian optimization but I get this error can you help me to solve it 
![Screenshot 2023-05-03 144243](https://user-images.githubusercontent.com/55294434/235934444-dcdcd00c-0372-4005-a0f9-1cdece0c2110.png)

**Comment by mpolson64** [comment]
Hi Samir -- it looks like you're trying to set up an Ax Experiment, but using the Service API experiment creation syntax. Ax exposes a number of different API's to its users that are appropriate for different settings. The Service API is designed to allow the user to "ask" Ax to generate new parameterizations while scheduling their own trials; I suggest you check out this tutorial as a good starting point https://ax.dev/tutorials/gpei_hartmann_service.html . Let me know if this was helpful or if you have any follow up questions.

As an aside: I notice you're passing in a variable called "sense" to the Objective. Ax does not have a notion of sense or ObjectiveSense; are you using Ax directly or some other library that wraps around Ax?

**Comment by lena-kashtelyan** [comment]
@SamirLamin  it seems to me that your question was answered, so I'm closing this issue. Please feel free to follow up on it, but if you do, please reopen the issue as we might not see your comment on a closed one.
