### ISSUE TITLE
Latest release 0.3.2 not on pypi

### ISSUE THREAD

**Issue by ClaasRostock** [facebook/Ax#1605]
I recognized that the latest release 0.3.2 is not published to pypi.
It seems the former release 0.3.1 got published to pypi the same day the release was created on GitHub (March 15).
This made me think that maybe the deployment workflow did not run through and not-publishing to pypi might be by mistake this time?  If intended, then feel of course free to simply close this issue ;-)
Best regards
Claas

**Comment by mpolson64** [comment]
Thanks for your concern on this! The team is aware of the issue and hoping to get it sorted out ASAP -- hoping to get a version published either today or tomorrow. In the meantime please continue to use v0.3.1 :)
