### ISSUE TITLE
ax_client.get_optimization_trace() does not discard unfeasible trials

### ISSUE THREAD

**Issue by leandrobbraga** [facebook/Ax#1628]
Hello! I'm using the service API to solve a single-objective optimization with an outcome constraint defined by `outcome_constraint=["SLA >= 0.9"]`.

So far so good. Upon inspection, I see that the `ax_client.get_trials_data_frame()` correctly identifies feasible/unfeasible trials as desired. The issue is when I use the `render(ax_client.get_optimization_trace())` function. The plot it outputs does consider unfeasible points and also does not offer an option to discard them.

Is that a design choice? If not, can we add a parameter to do it?

I'm not familiar with the code base yet but I can give it a shot if you guys think it is useful.

I'm using `version 0.3.2`.

**Comment by leandrobbraga** [comment]
Just to be clearer, you can see in this screenshot that all the points after the 14th one are unfeasible.
![image](https://github.com/facebook/Ax/assets/18340809/6bb5fe37-2a90-446e-9ff2-b42ddd6aa590)

But when I plot the `get_optimization_trace()` it keeps improving:
![image](https://github.com/facebook/Ax/assets/18340809/f936f8be-fe8a-42fb-8651-d5f0a98c8702)

Is that expected?

**Comment by leandrobbraga** [comment]
Another strange thing to me is the GPEI not respecting the constraint in a single trial. That's not because there is no feasible regions in the problem, but rather the model struggling somehow. When I tried the same problem as a MOO it did a way better job of respecting the constraint and finding good values.

Even in the new trials that it suggest, when I ask for a prediction, the model predicts it to be unfeasible.

**Comment by Balandat** [comment]
Yeah, we should add support for outcome constraints for `get_optimization_trace()`.

There are a few ways we could do it; I think one would be to just show feasible points (and potentially toggle to also show infeasible ones). We could also consider a model-based version where in case of noisy observations we use the model mean prediction for the value, and we could use the constraint model to compute the probability of feasibility (though that would require more work and make things slower).

> I'm not familiar with the code base yet but I can give it a shot if you guys think it is useful.

We'd love to accept a PR on this and can help give advice and review :)

**Comment by leandrobbraga** [comment]
Ok, I'll give it a shot in the weekend :)
