### ISSUE TITLE
Heteroscedastic modification of SAASBO

### ISSUE THREAD

**Issue by Kakedral** [facebook/Ax#1632]
Hello! I am expanding on a previously implemented study where I used heteroscedastic GPs in BO with BOTORCH_MODULAR using HeteroskedasticSingleTaskGP as the surrogate. I was wondering if there is a quick way of modifying models.FULLYBAYESIAN such that the variance is also modelled by another GP as in HeteroskedasticSingleTaskGP in order to tackle scalability issues as handled in SAASBO. Thank you so much in advance!

Best Kiet

**Comment by Balandat** [comment]
Interesting question! 

This should be possible with some changes - the main one is that you need to replace the `noise * torch.eye(self.train_X.shape[0], **tkwargs)` term in https://github.com/pytorch/botorch/blob/main/botorch/models/fully_bayesian.py#L180 with the predicted variances from the inner GP conditional on the noise sampled from that inner GP (you'd essentially do two-stage sampling for that). This should take care of the pure model to run the MCMC chain on. As with the vanilla models, you'd then also have to create a GPyTorch model into which you'd have to load those MCMC samples (including the inner GP).

So this should definitely be possible but I'm not sure if it's particularly quick to do (it shouldn't be too bad though). 

cc @dme65, @sdaulton, @qingfeng10, @Ryan-Rhys

**Comment by lena-kashtelyan** [comment]
@Kakedral it seems to me that your question was answered, so I'm closing this issue. Please feel free to follow up on it, but if you do, please reopen the issue as we might not see your comment on a closed one.
