### ISSUE TITLE
Sobol model doesn't respect equality constraint passed to `model_gen_kwargs`

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1634]
EDIT: I remembered some discussion from https://github.com/facebook/Ax/issues/903, and I think the solution is to use [DelaunayPolytopeSampler](https://github.com/pytorch/botorch/blob/21ce6c7fa9fa907674c37b849e2e5dc683ca2682/botorch/utils/sampling.py#L697-L715) to generate the candidates per @Balandat's suggestion in https://github.com/facebook/Ax/issues/903#issuecomment-1099243978 and then attach and complete those trials (rather than using `get_next_trials` with a custom generation strategy, as below).

[Colab Reproducer](https://colab.research.google.com/drive/1vGUOKggx6Yntf0kkaAg1Ynxd-CNME1sM?usp=sharing)

Related to #1430 

```python
import torch

num_components = len(unique_components)

# sum(x) == 1
equality_constraints = [
    (
        torch.arange(num_components, dtype=torch.long),
        torch.ones(num_components, dtype=torch.double),
        1,
    )
]

gs = GenerationStrategy(
    steps=[
        # 1. Initialization step (does not require pre-existing data and is well-suited for 
        # initial sampling of the search space)
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
            model_gen_kwargs={
                "model_gen_options": {
                    "optimizer_kwargs": {
                        "equality_constraints": equality_constraints,
                    },
                }
            },
        ),
    ]
)

objectives = {
    objective_name: ObjectiveProperties(minimize=False)
    for objective_name in objective_names
}

# setup the experiment
experiment_name = "dummy"
ax_client = AxClient(generation_strategy=gs)
ax_client.create_experiment(
    name=experiment_name,
    parameters=tight_parameters,
    parameter_constraints=parameter_constraints,
    objectives=objectives,
)
```

Sum of values for each of the 5 suggested trials:
```
1.3888615406118334
1.5019170874496923
1.3481515500461685
1.0915423575090244
1.0647917828755453
```
(i.e., not summing to 1.0).

I'll try to include a simple example using the technique mentioned in the EDIT above.

**Comment by Abrikosoff** [comment]
@sgbaird Prof. Baird, sorry to reactivate this closed issue, but I am running (almost) exactly into the same problem as you here (only I have a nonlinear_inequality_constraint instead of your equality_constraint); may I ask how did you manage to solve this problem?
