### ISSUE TITLE
Support inequality constraints for knowledge gradient as long as they are not inter-point

### ISSUE THREAD

**Issue by esantorella** [facebook/Ax#1639]
See https://github.com/pytorch/botorch/issues/1220 for context. BoTorch does support inequality constraints (and probably also equality constraints) with knowledge gradient, as long as they are not inter-point. That means that when the `indices` field of a constraint is 1d, it's okay, but when it's 2d, there will be an error.

Currently, Ax will [error if any inequality constraints are provided](https://github.com/facebook/Ax/blob/23008c6d18e3fbd102a0a748c2e97063d02d9a63/ax/models/torch/botorch_kg.py#L136), even though constraints that are not inter-point will work. So this error can become

```python
if inequality_constraints is not None:
    indices, _, __ = inequality_constraints
    if indices.ndim >= 2:
            raise UnsupportedError(
                "Inter-point constraints are not yet supported for KnowledgeGradient!"
            )
```

Then there will be some further work needed to use the constraints in the 1d case.

**Comment by lena-kashtelyan** [comment]
Merged to a larger KG issue.

**Comment by esantorella** [comment]
This should be supported by using [botorch_modular](https://ax.dev/tutorials/modular_botax.html) with inequality constraints.
