### ISSUE TITLE
How to save and load my Ax Client and experiment

### ISSUE THREAD

**Issue by KamjiLee** [facebook/Ax#164]
I'm trying to use Ax to maximize a function, and wonder how to save and load my client.

```
my_ax = AxClient()

my_ax.create_experiment(
    name='value',
    parameters=[
        {"name": "x", "type": "choice", 'values' : [1,2,3,4,5]}
    ],
    objective_name="y"
)

for i in range(4):   
    parameters, trial_index = my_ax.get_next_trial()
    my_ax.complete_trial(trial_index=trial_index, raw_data=1)

my_ax.save('client.json')
ax.save(my_ax.experiment, 'exp.json')
```

Then I tried 

```
new = AxClient()

new = new.load('client.json')
new.load_experiment('exp.json')
```

But then it gives an error like

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-112-184fdad25d6f> in <module>()
     21 
     22 new = new.load('client.json')
---> 23 new.load_experiment('exp.json')

/usr/local/lib/python3.6/dist-packages/ax/service/ax_client.py in load_experiment(self, experiment_name)
    468         if not self.db_settings:
    469             raise ValueError(  # pragma: no cover
--> 470                 "Cannot load an experiment in the absence of the DB settings."
    471                 "Please initialize `AxClient` with DBSettings."
    472             )

ValueError: Cannot load an experiment in the absence of the DB settings.Please initialize `AxClient` with DBSettings.
```

Is there a simple way to just save-load my optimization?

**Comment by lena-kashtelyan** [comment]
Hey, @KamjiLee, just to clarify, it seems that you are looking to save the optimization to `.json` file, not to an SQL database, so the functions you need are:

```
ax_client.[save](https://ax.dev/api/service.html#ax.service.ax_client.AxClient.save)(filepath='my_json.json')
AxClient.l[oad](https://ax.dev/api/service.html#ax.service.ax_client.AxClient.load)(filepath=my_json.json')
```
You can also not pass a `filepath` argument  to `save` and `load`, in which case it will use the default. 

`ax_client.[load_experiment](https://ax.dev/api/service.html#ax.service.ax_client.AxClient.load_experiment)` is used to reload an experiment saved to an SQL database. If that is what you are trying to do, you will need to pass DB settings to `AxClient` on instantiation and reload the experiment by its name (no need to separately save it, it will be saved each time a change is made). 

You will need the latest stable version for the saving functionality, so do make sure to update your Ax installation to 0.1.5. 

Feel free to reopen the issue if that doesn't work or if you are in fact trying to save to an SQL backend!

**Comment by sgbaird** [comment]
> ```python
> # Reinstantiate an `AxClient` from a JSON snapshot.
> ax_client = AxClient.load(filepath='my_json.json')
> ```
I believe this syntax was updated:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[c:\users\sterg\documents\github\sparks-baird\ax\ax\service\ax_client.py]()", line 1739, in load
    raise NotImplementedError(
NotImplementedError: Use `load_experiment_from_database` to load from SQL database or `load_from_json_file` to load optimization state from .json file.
```

So:
```python
# Reinstantiate an `AxClient` from a JSON snapshot.
ax_client = AxClient.load_from_json_file(filepath='my_json.json')
```
