### ISSUE TITLE
Set `num_samples` and `warmup_steps` in SAASBO

### ISSUE THREAD

**Issue by ga92xug** [facebook/Ax#1640]
It is not possible to set warmup_steps to a different number in this tutorial https://ax.dev/tutorials/saasbo_nehvi.html. It says:
use fewer num_samples and warmup_steps to speed up this tutorial
num_samples=256,
warmup_steps=512,

But if we now toggle disable_progbar to False we see that this setting does not work. How can we set the warmup_steps? I have read somewhere that so many warmup steps are in general a bit much. 

I have an additional question. The fitting function runs for 5 epochs right? Because I get this progress bar 5 times. Is there somewhere documentation where I can read up on that. And what num_samples and warmup_steps does.

**Comment by dme65** [comment]
Hello @ga92xug,

> It is not possible to set warmup_steps to a different number in this tutorial https://ax.dev/tutorials/saasbo_nehvi.html

It should be possible to change the values of `num_samples` and `warmup_steps `. I just verified that this works as expected in this tutorial (setting `num_samples=128` and `warmup_steps=256` results in a total of 384 steps). Note that we also define smaller values of these parameters in the case `SMOKE_TEST` is set to `True`. These settings are only being used to make our tests run faster, so changing those values will not have an effect in your case.

> I have read somewhere that so many warmup steps are in general a bit much.

We have seen that using `num_samples=128` and `warmup_steps=256` can work well in some cases, but in this tutorial we just use the same settings as was used in the SAASBO paper.

> The fitting function runs for 5 epochs right?

No, the fitting only runs once per objective, so you should observe exactly two progress bar when calling `model.gen`.

**Comment by ga92xug** [comment]
Hello @dme65, 

thanks for the detailed explanation. Now everything is a lot clearer.

I did not get the progress bar at first. I thought 512 steps would appear there. And it would train on 128 samples. Now it is clear. Can you give some guidelines on how to set num_samples and warmup_steps? Is it in general a good baseline to start with the defaults or does it make sense to increase them depending on how long the evaluation of 1 trial takes?

**Comment by lena-kashtelyan** [comment]
Hi @ga92xug ! Please let us know if the answer @dme65 gave above is not exhaustive/if there is still something you are wondering. Please reopen the issue if you follow up, as we are unlikely to see comments on a closed issue.
