### ISSUE TITLE
get_next_trial does not have max_trials argument

### ISSUE THREAD

**Issue by ga92xug** [facebook/Ax#1644]
https://github.com/facebook/Ax/blob/99a7052c9080893641bc5290b8a8a6e059abda0c/ax/service/ax_client.py#L504

The get_next_trial does not have a max_trials argument as state here: https://ax.dev/api/_modules/ax/service/ax_client.html#AxClient.get_next_trials

**Comment by Balandat** [comment]
You're looking at the code of `get_next_trial` but at the documentation of `get_next_trials` - these are different methods. Seems to be all in order to me.
