### ISSUE TITLE
Start generator run from callable and function bounds

### ISSUE THREAD

**Issue by hvarfner** [facebook/Ax#1662]
Hi,

I've been using Ax through the AxClient, but since I now need to run batch trials, I'm looking to set up a generator run.

Most (all?) tutorials use a `setup_branin_experiment` or similar, so this part of the experiment setup is slightly overlooked in my opinion. So, how does one set up a general (batch) generator run from a callable  `f` and `bounds`?

**Comment by hvarfner** [comment]
Sequential greedy is indeed fine for now, so that solves it. I was under the impression that `AxClient` did not support it, but I'm glad to see I was mistaken.

If, in the future, sequential greedy would _not_ suffice (so joint optimization indeed), do I need to change interfaces?

**Comment by Balandat** [comment]
> If, in the future, sequential greedy would not suffice (so joint optimization indeed), do I need to change interfaces?

I believe currently `AxClient` does not support joint optimization of the acquisition function, but it would be rather straightforward to add this (e.g. via a `jointly_optimize` kwarg to `get_next_trials()` or some kind of setting on the client). Do you have a concrete use case for this coming up? If not we should probably hold off implementing this until it becomes needed.

**Comment by hvarfner** [comment]
No, it seems like the greedy approach will suffice - it was primarily out of curiosity. Thanks for taking the time!
