### ISSUE TITLE
figure not showing in multi-task tutorial notebook on ax.dev

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1673]
This isn't a problem for me since I'm looking at a downloaded copy. Normally, I thought these would appear, so I figured I'd pass this on.

See the snippet from https://ax.dev/tutorials/multi_task.html

![image](https://github.com/facebook/Ax/assets/45469701/ff24855c-71de-4581-996a-f7c1b27e8a6e)

Same in https://ax.dev/tutorials/multiobjective_optimization.html (and probably others)

Related, but I think it's a different issue than https://github.com/facebook/Ax/issues/306

**Comment by lena-kashtelyan** [comment]
@mpolson64 and @saitcakmak are looking into addressing this; our website build script is currently not healthy and we cannot re-publish it.

**Comment by saitcakmak** [comment]
Closing as the issues with the plots have been resolved
