### ISSUE TITLE
Optimization of Acquisition Function subject to Parameter Constraints

### ISSUE THREAD

**Issue by chakrabarti** [facebook/Ax#169]
I have been running into issues generating points that obey the parameter constraints I specify. Below is a simple example that should reproduce the issue (I realize that the linear constraint can just be incorporated as an upper bound on the parameter types).

Do I need to manually implement an acquisition function in Botorch that can handle parameter constraints? I didn't seem to have this issue earlier when I was using the Service API but the points generated by the BOTORCH model don't seem to respect the constraints.
```
from ax import (
    ParameterType, 
    RangeParameter,
    SearchSpace, 
    SimpleExperiment, 
    ParameterConstraint
)

from ax.modelbridge.registry import Models
parameters = [RangeParameter(name = "x1", parameter_type = ParameterType.FLOAT, lower = 0, upper = 100)]
constraints = [ParameterConstraint({"x1": 1}, 5)]
search_space = SearchSpace(parameters = parameters, parameter_constraints = constraints)
exp = SimpleExperiment(name = "dummy", search_space = search_space, evaluation_function = lambda d : abs(d['x1'] - 5))
print(f"Running Sobol initialization trials...")
sobol = Models.SOBOL(exp.search_space)
for i in range(5):
    exp.new_trial(generator_run=sobol.gen(1))
    
for i in range(10):
    print(f"Running GP+EI optimization trial {i+1}/10...")
    # Reinitialize GP+EI model at each step with updated data.
    gpei = Models.BOTORCH(experiment = exp,  data=exp.eval())
    batch = exp.new_trial(generator_run=gpei.gen(1))
    print(batch)
```

**Comment by ldworkin** [comment]
Hi @chakrabarti ! Thanks for reporting this issue. Someone on our team will look into it ASAP. I'll keep you posted!

**Comment by lena-kashtelyan** [comment]
Hello, @chakrabarti! I'm seeing the exact same behavior with the Service API; if you still have the example that was working for you, it would be very helpful to see it! Service API does not support `ParameterConstraint`, also, so maybe your constraint was different?

In the meantime, we will investigate this further, since it seems that this is not simply an API issue.

**Comment by chakrabarti** [comment]
It seems like I can't replicate this exact problem in the Service API. I think perhaps this issue only occurs if the constraint plane is orthogonal to one of the dimensions (so that the vector defining the constraint only has 1 non-zero entry and the constraint is essentially a bound on the variable corresponding to the non-zero entry).

However, I am still curious why this happens in this case (I want to be sure that this doesn't occur for constraints involving multiple variables and even though it seems to work, it seems like there isn't anything fundamentally different between the two cases). Is the constrained optimization guaranteed to work if multiple variables are involved in the constraints (barring an infeasible region or some other issue like that)?
