### ISSUE TITLE
The output of Multi-Objective Optimization is not render figure but the json file.

### ISSUE THREAD

**Issue by Shu1999-07** [facebook/Ax#1715]
Hello,
I try to use the Service API to run Multi-Objective Optimization just like the tutorial. But I cannot get the figure of the Pareto-front, but the json file like the picture show. I don't know how to solve it. Could you please help me?

![7f2031a26e199a37a89654a1b003a48](https://github.com/facebook/Ax/assets/120472496/d23db793-7870-4c1a-9861-3b173520daac)

**Comment by Balandat** [comment]
What environment are you running this in? Jupyter notebook? This looks like the command line (the visualization code in the tutorial is meant to be run in a notebook).

**Comment by lena-kashtelyan** [comment]
@Shu1999-07, please let us know about what environment you are running this in. As @Balandat mentioned, this code is meant for Jupyter notebooks, so it just won't work from the command-line.

**Comment by Shu1999-07** [comment]
Sorry for late reply, I try to run this in notebook and it worked. :)

**Comment by lena-kashtelyan** [comment]
Great news! Seems resolved, so closing this off.
