### ISSUE TITLE
ax.models.torch.botorch_modular.model.BoTorchModel API docs is inconsistent with source code doc

### ISSUE THREAD

**Issue by smao-astro** [facebook/Ax#1720]
Dear developers and contributors,

The input parameter documentation at https://ax.dev/api/models.html#ax-models-torch-botorch-modular-model-module indicates that `BoTorchModel` has an input `surrogate_options`, which is inconsistent with the source code below

https://github.com/facebook/Ax/blob/99bf4c8f728390e4adcdf9b80e2441edfedff7d7/ax/models/torch/botorch_modular/model.py#L100-L136

which expects a parameter `surrogate_specs` instead.

**Comment by mpolson64** [comment]
Hi @smao-astro, it looks like our website documentation is out of date here. We're working through some technical difficulties on our end with the system that translates docstrings into website pages, but hope to get a new website version built and updated soon. In the meantime, the docstrings are the most up to date information.

Thanks for bearing with us while we update our documentation.

**Comment by esantorella** [comment]
The website has been updated. You'll need to toggle "v: latest" in order to see documentation that matches the GitHub source code rather than the most recent release.
