### ISSUE TITLE
Question about setting specified parameters.

### ISSUE THREAD

**Issue by yjhong89** [facebook/Ax#176]
Hello.

I am trying to use Ax for a problem which seems to be solved by a bandit optimization.

Here, I have a question about how I can set specified parameters (arms in Ax) for function evaluation.

For example, I have two parameters named 'x1' and 'x2' which have 'x1' in {1,2,3} and 'x2' in {1,2}, respectively.

I read this tutorial(https://ax.dev/docs/core.html) and I can set a search space through Choice parameters or Range parameters(int).

The problem is I have true evaluation function values for specific combination of 'x1' and 'x2'. 
e.g) I have f(x1=1, x2=1) but I don't know f(x1=3, x2=2).

Therefore, I want to specify a search space in a way that makes it have parameter combinations I know real function values. (do not need search (x1=3, x2=2) from above examples)

How can I do that? Please help.

Thanks in advance.

**Comment by kkashin** [comment]
Hey @yjhong89 - great question. 

We do support certain forms of constraints on the search space, but they do not generally allow for the kind of flexibility that I think you want in this case, if I understand you correctly. You're really asking for an ad hoc, non programmatically generated, set of initial arms for your initial exploration round, which you will then run the bandit algorithm on top of.

I've attached an example notebook that adapts the bandit tutorial to demonstrate how one can manually select the initial arms instead of using a full-factorial design (which will take combinations of all the arms in the search space) for the initial exploration trial / round, and then run the bandit algorithm. 

See the ipynb and html of notebook here: 
[bandit_adhoc.zip](https://github.com/facebook/Ax/files/3693614/bandit_adhoc.zip).

Can you let me know if this addresses your question?

Longer term, we're working on improving our APIs to better support ad hoc search spaces.

**Comment by yjhong89** [comment]
@kkashin - Thank you for your answer. 

I will try your solution and let you know.

Thanks.

**Comment by 2timesjay** [comment]
@yjhong89  if the unknown areas of your search space can be represented as linear constraints (the valid area is a convex linear polytope) then you can use [ParameterConstraints](https://our.internmc.facebook.com/intern/anp/view/?id=150460). These are accepted as arguments to the Search Space.

If your invalid areas can't be represented this way (if they're "holes" in the search space for instance) then your solution is pretty similar to any other options I could suggest. Creating your own [RandomModel](https://github.com/facebook/Ax/blob/master/ax/models/random/base.py) would be a reasonable but heavyweight option that would let you implement custom rejection sampling.

**Comment by lena-kashtelyan** [comment]
@yjhong89, I believe you can also do Bayesian optimization on search spaces that consist of `ChoiceParameter`-s, however, you would still have to mark some trials as failed right away if they cannot be described as constraints and you don't want to just exclude those parameter values from the search space.

May I ask a bit more about your use case? How many total valid combinations are in your search space? Are all of your parameters choice? What percentage of the total number of combinations you know to be invalid?

**Comment by yjhong89** [comment]
@2timesjay
Thanks for your suggestion.
I tried to constraint my search space, but I think it is not proper in my case since empty combinations in my search space are not represented in convex representation.

@lena-kashtelyan 
I already tried ChoiceParameter but this case is similar to IntRangeParameter in that I would still have to reject manually some inputs.
My case consists of 8 input parameters each of which have 3 cases (0,1,2) so 3**8=6561 cases in total.
But I have results for only 200 results since function evaluation for each input case is very slow. 
I tried to use Ax to apply bayesian optimization for cases I have in now.
By the way, does bayesian optimization with gaussian process surrogate model work well with discrete input cases? I think it becomes tricky due to kernel representation. 
Or does Ax support tree parzen estimator surrogate model used in hyperopt?

Thank you.

**Comment by lena-kashtelyan** [comment]
@yjhong89, hi again! 

I am still somewhat confused about your setup –– please correct if my understanding below is wrong: 

1. You already have a set of 200 evaluation results for some parameter configurations in your search space, 
2. You are not looking to evaluate more configurations, but rather to find the best one among your results,
3. Ideally, you want all trials suggested via BayesOpt, to fall into the pool of 200 configurations you already have evaluated?

If this is the setup, then what is the expected use of BayesOpt here?

------

Re: TPE, we do not use it, the surrogate model is always Gaussian process.
Will get back to you re: performance of BayesOpt on discrete search spaces.

**Comment by yjhong89** [comment]
@lena-kashtelyan, Thanks for your answer.

You understand correctly. You are right.
But the expected use of BayesOpt is not important to me.
I just wanted to check how Ax works in discrete and holed search space technically,
since in my domain, there are situations where some parameter combinations in search space is not necessary to evaluate.

Thanks.

**Comment by lena-kashtelyan** [comment]
@yjhong89, would you say I fully answered your question or is there anything else you would like me to clarify?

**Comment by yjhong89** [comment]
@lena-kashtelyan 
I am satisfied for your answers and good for closing this issue.
