### ISSUE TITLE
The render can not work in my jupyter notebook

### ISSUE THREAD

**Issue by yuanquan010** [facebook/Ax#1768]
After running the BO optimization, I tried to plot the optimization trace, however, the render command can not work, it always remains a running condition. What's the reason?
![image](https://github.com/facebook/Ax/assets/54976645/bd8c2980-b801-4518-a803-7c6374094ac9)

**Comment by mpolson64** [comment]
Could you post your notebook, or at least the cells required for a minimal reproduction? It looks like you may need to initialize notebook plotting
```
from ax.utils.notebook.plotting import init_notebook_plotting

init_notebook_plotting()
```
but its hard to say without the full source. Thank you!

**Comment by lena-kashtelyan** [comment]
Closing this as inactive. @yuanquan010, please reopen the issue if you do follow up!
