### ISSUE TITLE
How to add order / type constraints?

### ISSUE THREAD

**Issue by dqii** [facebook/Ax#177]
I was looking at the sample code at the bottom of https://ax.dev/.

I want to add constraints. E.g., x1 <= x2 or x1 must be integer.
There is an API for constraints here: https://ax.dev/tutorials/building_blocks.html

But it seems incompatible with the first API. The first API is very simple, so I'd like to use that if possible. I looked in the repo and couldn't find a suitable API.

Could someone help me with this? Thanks so much!

**Comment by dqii** [comment]
I found this example which was helpful:
https://ax.dev/tutorials/gpei_hartmann_loop.html

And also this code which defined the parameter constraints:
https://github.com/facebook/Ax/blob/230cdb5f6cec123aebe872b0f1d8f784f9a2f23b/ax/service/utils/instantiation.py

**Comment by 2timesjay** [comment]
Hi @dqii,

Take a look at https://ax.dev/api/_modules/ax/service/utils/instantiation.html#constraint_from_str

We can parse order constraints of the form "x1 >= x2" from strings, but for more general constraints we suggest using the classes from your other link. 

To constrain a variable to be an int with the Loop API you can define it as follows:

```

        {
            "name": "x1",
            "type": "range",
            "bounds": [0, 10],
            "value_type": "int",  # Optional, defaults to inference from type of "bounds".
        },
```
