### ISSUE TITLE
How to run a SMOKE_TEST with multi-fidelity knowledge gradient / `GPKG`? (still too slow)

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#1775]
I can't seem to get it any faster than ~40 seconds with the following approach:
```python
...
gs = GenerationStrategy(
    steps=[
        GenerationStep(model=Models.SOBOL, num_trials=num_sobol),
        GenerationStep(
            model=Models.GPKG,
            num_trials=-1,
            model_gen_kwargs=dict(num_fantasies=2, num_restarts=2, raw_samples=8),
        ),
    ]
)
ax_client = AxClient(generation_strategy=gs)
...
```
See this reproducer: https://colab.research.google.com/gist/sgbaird/bea31550d44a04b233be32769dced7c0/6-2-1-multi-fidelity-continuous.ipynb

You can ignore everything until the cell with `from ax.service.ax_client import AxClient`

Aside: it was slower when switching to CUDA with my RTX 2060 (not a smoke test).

**Comment by mpolson64** [comment]
@saitcakmak can you weigh in here on expected performance of MFKG?

**Comment by saitcakmak** [comment]
Hi @sgbaird. The `model_gen_kwargs` you're passing in are being ignored. This docstring explains how to pass these in: https://github.com/facebook/Ax/blob/main/ax/models/torch_base.py#L58-L69

In your case, this would look like
```
model_gen_kwargs = {
    "model_gen_options": {
        "optimizer_kwargs": {
            "num_restarts": 2,
            "raw_samples": 8,
        },
        "acquisition_function_kwargs": {"num_fantasies": 2},
    },
},
```

**Comment by lena-kashtelyan** [comment]
Sounds like this might be resolved, @sgbaird? : )

**Comment by sgbaird** [comment]
Yes, thank you!
