### ISSUE TITLE
Setting parameter constraints of the form x - y >= 1

### ISSUE THREAD

**Issue by dqii** [facebook/Ax#178]
It seems like parameter restraints are very strict, so x - y >= 1 does not work. Is it possible to support this in the future or does something prevent it?

"Parameter constraint should be of form <parameter_name> >= <other_parameter_name> for order constraints or `<parameter_name> + <other_parameter_name> >= x, where any number of parameters can be summed up and `x` is a float bound. Acceptable comparison operators are ">=" and "<=".'

**Comment by 2timesjay** [comment]
Using the [ParameterConstraint](https://ax.dev/api/core.html#ax.core.parameter_constraint.ParameterConstraint) class, 

`ParameterConstraint(constraint_dict={"x": 1, "y": -1}, bound=1)`

Will work. Constraints of this form cannot currently be parsed from strings expressions.

**Comment by lena-kashtelyan** [comment]
@dqii, it seems that you are using the Service or Loop APIs? For those, only addition is supported at the moment, but I will flag this as something we need to add. To use the answer Jacob provided above, you would need to use the Developer API. 

Also, one solution could be simply changing your problem setup such that you convert y to -y in your evaluation procedure –– that might be the fastest way to get your constraint working for now.

**Comment by dqii** [comment]
Correct, I'm using the Loop API currently. Thanks for the response!

**Comment by lena-kashtelyan** [comment]
@dqii, this functionality is now available on `master`, check [latest version](https://github.com/facebook/Ax#latest-version) for installation instructions. This will also be included in the next stable version when it comes out.

**Comment by lena-kashtelyan** [comment]
This functionality is now part of the latest stable version, 0.1.8!
