### ISSUE TITLE
Changing colormap scheme of get_contour_plot

### ISSUE THREAD

**Issue by VMLC-PV** [facebook/Ax#1787]
Is there any way to customize the colormap when using:

`ax_client.get_contour_plot(param_x=params[0].name,param_y=params[2].name, metric_name=obj_type) `

Like what if I want viridis colormap?

Thanks for your help

**Comment by VMLC-PV** [comment]
Once again I post here and find the solution...
You need to update the colorscale of the object

```python
plot = ax_client.get_contour_plot(param_x=params[0].name, param_y=params[-1].name, metric_name=obj_type)  
colorscale = np.asarray(plot.data['data'][0]['colorscale'])  
#create an rgb array for viridis color scale  
viridis = cm.get_cmap('viridis', len(colorscale[:,0]))  
colors = plt.cm.viridis(np.linspace(0, 1, len(colorscale[:,0]))).tolist()  
for i in range(len(colors)):  
    colors[i] = f'rgb{tuple([int(255*x) for x in colors[i][:-1]])}'  # convert colors to rgb  
plot.data['data'][0]['colorscale'] = colors  
render(plot)   
```

**Comment by bernardbeckerman** [comment]
![gif](https://media.tenor.com/LnBL4k3CN8wAAAAC/liz-lemon-self-high-five.gif)
Thanks for raising and resolving this issue @VMLC-PV! Good to know!
