### ISSUE TITLE
[Question] How to skip the Sobol step from the generation strategy and initialize the model with existing data?

### ISSUE THREAD

**Issue by klywa** [facebook/Ax#180]
I have some initial evaluations and I want  to go straight in to GPEI steps. How can I skip the Sobol step and use my existing data to initialize the model? Thanks.

**Comment by stevemandala** [comment]
Closing out. Feel free to reopen if you have any followup questions

**Comment by lena-kashtelyan** [comment]
https://github.com/facebook/Ax/issues/199 has another example of custom generation strategy; linking here just in case someone looking for that example checks out that issue.
