### ISSUE TITLE
Duplicate trial_index+arm_name identifiers

### ISSUE THREAD

**Issue by wlanghans** [facebook/Ax#1803]
When combining trial index and arm name to one identifier there's currently the possibility that the resulting identifier is not unique. For example, trial index 17 and arm 7_0 will yield 177_0, but trial index 1 and arm 77_0 will also yield 177_0. 

This will in line 463 in report_utils.py where duplicate entries are searched for, lead to a data frame without results. An easy fix is to just add a hyphen between trial index and arm name when creating the ID string.

**Comment by mpolson64** [comment]
Thanks for noticing this. I've put up a PR to address this and it should make it into the next release. https://github.com/facebook/Ax/pull/1807
