### ISSUE TITLE
Questions about multi-objective optimization.

### ISSUE THREAD

**Issue by showgood163** [facebook/Ax#185]
Hi, newbie here!

I have a question about *Multi-objective optimization* mentioned [here](https://ax.dev/docs/why-ax.html).

Does Ax have the ability to simultaneously optimize more than one [objectives](https://ax.dev/api/ax.html#ax.Objective)? If so, how do I achieve that? Is there any suggestions/tutorials?

**Comment by BCJuan** [comment]
Hi,

There is an objetive function class named `ScalarizedObjective` in `ax.core.objective.ScalarizedObjective` which allows to establish several metrics and weights among them. 

https://ax.dev/api/core.html?highlight=scalarized%20objective#ax.core.objective.ScalarizedObjective

indeed, you could also change the weights of each of the objectives whenever you desired to by accessing them from the experiment configuration in the squence generator or in the experiment directly. Take a look to the "Human in the loop tutorial" to see the change in action.

**Comment by sdsingh** [comment]
Hey there! Thanks for the answer, @BCJuan!

Typically, our users deal with multiple-objective optimization by specifying both an `Objective` and a series of `OutcomeConstraints`. The "Human in the loop tutorial" demonstrates how one can set and adjust `OutcomeConstraints`/`Objectives` to obtain a different set of results. 

In that tutorial, we don't actually use `ScalarizedObjective`. Typically, users find it difficult to come up with a single scalarization of their multi-objective problem, and thus prefer the `Objective` + `OutcomeConstraint` formulation.

If you would prefer to use `ScalarizedObjective`, you could attempt to change the weights within the objective, and repeatedly generate candidates, in a similar fashion to the tutorial.
