### ISSUE TITLE
status_quo not being properly set on ModelBridge object

### ISSUE THREAD

**Issue by thiago-franco** [facebook/Ax#186]
## Context

I am trying to use Ax to perform an optimization on video streaming metrics (such as playtime, buffering, bitrate, etc) by experimenting with video playback parameters. For this, I am using the Developer API and several custom metrics. The first batch of parameters is given by Sobel and the model for the next iterations is BoTorch. There is a control alternative (status quo) set to the experiment and some outcome constraints. As there are many features, I have passed the                               `status_quo_features` with `ObservationFeatures.from_arm(control_arm, trial_index))` to the BoTorch initialization.

## Problem

When using several custom metrics, as soon as I reach the iteration where the BoTorch model is used, I keep receiving the error `"Optimization config has relative constraint, but model was         not fit with status quo."`, meaning the status_quo property was not being set on the ModelBridge object as expected. 

Further investigation lead me to find that this bug was somehow related to the use of many custom metrics. When using only one, the status_quo was properly set and I could run the experiment just fine. 

## Solution

In fact, there is no json encoder registered for the ObservationFeatures type and it turns out this is the cause of the status_quo not being set on the ModelBridge. 

The solution, as implied, is to add a json encoder to the ObservationFeatures.

**Comment by ldworkin** [comment]
Hi @thiago-franco ! Thanks so much for reporting this and implementing the fix! I'll take a look at your PR shortly.

**Comment by ldworkin** [comment]
Since https://github.com/facebook/Ax/pull/187 got in, this should be fixed! Let me know if not
