### ISSUE TITLE
Recommendation of implementation when we can do unlimited number of trials

### ISSUE THREAD

**Issue by Yuancheng-Xu** [facebook/Ax#1860]
Hi!

I am currently using the service API for a black-box optimization problem. The input is parameters of a deep neural network, and the output is its performance. For my problem, the dimension of the optimizing variables is 5 and I am allowed to use as many trials as I would like to (say, 2000). 

I wonder in this case where trial budget is high, are there any recommendation on implementations to take advantage of the high trial budget? For example, modifying the Generation Strategy. It seems that the Auto-selected GS for a 5-dimensional problem is Sobol for 10 trials, GPEI for subsequent trials. However, it does not seem to consider the number of trial budgets (in this case, say 2000).

Any recommendation is appreciated!

**Comment by Balandat** [comment]
> I am allowed to use as many trials as I would like to

How costly (in terms of compute or wall time) is a single evaluation of the output? Does this require a NN training job or some other costly evaluation? If not and this is very fast and you indeed have almost unlimited budget then Ax and its algorithms that focus on sample-efficient Bayesian optimization may not be the right tool for the job.

**Comment by Yuancheng-Xu** [comment]
Well in my case the cost of one trial is a forward pass of a large language model. I would say it is not that expensive (several seconds per forward pass) nor super cheap. I wonder how I can modify the generation strategy to take this into considerations.

**Comment by Balandat** [comment]
I see. The number of random initial trials is probably not all that important here then. And GPEI should be a good initial starting point (@SebastianAment are we using log(N)EI already by default here?).

The main challenge will be that candidate generation will slow down pretty substantially once you've gathered a few hundred data points. We can consider more scalable models, but with just 5 parameters you may really need to go there. So I'd recommend just trying this out with the defaults to see how well that works. 

I'm curious, what are the parameters you're tuning if the eval is just a forward pass?

**Comment by SebastianAment** [comment]
> are we using log(N)EI already by default here?

Yes, `qLogNEI` is the default for both MBM and legacy models.

**Comment by Yuancheng-Xu** [comment]
Thanks Balandat! Yeah I will try out the default first.

I am doing a project on tuning a large model with only forward passes, and the tuning parameters are only governed by, say, 5 free parameters (multiplied by a random matrix).

**Comment by lena-kashtelyan** [comment]
Assigning to @sdaulton, M&O oncall at the time of this issue opening.

@Yuancheng-Xu, is this issue resolved?

**Comment by Yuancheng-Xu** [comment]
Yes! Thanks a lot!
