### ISSUE TITLE
[Question] How to enforce high parallelism in Generation Strategy

### ISSUE THREAD

**Issue by yuanqing-wang** [facebook/Ax#1883]
When using Generation Strategy in this tutorial: https://ax.dev/tutorials/generation_strategy.html to generate trials for `ray.tune`, even if I set the `max_ parallelism` to a high number the strategy generates few trials at a time. Is there a way to force the algorithm using (very) high parallelism, i.e. generating numerous trials all at once.

**Comment by lena-kashtelyan** [comment]
Hi @yuanqing-wang! A couple things:
1. How high is the very high parallelism? If we're talking hundreds of trials, candidate generation might get quite slow. If you want to tell us more about what you are looking to do, we will be able to advise on the optimal optimization methodology.
2. Please see my answer here: https://github.com/facebook/Ax/issues/1702#issuecomment-1650637928; this might be about the `num_trials` setting for the first generation step in your strategy. Please paste your whole generation strategy for us to look at, and we will be able to give a more precise answer.

**Comment by lena-kashtelyan** [comment]
Closing this as inactive, @yuanqing-wang. Please reopen if you need more help (we won't see a follow up on a closed issue).
