### ISSUE TITLE
Hierarchy of experiments

### ISSUE THREAD

**Issue by newtonle** [facebook/Ax#189]
I'm interested in using AxClient with a SQL backend for multiple users at Twitter. Ideally, the experiments would be grouped by users and projects. Is there any recommended way of doing this? Or is this on a roadmap? How can I be aware of future features for Ax?

**Comment by kkashin** [comment]
@newtonle - thanks for your interest! Can you elaborate what you mean by "grouping" in this case, and the sort of API you'd like to use for accessing this grouping? Phrased differently, what is the sort of functionality you hope to leverage this grouping for?

We are actually working on a way of grouping experiments into "Projects" (where the project may have some basic metadata, such as owners, description, etc.). At the moment, this is not yet available through the ServiceAPI, but if I better understand how you want to use this abstraction, we can evaluate building that out.

I'd be happy to discuss this in more detail over a phone call, as well; feel free to contact me at kkashin (at) fb (dot) com.

**Comment by newtonle** [comment]
Essentially, imagine a directory-like structure, where an experiment is referenced by `user/project/experiment_name`. This would prevent things like name collisions, say two users want the experiment_name "test". I wasn't thinking of an API per se, but we have an experimenting tracking web UI that I was hoping could tap into this structure. I'll email you with my contact info so we can discuss.

**Comment by lena-kashtelyan** [comment]
We will now be tracking wishlist items / feature requests in a master issue for improved visibility: #566. Of course please feel free to still open new feature requests issues; we'll take care of thinking them through and adding them to the master issue.
