### ISSUE TITLE
[Question/Documentation] Not showing graphs on JupyterLab in python 3.7

### ISSUE THREAD

**Issue by casassg** [facebook/Ax#192]
Plotly plots don't show up on JupyterLab when running under python 3.5+. After some debugging and exploration, I found information on the [plotly.py repo](https://github.com/plotly/plotly.py#jupyterlab-support-python-35) that mentions the requirement to install a couple of `labextension` for plotly.py to work properly. 

Posting this here to see if there's anything that can be done on terms of documentation for installation.

**Comment by lena-kashtelyan** [comment]
@casassg, thank you for bringing this to our attention! https://github.com/facebook/Ax/pull/196 should address it : )
