### ISSUE TITLE
Can't run REMBO in a standard env

### ISSUE THREAD

**Issue by lujiaming-12138** [facebook/Ax#1924]
I am runing the code of Alebo, a quickstart.ipynb, but when i use the REMBOStrategy instead of ALEBOStrategy, i got wrong!
I use 'eneration_strategy=rembo_strategy' in funtion optimize. Here are my code.
______________________________________________________
import numpy as np
from ax.utils.measurement.synthetic_functions import branin

def branin_evaluation_function(parameterization):
    x = np.array([parameterization["x0"], parameterization["x1"]])
    return {"objective": (branin(x), 0.0)}

parameters = [
    {"name": "x0", "type": "range", "bounds": [-5.0, 10.0], "value_type": "float"},
    {"name": "x1", "type": "range", "bounds": [0.0, 15.0], "value_type": "float"},
]
parameters.extend([
    {"name": f"x{i}", "type": "range", "bounds": [-5.0, 10.0], "value_type": "float"}
    for i in range(2, 100)
])

from ax.modelbridge.strategies.alebo import ALEBOStrategy
from ax.modelbridge.strategies.rembo import REMBOStrategy
alebo_strategy = ALEBOStrategy(D=100, d=4, init_size=5)
rembo_strategy = REMBOStrategy(D=100, d=4, k=1, init_per_proj=4)

from ax.service.managed_loop import optimize

best_parameters, values, experiment, model = optimize(
    parameters=parameters,
    experiment_name="branin_100",
    objective_name="objective",
    evaluation_function=branin_evaluation_function,
    minimize=True,
    total_trials=30,
    generation_strategy=rembo_strategy,
)
______________________________________________________

[INFO 10-20 23:58:31] ax.service.managed_loop: Started full optimization with 30 steps.
[INFO 10-20 23:58:31] ax.service.managed_loop: Running optimization trial 1...
[INFO 10-20 23:58:31] ax.core.experiment: No trials are in a state expecting data.
[INFO 10-20 23:58:31] ax.service.managed_loop: Running optimization trial 2...
[INFO 10-20 23:58:32] ax.service.managed_loop: Running optimization trial 3...
[INFO 10-20 23:58:32] ax.service.managed_loop: Running optimization trial 4...
[INFO 10-20 23:58:32] ax.service.managed_loop: Running optimization trial 5...
[ERROR 10-20 23:58:32] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/service/managed_loop.py", line 228, in full_run
    self.run_trial()
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/utils/common/executils.py", line 161, in actual_wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/service/managed_loop.py", line 202, in run_trial
    trial = self._get_new_trial()
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/service/managed_loop.py", line 160, in _get_new_trial
    generator_run=self.generation_strategy.gen(
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/modelbridge/strategies/rembo.py", line 204, in gen
    gr = m.gen(n=n)
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/modelbridge/base.py", line 805, in gen
    gen_results = self._gen(
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 611, in _gen
    gen_results = not_none(self.model).gen(
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/models/torch/rembo.py", line 184, in gen
...
    parameters={p: float(x[i]) for i, p in enumerate(param_names)}
  File "/opt/homebrew/anaconda3/envs/fb_ax/lib/python3.9/site-packages/ax/modelbridge/modelbridge_utils.py", line 634, in <dictcomp>
    parameters={p: float(x[i]) for i, p in enumerate(param_names)}
IndexError: index 4 is out of bounds for axis 0 with size 4
_____________________________________________________________
here are the wrong information

**Comment by bernardbeckerman** [comment]
Hi there! This looks to be coming from the [`_roundtrip_transform`](https://github.com/facebook/Ax/blob/main/ax/modelbridge/modelbridge_utils.py#L634) method of `transform_callback`. cc @saitcakmak as the modopt oncall - are you able to assist here?

**Comment by saitcakmak** [comment]
Hi @lujiaming-12138. Both ALEBO & REMBO are deprecated. We recommend using SAASBO for high dimensional optimization.

**Comment by lujiaming-12138** [comment]
Hello @saitcakmak @bernardbeckerman, thank you for your replies. I roughly understand that these two strategies have been deprecated.  I am currently learning the Alebo and Rembo algorithms, as well as the theoretical knowledge related to this "[Re-Examining Linear Embeddings for High-Dimensional Bayesian Optimization](https://arxiv.org/abs/2001.11659)". I want to know, if I want to use the code under this [repository](https://github.com/facebookresearch/alebo) perfectly, then what version of ax-platform, torch, gpytorch, botorch should I use? And the corresponding python version, can you recommend it?

**Comment by saitcakmak** [comment]
The repo lists Ax 0.1.17 on its requirements. I'd that that along with the versions of BoTorch and other dependencies that were current around the same time. Ax 0.1.17 was released on Oct 1, 2022 (https://github.com/facebook/Ax/releases/tag/0.1.17)

https://github.com/facebookresearch/alebo/blob/main/requirements.txt

**Comment by saitcakmak** [comment]
@lujiaming-12138 The bug is being fixed in https://github.com/facebook/Ax/pull/1926.

**Comment by saitcakmak** [comment]
Closing as the bug has been fixed.
