### ISSUE TITLE
[Feature Request] Support fixing parameter values in `get_next_trial()` in ServiceAPI 

### ISSUE THREAD

**Issue by Balandat** [facebook/Ax#1951]
Using `fixed_features` in [`Modelbridge.gen()`](https://github.com/facebook/Ax/blob/main/ax/modelbridge/base.py#L748) allows one to fix the values of certain parameters. This is useful in certain "contextual" optimization setups, see e.g. #1931 for a discussion. 

Currently, this is not supported in the Service API (i.e. in [`AxClient.get_next_trial()`](https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L513)). If we want the Service API to be more powerful / the primary way of using Ax for most people, then we should consider adding support for this there.

**Comment by sgbaird** [comment]
This would be a big benefit to me!
Related:
- https://github.com/facebook/Ax/issues/905
- https://github.com/facebook/Ax/issues/746
- https://github.com/facebook/Ax/issues/772
- https://github.com/facebook/Ax/issues/268

**Comment by chanansh** [comment]
was this fixed? I cannot see it in the Service API.

**Comment by Balandat** [comment]
cc @mpolson64
