### ISSUE TITLE
[Question] Migrate hyperparameter optimization from SimpleExperiment to Experiment

### ISSUE THREAD

**Issue by surajgattani** [facebook/Ax#1954]
I am working on migrating the hyperparameter optimization setup from `SimpleExperiment` to `Experiment`, since `SimpleExperiment` is now deprecated. 

This requires a couple changes:
I need to define a new custom metric (let's call it CustomX) to replace the `evaluation_function` previously used in `SimpleExperiment`.
The save and load functions need to be updated to bundle the new custom metric with the `RegistryBundle`.

The main challenges are:
1. The new custom metric breaks backwards compatibility with previously stored `Experiment` jsons.
2. The `evaluation_function` parameter used in `SimpleExperiment` needs to be replaced with the new custom metric.

My main goals are:
1. Migrate to `Experiment` in a way that is seamless on the backend.
2. Improve save/load functions to maintain backwards compatibility if possible.

Questions:
1. Is there a good way to migrate from `SimpleExperiment` to `Experiment` while still using the evaluation function as the objective metric?
2. How can I update the save and load functions to maintain backwards compatibility with the old json files?

Let me know if any part of the problem or goals need clarification!

**Comment by lena-kashtelyan** [comment]
Hi @surajgattani, can you just use the Ax Service API (AxClient, tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html)? That should resolve all the issues you are facing.

**Comment by lena-kashtelyan** [comment]
> How can I update the save and load functions to maintain backwards compatibility with the old json files?

Do you mean you'd like to be able to load old experiments essentially? You should be able to load them as `AxClient.load_from_json_file`. Let me know how that works out for you!

**Comment by surajgattani** [comment]
Thanks a lot @lena-kashtelyan -- Appreciate the quick response
I will try this out and post any questions that I might have!

**Comment by surajgattani** [comment]
@lena-kashtelyan I was able to solve all the issues with the save and load experiment from json store.
Also, the example in the tutorial -- [link](https://ax.dev/tutorials/gpei_hartmann_developer.html) explains the custom metric definition as well which allowed me to replace the evaluation function from the previous implementation.
I changed the custom definition a tiny bit marked with `-->` which worked for me:


```
from ax import Data
import pandas as pd
from ax.utils.common.result import Ok

class BoothMetric(Metric):
    def fetch_trial_data(self, trial):
        records = []
        for arm_name, arm in trial.arms_by_name.items():
            params = arm.parameters
            records.append(
                {
                    "arm_name": arm_name,
                    "metric_name": self.name,
                    "trial_index": trial.index,
                    # in practice, the mean and sem will be looked up based on trial metadata
                    # but for this tutorial we will calculate them
                    "mean": (params["x1"] + 2 * params["x2"] - 7) ** 2
                    + (2 * params["x1"] + params["x2"] - 5) ** 2,
                    "sem": 0.0,
                }
            )
        ---> return Ok(value=Data(df=pd.DataFrame.from_records(records)))

    def is_available_while_running(self) -> bool:
        return True
```

Thanks a lot for your quick response! Appreciate it
