### ISSUE TITLE
ValueError: Raw data must be data for a single arm for non batched trials. for the below code which is part of the tutorial. for v0.2.6

### ISSUE THREAD

**Issue by leeauk21** [facebook/Ax#1963]
ax version 0.2.6

ValueError: Raw data must be data for a single arm for non batched trials. for the below code which is part of the tutorial.

`from ax.service.ax_client import AxClient
from ax.utils.measurement.synthetic_functions import branin

ax_client = AxClient()
ax_client.create_experiment(
    name="branin_test_experiment",
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [-5.0, 10.0],
            "value_type": "float",
        },
        {
            "name": "x2",
            "type": "range",
            "bounds": [0.0, 10.0],
        },
    ],
    objective_name="branin",
    minimize=True,
)

for _ in range(15):
    parameters, trial_index = ax_client.get_next_trial()
    ax_client.complete_trial(trial_index=trial_index, raw_data=branin(parameters["x1"], parameters["x2"]))

best_parameters, metrics = ax_client.get_best_parameters()`

**Comment by mpolson64** [comment]
Hi @leeauk21, unfortunately I'm unable to reproduce this error using the latest release of Ax, v0.3.4 . Please update to this version and the above snippet should work.

If you're still encountering issues after updating don't hesitate to reopen the task and we will take a look.

**Comment by mpolson64** [comment]
@leeauk21 While I can't go back and try and reproduce this error, I believe it may have be related to this issue from June: https://github.com/facebook/Ax/pull/1664 . The TL;DR is that Typeguard, the library we were using at the time for runtime type checking, was not working properly and causing strange errors deep in our stack -- this was quite a tricky issue to investigate and we ended up needing to remove Typeguard completely.

If you are unable to upgrade to the latest version of Ax the best advice I can give you is to grep for TRIAL_RAW_DATA_FORMAT_ERROR_MESSAGE (the string of the value error you're seeing) and remove places where it's raised or where Typeguard is used. If I recall correctly, the primary place will be in ax/core/trial.py where we call a method named checked_cast_complex that calls Typeguard under the hood. Removing that checked_cast_complex and just passing in the value directly should solve your issue.

I'm sorry I can't offer more help, but I am sympathetic to your inability to upgrade to to legacy code so I hope this helps. Best of luck!

**Comment by leeauk21** [comment]
Thanks a lot @mpolson64 !!!
