### ISSUE TITLE
[Question] update model using previous runs

### ISSUE THREAD

**Issue by inkrement** [facebook/Ax#197]
Is it somehow possible to "update" the model before starting it? I guess in some cases the user already has some models already trained.  For example, we already used the Ax once and stored all the results in a folder. Now I want to re-run Ax, but would like to use the existing information. Is it somehow possible to update the model given some pre-existing knowledge ?

**Comment by lena-kashtelyan** [comment]
Hi, @inkrement! There are multiple ways of doing this depending on which API you are using. May I ask which one it is?

Also, one thing to beware of: if there is any data non-stationarity between the old experiment and the current one, directly adding old data to new experiment will lead to poor performance, and you might need to use [multi-task optimization](https://ax.dev/tutorials/multi_task.html).

**Comment by inkrement** [comment]
Thanks for the fast reply! Can you explain what you exactly mean by API in this context? I use it for fasttext-hyperparameter optimisation. Thus, my code is similar to this here: https://ax.dev/tutorials/tune_cnn.html.

**Comment by lena-kashtelyan** [comment]
We have three APIs: Developer, Service, and Loop –– check out the [API page](https://ax.dev/docs/api.html) of the website to see how they differ. The CNN-tuning tutorial you linked uses the Loop API. That API does not allow for updating the model before starting the optimization, unfortunately.

However, via the Service or the Developer API, you can attach the trials to the experiment. Refer to the [Service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html) –– in "Special Cases" section at the end it shows how to attach custom trials to optimization. You could start by attaching all the trials you want, then use `get_next_trial` to get the new ones.

Let me know if you'd like to use the Developer API instead, and I can show how to achieve a similar behavior there (check out the [Dev API tutorial](https://ax.dev/tutorials/gpei_hartmann_developer.html) and the [Building Blocks of Ax](https://ax.dev/tutorials/building_blocks.html) tutorial for a fuller look of what it can do).

**Comment by inkrement** [comment]
I'll try it!
