### ISSUE TITLE
[Question] Is it possible that AX to work with other external programs?

### ISSUE THREAD

**Issue by NoobIamNoob** [facebook/Ax#1976]
Hello! good morning!

I am trying to estimate the optimized parameter (My field calls this as "parameter identification, Reverse analysis") 
of the constitutive soil models in the FEM program 
through the Bayesian optimization method.

Fortunately, I found AX/Botorch and 
Learn & apply it to my optimization process.

I am stuck in the pre-processing work to put the FEM program in the framework of the AX.
So, I am writing this issue to ask for help.

Before going into the questions, I would like to describe how my FEM works briefly.
It consists of a total of three steps briefly.

1. write .txt file for the input parameters
2. run the .EXE file with provided .txt file
3. get the output file (.txt format)

What I want to do is 
to find the optimized input parameters that fit with the measured data and the simulated data(output) as close as they can.(given, fixed) 

For the optimization method, I am going to use the GPEI method. 

So I think that the flow will be like as below in order to combine the Ax with the external program: 

For prior process:
Generate the input parameters (from AX) -> put the parameters into the FEM input parameter .txt file (from External) - > run the FEM (from External) -> read the output file(.txt file) and return the numbers to the AX -> repeat

During the Bayesian Optimization process
From the Prior process, draw the surrogate function (From the AX) -> Find the space(Input parameters) to search from the acquisition function (From the AX) **->** export the search spaces(input parameters) to the .txt file -> Re-write the input parameters in the txt file for newly designated input parameters by the AX's acquisition function ->  RUN the FEM program and return the output result(.txt) to the AX -> repeat

So here is my question.

1. Is this process technically possible in the AX?
2. Is it possible to obtain & export the input parameters to be explored in the next step from the Acquisition function step?
3. I am working with the developer API example, I made the code for run the FEM simulation and Calculate the Mean squared Error for pre-processing. But I am still not sure how to compose the structure. Where should I put this loop that I've mentioned above? Metric? Runner?

**If there is a similar problem, I would greatly appreciate it if you give me the link.**

Thank you for your reading and
Sorry for my poor English skills
Hope you have a good time!

**Comment by Balandat** [comment]
Hi @NoobIamNoob this is definitely possible and one of the poster child use cases for Ax. It seems that you may better served with the more accessible Service API though: https://ax.dev/tutorials/gpei_hartmann_service.html, which basically is an ask/tell interface that will suggest new trials with new parameters to you, but allows you evaluate them and orchestrate the loop in your own code. You  basically just have to replace the `evaluate` function in that tutorial with the code that does the three steps required for running the external program and reading the results.

**Comment by NoobIamNoob** [comment]
> Hi @NoobIamNoob this is definitely possible and one of the poster child use cases for Ax. It seems that you may better served with the more accessible Service API though: https://ax.dev/tutorials/gpei_hartmann_service.html, which basically is an ask/tell interface that will suggest new trials with new parameters to you, but allows you evaluate them and orchestrate the loop in your own code. You basically just have to replace the `evaluate` function in that tutorial with the code that does the three steps required for running the external program and reading the results.

Thank you for your reply sir!
I finally made the full code by referring developer API
I will do the same work by using the service api for sake of brevity of the code..

Since the problem is solved, i will close the issue!
Thank you for your help and i appreciate it!

Sincerely,
