### ISSUE TITLE
[feature] Add `verbose_logging` kwarg in `AxClient. from_json_snapshot`

### ISSUE THREAD

**Issue by casassg** [facebook/Ax#201]
Using `from_json_snapshot` for restoring state in a distributed setting. Unfortunately the `AxClient. from_json_snapshot` creates the AxClient without allowing you to set `verbose_logging` which mainly means that it logs the initial info message about  `verbose_logging` being enabled every single time. 

This not breaking any code, it's just bothering me a bit. I can quickly draft a PR if needed for this.

**Comment by lena-kashtelyan** [comment]
Oh, thanks for spotting it, @casassg! Adding the kwarg (or maybe just storing the verbosity level in a field, so that it can be changed any time) sounds like a great idea –– a PR would of course be appreciated, but if not, we can add it on our side, too.
