### ISSUE TITLE
Question regards how to enforce one set of user choice default values during the Sobol initial trial generation. 

### ISSUE THREAD

**Issue by yizhanKT** [facebook/Ax#2040]
Hi,

During Sobol initial sampling for BO, I would like model generation strategy to always include a trial with user input default parameter value set, then random select among the search range.  May I ask if that's feasible? If so, a simple example code would be very helpful! Thank you.

**Comment by danielcohenlive** [comment]
Hi @yizhanKT , I think by "user input default parameter value set" you mean what we commonly refer to as the status quo. 
 I'm trying to figure out if there is a more canonical way to do this, but if you're using the [service API tutorial](https://ax.dev/tutorials/gpei_hartmann_service.html) you can always add a status quo to the experiment and manually attach that trial
```
# attach status quo on experiment creation
ax_client.create_experiment(
    ....
    # substitute your parameters here
    status_quo={"x1": 0.0, "x2": 0.0, "x3": 0.0, "x4": 0.0, "x5": 0.0, "x6": 0.0},
}
# alternatively you can set it later
ax_client.set_status_quo(params={"x1": 0.0, "x2": 0.0, "x3": 0.0, "x4": 0.0, "x5": 0.0, "x6": 0.0})
# you can then manually create the status quo trial and evaluate it
parameters, trial_index = ax_client.attach_trial(
   parameters=ax_client.status_quo,
   # it's probably the status quo
   arm_name="status_quo",
)
ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))
# then continue with the code already in the tutorial to get trials from the generation strategy
for i in range(25):
    parameters, trial_index = ax_client.get_next_trial()
    # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))
```

**Comment by yizhanKT** [comment]
@danielcohenlive  Thank you for your reply! yes, the status quo arm is the exact function I was looking for. Just want to confirm, as I am currently using develop API, in this case, I shall just append an Arm to the AX experiment as the following? 

```
 # If only one arm should be evaluated
experiment.new_trial().add_arm(Arm(parameters={"x1": 0.0, "x2": 0.0, "x3": 0.0, "x4": 0.0, "x5": 0.0, "x6": 0.0},  name="status_quo"))
```

**Comment by danielcohenlive** [comment]
@yizhanKT Yes, then you'll still need to run it, and fetch data/complete it as you do for other trials.

**Comment by yizhanKT** [comment]
Got it, thank you!

**Comment by danielcohenlive** [comment]
I'm closing this issue, but feel to reopen or open a new one if you have further questions
