### ISSUE TITLE
[Bug] Experiment name is not optional for non-DB usage

### ISSUE THREAD

**Issue by casassg** [facebook/Ax#206]
Experiments can be created [without a name](https://github.com/facebook/Ax/blob/6609095d8c2174daddacf88f687c5c2b29a72d93/ax/service/ax_client.py#L162), however the `from_json_snapshot` method fails if experiment name is not set due to it [accessing the `name` property](https://github.com/facebook/Ax/blob/6609095d8c2174daddacf88f687c5c2b29a72d93/ax/storage/json_store/encoders.py#L36) that [fails if not set](https://github.com/facebook/Ax/blob/master/ax/core/experiment.py#L90). 

A quick fix would be to access the `_name` instead of `name` or make the name in the `create_experiment` method a mandatory field.

**Comment by 2timesjay** [comment]
Thanks for letting us know. We have a fix ready and we'll update again when we get it into open source.

**Comment by lena-kashtelyan** [comment]
Just to clarify, the fix is on master, just not in the stable version yet! It will be included in the next stable version.

**Comment by casassg** [comment]
Is there any plans to release 0.1.7 any time soon to include these minor fixes?

**Comment by lena-kashtelyan** [comment]
@casassg, yep, there is! Will update you when the version is out, which should be in the next few days.

**Comment by lena-kashtelyan** [comment]
The fix is now part of the latest stable version, 0.1.8!
