### ISSUE TITLE
API docs still show usage of minimize=True and objective_name="branin" despite deprecation warning

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#2072]
See https://ax.dev/docs/api.html

> ```
> /home/vscode/.local/lib/python3.10/site-packages/ax/service/ax_client.py:350: DeprecationWarning: objective_name and minimize are deprecated
> ```

![image](https://github.com/facebook/Ax/assets/45469701/a88ca098-5f35-4646-aa72-8a8465eae944)

**Comment by mpolson64** [comment]
Thanks for the heads up, let me put up a PR right now to fix that. Also, this tutorial for the Service API specifically might be a better resource (and has a correct snippet for create_experiment already).
```
ax_client.create_experiment(
    name="hartmann_test_experiment",
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [-5.0, 10.0],
            "value_type": "float",  # Optional, defaults to inference from type of "bounds".
            "log_scale": False,  # Optional, defaults to False.
        },
        {
            "name": "x2",
            "type": "range",
            "bounds": [0.0, 10.0],
        },
    ],
    objectives={"branin": ObjectiveProperties(minimize=True)},
)
```
