### ISSUE TITLE
Using `evaluate_acquisition_function` on `AxClient` causes subsequent optimziation errors

### ISSUE THREAD

**Issue by Balandat** [facebook/Ax#2103]
> After calling evaluate_acquisition_function(), the ax_client object is neither able to propose the next trial with get_next_trial() nor able to predict the true function with get_model_predictions_for_parameterizations() anymore.

More detail here: https://github.com/facebook/Ax/discussions/2035#discussioncomment-7750433

**Comment by sdaulton** [comment]
This is already an open issue in https://github.com/facebook/Ax/issues/2083.

**Comment by Balandat** [comment]
Ah thanks, I just created this based on the discussion - looks like @lsassen was way ahead of me there.
