### ISSUE TITLE
Question :  modifications of  compute_posterior_pareto_frontier

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#2114]
Hello,

When using compute_posterior_pareto_frontier and adding outcome_constraints , the line : 
run = model.gen(1, model_gen_options=model_gen_options, optimization_config=oc) is giving us one point.

If we add : run = model.gen(tests, model_gen_options=model_gen_options, optimization_config=oc) with tests >1, new points aren't respecting the outcome constraints. Why is that ? I don't quite understand the behavior here.

Thanks for your help,
Regards,

**Comment by esantorella** [comment]
How do you know that points are not respecting outcome constraints? Generally, points that violate outcome constraints can be generated because the outcomes won't be known until the points are evaluated. Could you provide a reproducible example to illustrate the issue?

**Comment by esantorella** [comment]
Closing as inactive, but feel free to reopen.
