### ISSUE TITLE
Tracking of auxiliary metrics

### ISSUE THREAD

**Issue by hvarfner** [facebook/Ax#2118]
Hi,

I'm wondering whether there's built-in support for tracking of auxiliary metrics - i.e. those that are **not** relevant for optimization, but occasionally nice to track nonetheless. For example, this could involve the objective returning both the noisy and noiseless function eval (in the strictly synthetic case), or evaluating multiple metrics of a Multi-objective problem but _only modeling one/a few of them_.

So, can a metric be tracked without being considered for the purpose of optimization?

**Comment by hvarfner** [comment]
False alarm, found the relevant argument [here](https://github.com/facebook/Ax/blob/21dc6b416b419eaa0fcc77341c060b5c17a2e4cf/ax/modelbridge/torch.py#L111).

**Comment by Balandat** [comment]
>  For example, this could involve the objective returning both the noisy and noiseless function eval (in the strictly synthetic case)

FWIW I have a big refactor of the Ax benchmarks in the works that uses exactly this approach to add support for benchmarks with noisy metrics for which we know the ground truth noiseless function value(s).
