### ISSUE TITLE
`qMaxValueEntropy` doesn't seem to work with `ObjectiveProperties(minimize=True)`

### ISSUE THREAD

**Issue by rentruewang** [facebook/Ax#2133]
I have the following script where I'm simply minimizing / maximizing $\sum_i(x_i)$. It works for `botorch.acquisition.qExpectedImprovement`. However, for `botorch.acquisition.qMaxValueEntropy`, only  maximize works. Minimize=true would also result in maximization.

Reproduction: For the following script `script.py`,  `python script.py --mini=1 --neg=0 --typ=qme` would maximize, despite having `ObjectiveProperties(minimize=True)`.
Maximizing like `python script.py --mini=0 --neg=1 --typ=qme` would work fine (`--typ=qei` would work for both min and max).

```python
import fire
import torch
from ax.modelbridge import Models
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.service.ax_client import AxClient, ObjectiveProperties
from botorch.acquisition import qExpectedImprovement, qMaxValueEntropy
from rich import print
from torch import cuda

torch.manual_seed(42)

DEVICE = "cuda" if cuda.is_available() else "cpu"

KEY = "y"


def main(mini: bool, neg: bool, dims: int = 10, typ: str = "qei"):
    print("minimize:", mini)
    print("negate:", neg)
    print("dims:", dims)
    print("type:", typ)

    def maybe_neg(result):
        if neg:
            return -result
        return result

    params = [
        {"name": f"x{i}", "type": "range", "value_type": "float", "bounds": [-1, 1]}
        for i in range(dims)
    ]

    if typ == "qei":
        acqf = qExpectedImprovement
    elif typ == "qme":
        acqf = qMaxValueEntropy
    else:
        raise ValueError(f"Unknown acquisition function {typ}")

    client = AxClient(
        GenerationStrategy(
            [
                GenerationStep(Models.SOBOL, num_trials=10),
                GenerationStep(
                    Models.BOTORCH_MODULAR,
                    num_trials=-1,
                    model_kwargs={
                        "torch_device": DEVICE,
                        "botorch_acqf_class": acqf,
                    },
                ),
            ]
        )
    )

    client.create_experiment(
        params, objectives={KEY: ObjectiveProperties(minimize=mini)}
    )

    smallest = float("inf")
    largest = -float("inf")
    for i in range(60):
        param, idx = client.get_next_trial()
        result = maybe_neg(sum(param.values()))
        client.complete_trial(idx, {KEY: result})
        smallest = min(smallest, result)
        largest = max(largest, result)
        print(
            f"iter: {i:2d}, result: {result:.6f}, min: {smallest:.6f}, max: {largest:.6f}"
        )


if __name__ == "__main__":
    fire.Fire(main)
```

**Comment by SebastianAment** [comment]
@rentruewang Thanks for raising this issue. This likely has to do with the `minimize` keyword usually being consumed by an `objective` for Monte-Carlo acquisition functions in BoTorch. We'll investigate further.

**Comment by rentruewang** [comment]
@SebastianAment I'm not sure it's for all montr carlo based methods as qei and quick works fine.

**Comment by SebastianAment** [comment]
Hi @rentruewang, 

I put up a fix (https://github.com/pytorch/botorch/pull/2181), ran your script on top of it, and it behaves as expected. Once this lands, you can immediately use it by pointing your BoTorch version to the main branch. Otherwise, the fix will land in the official Ax/BoTorch packages upon their next release.

Let me know if this resolves your issue, and thanks again for reporting it!

**Comment by rentruewang** [comment]
@SebastianAment﻿ Thanks for the fix! It is working now.
