### ISSUE TITLE
[Question] Serialization of Experiment components

### ISSUE THREAD

**Issue by BCJuan** [facebook/Ax#214]
Hi,

I am trying to save an experiment. The problem occurs because my metrics have dataloaders and datasets from pytorch inside them. Those objects are not JSON serializable and hence I cannot save the experiment.

The error is: `TypeError: Object of type CIFAR10 is not JSON serializable`

Example of metric:

```
class AccuracyMetric(Metric):
    """
    Class for the accuracy metric
    """

    def __init__(self, datasets, dataloaders,
                 device, datasetsizes, epochs,
                 dtype=floatp, **kwargs):
        super().__init__(**kwargs)
        self.datasets = datasets
        self.dataloaders = dataloaders
        self.device = device
        self.dtype = dtype
        self.datasetsizes = datasetsizes
        self.epochs = epochs

    def fetch_trial_data(self, trial):
        """
        Function to retrieve the trials data for this metric
        """
        records = []
        for arm_name, arm in trial.arms_by_name.items():
            self.parametrization = arm.parameters
            records.append({
                "arm_name": arm_name,
                "metric_name": self.name,
                "mean": self.train_evaluate(),
                "sem": 0.0,
                "trial_index": trial.index,
            })
        return Data(df=DataFrame.from_records(records))

    def train_evaluate(self):
        """
        Trains the network and evaluates its performance on the test set
        """
        net = Net(self.parametrization, classes=10,
                  input_shape=self.datasets['train'].data[0].T.shape)
        net = train(net=net, dataloaders=self.dataloaders,
                    parameters=self.parametrization,
                    dtype=self.dtype, devicy=self.device,
                    datasizes=self.datasetsizes, epochs=self.epochs)
        return 1 - evaluate(
            net=net,
            data_loader=self.dataloaders['val'],
            dtype=self.dtype,
            device=self.device,
        )
```

I have tried to declare partials of the functions in train_evaluate but the problem is that when registering the metric, `register_metric(AccuracyMetric)` another error appears: 

`AttributeError: <class 'utils.AccuracyMetric'> is missing a value for build, which is needed by its constructor.`

Help will be really appreaciated, as I am stuck with this and I cannot save and reload my experiments.

Thank you very much.

Best regards

**Comment by sdsingh** [comment]
cc @ldworkin, who's thought a lot about the storage/serialization layer.

**Comment by BCJuan** [comment]
@sdsingh Thank you. 

I think that this issue is more of a problem of mine, i'll find a workaround. 

However, the idea is just to call the attention about what happens when someone tries to insert something that is not JSON serializable into a metric or experiment. How can the experiment be saved? Is there any workaround about this matter?

Maybe the software is just intended for serializable objects and should work that way.

**Comment by ldworkin** [comment]
@BCJuan I don't think we have a good answer for this at the moment, unfortunately. The software currently only supports JSON serializable objects. This is something we could think about for the future, but I don't think it'll be on our immediate roadmap.

**Comment by lena-kashtelyan** [comment]
I don't this this is something that is on our roadmap for the foreseeable future.
