### ISSUE TITLE
Nontrivial parameter constraints

### ISSUE THREAD

**Issue by fernexda** [facebook/Ax#2147]
Hello,
I'm currently working on optimizing a curve, parametrized by Fourier series, to achieve a certain objective. The curve is defined by $$\alpha = A_0 + \sum\limits_{n=1}^4 A_n \sin(\frac{2\pi}{T}nt + \phi_n),$$ so I'm really trying to optimize the fourrier coefficients $A_n$ and $\phi_n$.

This curve corresponds to an actual motion performed by a motor, and its max amplitude is constrained. The motor can not exceed this amplitude, or it might result in damage of the setup. So practically, for each generated set of parameters (=Fourier coefficients), I should verify the min and max values of the corresponding curve, and reject the point if these extrema exceed the limit.
Is there a way to achieve this? I've seen that nonlinear constraints are not possible, and I've seen a few workarounds being suggested, but I don't see how they would apply in this case.

Any help will be greatly appreciated!

**Comment by mgarrard** [comment]
Hi, @fernexda thanks for reaching out! Unfortunately, we currently do not support non-linear parameter constraints, and it isn't on our immediate roadmap. https://github.com/facebook/Ax/issues/769 has a pretty lengthy discussion of this, incl. pointers to other issues as well a draft PR (https://github.com/facebook/Ax/pull/794) that can allow this - but this is very much preliminary work and can potentially cause unwanted behavior when interacting with the transforms we do of the parameters - if you want to try this out USE AT YOUR OWN RISK.

**Comment by mgarrard** [comment]
Supporting non-linear constraints is already on the wishlist here: https://github.com/facebook/Ax/issues/566#issue-866378005, closing to avoid duplication.
