### ISSUE TITLE
[Feature]  Make `overwrite_existing_experiment`  in `create_experiment` fail if experiment set locally

### ISSUE THREAD

**Issue by casassg** [facebook/Ax#215]
Given that AxClient has a 1:1 relationship with experiments, I would really like to see the `create_experiment` function to fail if the local instance has an experiment set. This would be really useful for error runs of JupyterLab notebooks where the `create_experiment` is in a single cell and you may trigger running it again by error. One way to do it would be to extend the `overwrite_existing_experiment` flag to also make the function fail if the local instance has an experiment. We could check the local experiment name being the same as the created one. An extra check would be if the _name is not set for either one of them, and make the function fail as well.

**Comment by sdsingh** [comment]
I'd be happy with this suggestion, as long as we have a flag for overriding this behavior. I think this could just be another use of the `overwrite_existing_experiment` flag, as you've mentioned.

I would be happy to review a PR for this, it sounds like you may already have a draft?

**Comment by lena-kashtelyan** [comment]
Fix is now on master and will be in stable release shortly!

**Comment by lena-kashtelyan** [comment]
The merged PR is now part of the latest stable version, 0.1.8!
