### ISSUE TITLE
Different Errors when initializing my loop with Service API and Developer API

### ISSUE THREAD

**Issue by Jgmedina95** [facebook/Ax#2165]
Hi! First of all, I would like to thank the developer team as this is probably my 4th issue and I've always have gotten a helpful answer or guide.

I would like to report a bug, I've developed my loop through error and iteration and a lot of help from people here (see issues: #1951 and #). 

Im (finally) organizing everything in a (hopefully well notebook for myself and future reference. But during it I've found some unusual bugs, that may either be bugs or an error during implementation from my part. See the end for extra context.

When I tried to use the developer API to fix some parameters, I found issues during the initialization of the model. 

If I follow the steps 

```
### Some pseudo code, the notebook has the actual code.
data_df = pd.read_csv(FILENAME)
features = data_df..iloc[:,0:9] #I have 9 features
label =  data_df.iloc[:,9]

features = torch.tensor(features.values,dtype=float)
label       = torch.tensor(features.values,dtype=float)

### Define my model

class ExactGPModel(gpytorch.models.ExactGP, GPyTorchModel):
    
    _num_outputs = 1 

    def __init__(self, train_X, train_Y,**kwargs):
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood(), **kwargs)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=9))
        self.to(train_X)
        
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


#### Search space

ax_parameters = [{
                                "name": "Parameter1"
                                "type": "ParameterType"
                                "bounds/values": [list of min and max bounds or list of values]
                                }.... # repeat with all the parameters.

####Developer API ingredients
objective_metric = Metric(name="f", lower_is_better=None)  

### Not sure why i have to do this still. It seems to be a way of handling data communitation between the model and the experiment
class MyRunner(Runner):
    def run(self, trial):
        trial_metadata = {"name": str(trial.index)}
        return trial_metadata

# Define the search space based on the ax_parameters
# Run the cell of search_space above to have the ax_parameters. Is just easier at this point haha
search_space = SearchSpace(
    parameters=[
        RangeParameter(
            name=param["name"], 
            parameter_type=ParameterType.FLOAT, 
            lower=float(param["bounds"][0]), 
            upper=float(param["bounds"][1])
        )
        if param["type"] == "range" else
        ChoiceParameter(
            name=param["name"],
            values=param["values"],
            parameter_type=ParameterType.FLOAT
        )
        for param in ax_parameters
    ]
)

# Define the experiment with the search space
#the optimization configuration (the objective and metrics)
experiment = Experiment(
    search_space=search_space,
    optimization_config=OptimizationConfig(objective=Objective(objective_metric, minimize=False)),
    runner=MyRunner(),
)
```

Now, the issue:

If I start with my old data like follows: (this was obtained from issue #768)
```for i in range(len(modified_features)):
    #parameters
    start_params = {ax_parameters[j]['name']: modified_features.values[i][j] for j in range(9)} #change this accordingly, this is for 9 features ordered as in the search_space defined above (you better run that cell!)
    start_data = Data(
        df=pd.DataFrame.from_records([{"arm_name": f"{i}_0",
                                       "metric_name":"f",
                                       "mean": train_final_label.values[i],
                                       "sem": 0.0,
                                       "trial_index": i}]),
    )
    trial = experiment.new_trial()
    trial.add_arm(Arm(name=f"{i}_0", parameters=start_params))
    experiment.attach_data(start_data)
    trial.run().complete()```
```
and try to start my model
```
model_bridge_with_GPEI = Models.BOTORCH_MODULAR(
    experiment=experiment,
    data=experiment.fetch_data(),                     ###if option 1 for Data uncomment this line
    surrogate=Surrogate(ExactGPModel,mll_class=LeaveOneOutPseudoLikelihood),
                                   # ),  # mll class optional, will use default if unspecified
    botorch_acqf_class=qExpectedImprovement,  # Optional, will use the default if unspecified
    #transforms=[StandardizeY(), UnitX()],    # Optional, will use the default if unspecified (see Transforms documentation)
)
```

I get the following error:
```
      7 def __init__(self, train_X, train_Y,**kwargs):
----> 8     super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood(), **kwargs)
      9     self.mean_module = gpytorch.means.ConstantMean()
     10     self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=9))

TypeError: ExactGP.__init__() got an unexpected keyword argument 'train_Yvar'
```
This is the first time I've seen this, and the reason why im writing this issue. 

If instead, i start everything using the Service API to gather my old data like:

```
### Generation Strategy for service API
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            # For `BOTORCH_MODULAR`, we pass in kwargs to specify what surrogate or acquisition function to use.
            model_gen_kwargs={"max_retries": 10},
            model_kwargs={
                "surrogate":Surrogate(ExactGPModel,
                                      mll_class=LeaveOneOutPseudoLikelihood),
                
                "botorch_acqf_class": qExpectedImprovement,
                },
        ),
    ]
)

#### Initialize AxClient
ax_client = AxClient(generation_strategy = gs)
ax_client.create_experiment(parameters = ax_parameters, 
                            objectives= {"f":ObjectiveProperties(minimize=False)},) 

### Adding old data to Service API
### This was also inspired from #768 discussion
for i in range(len(modified_features)):
    ax_client.attach_trial(parameters = {ax_parameters[j]['name']: modified_features.values[i][j] for j in range(9)})
    ax_client.complete_trial(trial_index = i, raw_data = {"f": train_final_label.values[i]})

```
and then use the Developer API with the following changes:
```
### add this after instantiating Experiment above
experiment.warm_start_from_old_experiment(ax_client.generation_strategy.experiment)

### and start the model
model_bridge_with_GPEI = Models.BOTORCH_MODULAR(
    experiment=experiment,
    data=experiment.fetch_data(),                     ###if option 1 for Data uncomment this line
    surrogate=Surrogate(ExactGPModel,mll_class=LeaveOneOutPseudoLikelihood),
                                   # ),  # Optional, will use default if unspecified
    botorch_acqf_class=qExpectedImprovement,  # Optional, will use default if unspecified
)

```
This doesn't find the error, which sounds crazy to me. 
Additionally, if I do not put the `data` argument (and naively expect that the experiment containing the data will be enough)

i get the following error:
```DataRequiredError: `StandardizeY` transform requires non-empty data.```

Summary:
In any case, I'm unsure why I get the weird ExactGP __init__ error with one way of initializing my data. There's probably something I'm not considered under the hood that I haven't had the time to check this time. 

And secondly, is weird that i need to use that data argument. during the Model instantiation in the Developer API even when the experiment already has it included. 

The files for replication are here:
[Archive.zip](https://github.com/facebook/Ax/files/14115429/Archive.zip)

**Comment by bernardbeckerman** [comment]
Hi there, taking a look!

**Comment by bernardbeckerman** [comment]
Is there any particular reason that the developer API is required for your use-case, or can you work around this issue by using the service API instead?

> Additionally, if I do not put the data argument (and naively expect that the experiment containing the data will be enough) i get the following error:
> DataRequiredError: `StandardizeY` transform requires non-empty data.

This is because your the BO model has no prior data off of which to train. Usually, GenerationStrategies begin with a Sobol (random initialization) step, followed by a BO step. The former seeds the search space with data off of which the latter trains. When you provide prior data, it's possible to skip the Sobol step as you saw above, but when no prior data is provided, a Sobol step is required. Does that answer your questions?

**Comment by mgarrard** [comment]
Hi @Jgmedina95 -- let me find the associated feature request and mark another interest for you. Also re: your comment about not sure why runner is needed -- your guess is right! Essentially a runner defines how to deploy the experiment, meaning how to evaluate the trials and then stores that data somewhere. It also keeps track of where that data is stored so that it can be easily fetched in the future. [This page has a bit of info on runners](https://ax.dev/docs/trial-evaluation.html#adding-your-own-runner).

Bernie's call-out re: the SOBOL initialization step being missing causing the error seems accurate to me -- does this help answer your question, or would you like further support? Will agree definitely a bit ambiguous, so will also make a note of that.

**Comment by bernardbeckerman** [comment]
Thanks @mgarrard for jumping in here! I was out of town for a bit but am back. @Jgmedina95 have you been able to resolve your issue?

**Comment by Jgmedina95** [comment]
Hi!, my experimental setup got some setbacks, so I haven't been able to work too much on this at the moment. 
I need to test the SOBOL step, to see how the issue does, but as of now, I do have some workarounds that allow me to get the setup running (the same described above). I mainly wanted to understand why this could be happening, and it could be a bug that haven't been described before.
