### ISSUE TITLE
Tutorial Request: Deploying Runners on Clusters

### ISSUE THREAD

**Issue by CCranney** [facebook/Ax#2179]
Hi,

I'm writing a script based on the [Multi-Objective NAS with Ax](https://pytorch.org/tutorials/intermediate/ax_multiobjective_nas_tutorial.html) that was written by @dme65 and @Balandat, among others. My script has run successfully on my local computer, but fails when submitted as a batch job to my company's high-process computing (HPC) resources. I was wondering if any tutorials exist for enabling Ax-based scripts for batch job submission, as I have been unable to find any at this time. 

If no such tutorial exists, I would have two specific questions, detailed below.

> -------
> -------

1. As a general question, I am trying to learn to debug scripts that were submitted by a Scheduler object. Specifically, where one sees output like the following when `scheduler.run_all_trials()` is run:
```
[INFO 02-03 05:14:15] Scheduler: Running trials [0]...
[INFO 02-03 05:14:16] Scheduler: Running trials [1]...
[INFO 02-03 05:14:17] Scheduler: Running trials [2]...
[INFO 02-03 05:14:18] Scheduler: Running trials [3]...
[INFO 02-03 05:14:19] Scheduler: Waiting for completed trials (for 1 sec, currently running trials: 4).
[INFO 02-03 05:14:20] Scheduler: Waiting for completed trials (for 1.5 sec, currently running trials: 4).
etc.
```
In my original coding attempts I would often get the following error, soon followed by a quick abort as every trial fails:

```
[INFO 01-31 19:22:06] Scheduler: Retrieved FAILED trials: 0 - 3.
...
[INFO 01-31 19:22:59] Scheduler: Retrieved FAILED trials: 4 - 7.
...
ax.service.scheduler.FailureRateExceededError: Failure rate exceeds the tolerated trial failure rate of 0.5 (at least 8 out of first 8 trials failed). Checks are triggered both at the end of a optimization and if at least 5 trials have failed.
```

I learned through trial-and-error that this would be because some package had not yet been installed in my environment. However, I cannot see where those kinds of error messages are ever created, and therefore have difficulty debugging the process. **_How would I see what errors caused the trials to fail?_** I have been searching the documentation, tutorials and code, but have not found it so far.

> -------

2. What changes would need to occur in a Runner object to be submitted as a batch job? I assume in this snippet of code from the tutorial, one would need to change `local_cwd` to something like `slurm`. 

```python
ax_runner = TorchXRunner(
    tracker_base="/tmp/",
    component=trainer,
    # NOTE: To launch this job on a cluster instead of locally you can
    # specify a different scheduler and adjust arguments appropriately.
    scheduler="local_cwd",
    component_const_params={"log_path": log_dir},
    cfg={},
)

```

I am experimenting with variations on this, but so far consistently get the Scheduler errors listed in question 1 above. The comments suggest arguments need to be adjusted appropriately - however, I am not sure what those necessary argument adjustments must be, hence my search for a tutorial.

I have determined that using a `slurm` scheduler generates a new batch job for each trial. This could be useful moving forward, but I'm also wondering if there's a way to run it all on one batch job. Alternatively, if I did go the route of submitting new batch jobs regularly, I'd also be interested in learning to customize the script - for example, how to specify a partition.

**Comment by Balandat** [comment]
Hi @CCranney, thanks for your interest!

Fortunately, we added a Submitit tutorial for submitting jobs to slurm just the other day: https://github.com/facebook/Ax/blob/main/tutorials/submitit.ipynb 


> However, I cannot see where those kinds of error messages are ever created, and therefore have difficulty debugging the process. How would I see what errors caused the trials to fail?

In the PyTorch MOO NAS tutorial, the jobs are running locally in via TorchX in their own process, which makes debugging quite hard. I think there should be a way to somehow set things up in TorchX to pipe the logs back to the `TorchXRunner` or at least save them to disk, but I'm not sure how to do that (if you figure it out please let us know, I think this is a question for the TorchX folks).

> What changes would need to occur in a Runner object to be submitted as a batch job?

I haven't tried the TorchXRunner with remote job submission yet (we use a different kind of remote backend), so unfortunately I don't know the answer here. I would recommend starting from TorchX and see if you can just use pure TorchX code to run a slurm job on the cluster - that should tell you what kind of settings would need to be piped through to the respective TorchX logic from the runner (this might require some minor updates to the runner, we'd be happy to help with those). 

But if you're fine with using Submitit, I recommend you give the tutorial I mentioned above a try.

**Comment by CCranney** [comment]
Thank you @Balandat! This definitely set me off on the right direction. I'll be digging into the TorchXRunner question further, if I get those answers I'll definitely reach out. Thank you for the tutorial and for the tips! I'll go ahead and close this issue.

**Comment by Balandat** [comment]
Great. Please do report back and share your solution :)

**Comment by CCranney** [comment]
Hi all,

While I have not resolved the best method for deploying jobs to the scheduler, I have landed on a debugging solution for investigating specific trial runs. My code is split into two files, one that utilizes Ax classes to compile experiments, trials, and runners and schedulers. This script relies on a second file that uses pytorch-lightning to generate, train and evaluate models specified by the search space. All of this is outlined in the tutorial link in my first post.

Because it is errors in the second script file that are not printed to the screen/terminal, I have found a method for logging all output of the second script to a text file. It's a workaround, but it works at identifying how or why specific trials failed.

I pasted the following code at the top of the second script. Note that I manually created a `log` directory for it to save files to prior to running the code.

```python
import logging
import sys
import io
from datetime import datetime

class StreamToLogger(io.TextIOBase):
    def __init__(self, logger, level=logging.INFO):
        self.logger = logger
        self.level = level
        self.linebuf = ''

    def write(self, buf):
        for line in buf.rstrip().splitlines():
            self.logger.log(self.level, line.rstrip())

# Configure the logging module
logging.basicConfig(filename=f'logs/output_{datetime.now().strftime("%Y%m%d-%H%M%S-%f")}.log', level=logging.INFO)

# Redirect stdout to the logger
stdout_logger = logging.getLogger('STDOUT')
sys.stdout = StreamToLogger(stdout_logger, logging.INFO)

# Redirect stderr to the logger
stderr_logger = logging.getLogger('STDERR')
sys.stderr = StreamToLogger(stderr_logger, logging.ERROR)
```

The saved files are marked by the date and time down to microseconds (to ensure that even rapidly-generated jobs will not accidentally write to the same file). This may be overkill, but better too much info than not enough in my opinion.
