### ISSUE TITLE
Question: does Ax support working with Tensorflow models?

### ISSUE THREAD

**Issue by mzabaletasar** [facebook/Ax#2187]
I want to use Ax for hyperparameter tuning of my Tensorflow models.

**Comment by Cesar-Cardoso** [comment]
It does. You should be able to follow our notebook tutorial to [tune a PyTorch CNN](https://ax.dev/tutorials/tune_cnn_service.html), and replace the PyTorch CNN with your Tensorflow model.

**Comment by mzabaletasar** [comment]
I see, thank you!
