### ISSUE TITLE
Unable to install on MacOS

### ISSUE THREAD

**Issue by chengrunyang** [facebook/Ax#221]
Hi, when trying to install into a Python 3.7.5 conda virtual environment on MacOS 10.14.5, after doing the following steps

```
conda install pytorch torchvision -c pytorch 
pip3 install ax-platform
pip3 install jupyter
```

I get the following error

```
>>> import ax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ax'
```
in both Python prompt and Jupyter notebook. Is there any possible reason why `ax` can't be found in namespace? Thanks!

**Comment by Balandat** [comment]
Wan you make sure that the `pip3` that you're calling here is in fact the `pip` of your conda venv?
`which pip3` should help clarify. Also, double check that your venv is in fact activated.

**Comment by lena-kashtelyan** [comment]
Closing this since this should definitely be installation directory / environment issue, as @Balandat suggested –– I verified that the installation still works if all packages are installed in the correct environment. Please reopen if you need more help, @chengrunyang !

**Comment by chengrunyang** [comment]
Sorry for my late reply. I took a look and indeed my `pip3` was not the local one. Problem solved. Thanks @Balandat !
