### ISSUE TITLE
Questions about define how to evaluate 

### ISSUE THREAD

**Issue by Zhehao986** [facebook/Ax#2212]
Hello, I am a beginner with Ax and currently trying to apply Bayesian optimization to optimize a production process. I followed the tutorial provided in the Ax documentation, where the optimization is implemented with a known function. However, I'm struggling to define the metric due t limited knowledge about the function, which has prevented me from establishing the 'optimization config'. I would appreciate guidance on how to code this part. Below is my code snippet:

from ax.service.ax_client import AxClient
from ax.utils.notebook.plotting import render, init_notebook_plotting

# Initialize plotting for Jupyter Notebooks
init_notebook_plotting()

# Initialize the AxClient
ax_client = AxClient()

# Create an experiment
ax_client.create_experiment(
    name="Drugloading_optimization",
    parameters=[
        {"name": "Cycle", "type": "range", "bounds": [2, 12], "value_type": "int"},
        {"name": "Grinding_time", "type": "range", "bounds": [1, 5], "value_type": "int"},
        {"name": "Cooling_time", "type": "range", "bounds": [1, 5], "value_type": "int"},
        {"name": "Polymer", "type": "range", "bounds": [350, 800], "value_type": "int"},
        {"name": "Glucose", "type": "range", "bounds": [0, 863.7], "value_type": "float"},
        {"name": "Temperature_disper", "type": "range", "bounds": [25, 80], "value_type": "int"},
    ],
    objectives={"yield": ObjectiveProperties(minimize=False)},
)

# Define the evaluation function
def evaluate(parameters):
    cycle = parameters["Cycle"]
    grinding_time = parameters["Grinding_time"]
    cooling_time = parameters["Cooling_time"]
    polymer = parameters["Polymer"]
    glucose = parameters["Glucose"]
    temperature_disper = parameters["Temperature_disper"]
    # Assume 'black_box' is a function that calculates the outcome based on the parameters
    outcome = black_box(cycle, grinding_time, cooling_time, polymer, glucose, temperature_disper)
    return {"yield": (outcome, 0.0105)}

# Run the optimization loop
for i in range(25):
    parameters, trial_index = ax_client.get_next_trial()
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))

**Comment by Balandat** [comment]
Not sure I understand the question - `evaluate` is a placeholder for the behavior of your production process, that is something you need to provide (we can't help with that). This could either mean calling some kind of simulator, or run actual lab experiments to obtain the results and return them to Ax.

**Comment by Zhehao986** [comment]
> Not sure I understand the question - `evaluate` is a placeholder for the behavior of your production process, that is something you need to provide (we can't help with that). This could either mean calling some kind of simulator, or run actual lab experiments to obtain the results and return them to Ax.

thank you very much for your help. I understand
