### ISSUE TITLE
cannot import name 'TrainingData'

### ISSUE THREAD

**Issue by hello-eternity** [facebook/Ax#2294]
pip install botorch==0.8.5 0.9.5 0.10.0 meet error 

```
>>> from botorch.utils.containers import TrainingData
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TrainingData' from 'botorch.utils.containers'
```

**Comment by mpolson64** [comment]
Hi @hello-eternity -- I believe TrainingData was deprecated in favor of BotorchContainer back in 0.6.5 (see https://github.com/pytorch/botorch/commit/f998e065a2fef42c59a59c0978b20cd472393e67, https://github.com/pytorch/botorch/pull/1205). If you have any questions about this change please feel free to ask in the botorch repository and our teammates there will be more than happy to help.

I hope this was helpful, and let us know if you have any questions about Ax :)

**Comment by hello-eternity** [comment]
thank you, that's worked
