### ISSUE TITLE
[Feature Request] support constraints on `ChoiceParameters`

### ISSUE THREAD

**Issue by zhqrbitee** [facebook/Ax#2311]
Hi, I'm having a use case that my parameters A and B are all odd values, so I put them as `ChoiceParameters`, but I also want to bound them to make them close enough, e.g. `-10 <= A - B <= 10`. 
Currently, when putting constraint on a `ChoiceParameters`, I got below error msgs (the ax version is 0.3.7):
```python
ax.exceptions.core.UnsupportedError: Constraints on ChoiceParameters are not allowed. Try absorbing this constraint into the associated range parameter's bounds.
```

I searched through existing issues and find this one: https://github.com/facebook/Ax/issues/621. According to the comment here: https://github.com/facebook/Ax/issues/621#issuecomment-881781266:

> As far as choice parameters are concerned, the reason we didn't allow constraints on these was that they were one-hot encoded and thus representing the constraint as a linear constraint is not straightforward. However, we made some changes recently that handle choice parameters in a different way and optimize over their actual values, so it would potentially be possible to incorporate them into parameter constraints (in fact, potentially even nonlinear ones)

So I'm wondering if above is still true? If possible, is there any plan for this?

**Comment by mgrange1998** [comment]
Hi @zhqrbitee, I am taking a look into whether ordered choice parameters can be incorporated into parameter constraints. 

One quick thought first- is it possible to use RangeParameters for A and B across all integers, but then map the parameters to odd values in your usecase?

**Comment by mgrange1998** [comment]
Hi, so I found that we have an open issue for supporting constraints on choice parameters on our wishlist
 https://github.com/facebook/Ax/issues/710.

Closing this issue for now, please feel free to make another issue for help with the usecase design if the mapping approach doesn't work. Thank you!

**Comment by mgrange1998** [comment]
Yes, please close the issue. Best of luck with your problem!
