### ISSUE TITLE
List RayTune tutorial on Website?

### ISSUE THREAD

**Issue by richardliaw** [facebook/Ax#232]
It seems that the RayTune PyTorch CNN tutorial which shows up on the Github (https://github.com/facebook/Ax/tree/master/tutorials) is unlisted on the main website (https://ax.dev/tutorials/). 

Perhaps listing it could better support some use cases? Happy to push a fix.

cc @lena-kashtelyan

**Comment by eytan** [comment]
Yes please do add it! PR would be appreciated!

**Comment by ldworkin** [comment]
Agreed, if it's easy for you to push a fix that would be awesome! Thanks!

**Comment by lena-kashtelyan** [comment]
This has been part of the plan for a while, @stevemandala owns the task!

**Comment by stevemandala** [comment]
PR #234 should add this to the main site

**Comment by richardliaw** [comment]
Awesome! Thanks for the fast response!

**Comment by lena-kashtelyan** [comment]
The tutorial is now on the website for the stable version, 0.1.8 : )
