### ISSUE TITLE
Extending Models.THOMPSON with an extra parameter

### ISSUE THREAD

**Issue by seabull** [facebook/Ax#2334]
Hello Ax team,

We are looking to extend the Thompson model with an annealing parameter. The call would be like the following:
```
# The current Ax Thompson 
# Models.THOMPSON(
#                experiment=my_experiment,
#                data=trial_data,
#                min_weight=min_weight,
#            )

# EXTENDED_THOMPSON would extend from current Ax Thompson
Models.EXTENDED_THOMPSON(
                experiment=my_experiment,
                data=trial_data,
                min_weight=min_weight,
                anneal_factor=anneal_factor,
            )
```
The current Ax library doesn't support extending the model with an extra parameter. To make it work, we had to fork Ax library and add `EXTENDED_THOMPSON` to the source code, which is not ideal. 

I wonder whether the Ax library could be enhanced to support extra parameters in the Thompson model (and/or other models) or other alternatives to make models extend-able?

**Comment by sdaulton** [comment]
Hi @seabull,

Feel free to open a pull request that adds this new parameter to `Models.THOMPSON`! Contributions are always welcome!

**Comment by lena-kashtelyan** [comment]
Closing this as it went on the wishlist and appears inactive. @seabull, please reopen if you would like to continue this discussion or put up a PR!
