### ISSUE TITLE
Plotting outside of a notebook

### ISSUE THREAD

**Issue by cheeseheist** [facebook/Ax#2369]
Hi, 

I'm curious if there is a method of leveraging the Ax plotting tools outside of a notebook environment. Everything I see seems to be oriented towards jupyter notebooks. I'm just running a standard .py script via VSCode and haven't found any render functions in the API that aren't geared towards a notebook.

Thanks!

**Comment by Cesar-Cardoso** [comment]
Hello there! This is the render function we use for notebooks https://github.com/facebook/Ax/blob/main/ax/utils/notebook/plotting.py#L35-L46. This functionality is only for Jupyter notebooks; but you should be able to, for example export them as an image, without much trouble.

Our plots are rendered as Plotly plots or HTML, and the data is contained in [AxPlotConfig.data](https://github.com/facebook/Ax/blob/main/ax/plot/base.py#L39).
