### ISSUE TITLE
Arms from previous batch keep appearing in new batches

### ISSUE THREAD

**Issue by Samperius** [facebook/Ax#2385]
I have a problem in my optimization loop, that previous batch trial arms keep popping to new generated batches (In the example, arm 0_2). Sorry for a bit messy code.

Optimization loop:
```
n_iterations = 15
batch_size = 3
model = Axmodel()
model.create_experiment('arylation', params)
for i in range(n_iterations):
     if i==0:
         model.generate_sobol(batch_size, params)
         print('initial arms', model.trial.arms)
     else:
         model.new_batch(batch_size)
     results = get_results(model, df) #this gets result from an excel and adds them to a list of tuples [(arm_name, yield)]
     model.add_results(results) #this 
     model.build_model(function=model_name)
     print(model.trial.fetch_data().df)
```

Key methods of Axmodel class
```
class Axmodel:
    def generate_sobol(self, batch_size, params,fix_temperature=False):
        self.sobol = Models.SOBOL(search_space=self.experiment.search_space, seed = 1234)
        self.generator_run = self.sobol.gen(
                                            n=batch_size
                                            , optimization_config=self.optimizationconfig
                                            
                                            )
        self.trial = self.experiment.new_batch_trial(generator_run=self.generator_run)
    
  def new_batch(self, n, fixed_temperature = False):
              self.generator_run = self.model.gen(
                  n = n,
                      optimization_config=self.optimizationconfig,
  
                      )
              self.trial = self.experiment.new_batch_trial(generator_run=self.generator_run)
              print('generating batch', self.generator_run.arms)

    def add_results(self,results):
        n = len(self.trial.arms)
        arm_datas = []
        for arm_num in range(n):
            arm = self.trial.arms[arm_num]
            arm_name = arm.name
            trial_num = int(arm_name.split('_')[0])
            result = results[arm_num]
            arm_datas.append(
            {
                "arm_name": result[0],
                "metric_name": "yield",
                "mean": result[1],
                "sem": None,
                "trial_index": trial_num
            })        
        data = Data(df=pd.DataFrame.from_records(arm_datas))
        self.trial.run().complete()
        self.experiment.attach_data(data)

    def build_model(self, function='qEI'):
            elif function == 'qEI':
                acq_func = qExpectedImprovement
                print('model is qEI')
            elif function == 'qUCB':
                acq_func = qUpperConfidenceBound
                print('model is qUCB')

            self.model = Models.BOTORCH_MODULAR(search_space=self.experiment.search_space,
                                        experiment=self.experiment,
                                        data=self.experiment.fetch_data(),
                                        surrogate=Surrogate(SingleTaskGP),  # Optional, will use default if unspecified
                                        botorch_acqf_class= acq_func,  # Optional, will use default if unspecified
                                               )
            

```
Some prints:

```
Experiment defined:
{'base': ChoiceParameter(name='base', parameter_type=STRING, values=['KOAc', 'KOPiv', 'CsOAc', 'CsOPiv'], is_ordered=False, sort_values=False), 'ligand': ChoiceParameter(name='ligand', parameter_type=STRING, values=['BrettPhos', 'PPhtBu2', 'tBPh-CPhos', 'PCy3 HBF4', 'PPh3', 'X-Phos', 'P(fur)3', 'PPh2Me', 'GorlosPhos HBF4', 'JackiePhos', 'CgMe-PPh', 'PPhMe2'], is_ordered=False, sort_values=False), 'solvent': ChoiceParameter(name='solvent', parameter_type=STRING, values=['DMAc', 'BuCN', 'BuOAc', 'p-Xylene'], is_ordered=False, sort_values=False), 'concentration': RangeParameter(name='concentration', parameter_type=INT, range=[1, 3]), 'temperature': RangeParameter(name='temperature', parameter_type=INT, range=[1, 3])}

initial arms :
[Arm(name='0_0', parameters={'concentration': 2, 'temperature': 2, 'base': 'KOPiv', 'ligand': 'PPh3', 'solvent': 'p-Xylene'}), Arm(name='0_1', parameters={'concentration': 2, 'temperature': 2, 'base': 'KOAc', 'ligand': 'P(fur)3', 'solvent': 'BuOAc'}), Arm(name='0_2', parameters={'concentration': 1, 'temperature': 3, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'})]

trial after first iteration (13.     print(model.trial.fetch_data().df)):
  arm_name metric_name   mean  sem  trial_index
0      0_0       yield   1.41  NaN            0
1      0_1       yield   9.87  NaN            0
2      0_2       yield  89.95  NaN            0
arms of the second batch:
generating batch [Arm(name='0_2', parameters={'concentration': 1, 'temperature': 3, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'}), Arm(name='1_0', parameters={'concentration': 2, 'temperature': 3, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'}), Arm(name='1_1', parameters={'concentration': 1, 'temperature': 2, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'})]
```

**Comment by esantorella** [comment]
Hi, thanks for reaching out. Some amount of repetition is expected in a discrete search space like you have. When you pass in an SEM of `None`, Ax assumes that the data has some unknown amount of noise and tries to infer the amount of noise. Repeating an arm that performed well in the past provides informational value and helps the model infer the noise level. If your observations are noiseless, pass in an SEM of 0, and there shouldn't be repetition.

**Comment by Samperius** [comment]
Hi, thank you for the quick response. I tried to use the SEM of 0. The same behavior seems to reproduce.

`initial arms: [Arm(name='0_0', parameters={'concentration': 2, 'temperature': 2, 'base': 'KOPiv', 'ligand': 'PPh3', 'solvent': 'p-Xylene'}), Arm(name='0_1', parameters={'concentration': 2, 'temperature': 2, 'base': 'KOAc', 'ligand': 'P(fur)3', 'solvent': 'BuOAc'}), Arm(name='0_2', parameters={'concentration': 1, 'temperature': 3, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'})]
model is qUCB
  arm_name metric_name   mean  sem  trial_index
0      0_0       yield   1.41  0.0            0
1      0_1       yield   9.87  0.0            0
2      0_2       yield  89.95  0.0            0`

`generating batch:  [Arm(name='0_2', parameters={'concentration': 1, 'temperature': 3, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'}), Arm(name='1_0', parameters={'concentration': 3, 'temperature': 2, 'base': 'KOPiv', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'}), Arm(name='1_1', parameters={'concentration': 2, 'temperature': 2, 'base': 'CsOAc', 'ligand': 'CgMe-PPh', 'solvent': 'DMAc'})]`

It seems that the candidates with the highest yield keep repeating. For instance, arm in the next trial:
`0      1_0       yield  98.49  0.0            1`
repeats still in trial 10 even though I always pass it to the same result (as I am using a pre-collected dataset and not actually perform the experiments again).

To me, it seems that there is still some uncertainty left in the GP of those repeating parameters resulting in UCB to expect high acquisition value remaining on those parameters.

To be noted that I get a numerical warning:
`[.../python3.12/site-packages/linear_operator/utils/cholesky.py:40](.../lib/python3.12/site-packages/linear_operator/utils/cholesky.py#line=39): NumericalWarning:

A not p.d., added jitter of 1.0e-08 to the diagonal`

**Comment by esantorella** [comment]
A few hypotheses and suggestions:
* My best guess by far is that this is a result of using UCB, which will choose points with zero uncertainty if it believes they are sufficiently better than the other options. 10+/-0 has a higher upper confidence bound than 1+/-1. I would expect better performance and no repetition from leaving the acquisition function unspecified. Then Ax will default to using `qLogNoisyExpectedImprovement`, which shouldn't have this issue. (`qLogNoisyExpectedImprovement` is  an improvement to `qNoisyExpectedImprovement` that has better numerical behavior.) If you really want to use UCB, although I don't recommend it, you could set a higher `beta` to prefer more uncertain arms.
* Are you using BoTorch < 0.9.3? 0.9.3 was released in November 2023. Before that, `SingleTaskGP` would not handle SEM data. I would have hoped Ax would raise an exception rather than silently ignoring the SEM data, but this is my next-best guess if specifying the SEM made no difference at all.
* Could you look at `model.experiment.trials` and confirm that all of the trials you expect to see are present and have status COMPLETED? From looking at your code, I don't think this is the problem, but I want to rule out that this is a similar issue to #2371 where trials haven't been properly attached.

**Comment by esantorella** [comment]
By the way, it looks like your use case could work well with the Service API, which is more user-friendly. [Here](https://ax.dev/tutorials/gpei_hartmann_service.html) is a tutorial.

**Comment by Samperius** [comment]
Hi, thanks for the advice.

- I tried with expected improvement and the issue does not reproduce with that acquisition function.
- My Botorch version: botorch                   0.9.4
- All trials are seen as completed
