### ISSUE TITLE
 batch of suggestions 

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2437]
is it possible to get multiple trials at once and then evaluate them together.

**Comment by mgrange1998** [comment]
Hi,

Is a batch trial what you are looking for? It allows you to attach multiple arms to one trial and deploy and evaluate them together. (See https://ax.dev/api/core.html#batchtrial for more details)

In terms of trials running together, the GenerationStrategy objects allows you to specify "max_parallelism" which controls the number of trials which can be running at once. See the generation strategy wiki here for more details on that https://ax.dev/tutorials/generation_strategy.html#1.-Quick-start-examples

Let me know if this helps or if you have any other questions.

**Comment by Fa20** [comment]
thanks for your answer. I have multi-objective functions and I want to get e.g. 10 suggestions for the papameters values and then use them to evalaute the functions  and so on . in I another words I want to avaoid the sequantial way which give one sugesstion and evaluate the function and next iteration do the same

**Comment by Fa20** [comment]
Thanks ffor your answer. yes  attach mutiple arms to one trial. I have tried to use it with the follwoing example def create_experiment():
    ax_client = AxClient()
    ax_client.create_experiment(
        name="multi_objective_optimization",
        parameters=[
            {"name": "x1", "type": "range", "bounds": [-1.0, 3.0]},
            {"name": "x2", "type": "range", "bounds": [-2.0, 2.0]},
            {"name": "x3", "type": "range", "bounds": [-2.0, 2.0]},
            {"name": "x4", "type": "range", "bounds": [-20.0, 20.0]}
        ],
        objectives={
            "objective_1": ObjectiveProperties(minimize=True),
            "objective_2": ObjectiveProperties(minimize=False)
        },
        overwrite_existing_experiment=True
    )
    return ax_client

def evaluate_batch_trial(ax_client, batch_trial):
    for arm_name, arm in batch_trial.arms_by_name.items():
        objective_1_result = arm.parameters['x1'] * 2 
        objective_2_result = 100 - arm.parameters['x2']  

        ax_client.attach_trial_data(
            trial_index=batch_trial.index,
            arm_name=arm_name,
            results={
                "objective_1": (objective_1_result, 0.0),  
                "objective_2": (objective_2_result, 0.0)
            }
        )
    batch_trial.mark_completed()  

ax_client = create_experiment()

batch_trial = ax_client.create_batch_trial()  
for _ in range(10): 
    parameters = ax_client.get_next_trial().parameters
    batch_trial.add_arm(parameters)  

evaluate_batch_trial(ax_client, batch_trial)  but it does not work correct?  is there any tutorials which explain how mutiple arms can be used with example

**Comment by mgrange1998** [comment]
For a tutorial, you can follow the generation strategy tutorial https://ax.dev/tutorials/generation_strategy.html
Just set "use_batch_trials=True" when calling choose generation strategy.

For your example, could you please provide error logs and more details about why it is failing?

**Comment by Fa20** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[57], line 43
     40 ax_client = create_experiment()
     42 # Request a batch of 10 trials at once
---> 43 batch_trial = ax_client.create_batch_trial()  # Create a new batch trial
     44 for _ in range(10):  # Add 10 arms to the batch
     45     parameters = ax_client.get_next_trial().parameters

AttributeError: 'AxClient' object has no attribute 'create_batch_trial' , I have tried in the above code to use batch trail to get batch ot trials and then evaluate them   but it seems that I did it wrong

**Comment by Fa20** [comment]
https://ax.dev/tutorials/generation_strategy.html    but this toutorial I think for just one objective function  ? can I use it for batch trials in case of Multi-objective functions?

**Comment by mgrange1998** [comment]
Yes, try the "use_batch_trials" flag in the "choose_generation_strategy" method call. 
https://github.com/facebook/Ax/blob/9a624a2db22d7fda162091cd2522851a2e159385/ax/modelbridge/dispatch_utils.py#L290

**Comment by Fa20** [comment]
gs = choose_generation_strategy(
    search_space=get_branin_search_space(),  
    use_batch_trials=True, 
)

# Main optimization loop
for _ in range(2):  
    parameters, trial_index = ax_client.get_next_trial()
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate_parameters(parameters))
but how  can run the main optmization to get the multiply sugesstion of the papameters values  and not sequential  based on the above code I'm still geeting one sugesstion which is evaluted and then the nex  etc.

**Comment by Balandat** [comment]
> but how can run the main optmization to get the multiply sugesstion of the papameters values and not sequential based on the above code I'm still geeting one sugesstion which is evaluted and then the nex etc.

You can just call `.get_next_trial()` multiple times without calling `complete_trial()` in between. AxClient will be aware that the previous trials are "pending" and account for that in subsequent candidate suggestion(s).

**Comment by Fa20** [comment]
@Balandat  so in this case I do not need to use choose_generation_strateg  and no need to set the use_batch_trials=True if I understand you correct?  
my second question: is there any difference bewteen  using get_next_trial() multiple times  and then evalute the objective on them  and use choose_generation_strategy(
search_space=get_branin_search_space(),
use_batch_trials=True,
)  ?  are both give same accuracy of sugesstions for the value of the  parameters   ?

**Comment by Balandat** [comment]
> in this case I do not need to use choose_generation_strateg and no need to set the use_batch_trials=True if I understand you correct?

Yes. 

> are both give same accuracy of sugesstions for the value of the parameters ?

In a nutshell, yes. There are some subtleties about how exactly they are generated, but for all intents and purposes you can see them as equivalent in terms of generation. 

The main discerning factor of a `BatchTrial` is how the arms are being evaluated. You can read more about this here: https://github.com/facebook/Ax/blob/main/ax/core/batch_trial.py?fbclid=IwAR2UtrpXZwIWmylR2zZrq54v50RTtvs_r6pcJDWcG1a85riyjYGK0fGDL1g#L103-L115. If that's not the setting you're in you are fine with just calling`get_next_trial()` repeatedly.

**Comment by Fa20** [comment]
for the of  MOO (in my case differnt than the tutorial  since I do not have the refernce point). should I follow the same steps  since there are more detaials and also sobol sampling inclused  etc.  or should I follow create_experiment():
ax_client = AxClient()
ax_client.create_experiment(
name="multi_objective_optimization",
parameters=[
{"name": "x1", "type": "range", "bounds": [-1.0, 3.0]},
{"name": "x2", "type": "range", "bounds": [-2.0, 2.0]},
{"name": "x3", "type": "range", "bounds": [-2.0, 2.0]},
{"name": "x4", "type": "range", "bounds": [-20.0, 20.0]}
],
objectives={
"objective_1": ObjectiveProperties(minimize=True),
"objective_2": ObjectiveProperties(minimize=False)
},
overwrite_existing_experiment=True
)
return ax_client

def evaluate_batch_trial(ax_client, batch_trial):
for arm_name, arm in batch_trial.arms_by_name.items():
objective_1_result = arm.parameters['x1'] * 2
objective_2_result = 100 - arm.parameters['x2']

    ax_client.attach_trial_data(
        trial_index=batch_trial.index,
        arm_name=arm_name,
        results={
            "objective_1": (objective_1_result, 0.0),  
            "objective_2": (objective_2_result, 0.0)
        }
    )
batch_trial.mark_completed()  

ax_client = create_experiment()

batch_trial = ax_client.create_batch_trial()
for _ in range(10):
parameters = ax_client.get_next_trial().parameters
batch_trial.add_arm(parameters)   which is easy to understand it  but in this  case I will be not able to evaluate the results using  one of the two algoritms  explained in the tutorial

**Comment by Balandat** [comment]
You can follow the same steps for MOO, no need to use `BatchTrial`s for MOO. 

> which is easy to understand it but in this case I will be not able to evaluate the results using one of the two algoritms explained in the tutorial

You mean b/c the tutorial uses the developer API to evaluate the different algorithms? It is possible to also use different algorithms than the defaults in `AxClient` by passing a `GenerationStrategy` to the `AxClient()` instantiation: https://ax.dev/tutorials/generation_strategy.html

You also want to look at the current version of the tutorial if you're on a newer version of Ax (0.1.18 as in the tutorial is ancient): https://ax.dev/tutorials/multiobjective_optimization.html

**Comment by Fa20** [comment]
@Balandat  Thanks for your answer:  my problem like the following I have two objective functions that I want to find the solution for them with non linear constrained  and I need to get the values  of the sugested parameters then use them to calaculate the objective functions  but since get one sugesstion by one  will requried long time I need to use the batch trial  to get batch of sugesstions. I found the follwoing toutorial which looks not the new version : 
https://ax.dev/versions/0.1.18/tutorials/multiobjective_optimization.html

and the one which you sent me:
https://ax.dev/tutorials/multiobjective_optimization.html(I think I should follow this one ???)

my second question : in case that I will follow the implementation in the tutorial you share it (second link) how can I get batch of trials ?

my third question :  objectives = ax_client.experiment.optimization_config.objective.objectives
frontier = compute_posterior_pareto_frontier(
    experiment=ax_client.experiment,
    data=ax_client.experiment.fetch_data(),
    primary_objective=objectives[1].metric,
    secondary_objective=objectives[0].metric,
    absolute_metrics=["a", "b"],
    num_points=20,
)
render(plot_pareto_frontier(frontier, CI_level=0.90))  this part form the tutorial  which Algorithm is used here to evaluate the results  (qEHVI) or different one?  does the 20 point ploted represent the solution of the problem so that some one can print these values and consider them as solution for the problem in the tutorial? . The part start from "Deep Dive"  it is really not clear to me  do I need It for my  problem? because there are more detials

**Comment by mgrange1998** [comment]
Hi, 

`for i in range(5):
    trials_dict, _ = ax_client.get_next_trials(5)
    for trial_index, parameters in trials_dict.items():
        ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))`

This will create a group of 5 trials to be executed together. "trials_dict" is the batch of trials that you want.


- For the third question about the evaluation of plot_pareto_frontier, no algorithm is used here- the Pareto frontier just represent all optimal combinations of results of the trials. 
- Yes, the 20 point plot represents all optimal results from the run. Each point has a unique combination of the two objectives (labeled "a" and "b") which is not outperformed by any other point.
- Deep dive is not required to your problem
- It is a good idea to start with a lower number of trials just to get the experiment running. You could do 5 batches of 5 for 25 trials total.

**Comment by mgrange1998** [comment]
Yes, that is right- no need to set up qNEHVI or qNParEGO in order to use the pareto frontier call. 
Those algorithms use "plotted points are samples from the fitted model's posterior", wheras the regular pareto frontier call uses uses the observed samples of the experiment.

I don't expect you'd need >200 iterations, I'd start with a low number like 25 to get a feel for the results.

**Comment by Fa20** [comment]
but how can decide we that 25 iteration is ok  or we need more ? and in case that we need more should we start the experiment  form first trial  or can we continuou after the first 25 iteration  and how can we do this in case that I found that 25 iterations need to be increase to e.g.50 without to start from the  first trial ?

**Comment by bernardbeckerman** [comment]
@Fa20 There are rules of thumb for the minimum number of trials to achieve a reasonable model (roughly 2*n_parameters) but no strict guidelines on when you should stop sampling, since there's no guarantee that you will choose the global optimum without sampling the whole search space, and different folks are willing to spend different amounts of compute to achieve varying metric wins. Generally the idea is that you should optimize using what compute and/or time budget you have available, or if the compute cost starts to outweigh the cost of potential metric gain. Closing this out - please raise a new issue to get further help.
