### ISSUE TITLE
Crash after setting PyTorch default tensor type to cuda.FloatTensor

### ISSUE THREAD

**Issue by ebonetti** [facebook/Ax#247]
Hello folks at Facebook,
setting PyTorch default tensor type to cuda.FloatTensor leads Ax to crashing in a Colab GPU instance. 

[You can checkout a complete test setup in Colab.](https://colab.research.google.com/drive/14iURepsSmiLGdfaB9NGaDlDM9fbjZ3yO) This is the culprit:
`torch.set_default_tensor_type(torch.cuda.FloatTensor)`

Keep up the great work,
Enrico Bonetti Vieno

**Comment by 2timesjay** [comment]
@ebonetti thanks for bringing this to our attention. I can confirm that GPUs should be fully suppported, so we're investigating this bug now.

**Comment by Balandat** [comment]
This appears to be an issue with pytorch: 

```
import torch
from torch.quasirandom import SobolEngine

torch.set_default_tensor_type(torch.cuda.FloatTensor)
se = SobolEngine(3)  # crashes here
```

We'll have to fix this upstream.

**Comment by Balandat** [comment]
See #32494 for the issue and #32496 for the fix.

**Comment by Balandat** [comment]
I landed the fix upstream in pytorch. In order for this to work you'll have to use the pytorch nightlies (starting tomorrow)

**Comment by ebonetti** [comment]
Thank you for the fast resolution, great job! 💪
