### ISSUE TITLE
TensorBoard Support

### ISSUE THREAD

**Issue by Hailey-Liu** [facebook/Ax#248]
I am very new to Ax, I just wondering if Ax could automatically write to tensorboard for the experiments. Thanks!

**Comment by ldworkin** [comment]
Hi @Hailey-Liu! We don't have an example for this yet, but it should be possible to do. We can try to get you an example notebook in the next few weeks -- I'll keep you posted.

**Comment by lena-kashtelyan** [comment]
We will now be tracking wishlist items / feature requests in a master issue for improved visibility: #566. Of course please feel free to still open new feature requests issues; we'll take care of thinking them through and adding them to the master issue.
