### ISSUE TITLE
DEPRECATING DISCUSSIONS - USE ISSUES INSTEAD

### ISSUE THREAD

**Issue by bernardbeckerman** [facebook/Ax#2485]
We've decided to discontinue Discussions in the Ax repo for two reasons:

1. Most discussions we've seen lately are better tracked as issues.
2. This creates a redundant (and more poorly tracked) surface for us to monitor and maintain.

To bring an item up for discussion, please use the Issues tab instead.

**Comment by sgbaird** [comment]
Have the existing discussions been converted back to issues?
