### ISSUE TITLE
model.predict does not work

### ISSUE THREAD

**Issue by AliAlkadhim** [facebook/Ax#2490]
I am trying to trying to use the `model.predict()` method in Ax's Service API, but it is not working. For example, after completing my optimization study, I'm trying to use my model with something like
```
model = ax_client.generation_strategy.model
ab_features = df[params].values
ab_features = [torch.tensor(ab_features)]
means_ab, covarinaces_ab = model.predict(ab_features)
```

but I get the error: `AttributeError: 'Tensor' object has no attribute 'parameters'`. Trying this with `ab_features` being numpy arrays, lists, or torch tensors all result in the same error. The error seems to be coming from ax/modelbridge/transforms/unit_x.py:62

Please help me in using model.predict()! Thanks so much!

**Comment by mpolson64** [comment]
Hi @AliAlkadhim -- Modelbridge.predict consumes a List[ObservationFeatures], not a tensor or array. Calling the following snippet with your parameterization swapped out should lead to desired behavior. Let me know if you have any other questions.

```
from ax.core.observation import ObservationFeature

point = {
    "foo": 0,
    "bar": 1,
}

prediction = ax_client.generation_strategy.model.predict(
    observations=[
        ObservationFeature(parameters=point)
    ],
)
```
