### ISSUE TITLE
parameterization values are not disply  on the plot

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2502]
Hallo,

I have 12 parametrs  to find the optimal values that minimizes and maximize two objective function . why can'T we see values of the parameters on the plot  blow? and how can we access/get the parameters values that minimize and maximize the objective functions? 
P:S:  I have nonliner constarined .  I thing the problem becuase I have 12 parameters  my question how can we get the best values of the params even not  the plot 
![grafik](https://github.com/facebook/Ax/assets/44325972/83093f88-1ef9-48ff-a8d7-0f67da492761)

**Comment by mgarrard** [comment]
Hi @Fa20, thanks for the question. Could you provide a code snippet of how you are generating this plot so I can see which plot you are looking at here?

Likely you'll want to do something like `ax_client.get_trials_data_frame()` which will print the trial information as a dataframe so you can see each parameterization for each arm in each trial.

**Comment by Fa20** [comment]
@mgarrard objectives = ax_client.experiment.optimization_config.objective.objectives
frontier = compute_posterior_pareto_frontier(
    experiment=ax_client.experiment,
    data=ax_client.experiment.fetch_data(),
    primary_objective=objectives[1].metric,
    secondary_objective=objectives[0].metric,
    absolute_metrics=["a", "b"],
    num_points=30,
)
render(plot_pareto_frontier(frontier, CI_level=0.90))

**Comment by mgarrard** [comment]
Oh `compute_posterior_pareto_frontier` actually returns ParetoFrontierResults which contains param_dicts: List[TParameterization] -- if you look in there you will be able to see the parameterization of each arm.

Also yes the range represents the uncertainty with a ci_level = 90

**Comment by Fa20** [comment]
@mgarrard thanks.  how can we solve the problem related to the  visulaization ?

**Comment by mgarrard** [comment]
I think the above is the best we can do where you inspect the data values themselves, the plot cannot have 12 values shown on hover but by looking at the parameterizations of each arm as described above you should be able to easily match the point on the vizualization to the data. :)
