### ISSUE TITLE
Using nonlinear constraints with boolean masks

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2534]
Hallo
How can  I use 
 nonlinear constraints with boolean masks   in AX?

**Comment by danielcohenlive** [comment]
Hi @Fa20 , thanks for your question.  If by nonlinear constraints you mean something like `a^2 + b < 1` or `a^2 < b` we don't support that yet.  If you need it this can serve as a feature request though.  Do you need these constraints for parameters or the outcomes in constrained optimization.

**Comment by Fa20** [comment]
@danielcohenlive  thanks for your answer. I mean something like :(x1-2*x2>0)&(x2+0.5x1<0)

**Comment by danielcohenlive** [comment]
@Fa20 that's not supported. The constraints are in a python-like format, but they aren't actually executed as raw python under the hood.  Can you describe what you're trying to do at a high level?  Maybe there's another way to accomplish it.  If not you're welcome to make a feature request.

**Comment by Fa20** [comment]
@danielcohenlive  I 'm using this conditions to filter the the range of the prameters and one of the filter condition  is : (x1-2*x2>0)&(x2+0.5x1<0) but I'm thinking to split it to two condition and add them to parameters_constrains   ?

**Comment by Balandat** [comment]
> but I'm thinking to split it to two condition and add them to parameters_constrains ?

Yes, that's the right move here
