### ISSUE TITLE
input data is not standardized (mean = tensor([0.]

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2535]
```python
<<Input data is not standardized (mean = tensor([0.], dtype=torch.float64), std = tensor([0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.

C:\Users\anaconda3\Lib\site-packages\botorch\models\utils\assorted.py:202: InputDataWarning:

Input data is not standardized (mean = tensor([0.], dtype=torch.float64), std = tensor([0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.

second print
C:\Users\anaconda3\Lib\site-packages\botorch\models\utils\assorted.py:202: InputDataWarning:

Input data is not standardized (mean = tensor([0.], dtype=torch.float64), std = tensor([0.], dtype=torch.float64)). Please consider scaling the input to zero mean and unit variance.



another warning ;Encountered a `MultiObjective` without objective thresholds. We will winsorize each objective separately. We strongly recommend specifying the objective thresholds when using multi-objective optimization.
>>
```
what is the reason for this warning and how can I fix it?

**Comment by danielcohenlive** [comment]
Hi @Fa20 , I tried your code from the original comment and got a different error that goes away when you add spacing to the parameter constraints (`x1 - 1.5*x2 >= 0.0`).  Can you please provide a full repro?

**Comment by Fa20** [comment]
Hi @danielcohenlive 
1-which code exactly from original comment do you mean?
2- do you mean that the problem because of the spacing and can be fixed by adding spacing

**Comment by danielcohenlive** [comment]
> 1-which code exactly from original comment do you mean?

This is the original code I'm referring to 
<img width="515" alt="image" src="https://github.com/facebook/Ax/assets/6516020/11517c27-e660-48ec-a49b-069aa27889b1">

2- do you mean that the problem because of the spacing and can be fixed by adding spacing

When I run that code as is I get 
"ValueError: could not convert string to float: 'x1-1.5'"
If I change `"x1-1.5*x2 >= 0.0"` to `"x1 - 1.5*x2 >= 0.0"` I stop getting that when running the above code.

But I don't know how to get the "Input data is not standardized" you're showing.  Could you provide a minimal code repro with any private info redacted so I could help you?

**Comment by Fa20** [comment]
@danielcohenlive  Thank you very much.

based on the tutorial "parameter_constraints should be a list of strings of form "p1 >= p2" or "p1 + p2 <= some_bound"

I'm asking becuase I opend new issue related this point also that the x1 - 1.5*x2 >= 0.0   using service API since in the tutorial written  the above statment . I have tried and got an error that it is not allowed to multiply by some constant?

**Comment by Fa20** [comment]
@danielcohenlive  does this means that in Service API can we insert this cons. "x1 - 1.5*x2 >= 0.0?

**Comment by danielcohenlive** [comment]
> I have tried and got an error that it is not allowed to multiply by some constant?

Could you give a full repro of the error?

**Comment by Fa20** [comment]
![grafik](https://github.com/facebook/Ax/assets/44325972/8572df47-ee4c-41f3-8995-5262d774117a)

**Comment by danielcohenlive** [comment]
@Fa20 by full repro I mean code that I can copy and paste in a notebook in my own environment without modification that you have verified will result in the error you're describing when I run it.

**Comment by lena-kashtelyan** [comment]
Looks like this has been inactive for a while. @Fa20, please reopen this if you still need help! We are not likely to see further activity on a closed issue.
