### ISSUE TITLE
nonlinear constarined in evaluate paramter instead add to  the experiment

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2536]
Hallo,
in case that I have nonlinear constrained  as in the code( second_condition) and since I'm using service API can not add it to the experiement as paramter constarined . is it ok to keep it inisde the  evaluate_parameters ? does this will lead to more iteration in order the model to learn such this constarined on the parameters ?. Thanks
def evaluate_parameters(params:dict)->dict:

        x1=params.get('x1')
        x2=params.get('x2')
    
        x2=params.get('x3')
        x4=params.get('x4')
        x5=params.get('x5')
        ### constrained 1
    
      
        ### constrained 2
       lvec = x4* 1.5 
        u_ec =x4 * 5
       second_condition = (lvec <x5) & (
                x5 < u_ec
            )
       
    
     
        if   (second_condition) :
           
            return {"objective_1": (p_2(),0.0), "objective_2": (p_1(),0.0),"second_condition":(second_condition, 0.0)}

**Comment by Fa20** [comment]
Please  close this issue. Thanks

**Comment by danielcohenlive** [comment]
Closing as per request
