### ISSUE TITLE
Defining Metric in Ax Service

### ISSUE THREAD

**Issue by Abrikosoff** [facebook/Ax#2538]
Hi Ax team,

In my latest use case, I want to give suggestions that correspond to objectives that are as close as possible to some target values. A natural way to do this (I think) is via `Metric` definitions, something like 

```
class MetricClass(NoisyFunctionMetric):
   def f(self, x: TParameterization) -> float:
       return float(np.abs(x[variable_name] - reference_value))
```    
This should work well in Developer, but as I am exclusively doing Service now, I was wondering if I could do something similar, but for Service?

**Comment by danielcohenlive** [comment]
Hi @Abrikosoff, thanks for the question.  The service API as of now is not designed to work with metrics or runners.  It's an ask/tell API.  What you'd want to do is overwrite the [`evaluate` function](https://ax.dev/tutorials/gpei_hartmann_service.html#3.-Define-how-to-evaluate-trials) in the service API tutorial.

**Comment by Abrikosoff** [comment]
> Hi @Abrikosoff, thanks for the question. The service API as of now is not designed to work with metrics or runners. It's an ask/tell API. What you'd want to do is overwrite the [`evaluate` function](https://ax.dev/tutorials/gpei_hartmann_service.html#3.-Define-how-to-evaluate-trials) in the service API tutorial.

Thanks for the info regarding the API, and especially for the suggestion to overwrite `evaluate`! That was a ''D'oh" moment for me for sure :-( Closing this with thanks!
