### ISSUE TITLE
Services API  :×1-1.5*×2>=0

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2540]
Hallo
Can we  use service Api as here
https://ax.dev/tutorials/gpei_hartmann_service.html#2.-Set-up-experiment
to insert the above  condition in the parameters_constraints?
and how?
Based on the above tutorial the constraints should be p1+p2<=value
But in my case we have 1.5  multiply by p2?

**Comment by Abrikosoff** [comment]
Fly-by-comment: this should be possible, at least if you're going the `ParameterConstraint` definition route: [here](https://ax.dev/docs/core.html), but not sure if the same applies if you define an `AxClient`. Did you try it?

**Comment by Fa20** [comment]
@Abrikosoff  This in case of using Api developer

**Comment by danielcohenlive** [comment]
The tutorial gives those 2 examples, but from looking at the [docstring](https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L292) it should be valid, provided you insert a space like
```
×1 - 1.5*×2>=0
```

**Comment by Fa20** [comment]
@danielcohenlive  thanks for your Answer.
you can close the issue
