### ISSUE TITLE
 plot_pareto_frontier

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2543]
Hallo Ax Team, 
in case of MOO how can we descied if we need more iteration or not ?  using plot_pareto_frontier will be able to say if we need more iteration or not and how?

**Comment by danielcohenlive** [comment]
This is an area of Bayesian Optimization in general that requires a judgement call.  I don't know a lot about your particular use case, but there is a cost benefit analysis to be done about whether improvement has plateaud and how expensive it is to continue iterating. 

If you want a numerical way of evaluating it you could use [`AxClient.get_hypervolume()`](https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L1581).

**Comment by Fa20** [comment]
@danielcohenlive  is there any tutorial or example how can I use it?   could you please show this with example ?
My use case consist ot two objective functions with 7 conditions

**Comment by danielcohenlive** [comment]
@Fa20 yes.  Refer to https://ax.dev/tutorials/multiobjective_optimization.html.  Unfortunately this isn't written for the service API as it's considered advanced usage, but [AxClient.get_hypervolume()](https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L1581) will be able to handle the modeling setup for you.

**Comment by Fa20** [comment]
@danielcohenlive ok thanks

**Comment by danielcohenlive** [comment]
@Fa20 you can think of get_hypervolume as returning the numeric equivalent of what you might be looking for in the pareto plot.  So it would be instead, but you could call both in any order you want.  They're both read only operations.

**Comment by Fa20** [comment]
@danielcohenlive  you can close this issue . Thanks
