### ISSUE TITLE
Question: Multi-Task Multi Objective

### ISSUE THREAD

**Issue by VadimBim** [facebook/Ax#2555]
Dear Ax team, 

I use [optimas](https://github.com/optimas-org/optimas), which uses Ax for Bayesian Optimization.

I am interested in optimizing a multi-objective problem and wondered if I can use multi-task for this purpose. This question was asked a long time ago #564, and the answer is that fundamentally this is possible.

It seems that the developers of Optimas implemented [multi-task](https://github.com/optimas-org/optimas/blob/main/optimas/generators/ax/developer/multitask.py) using Ax developer API. But only one objective is supported at the moment.

I am curious how one would modify `AxMultitaskGenerator` class to handle multi-objective optimization?

I would greatly appreciate any guidance or examples on how to modify the `AxMultitaskGenerator` class to support multi-objective optimization. As an inexperienced student, I apologize if this is a naive question, and thank you in advance for your help and understanding !

**Comment by Abrikosoff** [comment]
Drive by commenting here, but from the optimas [code](https://github.com/optimas-org/optimas/blob/main/optimas/generators/ax/developer/multitask.py#L342), as first step you can probably modify this [line](https://github.com/optimas-org/optimas/blob/110b48da6cf2f38f2b8cf02f196e12e104d6ccf5/optimas/generators/ax/developer/multitask.py#L342) to one of these options in [this](https://github.com/facebook/Ax/issues/564#issuecomment-827273606) comment.
