### ISSUE TITLE
[GENERAL SUPPORT]: Using qNegIntegratedPosteriorVariance

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#2581]
### Question

Hello,

I tried to use the acquisition function qNegIntegratedPosteriorVariance for active learning as a new botorch_acqf_class in my generation straetgy. 

For example, after using save/load ax_client to json file, I added qNegIntegratedPosteriorVariance in botorch_modular_registry as asked.

Now I have a this message : 

RuntimeError: Cholesky errors typically occur when the same or very similar arms are suggested repeatedly. This can mean the model has already converged and you should avoid running further trials. It will also help to convert integer or categorical parameters to float ranges where reasonable. **Original error: : RuntimeError: Input constructor for acquisition class `qNegIntegratedPosteriorVariance` not registered. Use the `@acqf_input_constructor` decorator to register a new method.**

I'm wondering if what I'm doing is right considering the number of modifications needed.

Thanks for your help

### Please provide any relevant code snippet if applicable.

```shell
Example of generation step : 

GenerationStep( model=Models.BOTORCH_MODULAR,num_trials=-1, model_kwargs={"surrogate": Surrogate(SingleTaskGP),"botorch_acqf_class": qNegIntegratedPosteriorVariance,}
```

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by Abrikosoff** [comment]
This error means that you need to register the acquisition function following the example given in the [tutorial](https://ax.dev/tutorials/modular_botax.html#3B.-Using-an-arbitrary-BoTorch-AcquisitionFunction-in-Ax) before passing it to your generation strategy.

**Comment by mgarrard** [comment]
Hi @Kh-im let me know if the solution above isn't sufficient, and feel free to re-open the issue. Thanks @Abrikosoff for being an active community member :)

**Comment by Kh-im** [comment]
Yes Thanks !

**Comment by davifebba** [comment]
How to add this acquisition function to botorch_modular_registry and then use ax_client.save_to_json_file() ?
