### ISSUE TITLE
[GENERAL SUPPORT]: Reference point for multi-objective bayesian optimization

### ISSUE THREAD

**Issue by renaissanceM4n** [facebook/Ax#2582]
### Question

How is the reference point set in multi-objective Bayesian optimization with qNParEGO, qEHVI or qNEHVI if no reference point was specified by the user when defining the objectives?
I performed an optimization and was able to plot the progress of the hypervolume improvement per trial using the get_trace() method of the client.
I would be very happy to receive feedback.

### Please provide any relevant code snippet if applicable.

![image](https://github.com/user-attachments/assets/f275ddc0-41da-4fe0-8d79-28c07fe308c8)

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by Abrikosoff** [comment]
I believe this is actually mentioned in the MO [tutorial](https://ax.dev/versions/v0.1.20/tutorials/multiobjective_optimization.html):

`The reference point should be set to be slightly worse (10% is reasonable) than the worst value of each objective that a decision maker would tolerate. In the figure below, the grey area is the hypervolume in this 2-objective problem.`

**Comment by dpeitz** [comment]
Yes you're right. I just wanted to know what happens if no reference point is defined at all.

**Comment by Abrikosoff** [comment]
My uninformed guess would be that the optimizer would then be forced to search in a larger search space, which would probably impact some efficiency and processing cost metrics; but would love to hear from the devs, for sure!

**Comment by mgarrard** [comment]
Hi @renaissanceM4n and @Abrikosoff, this will end up going through  `infer_objective_thresholds` here (https://github.com/facebook/Ax/blob/main/ax/modelbridge/torch.py#L153) which will eventually set the reference point to slightly worse than nadir point (worst observation for each outcome - 0.1 of that outcome's range). But, in practice, it is optimal for the user to provide the reference point if it is known :) 

Please feel free to reopen the issue with any follow-ups.
