### ISSUE TITLE
[GENERAL SUPPORT]: Manual configuration,

### ISSUE THREAD

**Issue by Fa20** [facebook/Ax#2592]
### Question

Hello,
is there any difference between use GPEI model and Botorch model in the Generation Strategy  for MOO?

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by mgarrard** [comment]
Hi @Fa20, i'd recommend this tutorial to learn about modular botorch model: https://ax.dev/tutorials/modular_botax.html 

However, once nice thing about Ax is that when using the Service API, we will automatically select the best GenerationStrategy during the experiment setup step here (https://ax.dev/tutorials/gpei_hartmann_service.html#2.-Set-up-experiment). For almost all cases, relying on our logic for GenerationStrategy selection will yield the best results. 

Closing the issue for now, but please feel free to re-open if you have more specific questions about this.
