### ISSUE TITLE
[Bug]: Large sample time increase in ax-platform >=  version 0.3.5

### ISSUE THREAD

**Issue by GilesStrong** [facebook/Ax#2604]
### What happened?

The `AxClientget_next_trial()` call when using the service API shows a large increase (~3.7x) in completion time for Ax versions >= 0.3.5.

For the simple problem detailed below (taken from the [Ax service example](https://ax.dev/tutorials/gpei_hartmann_service.html)), the timings for the `get_next_trial` call are as follows (50 calls total, sobol samples excluded from Avg and max computation):

- ax-platform = "0.3.2": total time 23s, 0.54s Avg, 1.9 max
- ax-platform = "0.3.3": total time 25s, 0.59s Avg, 2.3 max
- ax-platform = "0.3.4": total time 24s, 0.58s Avg, 2.2 max
- ax-platform = "0.3.5": total time 62s, 1.6s Avg, 5.3 max
- ax-platform = "0.3.6": total time 61s, 1.5s Avg, 5.7 max
- ax-platform = "0.3.7": total time 78s, 2.0s Avg, 3.5 max
- ax-platform = "0.4.0": total time 55s, 1.3s Avg, 5.0 max
- ax-platform = "0.4.1": total time 78s, 2.0s Avg, 4.9 max

Note the large increase in average sample time, and maximum sample time between 0.3.4 and 0.3.5.

Looking through the release notes, there doesn't seem to be an obvious candidate for the cause of this slowdown.

Is there a plausible explanation for this?
Many thanks in advance.

### Please provide a minimal, reproducible example of the unexpected behavior.

```python
import timeit

import numpy as np
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.utils.measurement.synthetic_functions import hartmann6


def test_timing():
    """
    ax-platform = "0.3.2": 23s, 0.54s Avg, 1.9 max
    ax-platform = "0.3.3": 25s, 0.59s Avg, 2.3 max
    ax-platform = "0.3.4": 24s, 0.58s Avg, 2.2 max
    ax-platform = "0.3.5": 62s, 1.6s Avg, 5.3 max
    ax-platform = "0.3.6": 61s, 1.5s Avg, 5.7 max
    ax-platform = "0.3.7": 78s, 2.0s Avg, 3.5 max
    ax-platform = "0.4.0": 55s, 1.3s Avg, 5.0 max
    ax-platform = "0.4.1": 78s, 2.0s Avg, 4.9 max
    """
    ax_client = AxClient(verbose_logging=False)
    ax_client.create_experiment(
        name="hartmann_test_experiment",
        parameters=[
            {
                "name": f"x{i}",
                "type": "range",
                "bounds": [0.0, 1.0],
            }
            for i in range(6)
        ],
        objectives={"hartmann6": ObjectiveProperties(minimize=True)},
    )

    def evaluate(parameterization):
        x = np.array([parameterization.get(f"x{i}") for i in range(6)])
        return {"hartmann6": (hartmann6(x), 0.0)}

    sample_times = []
    for i in range(50):
        timer = timeit.default_timer()
        parameterization, trial_index = ax_client.get_next_trial()
        sample_time = timeit.default_timer() - timer
        print(f"Sample time: {sample_time}")
        if i >= 12:  # Not Sobol
            sample_times.append(sample_time)
        ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameterization))
    print(f"Average sample time: {np.mean(sample_times)}")
    print(f"Max sample time: {np.max(sample_times)}")
``` 

### Ax Version

0.3.5, 0.3.6, 0.3.7, 0.4.0, 0.4.1

### Python Version

3.10.12

### Operating System

Ubuntu 22.04

### Code of Conduct

- [X] I agree to follow Ax's Code of Conduct

**Comment by esantorella** [comment]
Thanks for reporting this. A slowdown definitely wasn't expected behavior. We'll look into this.

**Comment by mgrange1998** [comment]
Hi, also taking a look through the code changes between 0.3.4 and 0.3.5 here https://github.com/facebook/Ax/compare/0.3.4...0.3.5

**Comment by mgrange1998** [comment]
Haven't identified the source of the regression, but the long running method in the .get_next_trial() call is [GenerationStrategy::_gen_multiple](https://github.com/facebook/Ax/blob/f4d1ea8ef830ef9884218192f37c67d0efbca79c/ax/modelbridge/generation_strategy.py#L356), which contains the long running call [GenerationNode::gen](https://github.com/facebook/Ax/blob/f4d1ea8ef830ef9884218192f37c67d0efbca79c/ax/modelbridge/generation_node.py#L251)

I ran the code example on my own, and noticed that as "ax_client.get_next_trial()" was called repeatedly, the run time for _gen_multiple would increase over time. Over 50 calls, its run time increased from 0.03 to 15 seconds. 

So far, I haven't been able to find the change in GenerationNode that accounts for the increase between versions 0.3.4 and 0.3.5.

**Comment by dme65** [comment]
My guess is that this slowdown is coming from #1792 2 which improved the default acquisition functions in Ax. This is not a bug, but rather a significantly improvement.

Before this change, the acquisition functions were much harder to optimize (because of the gradients being numerically zero) so `.gen()` would terminate very quickly. After #1792, we are doing a much better job optimizing the acquisition function. While this will result in better optimization performance as Ax generates better candidates, it will also take longer since we will take many more gradient steps when optimizing the acquisition function.

**Comment by dme65** [comment]
I verified the suspicion above by running your code snippet with the two different acquisition functions:
- With `qNoisyExpectedImprovement` (the default before #1792) the average sample time is 0.65s.
- With `qLogNoisyExpectedImprovement` (the default after #1792) the average sample time is 2.06s.

**Comment by GilesStrong** [comment]
Ah, I see! That does seem like a worthwhile trade-off then.
Many thanks everyone for the quick response and diagnosis. I'll close this issue now.
