### ISSUE TITLE
Non-linear constraints "x1 * x2 <= 32"

### ISSUE THREAD

**Issue by aleczhanshi** [facebook/Ax#261]
Hi there, I'm trying to enforce a non-linear constraint between two parameters, like "x1 * x2 <= 32". It throws an error **"ValueError: A linear constraint should be the form a*x + b*y - c*z <= d, where a,b,c,d are float constants and x,y,z are parameters. There should be no space in each term around the operator * while there should be a single space around each operator +, -, <= and >=."**

Is there anyway that we can realize this in Ax?

Here's my code snippet.
```
best_parameters, values, experiment, model = optimize(
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [1, 32],
            "value_type": "int",
        },
        {  
            "name": "x2",
            "type": "range",
            "bounds": [1, 32],
            "value_type": "int",
        },
        {  
            "name": "x3",
            "type": "range",
            "bounds": [1, 32],
            "value_type": "int",
        },
        {  
            "name": "x4",
            "type": "range",
            "bounds": [1, 32],
            "value_type": "int",
        },
    ],
    evaluation_function=mapping,
    minimize=True,
    total_trials=10000,
    parameter_constraints=["x1 * x2 <= 32"],
)
```

**Comment by Balandat** [comment]
We currently don't support arbitrary parameter constraints in Ax. There is no fundamental reason for not supporting this, but it would require some work and the internals, and so far there has not been much demand for it. It would likely also slow down candidate generation quite a bit b/c solving the acquisition maximization problem over general non-convex constraint set will require a lot more evaluations of the surrogate model.

**Comment by aleczhanshi** [comment]
Thanks. Is there any trick that we can use to specify the constraints under the current framework?

**Comment by eytan** [comment]
Yes, you can create a new outcome variable or "metric" whose value is
x1*x2, and then use an outcome constraint.

**Comment by aleczhanshi** [comment]
@eytan Could you show me how to have a constraint like "x1*x2=32" using the outcome variable or "metric"? In particular, I want to add this to https://github.com/pytorch/botorch/blob/master/tutorials/custom_botorch_model_in_ax.ipynb and need a strict equal instead of GEQ or LEQ. Thanks!
