### ISSUE TITLE
Implement a constraint "x1*x2=32"

### ISSUE THREAD

**Issue by aleczhanshi** [facebook/Ax#263]
Could anyone show me how to have a constraint like "x1*x2=32" using the outcome variable or "metric"? In particular, I want to add this to https://github.com/pytorch/botorch/blob/master/tutorials/custom_botorch_model_in_ax.ipynb and need a strict equal instead of GEQ or LEQ. Thanks!

**Comment by ldworkin** [comment]
Duplicate of https://github.com/facebook/Ax/issues/265
