### ISSUE TITLE
[GENERAL SUPPORT]: Logical-or in outcome constraints

### ISSUE THREAD

**Issue by WangYuNeng** [facebook/Ax#2638]
### Question

Currently the outcome constraints are logic-and of inequalities such as `outcome_constraints=["a <= 1", "b<=2"]`.
Is there recommended way to have logic-or in outcome constraints such as `a<=1 or b<=2`?

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by bernardbeckerman** [comment]
@WangYuNeng this is currently not an option in Ax. Can you tell me a bit more about your use-case and how you would use this? E.g., I'm curious what these constraints are. I'm tempted to recommend a scalarization, but want to make sure I understand your use-case first.

**Comment by esantorella** [comment]
Yeah, this isn't supported in Ax. You could use BoTorch with a Monte Carlo acquisition function, which takes a generic callable that says whether a set of outcomes is feasible or not. See documentation [here](https://botorch.org/docs/constraints). So if you

**Comment by WangYuNeng** [comment]
Hi @bernardbeckerman  and @esantorella, thanks for answering. I am using Ax for a blackbox optimization. I didn't actually encounter the "or" scenario right now so don't have a good example to show. Just curious because I expect "or" might happen in the future. I think Botorch Monte Carlo acquisition will address the need then.

**Comment by bernardbeckerman** [comment]
Thanks for the additional info. Resolving this issue but please feel free to reopen or open a new issue if you need further assistance in the future.
