### ISSUE TITLE
[GENERAL SUPPORT]: Why `qLogNEI` by default?

### ISSUE THREAD

**Issue by jeffgortmaker** [facebook/Ax#2699]
### Question

I see last year (#1792) that the default acquisition function for all Botorch models was set to `qLogNEI`.

I was wondering why this is the default for Ax? Reading the [paper](https://dl.acm.org/doi/abs/10.5555/3666122.3667026), I see convincing comparisons to other `EI`-style acquisition functions, which I'm guessing is part of the the justification. But I don't see any comparisons to, e.g., `qKnowledgeGradient`, which seems to be a favorite in the Bayesian optimization literature.

Have there been other comparisons that suggest `qLogNEI` performs better than `qKnowledgeGradient`? Or other reasons why it's the default acquisition function for Ax?

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by Balandat** [comment]
Hi @jeffgortmaker, thanks for the question. The main reasons are scalability and robustness:

**Scalability:** KG perform a lookahead step, which makes it computationally a lot more expensive than (log)EI. While this is not a huge concern if evaluations are extremely expensive / time-consuming, many people use Ax also for cases where evaluations are cheaper / quicker - in these settings using KG by default could make the candidate generation overhead substantial and similar or even larger than the evaluation itself. 

**Robustness:** For KG to work well it requires a pretty decent & well-calibrated surrogate model. If that's not the case, its performance can degrade more than for acquisition functions that are not quite as reliant on a highly accurate surrogate. While one could evaluate this by analyzing the model fit during the optimization, automating this decision isn't straightforward from an engineering perspective (though we have plans to work on this kind of adaptive model selection problem more generally going forward).

**Comment by jeffgortmaker** [comment]
Thanks! Makes sense. I'd experienced the scalability reason when trying out KG, but hadn't seen a clear statement of the robustness reason before. I'm going to close this issue since I think this pretty much sums it up.
