### ISSUE TITLE
Is Ax a good interface for custom BoTorch model?

### ISSUE THREAD

**Issue by aleczhanshi** [facebook/Ax#272]
Hi there, I'm recently trying to get on with BoTorch, and was wondering if Ax is a good interface to use if I plan to customize the acquisition function and outcome constraints in BoTorch, or should I go with BoTorch directly. Thanks!

**Comment by ldworkin** [comment]
Hi @aleczhanshi ! You should definitely be able to use Ax with Botorch, even if you plan to customize the Botorch model. See this tutorial: https://botorch.org/tutorials/custom_botorch_model_in_ax. The only reason to use Botorch entirely on its own is if you need complete control of the optimization loop (e.g. https://botorch.org/tutorials/closed_loop_botorch_only).

Let me know if those tutorials help at all or if you need further guidance.

cc @Balandat

**Comment by ldworkin** [comment]
Going to close this issue, but let us know if you have any further questions!
