### ISSUE TITLE
[GENERAL SUPPORT]: Multi-Objective, scale about the objectives 

### ISSUE THREAD

**Issue by rachelhson** [facebook/Ax#2724]
### Question

Hello,

I am currently working with a test that involves two different objectives, each with different scales. For instance, one objective has values ranging from 500 to 1000, while the other ranges from 0.5 to 2.0. Can the ax-client  handle these objectives equally despite their different scales? If so, what would be the recommended setup to ensure both objectives are optimized equally?

Thank you!

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by eytan** [comment]
All of the outcomes are normalized under the hood, so they will be
optimized with equal weight by default!

**Comment by mgarrard** [comment]
@rachelhson thanks for the question, closing the issue per Eytan's answer. Feel free to re-open with follow-ups, or open another issue to for any future questions :)

**Comment by rachelhson** [comment]
@eytan Thank you for your response.  How it is normalized under the hood? Is there any reference page how it is handling? Thank you :)
