### ISSUE TITLE
[Question?] Factorials model usage

### ISSUE THREAD

**Issue by AlexJoz** [facebook/Ax#275]
I came up with this code:

```
strategy = GenerationStrategy(
    name="search_strategy",
    steps=[
        GenerationStep(
#             model=Models.FACTORIAL,
            model=Models.SOBOL, 
            num_arms=-1
        )
    ]
)
 
cl = AxClient(
    generation_strategy=strategy,
    enforce_sequential_optimization=False)

cl.create_experiment(
    name="test",
    parameters=[
        {
            "name": "a",
            "type": "range",
            "bounds": [0, 1],
        },
        {
            "name": "b",
            "type": "range",
            "bounds": [0, 1],
        }
        
    ],
    objective_name="obj"
)
```
When I use SOBOL, `cl.get_next_trial()` is working fine. If I change model to `Models.FACTORIAL` it fails with:

```
venv/lib/python3.8/site-packages/ax/modelbridge/array.py in validate_optimization_config(optimization_config, outcomes)
    482     for obj_metric_name in obj_metric_names:
    483         if obj_metric_name not in outcomes:  # pragma: no cover
--> 484             raise ValueError(
    485                 f"Objective metric {obj_metric_name} not found in fitted data."
    486             )

ValueError: Objective metric obj not found in fitted data.
```
Is it expected behaviour? Give me the correct workflow hint please.

**Comment by ldworkin** [comment]
Hi @AlexJoz ! Thanks for pointing this out. It looks like this is definitely a bug on our end, and we'll fix it ASAP.

However, I want to also point out that the Factorial model only works on discrete search spaces. In other words, all of your parameters need to be Choice or Fixed parameters (https://ax.dev/api/models.html#module-ax.models.discrete.full_factorial).

So even if this bug is fixed, you'll still see another error about that.

**Comment by AlexJoz** [comment]
Ok) got it. Thanks.

**Comment by ldworkin** [comment]
Actually, after looking at this further, it's really not sensible in any situation to use a factorial generator in this way. The service API currently only supports 1-arm trials, and the factorial generator always generates a trial containing an arm for each possible combination of parameters.

However we can definitely make the error message more instructive in this case!

Let me know if this makes sense; closing the issue for now.
