### ISSUE TITLE
How to Cite Ax

### ISSUE THREAD

**Issue by JanoschMenke** [facebook/Ax#281]
Is there a preferred way in which Ax wants to be cited?

I could not find anything online.

**Comment by Jakepodell** [comment]
Hi Janosch!

Thanks for bringing this to our attention. We're working on adding a section to our website that will explain the preferred way to cite Ax.

For now, please cite the following paper: https://konstantinkashin.com/assets/papers/AE-NeurIPS2018.pdf.

Please let me know if you have any other questions :)

**Comment by JanoschMenke** [comment]
Thanks, will do.

**Comment by hosseinjafar** [comment]
Any update on this? or should i just keep citing the paper above?

**Comment by ppriyank** [comment]
Can I get the name of the paper? 

https://konstantinkashin.com/assets/papers/AE-NeurIPS2018.pdf.
> For now, please cite the following paper: https://konstantinkashin.com/assets/papers/AE-NeurIPS2018.pdf.

This seems to be a hacked website

**Comment by Balandat** [comment]
Interesting - cc @kkashin... 

Here is another link to the paper: http://learningsys.org/nips18/assets/papers/87CameraReadySubmissionAE%20-%20NeurIPS%202018.pdf

You can cite this as 
> E. Bakshy, L. Dworkin, B. Karrer, K. Kashin, B. Letham, A. Murthy, S. Singh. AE: A domain-agnostic platform for adaptive experimentation. Workshop on Systems for ML and Open Source Software, NeurIPS 2018.

**Comment by ppriyank** [comment]
Gracias!

**Comment by sgbaird** [comment]
There is now the most recent ax paper: https://openreview.net/pdf/584b0ca2f24035d154417534025c3acde6cb819a.pdf

https://openreview.net/forum?id=U1f6wHtG1g#discussion
