### ISSUE TITLE
[GENERAL SUPPORT]: Getting extremely slow in multi-objective optimization

### ISSUE THREAD

**Issue by howardwang1997** [facebook/Ax#2859]
### Question

Hi, I am trying to do a multi-objective optimization with AxClient. I am optimizing 2 objectives with 513 parameters. I basically adopted the default setting and firstly generated ~1000 samples with SOBOL, when it switch to BOTORCH, it gets extremely slow. I tried to specify ApproximateGPyTorchModel by GenerationStrategy(steps=[GenerationSteps(surrogate=Surrogate(ApproximateGPyTorchModel))]) when defining AxClient, it raises ```Original error: : RuntimeError: All MarginalLogLikelihood objects must be given a GP object as a model. If you are using a more complicated model involving a GP, pass the underlying GP object as the model, not a full PyTorch module.```

Is there any advice to accelerate this generation with BoTorch? Thank you very much.

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by Balandat** [comment]
It's not surprising that things are slow, we use hypervolume computations to perform multi-objective optimization which can get very expensive if the Pareto Frontier is very complex, which can well be the case if you already have 1000 initial data points. 

How expensive is it for you to generate a data point? If you can easily evaluate 1000 points then maybe multi-objective BO may not be the best approach for your problem.

**Comment by howardwang1997** [comment]
Thank you for the reply, that makes sense. It is very cheap to generate and evaluate data points, then maybe I should try single-objective BO for each objectives? Is this expected to be faster?

**Comment by Balandat** [comment]
Single-objective BO for different objectives will be faster, but if you do need to solve an actual multi-objective problem it may not be the right problem to solve. 

Bayesian Optimization has a lot of compute overhead relative to other methods, so if evaluating the function(s) you need to optimize is very cheap, then it may not be the best fit. Have you looked into other alternatives? Evolutionary algorithms such as NSGA-II are a common choice for multi-objective optimization if evaluations are cheap. There are a number of python packages out there that provide these algorithms, e.g. [pymoo](https://github.com/anyoptimization/pymoo).

**Comment by howardwang1997** [comment]
Thank you for the advice! I am also looking into evolutionary algorithms.
