### ISSUE TITLE
Random scalarization doesn't work with "lower_is_better" metrics

### ISSUE THREAD

**Issue by mrcslws** [facebook/Ax#289]
The Ax code tries to support this scenario, but it has a bad bug. When using "random scalarization" and metrics with "lower is better", Ax quietly optimizes in the wrong direction.

When using a metric with `lower_is_better=True`, the MultiObjective assigns a weight of -1 to that metric. https://github.com/facebook/Ax/blob/a3315150edd26fea26052d309665c6eab1f06adc/ax/core/objective.py#L89-L91

But when the function `_extract_random_scalarization_settings` is called with `random_scalarization=True`, it overwrites the `objective_weights`. https://github.com/facebook/Ax/blob/6189165f5ae97d5c6ba807507e48c41b0c69ac34/ax/models/torch/botorch_defaults.py#L506

It doesn't have any logic to preserve the sign of the weights.

**Comment by 2timesjay** [comment]
Thanks for the feedback. I'll get in a fix quickly. The only good workaround until then is to invert your metric.

**Comment by 2timesjay** [comment]
Fixed by release 0.1.11
