### ISSUE TITLE
`AxClient.get_best_trial(...)` does not account for `optimization_config` parameter

### ISSUE THREAD

**Issue by vassilyl** [facebook/Ax#2927]
Steps:

* Complete a multi-objective experiment with Service API. 
* To get best predicted value for a single objective, create a new `OptimizationConfig` with the objective and pass it to `AxClient.get_best_trial`. 

Expected:

The call returns best parameterization and predictions.

Observed:

An exception is raised from the implementation method '_get_best_trial`. 

https://github.com/facebook/Ax/blob/c5fa11a14acf6f91d29d11483c946488217c0ccc/ax/service/utils/best_point_mixin.py#L266

since `AxClient.get_best_trial(...)` doesn't pass `optimization_config` parameter value to implementation

https://github.com/facebook/Ax/blob/c5fa11a14acf6f91d29d11483c946488217c0ccc/ax/service/ax_client.py#L1540

I've noticed similar issue for 

https://github.com/facebook/Ax/blob/c5fa11a14acf6f91d29d11483c946488217c0ccc/ax/service/ax_client.py#L1554

**Comment by mgarrard** [comment]
Hi @vassilyl could you provide the full repro for where you create a new OptimizationConfig? I'm curious if maybe the optimization config isn't being saved to the experiment.

**Comment by mgarrard** [comment]
Closing as no further engagement - please feel free to re-open if needed @vassilyl :)
