### ISSUE TITLE
[Question] How to configure model with custom settings/kwargs in generation strategy

### ISSUE THREAD

**Issue by rinc5** [facebook/Ax#293]
Thank you for your continuous support.

I have two follow-up questions about #278.

1. What should I do to pass my factory functions to `get_botorch`?
I understood that I can use BoTorch with Ax by setting factory functions (e.g. [`_get_and_fit_simple_custom_gp`](https://botorch.org/tutorials/custom_botorch_model_in_ax#Define-a-factory-function-to-be-used-with-Ax's-BotorchModel) for custom GP model and [`get_scalarized_UCB`](https://botorch.org/tutorials/custom_acquisition#Ad-hoc-testing-Scalarized-UCB) for custom acquisition function) to `get_botorch`'s argument `model_constructor` and `acqf_constructor` respectively. @lena-kashtelyan told me I can use `GenerationStep(model=get_botorch, ...)`. It is very simple but I don't know how to pass my factory functions to BoTorch.

2. Is there any way to confirm what kernel and acquisition function are used?
I changed my `GenerationStrategy` to use `Models.SOBOL` and `get_botorch`. Then, the result of optimization was changed. But I didn't know whether the kernel function and the acquisition function were changed because I didn't pass my factory functions to `get_botorch`. So, can I confirm what kernel and acquisition function are used in optimization?

My current code is like below:
```python
class RBFGP(SingleTaskGP, GPyTorchModel):
    _num_outputs = 2
    # __init__ and forward function are defined.

# factory function for GP model
def get_RBFGP(Xs, Ys, **kwargs):
    model = RBFGP(Xs[0], Ys[0])
    mll = ExactMarginalLogLikelihood(...)
    fit_gpytorch_model(mll)
    return model

# factory function for acquisition function PI
def get_qPI(
    model: Model,
    best_f: Union[float, Tensor],
    **kwargs: Any,
) -> AcquisitionFunction:
    return qProbabilityOfImprovement(model=model, best_f=best_f)

gs = GenerationStrategy(
    steps=[
        GenerationStep(model=Models.SOBOL, num_arms=5),
        GenerationStep(model=get_botorch, num_arms=-1),
    ]
)

# initialize client, set up experiment, and optimize
```

Maybe I have misunderstood, so any advice would be greatly appreciated.
And, please ask me if you want to know the details of my code.

**Comment by lena-kashtelyan** [comment]
@rinc5, thank you for the questions! : )

1. My bad for not specifying how to pass the BoTorch constructors you wrote as kwargs to [`GenerationStep`](https://github.com/facebook/Ax/blob/master/ax/modelbridge/generation_strategy.py#L54)! You can do `GenerationStep(model=Models.BOTORCH, num_arms=-1, model_kwargs={"model_constructor": ..., "acqf_constructor": ...})` (you can use `Models.BOTORCH` and `get_botorch` pretty much interchangeably, but the former will allow you to save the optimization to JSON of SQL). 

Just in case this is useful: to check what model and model bridge a given `get_X` or `Model.X` points to, check in [the `Models` registry enum](https://github.com/facebook/Ax/blob/master/ax/modelbridge/registry.py#L206), which points to an [entry in this dictionary](https://github.com/facebook/Ax/blob/master/ax/modelbridge/registry.py#L131-L136). You can check that "model_constructor" and "acqf_constructor" are the `BotorchModel` kwargs and not the `TorchModelBridge` kwargs because they are [inputs to `BotorchModel`](https://github.com/facebook/Ax/blob/5a2ccb9c99139eaec0772c75e91f3bd7a0412a5b/ax/models/torch/botorch.py#L226).

2. Beyond silly methods like putting print statements inside of the factory functions for the GP and acquisition function, I'm not sure if there is an easy way to confirm –– maybe @Balandat is aware of one? Regardless, in your case they are not used because `get_botorch` you are using is still our `get_botorch` without the custom kwargs, so the functions you wrote are not getting passed through to the generation strategy. My answer to #1 should help with that!

Happy to elaborate on anything as needed, so please follow up if anything is unclear or not working.

**Comment by rinc5** [comment]
@lena-kashtelyan, thank you for your kind reply!

1. Resolved.
I changed to `GenerationStep(model=Models.BOTORCH,  num_arms=-1, model_kwargs={"model_constructor": get_RBFGP, "acqf_constructor": get_qPI})` and no error occurred. Thanks!

2. Unresolved.
Putting print statements is okay for me. So, I put print statements inside of my factory functions for the GP and acquisition function. However, nothing was printed.

My code is changed like below:
```python
# not changed
class RBFGP(SingleTaskGP, GPyTorchModel):
    ...

# factory function for GP model
def get_RBFGP(Xs, Ys, **kwargs):
    print('inside of get_RBFGP')
    model = RBFGP(Xs[0], Ys[0])
    mll = ExactMarginalLogLikelihood(...)
    fit_gpytorch_model(mll)
    return model

# factory function for acquisition function PI
def get_qPI(
    model: Model,
    best_f: Union[float, Tensor],
    **kwargs: Any,
) -> AcquisitionFunction:
    print('inside of get_qPI')
    return qProbabilityOfImprovement(model=model, best_f=best_f)

gs = GenerationStrategy(
    steps=[
        GenerationStep(model=Models.SOBOL, num_arms=5),
        GenerationStep(model=Models.BOTORCH, num_arms=-1, model_kwargs={"model_constructor": get_RBFGP, "acqf_constructor": get_qPI}),
    ]
)

# initialize client, set up experiment, and optimize
# not changed
```

**Comment by lena-kashtelyan** [comment]
Looking into what happened in #2!

**Comment by lena-kashtelyan** [comment]
@rinc5, I tried a custom BoTorch model with an Ax generation strategy in a notebook: https://gist.github.com/lena-kashtelyan/18fb370a232e9e64fd3ecd26bc7b0657, and I believe things worked –– you can see the printout. I'm not certain what is different in your case (since some of your code I can't see), but I would suggest re-running your notebook, since things did work for me.

You'll notice that I'm using `num_trials` instead of `num_arms` as a kwarg to generation step –– if you update your Ax package to a newer version, you will need to change the name of that kwarg as well. You can keep the values the same, as one trial corresponds to one arm : )

**Comment by rinc5** [comment]
@lena-kashtelyan, thank you for your taking time to make the notebook. The reason why the print statements weren't worked in my code is that I called `get_next_trial` only one time. My code is like below:
```python
# attach my experimental data
for _, row in df.iterrows():
    _, trial_index = ax_client.attach_trial(row[['X1', 'X2', 'X3', 'X4', 'X5']])
    ax_client.complete_trial(trial_index, {Y1: (row['Y1'], None), 'Y2': (row['Y2'], None)})

# get next candidate
next_candidates, _ = ax_client.get_next_trial()
```
In fact, I added `for` loop to getting next candidate part, then the print statement is displayed.

Are the Sobol trials needed in my case? I think that the Sobol trials create some initial points for making GP model but there are some points in my case. (Maybe I have misunderstood, so I'd be grateful if you would tell me about that.)

**Comment by lena-kashtelyan** [comment]
@rinc5, ah of course, that makes sense. In case it helps, you can always quickly check what generation strategy you are using like so: `print(ax_client.generation_strategy)`, which will tell you some brief information on its steps, or examine its steps (`generation_strategy._steps`) for in-depth information about the steps.

Regarding whether you need the Sobol step: we use Sobol for the initial few trials for BayesOpt to have some decently sampled initial points to start with. If you already have points that you know will serve well as initialization points, then you can omit the Sobol step in your custom generation strategy (just remove it from the `steps` list you instantiate the GS with). Let me know if you run into any issues with that approach!

Note that the `attach_trial` and `complete_trial` loop you have before generating new points is always necessary for those points to be attached to the experiment and known to the generation strategy, so it uses that data to instantiate your custom BoTorch model. I'm sure you already knew that, just giving a reminder : ) You can also always check what trials your generation strategy is aware of by doing `ax_client.generation_strategy.trials_as_df`, so if you see unexpected generation strategy behaviors, that call is often the first to make and ensure that all the trials you expect are there.

**Comment by rinc5** [comment]
@lena-kashtelyan, `ax_client.generation_strategy` is useful! I could confirm the information very easy.

Thank you for teaching me the details of Sobol and `attach_trial` and `complete_trial` loop. I could understand more deeply. I omitted the Sobol step and no issue was occurred.

I could pass my factory function to generation strategy, but I got another error. I think that my custom kernel class or kernel's factory function is wrong because the size of metric data is incorrect. My metric data is Y1(maximize) and Y2(outcome constraint) and I have 100 records, so I think that `torch.Size([2, 100])` is correct size of metric. In fact, when I used `GenerationStrategy(steps=[GenerationStep(model=Models.GPEI, num_trials=-1)])`, `train_targets.shape` is `torch.Size([2, 100])` in `ExactGP`. But I got `torch.Size([100, 1])` in my current generation strategy(RBF kernel and default acquisition function).

Is there any code for multi-outcome custom model as a reference? I referred [this page](https://botorch.org/tutorials/custom_botorch_model_in_ax) and I only changed `_num_outputs`.

My code is below:
```python
class RBFGP(ExactGP, GPyTorchModel):

    _num_outputs = 2  # to inform GPyTorchModel API
    
    def __init__(self, train_X, train_Y):
        super().__init__(train_X, train_Y.squeeze(-1), GaussianLikelihood())
        self.mean_module = ConstantMean()
        self.covar_module = ScaleKernel(
            base_kernel=RBFKernel(ard_num_dims=train_X.shape[-1]),
        )
        self.to(train_X)
        
    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return MultivariateNormal(mean_x, covar_x)

def get_RBFGP(Xs, Ys, **kwargs):
    model = RBFGP(Xs[0], Ys[0])
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model
```

I'm sorry for taking a long time.
If you need more information or the details of my code, please ask me.
Thank you in advance.

**Comment by lena-kashtelyan** [comment]
Please don't apologize, we are happy to help and this feedback is very useful! I'm happy the generation strategy is working for you! I'll defer to @Balandat to help out with the custom kernel setup, since we is more knowledgeable in that domain.

**Comment by Balandat** [comment]
Hi @rinc5, this is a little down in the weeds, but for a multi-output model you'll have to make sure that the model returns a `MultiTaskMultivariateNormal` instead of a `MultivariateNormal` . 

You may also want to use [`BatchedMultiOutputGPyTorchModel`](https://github.com/pytorch/botorch/blob/master/botorch/models/gpytorch.py#L188) if you are OK modeling your outputs independently (i.e. not accounting for cross-terms in the covariances across outputs). 

To get what you want with with an RBF Kernel, the easiest thing would be to pass that kernel as a the `covar_module` to [`SingleTaskGP`](https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L45) .

**Comment by rinc5** [comment]
@lena-kashtelyan , @Balandat , I appreciate your kindness.

Can I use `BatchedMultiOutputGPyTorchModel` or `SingleTaskGP` when the correlation is existing? There is a positive correlation between two metrics.

Passing RBF kernel as the `covar_module` to `SingleTaskGP` is easy and readable, so I changed my factory function like this:
```python
def get_RBFGP(Xs, Ys, **kwargs):
    model = SingleTaskGP(Xs[0], Ys[0], covar_module=ScaleKernel(RBFKernel()))
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model
```

But `RuntimeError` was occurred. What should I do to solve this?
```
Traceback (most recent call last):
  File ".\custom_botorch_model.py", line 170, in <module>
    next_candidates, _ = ax_client.get_next_trial()
  File "~\Python38\lib\site-packages\ax\service\ax_client.py", line 281, in get_next_trial
    trial = self.experiment.new_trial(generator_run=self._gen_new_generator_run())
  File "~\Python38\lib\site-packages\ax\service\ax_client.py", line 866, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\generation_strategy.py", line 296, in gen
    generator_run = model.gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\base.py", line 610, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\array.py", line 202, in _gen
    X, w, gen_metadata = self._model_gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\torch.py", line 204, in _model_gen
    X, w, gen_metadata = self.model.gen(
  File "~\Python38\lib\site-packages\ax\models\torch\botorch.py", line 337, in gen
    model, objective_weights, outcome_constraints = subset_model(
  File "~\Python38\lib\site-packages\ax\models\torch\utils.py", line 188, in subset_model
    raise RuntimeError(
RuntimeError: Model size inconsistency. Tryting to subset a model with 1 outputs to 2 outputs
```

**Comment by Balandat** [comment]
> Can I use BatchedMultiOutputGPyTorchModel or SingleTaskGP when the correlation is existing? There is a positive correlation between two metrics.

This is about correlation in the observation noise, not about correlation of the metrics themselves. Even models that model the outputs independently will be able to model correlation between the metrics. More specifically, the assumption those will make that the observed function values (`f_1(x)`, `f_2(x)`) are *conditionally independent given `x`*.

Regarding the error: 
This is b/c the model is not properly instantiated in `get_RBFGP`. `SingleTaskGP` assumes you have a `batch_shape x n x d`-dim `X` and a `batch_shape x n x m`-dim `Y` as inputs, where `d` is the dimension of your feature space (i.e. the # of params in your Ax `SearchSpace`), and `m` is the number of outputs to model. The logic in Ax that constructs these from the modelbridge inputs lives [here](https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py#L100-L111).

There is actually another subtlety in this case when using a `BatchedMultiOutputGPyTorchModel`: In order to make sure that the model uses different lengthscales for each of the outputs, you need specify a `batch_shape` for both `ScaleKernel` and `RBFKernel`, similar as done in the constructor of `SingleTaskGP` [here](https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L112-L121). The correct way to do this is the following: 

```
from botorch.models import SingleTaskGP
from botorch.models.gpytorch import BatchedMultiOutputGPyTorchModel
from gpytorch.kernels import ScaleKernel, RBFKernel
from gpytorch.mlls import ExactMarginalLogLikelihood
from botorch.fit import fit_gpytorch_model
import torch

def get_RBFGP(Xs, Ys, **kwargs):
    X = Xs[0]
    Y = torch.cat(Ys, dim=-1)
    _, aug_batch_shape = BatchedMultiOutputGPyTorchModel.get_batch_dimensions(X, Y)
    covar_module = ScaleKernel(
        RBFKernel(batch_shape=aug_batch_shape),
        batch_shape=aug_batch_shape,
    )
    model = SingleTaskGP(X, Y, covar_module=covar_module)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model
```

We realize this is not very user-friendly, and we do have on our roadmap to simplify using custom models (in both botorch and Ax), but it will take a bit to fully iron out all the kinks (lots of stuff going on under the hood...).

**Comment by rinc5** [comment]
Thank you for your explanation.
I could understand about the correlation. Assuming no correlation in the observation noise is OK in my case.

I also could understand the flow and inputs of `SingleTaskGP`. This is very helpful when understanding Ax and debugging.
And finally, the factory function for kernel has worked well!

But, `RuntimeError` was occurred in the factory function for acquisition function.
```
Traceback (most recent call last):
  File ".\custom_botorch_model.py", line 156, in <module>
    next_candidates, _ = ax_client.get_next_trial()
  File "~\Python38\lib\site-packages\ax\service\ax_client.py", line 281, in get_next_trial
    trial = self.experiment.new_trial(generator_run=self._gen_new_generator_run())
  File "~\Python38\lib\site-packages\ax\service\ax_client.py", line 866, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\generation_strategy.py", line 296, in gen
    generator_run = model.gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\base.py", line 610, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\array.py", line 202, in _gen
    X, w, gen_metadata = self._model_gen(
  File "~\Python38\lib\site-packages\ax\modelbridge\torch.py", line 204, in _model_gen
    X, w, gen_metadata = self.model.gen(
  File "~\Python38\lib\site-packages\ax\models\torch\botorch.py", line 368, in gen
    candidates, expected_acquisition_value = self.acqf_optimizer(
  File "~\Python38\lib\site-packages\ax\models\torch\botorch_defaults.py", line 260, in scipy_optimizer
    X, expected_acquisition_value = optimize_acqf(
  File "~\Python38\lib\site-packages\botorch\optim\optimize.py", line 109, in optimize_acqf
    candidate, acq_value = optimize_acqf(
  File "~\Python38\lib\site-packages\botorch\optim\optimize.py", line 145, in optimize_acqf
    batch_initial_conditions = ic_gen(
  File "~\Python38\lib\site-packages\botorch\optim\initializers.py", line 105, in gen_batch_initial_conditions
    Y_rnd_curr = acq_function(
  File "~\Python38\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "~\Python38\lib\site-packages\botorch\utils\transforms.py", line 202, in decorated
    return method(cls, X)
  File "~\Python38\lib\site-packages\botorch\utils\transforms.py", line 173, in decorated
    return method(cls, X)
  File "~\Python38\lib\site-packages\botorch\acquisition\monte_carlo.py", line 322, in forward
    val = torch.sigmoid((max_obj - self.best_f) / self.tau).mean(dim=0)
RuntimeError: The size of tensor a (1000) must match the size of tensor b (2) at non-singleton dimension 1
```

I used [this page](https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py#L195-L201) as a reference that you told me before. In [`qProbabilityOfImprovement`](https://botorch.org/api/acquisition.html#botorch.acquisition.monte_carlo.qProbabilityOfImprovement), we need to pass `best_f`. Is it correct way to calculate `best_f`?
```python
# factory function for acquisition function (PI)
def get_qPI(
    model: Model,
    **kwargs: Any,
) -> AcquisitionFunction:
    obj_tf = get_objective_weights_transform(kwargs.get('objective_weights'))
    con_tfs = get_outcome_constraint_transforms(kwargs.get('outcome_constraints'))
    X_observed = kwargs.get('X_observed')
    inf_cost = get_infeasible_cost(X=X_observed, model=model, objective=obj_tf)
    objective = ConstrainedMCObjective(
        objective=obj_tf, constraints=con_tfs or [], infeasible_cost=inf_cost
    )
    return qProbabilityOfImprovement(model=model, best_f=best_f, objective=objective)

# best_f
best_f = torch.tensor(df[['Z2', 'Z1']].max().values)

# create generation strategy for using existing data
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.BOTORCH,
            num_trials=-1,
            model_kwargs={'model_constructor': get_RBFGP, 'acqf_constructor': get_qPI}
        ),
    ]
)
```

Of course, I'm glad to be more user friendly, but issues and your answers help me. In fact, I could make my experimental data optimization program by referring issues about black box optimization. Thank you for your all supports!

**Comment by rinc5** [comment]
Above `RuntimeError` was not occurred when I used a scalar value for `best_f`. Is this correct way? Should I pass only the max value of metric which I want to maximize to `best_f`?

I have another concern.
Ax's default kernel is Matern 5/2 and `Models.GPEI`'s acquisition function is Expected Improvement. So, I tried to optimize by using `MaternKernel` as kernel (`covar_module`) and `qExpectedImprovement` as acquisition function. But its result is different from using `Models.GPEI`. It's not a big difference but also not similar.
I changed `qNoisyExpectedImprovement`, then the different was less than `qExpectedImprovement`. But it took more than double the time.
What are these differences? Which does `qExpectedImprovement` use EI or NEI?

I confirmed it by using below code:
```python
# factory function for Matern
def get_MaternGP(Xs, Ys, **kwargs):
    X = Xs[0]
    Y = torch.cat(Ys, dim=-1)
    _, aug_batch_shape = BatchedMultiOutputGPyTorchModel.get_batch_dimensions(X, Y)
    covar_module = ScaleKernel(
        MaternKernel(aug_batch_shape=aug_batch_shape),
        aug_batch_shape=aug_batch_shape,
    )
    model = SingleTaskGP(X, Y, covar_module=covar_module)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)
    return model

# factory function for acquisition function (EI)
def get_qEI(
    model: Model,
    **kwargs: Any,
) -> AcquisitionFunction:
    obj_tf = get_objective_weights_transform(kwargs.get('objective_weights'))
    con_tfs = get_outcome_constraint_transforms(kwargs.get('outcome_constraints'))
    X_observed = kwargs.get('X_observed')
    inf_cost = get_infeasible_cost(X=X_observed, model=model, objective=obj_tf)
    objective = ConstrainedMCObjective(
        objective=obj_tf, constraints=con_tfs or [], infeasible_cost=inf_cost
    )
    return qExpectedImprovement(model=model, best_f=best_f, objective=objective)

# factory function for acquisition function (NEI)
def get_qNEI(
    model: Model,
    **kwargs: Any,
) -> AcquisitionFunction:
    obj_tf = get_objective_weights_transform(kwargs.get('objective_weights'))
    con_tfs = get_outcome_constraint_transforms(kwargs.get('outcome_constraints'))
    X_observed = kwargs.get('X_observed')
    inf_cost = get_infeasible_cost(X=X_observed, model=model, objective=obj_tf)
    objective = ConstrainedMCObjective(
        objective=obj_tf, constraints=con_tfs or [], infeasible_cost=inf_cost
    )
    return qNoisyExpectedImprovement(model=model, X_baseline=X_observed, objective=objective)

# used this to confirm GPEI
gs = GenerationStrategy(
    steps=[
        GenerationStep(model=Models.GPEI, num_trials=-1)
    ]
)

# used this to confirm EI
best_f = df[args.opt_item].max()
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.BOTORCH,
            num_trials=-1,
            model_kwargs={'model_constructor': get_MaternGP, 'acqf_constructor': get_qEI}
        ),
    ]
)

# used this to confirm NEI
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.BOTORCH,
            num_trials=-1,
            model_kwargs={'model_constructor': get_MaternGP, 'acqf_constructor': get_qNEI}
        ),
    ]
)

# initialize client
ax_client = AxClient(...)
```

**Comment by Balandat** [comment]
> Above RuntimeError was not occurred when I used a scalar value for best_f. Is this correct way? Should I pass only the max value of metric which I want to maximize to best_f?

So the `best_f` is always w.r.t. the objective you're considering (which is a scalar); in this case it would be the max across your `objective` evaluated on all previous observations.

> Ax's default kernel is Matern 5/2 and Models.GPEI's acquisition function is Expected Improvement. So, I tried to optimize by using MaternKernel as kernel (covar_module) and qExpectedImprovement as acquisition function. But its result is different from using Models.GPEI. It's not a big difference but also not similar.

You'd expect a some difference b/c the model is different. Note also that there is stochasticity in the optimization (from the model fitting, as well as from the acquisition function optimization). So to compare performance you'd have to re-run the optimization loop a bunch of times and compare averages.

> I changed qNoisyExpectedImprovement, then the different was less than qExpectedImprovement. But it took more than double the time. What are these differences? Which does qExpectedImprovement use EI or NEI?

`Models.GPEI` is using `qNoisyExpectedImprovement` (qNEI). I guess that's not 100% consistent in terminology, but we've found that in our applications where there is noise involved, qNEI often does a lot better than qEI. You can read up on the basics of NEI in [this paper](https://projecteuclid.org/euclid.ba/1533866666). The implementation in BoTorch is slightly different than reported there, you can find some basic info about this in sec 6.2 of [this paper](https://arxiv.org/abs/1910.06403v1).

**Comment by rinc5** [comment]
Thank you for your quick response.

> So the best_f is always w.r.t. the objective you're considering (which is a scalar); in this case it would be the max across your objective evaluated on all previous observations.

I understand that `best_f` depends on `objective`. 

> You'd expect a some difference b/c the model is different. Note also that there is stochasticity in the optimization (from the model fitting, as well as from the acquisition function optimization). So to compare performance you'd have to re-run the optimization loop a bunch of times and compare averages.

Of course, I must run the optimization loop many times when I compare these performances. I ran only 5 times. On the other hand almost result of `Models.GPEI` were within outcome constraint, the results of Matern + qNEI had never been within outcome constraint. I will run the optimization loop more time, but it takes a little long time (about 10 min a trial). So, I'll report its results as another issue if there is a gap between the results of `Models.GPEI` and Matern + qNEI.

> Models.GPEI is using qNoisyExpectedImprovement (qNEI). I guess that's not 100% consistent in terminology, but we've found that in our applications where there is noise involved, qNEI often does a lot better than qEI. You can read up on the basics of NEI in this paper. The implementation in BoTorch is slightly different than reported there, you can find some basic info about this in sec 6.2 of this paper.

Thank you for teaching me the details of qNEI. A noise is involved in my case too. So, I'll use qNEI.

I really appreciate your supports. With all your help, I finally changed kernel and acquisition function.
