### ISSUE TITLE
[GENERAL SUPPORT]: Is it possible to abandon a trial in a terminal state?

### ISSUE THREAD

**Issue by rezaybsh** [facebook/Ax#2931]
### Question

Hi everyone,

First of all, I’d like to express my appreciation for the fantastic work on this library!

I’ve encountered an issue where I’m unable to abandon a trial that is already in a terminal state. I’ve tried both of the following approaches:

```
ax_client.experiment.trials[0].mark_abandoned()
ax_client.abandon_trial(trial_index=0, reason=None)
```

However, I receive the same error in both cases:

`_ValueError: Cannot abandon a trial in a terminal state._`

I understand that abandoning a trial in a terminal state might not be allowed, but I’m curious if this was possible in earlier versions based on the discussion in issue #506. Could someone clarify whether this behavior has changed, and if so, what the reasoning behind it is?

Thanks in advance for your help!

Best regards,
Mo

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by mgarrard** [comment]
Hi @rezaybsh, I'd be curious to learn a bit more about what you are hoping to accomplish by marking this trial as abandoned since it has already entered a terminal to state to help understand if this is in fact the best way to reach your end goal - could you provide that context :) 

Fwiw, you can override this by doing ```ax_client.experiment.trials[0].mark_abandoned(unsafe=True)``` but as the code implies, this is divergent from the intended usage pattern.

**Comment by rezaybsh** [comment]
Hi @mgarrard,

Thank you for your prompt response—it has been very helpful in resolving our issue so far.

To provide some additional context, we use Ax in a human-in-the-loop setup for multi-objective optimization (MOO). Recently, we discovered errors in some of our past experiments, which is why we are looking for a method to mark those experiments as failed or abandoned.

Given this scenario, do you think it would be appropriate to use the `unsafe=True` option in our case?

Thanks again for your guidance.

**Comment by rezaybsh** [comment]
After running the experiments, we found that errors occurred in some trails due to one specific parameter. To answer your question, it is indeed the parameterization that causes the experiment to fail. As a result, we mark those experiments as failed using the `marked_failed `method and adjust the parameter range to prevent this problematic parameterization in the future. Would you agree that this is the right approach?

**Comment by rezaybsh** [comment]
> That's the right approach, yes. In the future we hope to also add functionality that allows you to mark a trial failed due to the parameterization, and then internally fit a probabilistic classification model that allows us to learn what the problematic configurations are and avoid them in future exploration so that you wouldn't have to do that manual adjustment.

That sounds great :)

Is it recommended to use `mark_failed` instead of `mark_abandoned`, given that we do not intend to modify the model for parameter generation but want to ensure that the problematic parameterization is not suggested by adjusting the parameter range?

**Comment by Balandat** [comment]
In that case you should use `mark_abandoned`, which will help avoid re-suggesting similar points. I think the term "abandoned" is sort of a misnomer here and we'd like to improve this and make things more clear in the future.

**Comment by sgbaird** [comment]
> In that case you should use `mark_abandoned`, which will help avoid re-suggesting similar points. I think the term "abandoned" is sort of a misnomer here and we'd like to improve this and make things more clear in the future.

If someone happens to see, at some point it would be nice to understand the implementation here of how it "helps avoid re-suggesting similar points". If this becomes a higher priority I may open up a separate issue at some point

**Comment by sgbaird** [comment]
Within `mark_abandoned`, I found the following:
```
        NOTE: Arms in abandoned trials are considered to be 'pending points'
        in experiment after their abandonment to avoid Ax models suggesting
        the same arm again as a new candidate. Arms in abandoned trials are
        also excluded from model training data unless ``fit_abandoned`` option
        is specified to model bridge.
```
