### ISSUE TITLE
Predict and select best point according to acquisition function [Question]

### ISSUE THREAD

**Issue by BCJuan** [facebook/Ax#295]
Hello,

I predict mean and covariance for a group of new points as described in https://ax.dev/docs/models.html, that is:
```
obs_feats = [
    ObservationFeatures(parameters={'x1': 3.14, 'x2': 2.72}),
    ObservationFeatures(parameters={'x1': 1.41, 'x2': 1.62}),
]
f, cov = m.predict(obs_feats)
```
Now, I want to select one of them according to an acquisition function, but I have not found them in Ax. I suppose I have to relay on Botorch. In the example given in Botorch for UCB: 

```
>>> model = SingleTaskGP(train_X, train_Y)
>>> UCB = UpperConfidenceBound(model, beta=0.2)
>>> ucb = UCB(test_X)
```
they work directly with X instead of mean and covariance matrix. Also, I suppose that in Botorch the X matrix has already been through transformations, contrary to the `obs_feats` previously described. How could I adapt the the `obs_feats` for the Botorch interface?

Hence, the question is, how can I select the best point, according to an acquisition function, from a group of points in ax? Fro example, generated and predicted by a model.

Thanks in advance

**Comment by 2timesjay** [comment]
@BCJuan

Right now your best option is to predict the mean and variance and use these to manually compute the acquisition function (UCB in your example. 

We are discussing how to extend our API to make this more convenient.

**Comment by BCJuan** [comment]
Ok. Will do. Thanks!
