### ISSUE TITLE
Ax does not enforce parameter_type

### ISSUE THREAD

**Issue by andyznew** [facebook/Ax#296]
When I run:
```
from ax.service.ax_client import AxClient
from ax.core.parameter import (
    ParameterType,
)
ax_client = AxClient()
ax_client.create_experiment(
    name="hartmann_test_experiment",
    parameters=[
        {'name': 'param_test3', 'type': 'choice', 'parameter_type': ParameterType.BOOL, 'values': [1, 2]}, 
        {'name': 'param_test4', 'type': 'fixed', 'value': True}
    ],
    objective_name="hartmann6",
    minimize=True,  # Optional, defaults to False.
)
```
This succeeds. `ax_client.experiment.parameters['param_test3'].parameter_type` outputs `<ParameterType.INT: 1>`. I would expect for it to raise a `ValueError`, as happens when I directly create a `ChoiceParameter`.

**Comment by 2timesjay** [comment]
Hi @andyznew,

Thanks for bringing this up.

This is working as designed. At https://github.com/facebook/Ax/blob/master/ax/core/parameter.py#L360 we attempt to cast the argument. If this fails it will emit a ValueError. However, in your case both 1 and 2 will be cast as True which could be a difficult bug to track down.

We added this to avoid problems around int vs floats, and to enjoy the convenience of casting to strings. 

We'll re-evaluate, including whether we want to emit a warning.

**Comment by lena-kashtelyan** [comment]
@andyznew, to build upon @2timesjay's response above, I'd like to also note that the key "parameter_type" is not used by the Ax Service API (`AxClient`). If you want to specify a parameter type in the Service API, as exemplified in our tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html, you need to specify "value_type" as a string (you'll get an error message specifying all available options if you pass an incorrect one, too). In case that helps, this is the utility that parses parameters in the Service API: https://github.com/facebook/Ax/blob/master/ax/service/utils/instantiation.py#L135.

**Comment by andyznew** [comment]
Gotcha, thanks for the help. Did not realize that the correct key was `value_type` rather than `parameter_type`. Yeah the `ChoiceParameter` does not error out with BOOL and int; I was playing around with Int and String instead when directly setting, which makes sense with casting.
