### ISSUE TITLE
Question about Supported Databases for Ax

### ISSUE THREAD

**Issue by andyznew** [facebook/Ax#297]
The homepage of Ax quotes "Support for industry-grade experimentation and optimization management, including MySQL storage." though I noticed that the tutorial https://ax.dev/tutorials/gpei_hartmann_service.html uses `db_settings = DBSettings(url="postgresql+psycopg2://sarah:c82i94d@ocalhost:5432/foobar")`. Does Ax support both MySQL and Postgres? Or is there a recommended DB.

**Comment by ldworkin** [comment]
Hi @andyznew ! We support both postgres and mysql. 

Note that if you use postgres, you'll have to implement the workaround discussed here: https://github.com/facebook/Ax/issues/283#issuecomment-614031051

To use mysql, you can use a url like this: https://docs.sqlalchemy.org/en/13/core/engines.html#mysql

Let me know if you need further help!
