### ISSUE TITLE
Issue running create_all_tables on the pymysql dialect

### ISSUE THREAD

**Issue by andyznew** [facebook/Ax#298]
Running
```
        DB_URL="mysql+pymysql://user:password@localhost/ax_db"
        init_engine_and_session_factory(url=DB_URL)
        engine = get_engine()
        create_all_tables(engine)
```

Getting the following error 

``` line 405, in create_all_tables
    and engine.dialect.default_schema_name == "adaptive_experiment"
AttributeError: 'MySQLDialect_pymysql' object has no attribute 'default_schema_name'
```

**Comment by 2timesjay** [comment]
All that create_all_tables does it test whether to throw an exception that's relevant to internal use cases. So directly call

`
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base(cls=SQABase)
Base.metadata.create_all(engine)
`

Let us know how this workaround goes.

**Comment by andyznew** [comment]
Yeah that's basically the workaround I use; only thing is that you want to import Base from ax.storage.sqa_store.db rather than create a new declarative_base.
