### ISSUE TITLE
[Question] How to get best paramter if I use MultiObjective or ScalarizedObjective

### ISSUE THREAD

**Issue by bitosky** [facebook/Ax#299]
`get_best_parameters` is convenient to get the best paramters when tackling single-objective problem. But it can't get the best parameters from a multi-objective experiment.
```
...
NotImplementedError: ScalarizedObjective is composed of multiple metrics
```
It's there an API for geting the best parameters or Pareto front when using  MultiObjective or ScalarizedObjective?

**Comment by stevemandala** [comment]
Hey @bitosky, thanks for reaching out. In the case of scalarized objectives, we should be able to report the trial with the best scalarized performance via `get_best_parameters()`, I'll dig into the issue a bit more to see how much work this would take.

**Comment by Balandat** [comment]
We currently don't have functionality in place for getting Pareto frontiers, but we are working on that.

**Comment by stevemandala** [comment]
Support for best raw point selection was added in the aforementioned commit, should provide some basic support for this. Closing, but feel free to reopen if there are still issues.

**Comment by yifeng-li** [comment]
> We currently don't have functionality in place for getting Pareto frontiers, but we are working on that.

Do you have this functionality now?

**Comment by ldworkin** [comment]
cc @2timesjay

**Comment by yifeng-li** [comment]
> > We currently don't have functionality in place for getting Pareto frontiers, but we are working on that.
> 
> Do you have this functionality now?

Currently, we need an Ax example just as simple as this: https://github.com/ppgaluzio/MOBOpt

**Comment by 2timesjay** [comment]
@yifeng-li It's on the near-term roadmap. ETA late July/early August.

**Comment by yifeng-li** [comment]
> @yifeng-li It's on the near-term roadmap. ETA late July/early August. Thanks for the pointer to https://github.com/ppgaluzio/MOBOpt too.

Great! I am eagerly looking forward to this component. If would be nice if your future function can allow initialization of a user-specified set of data points {x_n,y_n}_n^N where x_n is a vector and y_n is also a vector for the corresponding to the objective values. MOBOpt has a nice interface but it does not allow such data initialization. I believe your implementation will be very useful in many applications. Thanks!
