### ISSUE TITLE
faster CI builds through optional dependencies

### ISSUE THREAD

**Issue by ibayer** [facebook/Ax#305]
Thanks for this great project!

After running some initial experiments we notices that some of our ci builds (docker) increased dramatically in size and also took much longer to run after adding ax as dependency.

The reason for this is somewhat obvious when considering the dependencies of ax.
The regular pytorch wheel is quite big (~500 mb) and even the cpu only version requires ~ 100 mb.

Only some of our projects and none of our ci tests require a gpu to run. We also have experiments/projects that can be run without using any model depending on BoTorch.

This motivates me to ask if you see any chance to install ax

- without gpu support?
- without BoTorch support?

We took a look at ax's source code but couldn't see an obvious way to make BoToch/gpu optional.
What's your take on this?

**Comment by Balandat** [comment]
Yeah, unfortunately the pytorch binaries are massive, especially w/ GPU support.

Re GPU support: If you install torch prior to installing ax without GPU support, then ax should not install the pytorch GPU version. When installing with pip, you can use 
```
pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
That should cut things down pretty significantly.

Regarding installing without BoTorch support: At the current time, BoTorch is a hard dependency and pretty tightly integrated in the code. There is no reason we couldn't make that an optional dependency, but it would require a good amount of engineering work. Basically we'd have to make sure that we track down every single botorch import and raise an appropriate and informative error. That's something we could think about, but it would take some time to get this done.

**Comment by ibayer** [comment]
Thanks for your feedback.

> Re GPU support: If you install torch prior to installing ax without GPU support, then ax should not install the pytorch GPU version

Yes, I tried this already. It works for the pytorch dependency part. However since BoTorch doesn't have a cpu version (at least last time I checked) the torch gpu version is added anyway and nothing is gained. :-(

> Basically we'd have to make sure that we track down every single botorch import and raise an appropriate and informative error.

Understood, that's also the impression we got. 

Could it be possible to replace BoTorch with something like a mock of the whole BoTorch library?

This could work if BoTorch doesn't provide any functionally strictly necessary for the simple models like factoral_design. I guess the question is if this feasible without changing ax a lot.

The install size change could be big, like going from 500mb to 5mb or something but compute resources are easier to get then dev time, at least till a certain deployment scale. :)

Looks like there are only two possible ways forward.

1. `good amount of engineering work` to make BoTorch optional
2. try to get/build a cpu only BoTorch version.

**Comment by Balandat** [comment]
> However since BoTorch doesn't have a cpu version (at least last time I checked) the torch gpu version is added anyway and nothing is gained. :-(

So botorch is platform / device agnostic, it is basically pure python (on top of pytorch). So whatever pytorch version you have will dictate whether BoTorch is GPU enabled or not. I particular, installing BoTorch should not re-install pytorch if already installed (GPU enabled or not). 

I just checked (clean anaconda env on CentOS 7) that
```
pip install torch==1.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
pip install ax-platform
```
indeed results in an install with the CPU-only variant of pytorch.

This should address 2.

**Comment by ibayer** [comment]
> indeed results in an install with the CPU-only variant of pytorch.

Maybe my package manager (poetry) tricked me if the install order of pytorch and BoTorch makes a difference. Getting 2 to work is already a huge step forward.  I'll try this again. Thanks for looking into it.

**Comment by Balandat** [comment]
Hmm thinking about it, we actually use pytorch directly for the Sobol quasi-RNG: https://github.com/facebook/Ax/blob/master/ax/models/random/sobol.py#L17 

So unfortunately it's not as straightforward as pulling out botorch.

**Comment by lena-kashtelyan** [comment]
This is not on our roadmap for now, so closing this for now but may reopen if we bump it in priority.
