### ISSUE TITLE
Added jitter of 1e-08 to the diagonal

### ISSUE THREAD

**Issue by Pzmijewski** [facebook/Ax#311]
Hey,
i´m working on a simulation optimization with range and choice parameters using Ax. I´m getting the following warning, but the optimization is still running. The warning appears after 50 Sobol trials and  around 20 GPEI trials. 
What does it mean?

Thank you!

> C:\code\env\lib\site-packages\gpytorch\utils\cholesky.py:43: RuntimeWarning:
> A not p.d., added jitter of 1e-08 to the diagonal

**Comment by ldworkin** [comment]
Hi @Pzmijewski ! Good question.

As part of the optimization, there's a step during model fitting / prediction where we attempt to perform a Cholesky decomposition of a matrix. This requires the matrix to be positive definite. If the matrix is not positive definite (as in your case), we add jitter to the covariance to make it more numerically stable.

If all goes well, this should allow us to proceed with the optimization. So if you don't see any further errors, you can assume that we "fixed" the matrix and the situation was resolved.

Let me know if you have any further questions!
