### ISSUE TITLE
[GENERAL SUPPORT]: Warm start re-fitting in BoTorchModel 

### ISSUE THREAD

**Issue by RoeyYadgar** [facebook/Ax#3208]
### Question

Hi,

I'm a bit confused about how the warm start refit happens in `BoTorchModel`. (I might have confused the terminology, but what I mean by warm start is to re-fit the model in the current iteration using the model's parameters values from the previous iteration as an initial guess).
This model has `warm_start_refit` attribute given at its constructor (which is True on default), but I don't understand where this attribute is actually used (except for the `cross_validate` method), I guess it used outside of `ax.models.torch.botorch_modular.model` but I can't seem to find where.
Additionally, the `fit` method has a `state_dicts` argument which is used for warm start of the surrogate model (If I understand correctly) but `TorchModelBridge` doesn't seem to pass this argument in its `_fit` method. 
Attaching below a code snippet I used to test if `state_dicts` is passed into 'BoTorchModel.fit` method.

Am I missing something that enables me to use warm start fitting?

Also, I guess this is more of an instance dependent question, but should I be expecting a substantial improvement in the fitting run time when warm start is used?

Thanks a lot!

### Please provide any relevant code snippet if applicable.

```python

from ax import (
    Experiment,
    Objective,
    OptimizationConfig,
    Models
)
from ax import (
    Experiment,
    Objective,
    OptimizationConfig,
    ParameterType,
    RangeParameter,
    SearchSpace,
)
from ax.metrics.l2norm import L2NormMetric
from ax import Runner
from ax.modelbridge.generation_node import GenerationStep
from ax.modelbridge.generation_strategy import GenerationStrategy
from botorch.acquisition import LogExpectedImprovement


#Initalize an experiment with the example from https://ax.dev/tutorials/gpei_hartmann_developer.html
class MyRunner(Runner):
    def run(self, trial):
        trial_metadata = {"name": str(trial.index)}
        return trial_metadata
    
search_space = SearchSpace(
    parameters=[
        RangeParameter(
            name=f"x{i}", parameter_type=ParameterType.FLOAT, lower=0.0, upper=1.0
        )
        for i in range(2)
    ]
)

param_names = [f"x{i}" for i in range(2)]
optimization_config = OptimizationConfig(
    objective=Objective(
        metric=L2NormMetric(name="l2norm", param_names=param_names),
        minimize=True,
    ))

exp = Experiment(
    name="exp_test",
    search_space=search_space,
    optimization_config=optimization_config,
    runner=MyRunner()
)


gs = GenerationStrategy(
    steps=[
        # Init Step
        GenerationStep(
            model=Models.SOBOL,
            num_trials=3,  
            min_trials_observed=3,  
            model_gen_kwargs={},  
        ),
        # BO step
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  
            model_kwargs={"botorch_acqf_class" : LogExpectedImprovement}

        ),
    ])

for i in range(20):
    generator_run = gs.gen(exp,data=exp.fetch_data())
    trial = exp.new_trial(generator_run=generator_run)
    trial.run()
    trial.mark_completed()

```

### Code of Conduct

- [X] I agree to follow this Ax's Code of Conduct

**Comment by sdaulton** [comment]
I believe that warm starting refitting is only used for cross-validation.

> should I be expecting a substantial improvement in the fitting run time when warm start is used?

It probably varies case to case, but my guess would be yes. The downside is that the previous HPs are likely close to a local maximum, but that might be quite suboptimal in the presence of new data. I.e. it may be beneficial to refit from scratch for more robust performance.

**Comment by RoeyYadgar** [comment]
Thanks for the answer!

>  The downside is that the previous HPs are likely close to a local maximum, but that might be quite suboptimal in the presence of new data. I.e. it may be beneficial to refit from scratch for more robust performance.

I'm not sure I understand why it would be suboptimal, I haven't dived deep enough into the HP optimization algorithm but I would guess that if I start from something that is closer to the optimal point, it would converge faster (i.e. with less iterations). If that is indeed the case, what would be the downside of it?

From what I understand I can do that by fitting the surrogate with warm start (i.e. provide `state_dict` from last iteration into `surrogate.fit`) but use `refit = True` (unlike in cross-validation which sets `refit = self.refit_on_cv` where `refit_on_cv` is `False` by default).

**Comment by Balandat** [comment]
> I'm not sure I understand why it would be suboptimal, I haven't dived deep enough into the HP optimization algorithm but I would guess that if I start from something that is closer to the optimal point, it would converge faster (i.e. with less iterations). If that is indeed the case, what would be the downside of it?

This is the case. However, the MLL that we optimize is non-convex and may have local minima. So it can happen that the initial data is kind of funky and results in some degenerate HP values (the risk for that is higher particularly in the low data regime) and if you warm-start from there you may keep digging into that local optimum and not get out of it by restarting the optimization from other HP values. 

> From what I understand I can do that by fitting the surrogate with warm start (i.e. provide state_dict from last iteration into surrogate.fit) but use refit = True (unlike in cross-validation which sets refit = self.refit_on_cv where refit_on_cv is False by default).

Indeed

**Comment by RoeyYadgar** [comment]
I see, thanks a lot!
