### ISSUE TITLE
The results of Models.GPEI and qNEI are different

### ISSUE THREAD

**Issue by rinc5** [facebook/Ax#323]
Hello.

I mentioned the results of Models.GPEI and qNEI are different in #293.
I tried Models.GPEI and qNEI 100 times respectively. As a result, the mean of qNEI's result is 1.5 times as big as the mean of Models.GPEI's result. Those std are almost the same.

However, when I tried Models.GPEI and qNEI for [this Hartmann6](https://ax.dev/tutorials/gpei_hartmann_service.html), then there is no difference.

So, does my code have any problem? Or, is this specific problem with using external data?
My code is not chenged from #293. Please feel free to ask me if you have any question about my code!

Thanks in advance.

**Comment by Balandat** [comment]
It's hard to say whether your code "has a problem" from this. 

> the mean of qNEI's result is 1.5 times as big as the mean of Models.GPEI's result

Does this mean qNEI does better or worse. In other words, are you maximizing or minimizing?

Your model specification differs from the default one `Models.GPEI` uses (you can see those here: https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L112-L120) in a number of ways:
- your kernel does not use ARD, whereas the default one does
- your Matern Kernel does not have a lengthscale prior
- your Scale kernel does not have a scale prior

These differences by themselves can have a pretty large impact on the model quality, so I would not be surprised if those were enough to cause the differences you are seeing on your data.

There is also a difference in the acquisition functions, namely that `Models.GPEI` will "prune" the baseline points passed to qNEI (which can speed up evaluation significantly):  https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py#L207-L210

Also, do you ever generate more than one candidate at a time before returning results (i.e. using a `max_parallelism` setting in the GenerationStrategy)? If that's the case then another difference could come from the fact that your setup for qNEI does not pass the pending points to the acquisition function.

**Comment by rinc5** [comment]
Thank you for your reply and sorry for the late reply.

> Does this mean qNEI does better or worse. In other words, are you maximizing or minimizing?

I'm maximizing. But, I have an outcome constraint and the result that mentioned my question is about the outcome constraint objective. `Models.GPEI` is closer to the constraint than qNEI.

> Your model specification differs from the default one Models.GPEI uses (you can see those here: https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L112-L120) in a number of ways:
> 
> * your kernel does not use ARD, whereas the default one does
> * your Matern Kernel does not have a lengthscale prior
> * your Scale kernel does not have a scale prior

I understand why the different has occured. I didn't know `Models.GPEI` uses ARD. So, can I get the result of qNEI closer to `Models.GPEI` one if I use ARD for my kernel?

> There is also a difference in the acquisition functions, namely that Models.GPEI will "prune" the baseline points passed to qNEI (which can speed up evaluation significantly): https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py#L207-L210

This is very useful! I have stuck on the problem that qNEI is slower than `Models.GPEI`. How do I determine `prune_baseline`?

> Also, do you ever generate more than one candidate at a time before returning results (i.e. using a max_parallelism setting in the GenerationStrategy)? If that's the case then another difference could come from the fact that your setup for qNEI does not pass the pending points to the acquisition function.

No, I don't use `max_parallelism`.

**Comment by rinc5** [comment]
I have an additional question.

I saw [this page](https://gpytorch.readthedocs.io/en/latest/kernels.html) and I understood that set `ard_num_dims` if I want to use ARD. Is this right? If so, what is base kernel of `Models.GPEI`?

I'd be happy when you point me out if I misunderstand.

**Comment by ldworkin** [comment]
cc @Balandat for thoughts on the last two comments (fwiw I looked up the modopt oncall ... but it's you this week :))

**Comment by Balandat** [comment]
> Models.GPEI is closer to the constraint than qNEI.

Presumably that's just b/c of the difference in the models.

> I understand why the different has occurred. I didn't know Models.GPEI uses ARD. So, can I get the result of qNEI closer to Models.GPEI one if I use ARD for my kernel?

If you specify the model exactly the same then yes you should get the same results.

> This is very useful! I have stuck on the problem that qNEI is slower than Models.GPEI. How do I determine prune_baseline?

https://github.com/pytorch/botorch/blob/master/botorch/acquisition/monte_carlo.py#L190


> I saw this page and I understood that set ard_num_dims if I want to use ARD. Is this right? If so, what is base kernel of Models.GPEI?

Yes. The default kernel in `Models.GPEI` is the one of `SingleTaskGP`: https://github.com/pytorch/botorch/blob/master/botorch/models/gp_regression.py#L110-L120

**Comment by rinc5** [comment]
Thank you for your reply.

I could finally get same result!
Also, I could get faster my `qNEI` by setting `prune_baseline`. (I'm sorry, I misunderstood about `prune_baseline`. I thought I must set data point to `prune_baseline`, but I just set `True`/`False`. Thanks your kindly explanation about it.)

I'm grateful for you always helping me out.
