### ISSUE TITLE
How to cite Ax?

### ISSUE THREAD

**Issue by lufol** [facebook/Ax#326]
Is there any paper out that could be reference when using Ax?

**Comment by eytan** [comment]
AE: A domain-agnostic platform for adaptive experimentation.
Eytan Bakshy, Lili Dworkin, Brian Karrer, Konstantin Kashin, Ben Letham, Ashwin Murthy, Shaun Singh. NeurIPS Systems for ML Workshop, 2018 

Is probably your best bet. There is also cite 

@article{balandat2019botorch,
  Author = {Balandat, Maximilian and Karrer, Brian and Jiang, Daniel R. and Daulton, Samuel and Letham, Benjamin and Wilson, Andrew Gordon and Bakshy, Eytan},
  Journal = {arxiv e-prints},
  Title = {{BoTorch: Programmable Bayesian Optimization in PyTorch}},
  Year = {2019},
  url = {http://arxiv.org/abs/1910.06403}
}

**Comment by lufol** [comment]
Thank you!

**Comment by mattrmd** [comment]
> AE: A domain-agnostic platform for adaptive experimentation. Eytan Bakshy, Lili Dworkin, Brian Karrer, Konstantin Kashin, Ben Letham, Ashwin Murthy, Shaun Singh. NeurIPS Systems for ML Workshop, 2018

In case anyone else is wondering, [here is the original NeurIPS link for the paper](http://learningsys.org/nips18/acceptedpapers.html). The domain is not `neurips.cc`, but this workshop is linked from [the official conference workshop page](https://neurips.cc/Conferences/2018/Schedule?showEvent=10919).

Also, the link on #281 leads to some kind of gambling site, and the PDF is not archived on the Wayback Machine. I think the domain must have expired and been bought by someone else.

**Comment by shuo-zhou** [comment]
Shall we cite [this AutoML paper](https://openreview.net/forum?id=U1f6wHtG1g) now?

**Comment by Balandat** [comment]
@shuo-zhou Yes this is the correct reference for Ax!

**Comment by Balandat** [comment]
Adding this to the readme and website in #4316 / #4317
