### ISSUE TITLE
use parameter constraints to express conditional dependencies

### ISSUE THREAD

**Issue by inkrement** [facebook/Ax#327]
Some of my hyper parameters conditionally depend on other parameters. How can I restrict the search space such that these parameters are only checked if they are really needed? For example, I  want to optimise fasttext and there are some parameters (e.g., neg) specific to certain loss functions (i.e., negative sampling). Is it possible to consider them only those specific cases? Or do I have to run different optimisations for each loss?

**Comment by 2timesjay** [comment]
@inkrement thanks for using Ax.

Right now the most straightforward option is several separate optimizations, one for each loss and including the loss-specific parameters.

To make it more straightforward to compare arms and their results, you might include all unused parameters as "fixed" parameters (see https://ax.dev/tutorials/building_blocks.html#1.-Define-the-search-space). This won't hurt optimization performance..

We're interested in adding hierarchical search space support though it's a pretty big project. If you have more details about your use case - number of total parameters, number of parameters shared between different conditional cases and the number exclusive to each, that would be very helpful in guiding us.

**Comment by lena-kashtelyan** [comment]
Closing this to merge with #140, since that's the main issue we keep open for the hierarchical search spaces feature request. Information about your use case, @inkrement, would still help our future work on this, as @2timesjay suggested, so feel free to post it in this issue or in #140!
