### ISSUE TITLE
Visualizations do not appear inside my Jupyter Notebook -- without any error messages

### ISSUE THREAD

**Issue by AlexanderKonstantinidis** [facebook/Ax#332]
When running the tutorial that is provided in the github of the Project, everything goes well otherwise but the visualizations do not actually appear in my Jupyter Notebook.  I am not getting any error messages.

The Jupyter Notebook I am referring to can be downloaded here: https://github.com/facebook/Ax/blob/master/tutorials/visualizations.ipynb.

Could you please advise?

![image](https://user-images.githubusercontent.com/22880894/84751250-04abaf80-afc5-11ea-8e57-eeaea55336e7.png)

**Comment by adamobeng** [comment]
Thanks for reporting this @AlexanderKonstantinidis! Could you say in which environment you're running this notebook (desktop OS, Google Colab, JupyterHub, etc.)?

**Comment by AlexanderKonstantinidis** [comment]
I am using my Notebook (Alienware) which has GPU and runs Windows 10.  I am using JupyterLab and Anaconda3.

Let me know if you need any more information.
________________________________

**Comment by Balandat** [comment]
FWIW @chauhang mentioned an issue in other libraries where visualizations would not show when run inside a docker container, this could possibly be related.

**Comment by ldworkin** [comment]
@2timesjay , maybe you can grab this one?

**Comment by 2timesjay** [comment]
@AlexanderKonstantinidis 

This is unfortunately a problem with all JupyterLab plotly plotting. 

I was able to resolve it by following https://plotly.com/python/getting-started/#jupyterlab-support-python-35 and installing the jupyter labextension suggested.

Please let us know if this works for you.

Alternately, Jupyter Notebooks should not encounter this problem.

**Comment by chsher** [comment]
I am encountering the same visualization issue (render yields blank output, no error messages) when attempting to execute https://github.com/facebook/Ax/blob/master/tutorials/tune_cnn.ipynb in Google Colab. Could you kindly advise?

**Comment by 2timesjay** [comment]
@chsher #306 covers this issue - the answer for colab still isnt' known yet. 

Closing and redirecting discussion to #306

**Comment by SauravS009** [comment]
> @AlexanderKonstantinidis
> 
> This is unfortunately a problem with all JupyterLab plotly plotting.
> 
> I was able to resolve it by following https://plotly.com/python/getting-started/#jupyterlab-support-python-35 and installing the jupyter labextension suggested.
> 
> Please let us know if this works for you.
> 
> Alternately, Jupyter Notebooks should not encounter this problem.



> @AlexanderKonstantinidis
> 
> This is unfortunately a problem with all JupyterLab plotly plotting.
> 
> I was able to resolve it by following https://plotly.com/python/getting-started/#jupyterlab-support-python-35 and installing the jupyter labextension suggested.
> 
> Please let us know if this works for you.
> 
> Alternately, Jupyter Notebooks should not encounter this problem.

i tried using jupyter notebook and still faced the issue. Visualizations are not visible.
I used plotly.express in the notebook

**Comment by Balandat** [comment]
@SauravS009 could you share a full repro on this, including which jupyter notebook version you are on?
