### ISSUE TITLE
ModuleNotFoundError: No module named 'ax.plot'

### ISSUE THREAD

**Issue by AlexanderKonstantinidis** [facebook/Ax#333]
This is the message I get when I run: `from ax.plot.contour import plot_contour.
`
I can import ax without a problem though.  (import ax)

**Comment by adamobeng** [comment]
Thanks for reporting this @AlexanderKonstantinidis! How did you install ax, and which version are you running?

**Comment by AlexanderKonstantinidis** [comment]
Installed it through pip and the version is shown below:

(torch) C:\WINDOWS\system32>pip show ax
Name: ax
Version: 0.48.0
Summary: Ax - workflow apps builder
Home-page: https://github.com/enf644/ax
Author: Mikhail Marenov
Author-email: enf644@gmail.com
________________________________

**Comment by fatotoro** [comment]
Similar problem here. Ax 0.48 installed from pip following the suggested instruction. 
If I run :
`from ax import optimize `

I get the following:
ImportError: cannot import name 'optimize' from 'ax' (unknown location)

If I run `import ax` no error is returned, but will still return error if trying to call ax.optimize.

Thanks for looking into this and please let me know if this should go to a separate thread!

**Comment by lena-kashtelyan** [comment]
Hi, @fatotoro! I think you want to `pip install ax-platform`, not `ax`! Sorry for the confusion there.
