### ISSUE TITLE
Will it be possible to extract the maximum value of acquisition function for each optimization loop?

### ISSUE THREAD

**Issue by cx1234paris** [facebook/Ax#334]
Hello! I found that your Ax framework was really convenient and useful for my task of bayesian optimization. However, when I try to launch the optimization loop (get_botorch), I would like to extract the maximum value of acquisition function to monitor the change of it. Is it possible to extract this maximum value within this Ax framework? Thank you so much for your help!

**Comment by ldworkin** [comment]
Hi @cx1234paris !

This isn't directly exposed through the API, but the Botorch model does return the acquisition function value here: https://github.com/facebook/Ax/blob/7af82212e0bea8f4a11a5aae8e8233185b931805/ax/models/torch/botorch.py#L373

And this value gets saved in the `gen_metadata` field on generator runs: https://github.com/facebook/Ax/blob/7af82212e0bea8f4a11a5aae8e8233185b931805/ax/modelbridge/base.py#L673

So if you're using the developer API, you can access the value as such:

```
for i in range(5):
    gpei = Models.BOTORCH(experiment=exp, data=exp.eval())
    gr = gpei.gen(1)
    print(gr.gen_metadata['expected_acquisition_value'])
    batch = exp.new_trial(generator_run=gr)
```

Let us know if that helps!

**Comment by cx1234paris** [comment]
Thank you so much for your help! Now I could monitor the expected acquisition value to stop my loop automatically.  Besides, I still have a question, with the developer API will it be possible to use the analytical acquisition function (ex. analytical EI) ? Thank you

**Comment by cx1234paris** [comment]
In fact, I just tried that if I could use an analytical AF by adding a kwarg in get_botorch() and defining a custom AF, but I found that the API only support types of MCAF, and to define an analytical AF I was confused by the parameters of 'objective_weights'

**Comment by ldworkin** [comment]
Hi @cx1234paris ! Yea, unfortunately it's not straightforward to use an analytical AF at this time.

**Comment by cx1234paris** [comment]
Thank you so much for your response! May be I will find another way. Good night!

**Comment by ldworkin** [comment]
Great, will close this for now, please let us know if you have any other questions!
