### ISSUE TITLE
Unused variable in `choose_generation_strategy`

### ISSUE THREAD

**Issue by andyznew** [facebook/Ax#341]
`    no_max_parallelism: bool = False,` is not used in the code, a relic of the past (https://github.com/facebook/Ax/blob/master/ax/modelbridge/dispatch_utils.py#L125). Not really a blocking issue but probably a todo to get rid of sometime

**Comment by Jakepodell** [comment]
This is a great call, thanks @andyznew for bringing this to our attention! :)

**Comment by lena-kashtelyan** [comment]
This is now fixed on the latest stable version, 0.1.14.
