### ISSUE TITLE
Sign of bias correction in 'relative' #164 #218

### ISSUE THREAD

**Issue by whimwang** [facebook/Ax#342]
https://github.com/facebook/Ax/blob/8b4046214857f7a0e66329e3119894230bb01789/ax/utils/stats/statstools.py#L164

I think the empirical means of 'm_t/m_c - 1' should be approximately normally distributed with mean
 [(mu_t - mu_c) / mu_c] + [(sigma_c)^2 * mu_t] / (mu_c)^3. The reasons are below.  Please let me know whether there is anything wrong in my proof. Thanks.

<img width="840" alt="WeChat563e805a7832057d45bc6ce15b978694" src="https://user-images.githubusercontent.com/40643936/86443580-1077cf80-bd42-11ea-830e-c29d14fcd242.png">

**Comment by ddimmery** [comment]
Hi @whimwang , thanks for looking into this!

Your proof is correct, but, we _have_ g(T_n) (which is mean(x) / mean(y)) and we _want to know_ g(theta). So we need to move the m_x / m_y ^ 3 sigma_y^2 to the other side. This leaves us with g(theta) \approx g(T_n) -  m_x / m_y ^ 3 sigma_y^2. You can also verify this through a quick simulation in R:

```{r}
sim = function(n = 100) {
  x = rnorm(n, 1)
  y = rnorm(n, .5)
  # true ratio, g(theta) is 1 / 0.5 = 2

  est0 = mean(x) / mean(y) # uncorrected
  est1 = mean(x) / mean(y) + mean(x) / mean(y)^3 * var(y) / n # adding the bias correction
  est2 = mean(x) / mean(y) - mean(x) / mean(y)^3 * var(y) / n # subtracting the bias correction (what we do)

  c(est0, est1, est2)
}

sims = replicate(1000, sim()) # get the sampling distribution of our three estimators

colMeans(abs(t(sims) - 2)) # calculate mean absolute deviation
```

The output is something like:
```
[1] 0.3764685 0.4348188 0.3309594
```

You can also verify that this difference is coming from bias and not variance:
```
colMeans((t(sims) - 2))
[1]  0.09218882  0.19948017 -0.01510253
```

It actually reduces bias quite substantially in this (contrived) example, where the mean of y is close enough to zero that bias-correction becomes important.
