### ISSUE TITLE
[Question] See optimal parameters without adding a trial?

### ISSUE THREAD

**Issue by bendemeo** [facebook/Ax#350]
Hello,

I am running Ax with the GPEI generation strategy (a basic Gaussian process), and would like to know the parameters that optimize the acquisition function, without incurring any side-effects. The parameters are accessible via AxClient.get_next_trial(), but this also adds a new trial to the underlying experiment, and we must either give it new data (the objective evaluated at the suggested parameters) or abandon it (which still leaves the abandoned trial in memory). Is there any function or workaround that would allow me to see the optimal parameters without instantiating this trial or otherwise affecting the underlying model? 

Sincerely,
Ben

**Comment by stevemandala** [comment]
Great question. We designed the Service API to tightly couple the modelling, param generation, and experimentation steps, which does make it harder to directly inspect the acquisition function without generating artifacts (e.g. trials). This is something we're hoping to improve in the future.

Today, one workaround would be to pull the data from the experiment, fit the model, and generate candidates separately:
```
data = ax_client.experiment.fetch_data()
gpei = Models.GPEI(experiment=ax_client.experiment, data=data)
generator_run = gpei.gen(1) 
```

Hopefully this supports what you were looking for, but do let us know if not.

**Comment by bendemeo** [comment]
Thanks @stevemandala! This is very helpful. In the case of a model besides GPEI, or a compound model like the default SOBO+GPEI behavior, could you extract the model directly from the client without knowing a priori what it is? I have made a pass at this, and came up with: 

`data = self.client.experiment.fetch_data()
model = client.generation_strategy._curr.model(experiment = client.experiment, data=data)
generator_run = model.gen(1)
params = generator_run.arms(0).parameters`

Does this look reasonable? It seems to accomplish what I need, though it requires accessing the protected _curr attribute.

**Comment by eytan** [comment]
Clarifying question, by optimal parameters do you mean those that would be chosen by EI (the best guess as to what’s optimal if you’ve run another trial), or the most optimal according to the current model (the data you’ve already collected)?

**Comment by 2timesjay** [comment]
@bendemeo client.get_best_parameters should work for you. See docs here: https://ax.dev/api/service.html#ax.service.ax_client.AxClient.get_best_parameters

**Comment by bendemeo** [comment]
@eytan The latter -- I mean the optimum of the acquisition function, conditioned on the data already collected. So the next point that would be added by get_next_trial(), just without the side-effects. Thank you for clarifying!

**Comment by ldworkin** [comment]
@bendemeo In that case, I think what you have above (where you access `._curr`) is indeed the best way! Curious if @lena-kashtelyan has other thoughts though.

**Comment by lena-kashtelyan** [comment]
@bendemeo, your code snippet looks right overall; you can simplify it a bit like so: 
```
generator_run = client.generation_strategy.gen(1)  # This will fetch all available data and instantiate model for you.
params = generator_run.arms(0).parameters
```

**Comment by lena-kashtelyan** [comment]
Closing this as I think it should be answered with all our responses above; feel free to reopen, @bendemeo, if you have any follow-up questions!
