### ISSUE TITLE
How to Save Multi-Task Optimization Experiments

### ISSUE THREAD

**Issue by johnbenweber** [facebook/Ax#351]
What is the recommended  approach for saving Multi-Task Optimization Experiments?

I followed the [Multi-Task Bayesian Optimization Tutorial](https://ax.dev/tutorials/multi_task.html) and I am interested in adapting that to a problem where the online task is a physical field experiment that may take days to complete. In this case it seems prudent to save the state of the optimization to be loaded upon the completion of field experiments.

I have tried using the save method but receive the following error:
```
JSONEncodeError: Object MultiTypeExperiment(mt_exp) passed to `object_to_json`
(of type <class 'ax.core.multi_type_experiment.MultiTypeExperiment'>)
is not registered with a corresponding encoder in ENCODER_REGISTRY.
```
So it seems a handler has not been implemented for this experiment type but perhaps there is a workaround that could be used in the mean time?

**Comment by ldworkin** [comment]
Hi @johnbenweber! Thanks for pointing this out, this seems like an oversight. I believe we have SQL support for these experiments but not JSON support. We'll try to get this fix in soon.

**Comment by johnbenweber** [comment]
Thanks for the quick response @ldworkin! I will give the SQL interface a try.

**Comment by EricZLou** [comment]
Hi @johnbenweber -- glad the SQL interface worked for you! Just an update that a fix for JSON storage of multi-task experiments is on master and will be included in the next stable release of Ax.
