### ISSUE TITLE
Update Readme.md - Add Link to the last line and also add on macOS 10.10 (Yosemite) or above.

### ISSUE THREAD

**Issue by adithyaakrishna** [facebook/Ax#360]
The last line in the section, Join the Ax Community doesn't have a link or the detail about which version is supported.
Also in the Latest Version Section, Line No.120

![image](https://user-images.githubusercontent.com/23498248/90310348-64173480-df0e-11ea-93fd-b70e9616c457.png)

**Comment by ldworkin** [comment]
Hi @adithyaakrishna , I'm not sure I understand what your request is. The line "see recommendation for installing PyTorch for MacOS users above" is referring to the section [here](https://github.com/facebook/Ax#installing-via-pip) which says:

> Recommendation for MacOS users: PyTorch is a required dependency of BoTorch, and can be automatically installed via pip. However, we recommend you install PyTorch manually before installing Ax, using the Anaconda package manager. Installing from Anaconda will link against MKL (a library that optimizes mathematical computation for Intel processors). This will result in up to an order-of-magnitude speed-up for Bayesian optimization, as at the moment, installing PyTorch from pip does not link against MKL.

Is there something you'd like to be made more clear?

**Comment by ldworkin** [comment]
Edit: I see, you were referring to the changes you made here: https://github.com/facebook/Ax/pull/362

**Comment by lena-kashtelyan** [comment]
@adithyaakrishna, moving this discussion to your PR: #362, as there are more specifics there to discuss. Feel free to reopen this issue if you'd like to follow up here!
