### ISSUE TITLE
[Question] How to attach custom trials in Developer API

### ISSUE THREAD

**Issue by theinlinaung2010** [facebook/Ax#365]
Hi, I would like to know how to attach custom parameterizations in Developer API like `attach_trial` method in Service API. I could not find a way in documentation nor in existing discussions.

The reason I want to use developer API is the need for a custom kernel (RBF kernel) as described in https://botorch.org/tutorials/custom_botorch_model_in_ax.

Thank you in advance.

**Comment by ldworkin** [comment]
Hi @theinlinaung2010 !

Great question. You have to manually create a GeneratorRun containing the parameterization you want, like this:

```
arm = Arm(parameters={"x1": 0.0, "x2": 0.0})
generator_run = GeneratorRun(arms=[arm])
trial = experiment.new_trial(generator_run=generator_run)
```

Let me know if that helps!

**Comment by theinlinaung2010** [comment]
It worked perfectly! Thank you.
