### ISSUE TITLE
What happens to subsequent trials when an output constraint(s) is not satisfied?

### ISSUE THREAD

**Issue by jangkj09** [facebook/Ax#375]
With Service API, the function I am optimizing returns two metrics (e.g. `m1` and `m2`), and I have defined one as the objective (`m1`) and placed an output constraint on the other (`m2 <= x`).
During the trials, if the output constraint is not satisfied, how is this recorded and how is this information used in a subsequent trial?
Is this information taken into consideration when sampling the next arm?

**Comment by lena-kashtelyan** [comment]
Please clarify what you mean by:
> During the trials, if the output constraint is not satisfied
Are you seeing a trial that doesn't satisfy the constrains? Please include code snippet of how you set up your experiment and what trials you are seeing.

**Comment by jangkj09** [comment]
Thanks, this clarifies a lot. 
Just two more things: 
1. The way I have it set up, when the output constraint is satisfied the other metric (the objective, i.e. `m1`) defaults to 0. will the model to generate future values use that value of 0?

2. I just want to understand it in more detail, but is there any reference for the mechanism which  tries to ensure that  future trials will be produced which satisfy the outcome?

**Comment by qingfeng10** [comment]
Re: taking into account trails that do not satisfy constraints / or trails that satisfy constraints but objective values are not great

In each trial, the method takes data from all the past trails and builds GP model to capture the relationship between metrics and your tuning parameters. Therefore, although some trials are not great in terms of optimization goal, they help to learn the relationship so the optimization can avoid the bad region. 

Method-wise, it's based on bayesian optimization (https://ax.dev/docs/bayesopt.html) As we are getting more trials, you will converge to a global optimal. If your outcome constraint is feasible, the best trial from running the Service API will satisfy the outcome with best objective.

**Comment by lena-kashtelyan** [comment]
> The way I have it set up, when the output constraint is satisfied the other metric (the objective, i.e. m1) defaults to 0. will the model to generate future values use that value of 0? 

Did you meant "when the output constraint is not satisied"? I'm not sure I understand what you are asking.

**Comment by jangkj09** [comment]
Right, it should be "when the output constraint is not satisfied". 

@qingfeng10 I understand that this is Bayesian optimization, but I suppose Ax is taking the outcome constraints and transforming it into some constrained form of BO 
I was wondering how this is being implemented (e.g. if it's calling BoTorch, then how is it calling it?) and if there is an example of customizing this part?

**Comment by lena-kashtelyan** [comment]
We have some documentation on specific type of BayesOpt we use [here](https://ax.dev/docs/models.html#gaussian-process-with-ei). Also, here is a [tutorial](https://botorch.org/tutorials/custom_botorch_model_in_ax) for setting up a custom BoTorch model in Ax, and you can read through the [`BotorchModel`](https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch.py#L91) and [`botorch_defaults.py`](https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_defaults.py) to see how Ax calls BoTorch. #293 and #363 might also be of interest to you –– as discussed in those, the process of setting up a custom BoTorch model is Ax is fairly cumbersome currently, but will soon be simplified with some work currently underway.

Feel free to reopen the issue or start a new one if you have more question!
