### ISSUE TITLE
Setting winsorization limits

### ISSUE THREAD

**Issue by jangkj09** [facebook/Ax#377]
When using the Service API, there is an option to set winsorization limits, but it's unclear what a valid value is for the limits. The documentation says: 
...clip the mean values for each metric to lay within the limits provided in the config as a tuple of (lower bound percentile, upper bound percentile)..., 
When I set a value of `(10.0,90.0)` I get an error. Are the values of the bounds supposed to be between 0~1 (i.e. quantiles, not percentiles)?

If I try setting it to `(0.1, 0.9)` I get the error: 
`AssertionError: Upper bound: 0.9 was less than the inverse of lower: 0.1`
I'm not quite understanding what the problem is.

**Comment by 2timesjay** [comment]
The expected values are actually the percentile to trim from each end as a float in [0,1).

So to trim 10% from lower and upper bounds you'll pass

{"winsorization_lower": 0.1, "winsorization_upper": 0.1}

I'll clarify the docs. let me know if this works, and please post with a follow-up with your code if it doesn't.

**Comment by jangkj09** [comment]
Thank you, this allowed my code to run properly.
