### ISSUE TITLE
Links in the Tutorials docs aren't working

### ISSUE THREAD

**Issue by markgoodhead** [facebook/Ax#390]
The Tutorials docs here: https://ax.dev/tutorials/ contain links which don't work, e.g. https://ax.dev/tutorials/multi_task.html which gives a page with the following text:

> 404
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
> 
> Read the full documentation for more information about using GitHub Pages.

**Comment by lena-kashtelyan** [comment]
We're currently addressing that and will re-release a working version shortly!

**Comment by lena-kashtelyan** [comment]
This is now fixed.
