### ISSUE TITLE
ax-platform 0.1.15 installation issues - ModuleNotFoundError: No module named 'ax.models.torch.botorch_modular'

### ISSUE THREAD

**Issue by optiluca** [facebook/Ax#394]
Hi.  I'm trying to install Ax, I've tried using conda, pip, python 3.7, python 3.8 and any permutation of the above but the error is always:

```
>>> import ax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lbortolotti\Miniconda3\lib\site-packages\ax\__init__.py", line 31, in <module>
    from ax.modelbridge import Models
  File "C:\Users\lbortolotti\Miniconda3\lib\site-packages\ax\modelbridge\__init__.py", line 10, in <module>
    from ax.modelbridge.factory import (
  File "C:\Users\lbortolotti\Miniconda3\lib\site-packages\ax\modelbridge\factory.py", line 22, in <module>
    from ax.modelbridge.registry import (
  File "C:\Users\lbortolotti\Miniconda3\lib\site-packages\ax\modelbridge\registry.py", line 48, in <module>
    from ax.models.torch.botorch_modular.model import BoTorchModel
ModuleNotFoundError: No module named 'ax.models.torch.botorch_modular'
```
For this specific run, the setup is:

- Miniconda windows x86-64 4.8.5
- Vanilla Python 3.8.5 environment
- conda install pytorch torchvision -c pytorch
- pip3 install ax-platform

Everything runs without error, but then trying to open a python session and importing ax gives rise to the error above. 

This is the list of packages in my env:

> 
> 
> ax-platform               0.1.15                   pypi_0    pypi
> blas                      2.16                        mkl    conda-forge
> botorch                   0.3.1                    pypi_0    pypi
> brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
> ca-certificates           2020.6.20            hecda079_0    conda-forge
> certifi                   2020.6.20        py38h32f6830_0    conda-forge
> cffi                      1.14.3           py38hba49e27_0    conda-forge
> chardet                   3.0.4           py38h32f6830_1007    conda-forge
> conda                     4.8.5            py38h32f6830_1    conda-forge
> conda-package-handling    1.7.0            py38hd4486f3_5    conda-forge
> console_shortcut          0.1.1                         4
> cryptography              3.1.1            py38hba49e27_0    conda-forge
> cudatoolkit               10.2.89              h74a9793_1
> freetype                  2.10.2               hd328e21_0    conda-forge
> future                    0.18.2                   pypi_0    pypi
> gpytorch                  1.2.0                    pypi_0    pypi
> idna                      2.10               pyh9f0ad1d_0    conda-forge
> intel-openmp              2020.1                      216
> jinja2                    2.11.2                   pypi_0    pypi
> joblib                    0.16.0                   pypi_0    pypi
> jpeg                      9d                   he774522_0    conda-forge
> libblas                   3.8.0                    16_mkl    conda-forge
> libcblas                  3.8.0                    16_mkl    conda-forge
> liblapack                 3.8.0                    16_mkl    conda-forge
> liblapacke                3.8.0                    16_mkl    conda-forge
> libpng                    1.6.37               ha81a0f5_2    conda-forge
> libtiff                   4.1.0                h885aae3_6    conda-forge
> lz4-c                     1.9.2                h62dcd97_2    conda-forge
> m2w64-gcc-libgfortran     5.3.0                         6
> m2w64-gcc-libs            5.3.0                         7
> m2w64-gcc-libs-core       5.3.0                         7
> m2w64-gmp                 6.1.0                         2
> m2w64-libwinpthread-git   5.0.0.4634.697f757               2
> markupsafe                1.1.1                    pypi_0    pypi
> menuinst                  1.4.16                   py38_0    conda-forge
> mkl                       2020.1                      216
> msys2-conda-epoch         20160418                      1
> ninja                     1.10.1               h7ef1ec2_1    conda-forge
> numpy                     1.19.1           py38h72c728b_0    conda-forge
> olefile                   0.46                       py_0    conda-forge
> openssl                   1.1.1h               he774522_0    conda-forge
> pandas                    1.1.2                    pypi_0    pypi
> pillow                    7.2.0            py38h7011068_1    conda-forge
> pip                       20.2.3                     py_0    conda-forge
> plotly                    4.10.0                   pypi_0    pypi
> powershell_shortcut       0.0.1                         3
> pycosat                   0.6.3           py38h1e8a9f7_1004    conda-forge
> pycparser                 2.20               pyh9f0ad1d_2    conda-forge
> pyopenssl                 19.1.0                     py_1    conda-forge
> pysocks                   1.7.1            py38h32f6830_1    conda-forge
> python                    3.8.5           h60c2a47_9_cpython    conda-forge
> python-dateutil           2.8.1                    pypi_0    pypi
> python_abi                3.8                      1_cp38    conda-forge
> pytorch                   1.6.0           py3.8_cuda102_cudnn7_0    pytorch
> pytz                      2020.1                   pypi_0    pypi
> pywin32                   227              py38hfa6e2cd_0    conda-forge
> requests                  2.24.0             pyh9f0ad1d_0    conda-forge
> retrying                  1.3.3                    pypi_0    pypi
> ruamel_yaml               0.15.80         py38h1e8a9f7_1002    conda-forge
> scikit-learn              0.23.2                   pypi_0    pypi
> scipy                     1.5.2                    pypi_0    pypi
> setuptools                49.6.0           py38h32f6830_1    conda-forge
> six                       1.15.0             pyh9f0ad1d_0    conda-forge
> sqlite                    3.33.0               he774522_0    conda-forge
> threadpoolctl             2.1.0                    pypi_0    pypi
> tk                        8.6.10               he774522_0    conda-forge
> torchvision               0.7.0                py38_cu102    pytorch
> tqdm                      4.50.0             pyh9f0ad1d_0    conda-forge
> urllib3                   1.25.10                    py_0    conda-forge
> vc                        14.1                 h869be7e_1    conda-forge
> vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
> wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
> win_inet_pton             1.1.0                    py38_0    conda-forge
> wincertstore              0.2                   py38_1003    conda-forge
> xz                        5.2.5                h62dcd97_1    conda-forge
> yaml                      0.2.5                he774522_0    conda-forge
> zlib                      1.2.11            h62dcd97_1009    conda-forge
> zstd                      1.4.5                h1f3a1b7_2    conda-forge

**Comment by krfricke** [comment]
Hey @optiluca, it seems that you need the latest release `v0.1.16`, which hasn't been pushed to PyPI, yet.

```
pip install -U git+https://github.com/facebook/Ax.git@0.1.16
```

will solve the problem for now.

@lena-kashtelyan this lead to problems in our integration tests, too. Can you update the PyPI package, soon?

**Comment by sdsingh** [comment]
@krfricke, apologies for the breakage. We are working on pushing a new PyPI package by EOD today (hopefully sooner).

**Comment by lena-kashtelyan** [comment]
A new release is out (0.1.17) and should fix this. Please let us know if it does not!

**Comment by lena-kashtelyan** [comment]
Closing issue as the fix for this is now on the stable version.
