### ISSUE TITLE
Question: is the implementation of gen() for random forest planned?

### ISSUE THREAD

**Issue by Pzmijewski** [facebook/Ax#395]
hey,
i´m writing my master thesis about bayesian optimization applied to a logistic simulation and want to benchmark GP-EI and RF-EI, because i´m primary using discrete values. Currently RF in Ax has no generate-function. Is it planned in the near future or is there any workaround to add a gen-function to the [RF-model](https://github.com/facebook/Ax/blob/16cb868911eecba323759e2e129df8833361e614/ax/models/numpy/randomforest.py)?

thank you!

Philipp

**Comment by sdsingh** [comment]
Hi @Pzmijewski! I'm not sure of the current plans around the RF model. Let me check in with the owner of that project, @bletham, and we should be able to have a response for you early next week.

**Comment by bletham** [comment]
There aren't any current plans for implementing an RF-based BO method. The RF model in Ax is useful just for modeling and prediction, for instance as a baseline to which GPs model fit can be compared.

SMAC uses random forests in it's "HPO" mode (here is a usage example: https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_acq_rosenbrock.py). It is the only RF-based BO method that I'm aware of.

The challenge with using an RF for BO is that they don't provide the extrapolative uncertainty that acquisition functions like EI use to ensure good exploration. Their predictions are also not differentiable so optimizing the acquisition function becomes harder than with a GP.

**Comment by lena-kashtelyan** [comment]
Closing the issue, since this is unfortunately something that is not on our plan.
