### ISSUE TITLE
CUDA - expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by optiluca** [facebook/Ax#396]
ax.__version__
'v0.1.14'
botorch.__version__
'0.3.1'
torch.__version__
'1.6.0+cu101'

Running [this](https://gist.github.com/optiluca/265851e618919490cb311ce275b0fa0a) test script throws:

> Traceback (most recent call last):
>   File "<input>", line 1, in <module>
>   File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
>     pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
>   File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
>     exec(compile(contents+"\n", file, 'exec'), glob, loc)
>   File "C:/lbortolotti/PerformanceMethods/doe_toolbox/ax_test.py", line 58, in <module>
>     parameters, trial_index = ax_client.get_next_trial()
>   File "C:\Python\37\lib\site-packages\ax\service\ax_client.py", line 275, in get_next_trial
>     trial = self.experiment.new_trial(generator_run=self._gen_new_generator_run())
>   File "C:\Python\37\lib\site-packages\ax\service\ax_client.py", line 865, in _gen_new_generator_run
>     experiment=self.experiment
>   File "C:\Python\37\lib\site-packages\ax\modelbridge\generation_strategy.py", line 376, in gen
>     keywords=get_function_argument_names(model.gen),
>   File "C:\Python\37\lib\site-packages\ax\modelbridge\base.py", line 626, in gen
>     model_gen_options=model_gen_options,
>   File "C:\Python\37\lib\site-packages\ax\modelbridge\array.py", line 225, in _gen
>     target_fidelities=target_fidelities,
>   File "C:\Python\37\lib\site-packages\ax\modelbridge\torch.py", line 224, in _model_gen
>     target_fidelities=target_fidelities,
>   File "C:\Python\37\lib\site-packages\ax\models\torch\botorch.py", line 367, in gen
>     **acf_options,
>   File "C:\Python\37\lib\site-packages\ax\models\torch\botorch_defaults.py", line 186, in get_NEI
>     seed=torch.randint(1, 10000, (1,)).item(),
>   File "C:\Python\37\lib\site-packages\botorch\acquisition\utils.py", line 107, in get_acquisition_function
>     prune_baseline=kwargs.get("prune_baseline", False),
>   File "C:\Python\37\lib\site-packages\botorch\acquisition\monte_carlo.py", line 221, in __init__
>     model=model, X=X_baseline, objective=objective
>   File "C:\Python\37\lib\site-packages\botorch\acquisition\utils.py", line 266, in prune_inferior_points
>     obj_vals = objective(samples)
>   File "C:\Python\37\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "C:\Python\37\lib\site-packages\botorch\acquisition\objective.py", line 258, in forward
>     eta=self.eta,
>   File "C:\Python\37\lib\site-packages\botorch\utils\objective.py", line 140, in apply_constraints
>     obj = obj.add(infeasible_cost)  # now it is nonnegative
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by sdsingh** [comment]
Hi @optiluca, thanks for the very clear repro. I opened https://github.com/facebook/Ax/pull/397, and will land this. You can patch this on now to unblock; we were not respecting the Torch default device.

**Comment by lena-kashtelyan** [comment]
The fix is now in the latest stable, 0.1.18.
