### ISSUE TITLE
Store intermediary tables for demand forecasting

### ISSUE THREAD

**Issue by graceboatman** [facebook/Ax#418]
Demand forecasting is slow because every time we call the method we recompute several dataframes, it would be useful to store these as tables in a database.

**Comment by adamobeng** [comment]
Hi Grace!

Would you be able to share a little bit more about your application? In particular, what method are you calling? If you have any code we could look at, that would be helpful too!

**Comment by graceboatman** [comment]
Hi Adam,

So sorry, this was an accident I didn't mean to post this here. (Wrong git repo!!!)
