### ISSUE TITLE
Constant parameters to avoid rewriting parameter fetching code

### ISSUE THREAD

**Issue by rjurney** [facebook/Ax#431]
I want to be able to set parameters to constant values so that I can freeze them without having to replace my `parameters.get("value")` calls with `value`.

**Comment by lena-kashtelyan** [comment]
@rjurney, could you provide a bit more detail? I don't quite understand what you are looking to do. It would help to see:
- which API you are using (Service? Loop? Developer?),
- the snippet of what you are currently doing,
- what you'd like it to look like. 

One wild guess I can take is that fixed parameters might be what you are looking for: here are the [API docs for those](https://ax.dev/api/core.html#ax.core.parameter.FixedParameter). In the Service API you can use those by passing {..., "type": "fixed"}, I believe. Note that changing range parameters to fixed ones is currently buggy: see #383.

**Comment by rjurney** [comment]
> @rjurney, could you provide a bit more detail? I don't quite understand what you are looking to do. It would help to see:
> 
> - which API you are using (Service? Loop? Developer?),
> 
> - the snippet of what you are currently doing,
> 
> - what you'd like it to look like. 
> 
> 
> 
> One wild guess I can take is that fixed parameters might be what you are looking for: here are the [API docs for those](https://ax.dev/api/core.html#ax.core.parameter.FixedParameter). In the Service API you can use those by passing {..., "type": "fixed"}, I believe. Note that changing range parameters to fixed ones is currently buggy: see #383.

Thank you, I searched for a fixed type and couldn't find it.

**Comment by ldworkin** [comment]
Great, let us know if you have any other questions!
