### ISSUE TITLE
Contextual Bandits

### ISSUE THREAD

**Issue by drelum** [facebook/Ax#443]
Hi,

I couldn’t find any example on how to pass context to the MAB experiment trial. Does it support context?

Thank you

**Comment by sdsingh** [comment]
Hi André!

Do you have some more information about the problem you're trying to solve? 
In the Ax Thompson Sampling algorithm, we unfortunately don't support contexts. However, we have recently added contextual support to the Bayesian Optimization algorithms, in https://github.com/facebook/Ax/commit/956019be0a2a3ab0cb9e115de7a64bc5b03c41be (thanks to @qingfeng10!)

**Comment by lena-kashtelyan** [comment]
I'm closing this issue as inactive, please get back to us and reopen if you need more assistance, @drelum !
