### ISSUE TITLE
Raytune notebook tutorial is broken

### ISSUE THREAD

**Issue by lemairecarl** [facebook/Ax#457]
The output of cell 6 contains a literal ocean of stacktraces:
https://ax.dev/tutorials/raytune_pytorch_cnn.html

**Comment by ldworkin** [comment]
Hi @lemairecarl ! Yea, this is a known issue on our end and has proven trickier to debug than we'd like (the issue seems to be related to Travis and is hard for us to repro locally). We'll try to investigate/fix soon.

**Comment by lena-kashtelyan** [comment]
@lemairecarl, for what it's worth, the tutorial should actually be able to run locally; it seems that the issues with it on the website might stem from running it in the continuous integration service that we use for testing and website deployment. If you are looking to use Ax with Ray, try out running that tutorial locally –– it should work (please let us know if it doesn't).

**Comment by lemairecarl** [comment]
Ok good.
But even if it's just because of CI, it makes the page (almost) useless.
I can understand you have better things to do than fix that, though!

**Comment by lena-kashtelyan** [comment]
We are prioiritizing the fix for this, and it should be up on the website soon.

**Comment by lena-kashtelyan** [comment]
The tutorial is now fixed and on master, the latest version of the website reflects the fixes: https://ax.dev/versions/latest/tutorials/raytune_pytorch_cnn.html. This will be included in the next stable version we will be releasing soon.

**Comment by ldworkin** [comment]
Fixed on stable now! https://ax.dev/versions/latest/tutorials/raytune_pytorch_cnn.html
