### ISSUE TITLE
How to limit number of CPU cores Ax uses?

### ISSUE THREAD

**Issue by aero-108** [facebook/Ax#461]
Hi,
can anyone tell me how to limit CPU cores?
Simple trial use all cores:

```
import logging
from ax import optimize, RangeParameter, ParameterType

logging.basicConfig(level=logging.DEBUG)

def eval_func(p):
    # print(p)
    return (p["x1"] + p["x2"] + p['x3'] + p['x4'])/100.00
    
best_parameters, best_values, experiment, model = optimize(
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [-10, 10],
            "value_type": 'int',
        },
        {
            "name": "x2",
            "type": "range",
            "bounds": [-10, 10],
            "value_type": 'int',
        },
        {
            "name": "x3",
            "type": "range",
            "bounds": [-10, 10],
            "value_type": 'int',
        },
        {
            "name": "x4",
            "type": "range",
            "bounds": [-10, 10],
            "value_type": 'int',
        },
    ],
    # Booth function
    evaluation_function=eval_func,
    minimize=True,
)

print(best_parameters)
```

**Comment by lena-kashtelyan** [comment]
cc @Balandat, who I believe might know this.

**Comment by Balandat** [comment]
So we don't do any explicit multiprocessing / threading handling in Ax/BoTorch, this is the default threading behavior of MKL (which is used under the hood in PyTorch for the heavy lifting GP and linear algebra computations).

I haven't tried this myself yet, but you should be able to disable this on the pytorch end using https://pytorch.org/docs/stable/torch.html#torch.set_num_threads. You can also try setting the `MKL_NUM_THREADS` and `OMP_NUM_THREADS` env vars. See https://github.com/pytorch/pytorch/issues/16894 for more on this. 

Are you running into any issues with the default behavior? Why do you want to limit the parallelism?

**Comment by lena-kashtelyan** [comment]
I'm closing this issue as inactive, please get back to us an reopen if you need more assistance, @aero-108!
