### ISSUE TITLE
Does Ax support One-Shot Knowledge Gradient?

### ISSUE THREAD

**Issue by aliosmanulusoy** [facebook/Ax#465]
One-shot KG seems to perform better than EI and noisy EI according to the BO paper https://arxiv.org/pdf/1910.06403.pdf.

**Comment by stevemandala** [comment]
Hey @aliosmanulusoy! We do support one-shot KG as one of the models, we include it in our model registry, so you can instantiate it like an Ax EI model:

```
from ax.modelbridge.registry import Models

kg = Models.GPKG(experiment=exp, data=data)
```

The implementation is here: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_kg.py

(By no coincidence, the authors on that paper are Ax contributors, so let us know if you have any questions or feedback)

**Comment by aliosmanulusoy** [comment]
Thanks! I'll give it a try. 

A quick feedback: it'd be great if there was some documentation about the models already implemented in the registry. I had seen the GPKG model but thought it was Frasier's KG, and not the approach proposed in the paper you cited.

**Comment by eytan** [comment]
It’s still KG, it’s just a different way of optimizing the KG objective :) It might still be good to add a reference to the BoTorch paper in the comments, cc @danielrjiang. Also not sure why we don’t support constraints in Ax KG—this should work just fine in BoTorch.
