### ISSUE TITLE
migration to docusaurus 2

### ISSUE THREAD

**Issue by davidjgoss** [facebook/Ax#466]
As part of [an effort to roll out Docusaurus 2 and test its site migration tools](https://github.com/facebook/docusaurus/issues/1834), would you be okay with having me (or somebody else) do a PR that migrates the Ax website to Docusaurus 2?

**Comment by ldworkin** [comment]
Hi @davidjgoss! Sure, this sounds good to me. Are there any downsides to it? I can't think of a reason why this would be a problem, but I'm also not very familiar with Docusaurus.

**Comment by Balandat** [comment]
When we looked at this in the past, one issue was that we do some manual versioning of the whole site (incl. tutorials and Sphnix-generated API docs), and docusaurus2 at the time wasn't able to properly support that. So we want to make sure that the functionality remains as is (or gets better) with the migration.

If you are considering migrating Ax, please also consider migrating pytorch/botorch, as the site setup is essentially the same as for Ax.

**Comment by davidjgoss** [comment]
@ldworkin @Balandat looking at the current site I don't think there should be any blockers. Versioning wasn't there in the earlier alphas but is well supported now including by the migration tooling. i18n is still not there but I don't think the Ax site uses that?

**Comment by Balandat** [comment]
Just to be clear, this is versioning for externally include sites such as the tutorials and the sphinx-autogenerated html code that we stick into the site. This versioning happens in https://github.com/facebook/Ax/blob/master/scripts/publish_site.sh. We do not use i18n.

**Comment by lena-kashtelyan** [comment]
We will now be tracking wishlist items / feature requests in a master issue for improved visibility: #566. Of course please feel free to still open new feature requests issues; we'll take care of thinking them through and adding them to the master issue.
