### ISSUE TITLE
ScalarizedOutcomeConstraint support (e.g. sum outcome constraint)

### ISSUE THREAD

**Issue by reiter-ja** [facebook/Ax#472]
Hello Ax team,

Is there a way to use **SumConstraint()** as an **OutcomeConstraint()** with a set of different metrics?

Background:
I have a set of metrics, each of them depends on three input parameters:
_Metric1 = f(x1,x2,x3)_
_Metric2 = f(x4,x5,x6)_
_Metric3 = f(x7,x8,x9)_

Now I want to set an outcome constraint like:
_Limit <= Sum(Metric1, Metric2, Metric3)_

Right now I use python to calculate the sum of the three different metrics and define a fourth metric like:
_Metric4 = np.sum( Metric1, Metric2, Metric3)_
and then I define one single OutcomeConstraint based on Metric4.

However, I think now it is much harder for Ax to learn the behavior of Metric4.

Many thanks in advance for the answer :-)

Best regards,
Jakob

**Comment by lena-kashtelyan** [comment]
Hi, @reiter-ja! This functionality is currently not supported, unfortunately, but not because there is a methodological blocker –– it's just something we have not yet had requests for and therefore have not dedicated the engineering effort to. We'll look into adding support for this, and I will let you know once we have a plan (or a decision that we are not supporting this in the short term).

**Comment by lena-kashtelyan** [comment]
Update on this: while we are interested in supporting this functionality, we probably will not get to it in the short-term, so marking this item as 'wishlist' for now.

**Comment by lena-kashtelyan** [comment]
Support for `ScalarizedOutcomeConstraints` has now been added to Ax and is included in the current 'master' version. It will be included in our next stable release sometime next month! Please feel free to ask any questions in this issue, @reiter-ja! 

cc @qingfeng10 who added support for this functionality

**Comment by lena-kashtelyan** [comment]
This is now done and included with latest stable release, 0.2.0.
