### ISSUE TITLE
TuRBO support in Ax

### ISSUE THREAD

**Issue by winf-hsos** [facebook/Ax#474]
Hi, do you have a working example to integrate TuRBO with Ax yet? Are there plans in this direction? 

I have recently read the paper and ran the Botorch example for the TuRBO-1 algorithm. We are currently working on optimizing a 60 dimensional (and larger) simulation model. We tried ALEBO but didn't get good results, probably due to too many parameters being important for the outcome.

Thank
Nicolas

**Comment by Balandat** [comment]
Hi and thanks for your interest.

We have an internal implementation of TuRBO in Ax, but it's quite complex and optimized for a particular high-dimensional high-throughput asynchronous optimization problem (hundreds of parameters, tens of thousands of evaluations, with high parallelism).

We are in the process of refactoring this, and we hope to be able to generalize this enough so we can make it available as part of Ax. I don't have a great timeline for this, but we should be able to give a status update on this in a few weeks from now.

**Comment by Mita2049** [comment]
Hi, are there any updates on this? Given that TuRBO has been implemented in Botorch, are there any specific reasons why porting it to Ax could be challenging? Thank you for all your work on both packages!

**Comment by lena-kashtelyan** [comment]
Hi, @Mita2049! Unfortunately we don't have an update on this yet. There is active work on TRBO in Ax open-source, but it's unfinished and not currently highest-priority.

**Comment by Balandat** [comment]
We're hoping to OSS it by the end of September, but as Lena said it could take a bit longer. We have a working version, but we want to take a step back and revisit the design to make sure it's solid rather than putting out a janky version :).

**Comment by eytan** [comment]
In the meantime, @Mita2049, @winf-hsos, you might want to try out SAASBO (https://arxiv.org/pdf/2103.00349.pdf), which outperforms TuRBO on a number of high-dim BayesOpt tasks, and is now currently supported in Ax:
https://github.com/facebook/Ax/blob/main/tutorials/saasbo.ipynb

**Comment by Mita2049** [comment]
@lena-kashtelyan @Balandat @eytan Thank you very much for chiming in, and apologies for the late reply! Appreciate the context behind the integration of TuRBO into Ax - it seems you've made all the right decisions :)

I did try SAASBO with Ax 0.2.1 and Botorch 0.5.0, but ended up with the same problem as mentioned here: https://github.com/facebook/Ax/issues/682. I just noticed Botorch 0.5.1 came out, can I assume that the problem has been fixed? (My setup is somewhat complicated and so I'm not just a simple `pip install botorch==0.5.1` away from testing this myself :) )

Thanks again for your continued work and support of these two libraries!

**Comment by Balandat** [comment]
Yes the problem has been fixed and things should work on BoTorch 0.5.1 with the latest Ax `main` branch. We are also planning to put out a new Ax release this week, which will resolve this issue without having to resort to  doing the dev install.

**Comment by lena-kashtelyan** [comment]
Work on getting TRBO into open-source has been delayed for now, so sending this back to the wishlist for now.
