### ISSUE TITLE
Outcome constraints and feasible points

### ISSUE THREAD

**Issue by IgorKuszczak** [facebook/Ax#483]
Hello, 
I am using Ax's Loop API for a minimum weight design of a truss structure with two black-box constraints - one relating to maximum allowed deflection and another for the maximum allowed stress.  To set up the optimizer, I followed the Loop API Tutorial  (https://ax.dev/tutorials/gpei_hartmann_loop.html) and I have some doubts about how the `outcome_constraints` option works. The optimization part of my code is as follows.
```
# Optimization routine 
up_bound = 0.05
lo_bound = 0.001
    
# Parameters are defined as a list comprehension
params = [{'name':'x{}'.format(i),
           'type': 'range',
            'bounds': [lo_bound, up_bound],
            'value_type': 'float'
            } for i in range(1,11)]
    
def eval_func(parametrization):
        x = np.array([parametrization.get(f'x{i}') for i in range(1,11)])
        
        mass, S_max, U_max = sim.get_results(x)
        
        return {'mass': (mass, 0.0), 's_max': (S_max, 0.0), 'u_max':(U_max, 0.0)}

 best_parameters, values, experiment, model = optimize(
        parameters= params,
        experiment_name='test_run',
        objective_name='mass',
        evaluation_function=eval_func,
        minimize=True, 
        outcome_constraints=['s_max <= {}'.format(sim.target_S),'u_max <= {}'.format(sim.target_U)], 
        total_trials=30,
        )

```
The code runs correctly and I am able to retrieve `best_parameters`. My doubt arises, when I get the optimal objectives from the `means` variable defined as:
```
means, covariances = values
```
and compare them to the mass values on a convergence plot where I use:
```
best_objectives = np.array([[trial.objective_mean for trial in experiment.trials.values()]])
 y = np.minimum.accumulate(best_objectives, axis=1)
```
The last mass value in `y` is significantly lower than the one in `means` and I do not understand why that is the case. Does the point in `means` correspond to the last feasible point evaluated (according to outcome `outcome_constraints`)?

**Comment by sdsingh** [comment]
Hi there! 
Here's my current understanding of your issue:
The point obtained by optimizing `objective_mean` across trials yields a _better_ objective value than the point returned by `optimize`. 

To directly answer your question: `means` returns a feasible point, but not the last feasible point. Rather, it returns the _best_ feasible point, taking `outcome_constraints` into consideration. 

Overall, the result you are seeing seems expected to me. If you added the `outcome_constraints`, and fetched that data as well via `get_metric_mean` on the trial, I think you'd be able to clearly visualize the result you're seeing from `optimize`. 

Hope that helps!
