### ISSUE TITLE
Multi-task with laboratory experiments

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#490]
Hi, 

I have been trying to use Ax for laboratory experiments optimization with the multi-task tutorial. 
I have an offline metric written in python like the one in the tutorial but the online one need several days so I can't use an automatic loop.

After the candidate generation for online problem, I must stop ax, add the results for each candidate manually and restart ax. 

I think it may be similar to human in the loop. Can you help me to find steps in Multi-task that must be modified ? 
 
Thanks a lot,

**Comment by sdsingh** [comment]
Hi there! 

I think you're definitely on the right track by following the human-in-the-loop tutorial. High-level, the main change 
necessary to the MT tutorial is to save the experiment after online experiment launch. When you're ready to come back with experiment results, you will need to load the experiment and continue the loop. 

The online experiments are launched in step 1 and step 6 of the block here: https://fburl.com/n6xy5uif
The particular line for running, within that code block, is `tr.run()`

This is the API for saving: https://fburl.com/u0fptzl9, and for loading: https://fburl.com/95eq7m98. 
There are also SQA equivalents, documented on the same page, with the same names!

From there, you just need to break the `for` loops, and run the inner BO loop one step at a time, as you get results from your online experiments.

**Comment by Kh-im** [comment]
Thanks for your comment, I think, it's working. I am going to do more tests.

Regards
