### ISSUE TITLE
What Acquisition Function does Ax use in Bayesian Optimization and is there a way to customize it?

### ISSUE THREAD

**Issue by viiids** [facebook/Ax#492]
I am trying to test a new Acquisition Function which I believe will improve the performance of my search. Is there a way to use a customer Acquisition Function with the existing underlying surrogate model?

**Comment by mkhan037** [comment]
You can take a look at the botorch tutorial for [customizing an acquisition function](https://botorch.org/tutorials/custom_acquisition).

**Comment by lena-kashtelyan** [comment]
Hi, @viiids! We use Noisy Expected Improvement acquisition function by default, more on this here: https://ax.dev/docs/models.html#gaussian-process-with-ei. It's definitely possible to customize the acquisition function; the BoTorch tutorial @mkhan037 links above should help, and also https://github.com/facebook/Ax/issues/363 is a relevant discussion, as we are adding new abstractions in Ax to facilitate this (currently in alpha-mode, please provide feedback!).

**Comment by lena-kashtelyan** [comment]
I'm going to close this as answered, but please feel free to reopen if you have follow-up questions (or direct them to #363 if they are about the new abstractions we are adding for acquisition function and surrogate model customization), @viiids!

**Comment by viiids** [comment]
Thank you @lena-kashtelyan and @mkhan037. I think I got what I needed for now.
