### ISSUE TITLE
How to run complex trial evaluations in Ax (when a given parameterization is not just evaluated via one function in notebook)

### ISSUE THREAD

**Issue by justinkterry** [facebook/Ax#498]
The function which I'm evaluating can't just pass "parameterization" to a net function like in pytorch, it has to take elements of the parameters list and send them to various locations. This is presumably a reasonably normal use case, but I don't believe you document how to do this anywhere.

**Comment by lena-kashtelyan** [comment]
@justinkterry, have you looked over our tutorials? It's hard to understand the issue you are running into without more specificity in your request. If you are referring to this tutorial: https://ax.dev/tutorials/tune_cnn.html, then the evaluation function there (simple example shown in this cell: https://ax.dev/tutorials/tune_cnn.html#2.-Define-function-to-optimize) could be any arbitrary function that sends the elements of the parameter dict wherever it needs to, and then collects the metric outputs. If your trials take a long time to run and/or are fairly complex to deploy (not just some evaluation runs done in a notebook), check out our Service API –– here is the tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html.

**Comment by justinkterry** [comment]
So I have looked through your tutorials. The other question was because I missed something, but I think this one is somewhat legitimate.

The answer to my question after referring to source was just that the parameterization is a dictionary keyed by the parameter names in create experiment. This is useful knowledge if the function you're searching needs to take individual parameters and do things with them, which seems like a normal thing to me at least. E.g. this code snippet:

```
def train(parameterization):
    letters = string.ascii_lowercase
    folder = ''.join(random.choice(letters) for i in range(10))+'/'  # user hyperparameters instead of random string?
    env = make_env(parameterization['n_envs'])
```

In the tutorial you reference for instance you ultimately just pass `parameterization` off to the PyTorch train function (which doesn't tell you a ton) and don't explain what the object is (e.g. it could be some sort of tuple structure, etc.). My codes working now so it's not a big deal for me, but it seems like something fairly normal to do and would've saved me referring to source.

**Comment by lena-kashtelyan** [comment]
@justinkterry, good to know, I'll note this in our list of planned improvements to the docs : )
