### ISSUE TITLE
How to save Ax objects

### ISSUE THREAD

**Issue by justinkterry** [facebook/Ax#500]
The hyperparameter run I intend to use will run for a very long time, so I would need to just save the ax object so that I can do things like generate plots and use the .get_best_parameters() method later. The documentation/examples don't specify anything about this (and perhaps should?); should I just use cloud pickle like I normally would or is there subtly here that I need to be aware of?

**Comment by lena-kashtelyan** [comment]
@justinkterry, which API are you using? If you are using the Service API, the this section of the tutorial will walk you through the storage practices for storage 1) to SQL backend or 2) to a JSON file.

**Comment by justinkterry** [comment]
I missed this, my apologies.
