### ISSUE TITLE
Cannot install 0.1.20 through pip

### ISSUE THREAD

**Issue by LukeAI** [facebook/Ax#512]
```
pip install --upgrade ax-platform==0.1.20
ERROR: Could not find a version that satisfies the requirement ax-platform==0.1.20
ERROR: No matching distribution found for ax-platform==0.1.20
```
0.1.20 release does appear on [pypi](https://pypi.org/project/ax-platform/) but I can't install it. Could this be because wheels aren't provided for my OS (ubuntu 16.04) ?

I try manually installing the wheel
```
pip install --upgrade ax_platform-0.1.20-py3-none-any.whl
```

and it fails requiring botorch==0.4.0

UPDATE:
turns out that botorch==0.4.0 requires min version python 3.7 - I am using 3.6.9, so I think this is the root problem.

If this requirement can't be relaxed, maybe it would be worth adding to the README that minimum python 3.7 is required for the latest release?

**Comment by ldworkin** [comment]
Hi @LukeAI ! Yea, the Python 3.7 requirement is a strict one. We do mention this right on the README here: https://github.com/facebook/Ax#requirements. Is there somewhere else we could put that warning that would make it more visible?

**Comment by LukeAI** [comment]
um.. no that's very clear. thankyou.
