### ISSUE TITLE
[Question] Deleting/Clearing old experiment data from SQL Storage

### ISSUE THREAD

**Issue by kjanoudi** [facebook/Ax#524]
As the database backing all experiments grows in size, each trial takes longer to generate. After a few hundred experiments are created, trials begin taking exponentially longer to generate due to the large amount of data stored in the SQL database. Deleting the database and creating a new one results in extremely snappy performance again. Is there a way to delete a single experiment and all it's data from the database without deleting the entire database?

**Comment by sdsingh** [comment]
Hi there! 
To answer your immediate question, the experiment and its dependencies can be deleted via SQLAlchemy directly. Here is a sample snippet:

```
from ax.fb.storage.sqa_store.db import init_engine_and_session_factory
from ax.storage.sqa_store.db import session_scope

init_engine_and_session_factory(echo=True)

with session_scope() as session:
    exp_name = 'EXP_NAME'
    exp = session.query(SQAExperiment).filter_by(name=exp_name).one_or_none()
    session.delete(exp)
    session.flush()
```

@kjanoudi, long-term we are working on improving the performance of the storage layer to prevent this problem. @lena-kashtelyan is working on that project, but it is a ways off, so one-off deletion is probably best for now.

**Comment by kjanoudi** [comment]
Thanks!
