### ISSUE TITLE
[Feature Request]: managed loop - add a callback capability

### ISSUE THREAD

**Issue by jultou-raa** [facebook/Ax#552]
Is-it possible to add an argument to the managed loop service so that for each loop we can call a function to retrieve some customized information ?

**Comment by Jakepodell** [comment]
Hi!

Would you be able to provide more information about what you are trying to accomplish with the callback/ what information you are trying to retrieve?

Also, have you tried using the [Service API](https://ax.dev/docs/api.html), which offers more manual control between iterations?

Best,

Jake

**Comment by jultou-raa** [comment]
Hi Jake !

Thanks for your interest.

I would like to use progress information to update a progress bar into a software UI.

I thought about the service API. I think it can do the trick for my needs. But as the managed loop is designed to be very easy to use, I thought it can be very interesting to have this feature inside.

**Comment by Jakepodell** [comment]
Hi,

Thats a great idea, but I think for now we would just recommend using the service API for that use case. If that doesn't work for any reason, feel free to reach back out!
