### ISSUE TITLE
Setting custom BoTorch objective in Ax

### ISSUE THREAD

**Issue by alantwm** [facebook/Ax#556]
Hello. Thank you for the excellent work.
I have a question regarding how one would specify custom objectives within the Ax framework. For example, say I had a multi-objective problem and wanted to calculate the distance to some predefined target, or perhaps transform my objectives in some other way. How would I go about doing this? If I define a custom metric that is some combination of objectives, then I would not have access to those particular outputs in order to apply outcome constraints, correct? 

In BoTorch, I see that you can define custom objectives (e.g. using the GenericMCObjective), but I don't see that option exposed in Ax. 

Have I simply missed something?
Thank you very much!

**Comment by lena-kashtelyan** [comment]
Hi @alantwm, I think you might have interest in https://github.com/facebook/Ax/issues/363 where we discuss some beta-functionality we added recently –– an improved interface between Ax and BoTorch that lets folks combine BoTorch components in Ax more easily. There is a tutorial linked there: https://github.com/facebook/Ax/blob/master/tutorials/Setup_and_Usage_of_BoTorch_Models_in_Ax.ipynb, too.

For specifying a custom objective, some useful examples could be (I recommend reading through the tutorial on the setup before looking at specific pointers to understand the role of new model components and how to use them):
- `MOOAcquisition`: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_modular/moo_acquisition.py#L37,
- overriding `_get_botorch_objective` like `MOOAcquisition` does: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_modular/moo_acquisition.py#L134, 
- checking out where `_get_botorch_objective` is used in base `Acquisition` class: https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_modular/acquisition.py#L143.

Hopefully this helps! This new functionality will soon have better documentation and be featured on our website –– just a few outstanding things to attend to on our side. Until then, please follow up with any questions or feedback in this issue or in #363!

**Comment by alantan-SQ40** [comment]
Thank you very much for the reply! I'll take a close look at those links you provided.

**Comment by alantan-SQ40** [comment]
I looked at the code and it seems very promising. Thanks again for the help.

I have an additional question. In my use case, I would like to optimize towards a particular point in the objective space. So, I would like to pass targets into the objective function so I could, for instance calculate the l2norm between Y and the target. However, passing appropriately normalized targets into the Acquisition class is proving to be challenging. I'm currently exploring creating subclasses for the Acquisition class, and TorchModelBridge class.

Am I approaching the problem incorrectly? Is there an easier way I'm missing?

Thanks again!

**Comment by alantwm** [comment]
Thank you very much for your help.
I have an additional question. In my use case, I would like to optimize towards a particular point in the objective space. Therefore, I would like to pass a set of targets to the custom objective so that I could, for instance, calculate the L2Norm between Y and the appropriately normalized targets. Additionally, I would like to retain the flexibility of being able to apply outcome constraints to individual objectives. However, from looking at the botorch_modular code, there does not seem to be an easy way to pass the targets to the Acquisition class. Currently, I'm exploring subclassing the Acquisition class and the TorchModelBridge class.

Am I approaching the problem wrong? Is there an easier way I'm missing?

Thanks again!

**Comment by alantwm** [comment]
Another question. In the notebook you linked: https://github.com/facebook/Ax/blob/master/tutorials/Setup_and_Usage_of_BoTorch_Models_in_Ax.ipynb, the DEFAULT_ACQUISITION_OPTIONS include "best_f" for qExpectedImprovement. Running the code, I find "best_f" in the qEI function unaltered. For example, if I specify the number -22225 in "best_f" in the definition of the DEFAULT_ACQUISITION_OPTIONS , that is the number that appears in the qEI function (under self.best_f). I'm curious how I should properly specify this number?

Thanks!

**Comment by lena-kashtelyan** [comment]
@alantwm, that may be a bug, let me look into it!

**Comment by lena-kashtelyan** [comment]
@alantwm, we recorded this bug for fixing in upcoming sprint we are planning for the modular `BoTorchModel` setup. Once that is done, we will publish two tutorials on the website and make a designated issue for discussion of it. In the meantime, I'll close this issue so we can centralize all the discussion of the setup in #363, but please know that the bug you reported is noted and will be fixed.
