### ISSUE TITLE
Ax installation upgrades pytorch version

### ISSUE THREAD

**Issue by mohammadbashiri** [facebook/Ax#563]
Hi, I am trying to install Ax on my machine (ubuntu), but it keeps upgrading the torch version which is something I would like to avoid. Version of Pytorch I have installed is 1.7.0, but Ax requires >=1.7.1 and ends up installing Pytorch 1.8.0. Is there away I can avoid the upgrade of pytorch while installing one of the recent versions of Ax?

**Comment by Balandat** [comment]
So the >=1.7.1 requirement comes from botorch (https://github.com/pytorch/botorch/blob/v0.4.0/setup.py#L84). It seems like the minor 1.7 -> 1.7.1 bump to pytorch shouldn't cause any major issues, so one thing you can do is just manually upgrade pytorch to 1.7.1 and then install ax (b/c the 1.7.1 req will be satisfied this shouldn't upgrade to pytorch 1.8). 

Alternatively I think 1.7.1 is technically not strictly required by botorch 0.4.0, so if you're adventurous you could hack this by
1. getting the source of botorch 0.4.0
2. manually editing the req in the line above to 1.7
3. installing botorch from the local modified source
4. installing ax

**Comment by mohammadbashiri** [comment]
@Balandat thanks for the prompt response. 
You are right, it shouldn't be an issue to upgrade from 1.7.0 to 1.7.1. 
If it turned out it is an issue, I'll go for the adventurous solution.
