### ISSUE TITLE
Question : Multi-task with multi-objective

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#564]
Hello,

I'm looking to do multi-objective optimization with multi-task problem, exactly as if you merge multi-task bayesian optimization tutorial with multi-objective optimization tutorial. Is it possible with the current API ? What step should be taken ?

Thanks!

**Comment by Balandat** [comment]
So fundamentally this is possible in the modeling layer. I don't think there is anything pre-canned defined as a high-level entry point, but this should be relatively straightforward to do with the new modular BoTorchModel setup (cc @lena-kashtelyan). I know that @sdaulton has run multi-task multi-objective optimization in the past.

**Comment by lena-kashtelyan** [comment]
Hi, @Kh-im! As @Balandat noted above, this should be very doable with a new beta-setup we have for `BoTorchModel` in Ax. There is information on it and a beta tutorial in this issue: https://github.com/facebook/Ax/issues/363, but we are also actively working on improving/debugging the setup and in a few weeks we will publish two tutorials on it on the website and open a designated issue for folks to ask questions about it.

**Comment by lena-kashtelyan** [comment]
I'm going to close this one and move the discussion to #363 so we have it centralized : ) Feel free to comment there or ask any questions, @Kh-im!

**Comment by Kh-im** [comment]
Thanks for the details. Ok :)

**Comment by sdaulton** [comment]
FWIW, using multi-task models with qEHVI supported in Ax by specifying the proper Transforms. For example in the tutorial, if there were a task parameter in the search space , then

```
ehvi_model = get_MOO_EHVI(
    experiment=ehvi_experiment, 
    data=ehvi_data,
)
```
would just need to be replaced with
```
from ax.modelbridge.registry import Models, ST_MTGP_trans
ehvi_model = Models.MOO(
    experiment=ehvi_experiment, 
    data=ehvi_data,
    transforms=ST_MTGP_Trans,
)
```
if the experiment is a Single Type Experiment or 
```
from ax.modelbridge.registry import Models, MT_MTGP_trans
ehvi_model = Models.MOO(
    experiment=ehvi_experiment, 
    data=ehvi_data,
    transforms=MT_MTGP_Trans,
)
```
if the experiment is a Multi-Type Experiment.
