### ISSUE TITLE
Number of SOBOL Steps vs GPEI Steps

### ISSUE THREAD

**Issue by kjanoudi** [facebook/Ax#577]
Is there anywhere that provides a better understanding as to how many sobol steps to run? I have an expensive function that only needs to optimize for two parameters, but each run can take 1-2 minutes. I'm experimenting with using fewer or more sobol steps, but can't seem to find the "magic" combination. Does anyone have insights on how to determine each?

Does more (50+, 100+) sobol steps lead to better GPEI/Botorch results later in the experiment? Or am i better off using the usual 2 sobol steps per input (4 total) sobol steps, then more GPEI?

Thanks

**Comment by eytan** [comment]
Hi @kjanoudi, unfortunately it's hard to come up with a straightforward answer to this, as this is going to be very problem dependent.  More Sobol points could hurt or help depending on the specific problem (for example, if the response surface is more or less smooth in regions around the global optima), but we have found that a minimal number like 2*num_inputs or 3*num_inputs works reasonably well, particularly if the noise isn't too high.  If there is a lot of noise in the data then using something like 5*d or as much as 10*d could be helpful for estimating the Gaussian process kernel hyperparameters (as to figure out if the response surface changing very rapidly, or is the data just noisy).

**Comment by lena-kashtelyan** [comment]
@kjanoudi, while as @eytan suggests above, more or less Sobol points can help or hurt depending on the problem specifics, we found that empirically 5 Sobol points works well with total intended trials in optimization around 25-30. So 5 Sobol points + 20-25 GPEI points often works well with search spaces that have not too many parameters.

Feel free to reopen the issue if you need more help!

**Comment by sgbaird** [comment]
An example of comparing number of initialization points [[article](https://www.sciencedirect.com/science/article/abs/pii/S0927025622002610)] [[preprint](https://chemrxiv.org/engage/chemrxiv/article-details/640198a363e8d44e59488465)] [[code](https://github.com/sparks-baird/crabnet-hyperparameter)]

In this case, the difference between 10 initialization vs. 46 initialization trials, with 100 iterations in total, optimizing 23 hyperparameters, exhibited marginal differences.

https://matbench.materialsproject.org/Leaderboards%20Per-Task/matbench_v0.1_matbench_expt_gap/

![Image](https://github.com/user-attachments/assets/07128f34-6b97-4e26-918a-bc81d3391505)
