### ISSUE TITLE
The 'bleeding edge' is bleeding...

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#587]
Are you fully aware of the fact that the recommendations for installation of your 'bleeding edge' version from git
https://github.com/facebook/Ax#installing-from-git
don't work? The error message is:
<pre>
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  WARNING: Generating metadata for package Ax produced metadata for project name ax-platform. Fix your #egg=Ax fragments.
WARNING: Discarding git+ssh://****@github.com/facebook/Ax.git#egg=Ax. Requested ax-platform from git+ssh://****@github.com/facebook/Ax.git#egg=Ax has inconsistent name: filename has 'ax', but metadata has 'ax-platform'
ERROR: Could not find a version that satisfies the requirement ax (unavailable) (from versions: 0.1.0, 0.3.0, 0.4.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.20.0, 0.21.0, 0.22.0, 0.24.0, 0.27.0, 0.29.0, 0.31.0, 0.32.0, 0.34.0, 0.35.0, 0.36.0, 0.39.0, 0.40.0, 0.41.0, 0.42.0, 0.43.0, 0.44.0, 0.45.0, 0.46.0, 0.47.0, 0.48.0, 0.49.0, 0.50.0, 0.51.0, 0.52.0)
ERROR: No matching distribution found for ax (unavailable)
</pre>
Also, I started trying to install it from git, because apparently the PIPY version contains a bug in db.py file and doesn't execute even the simplest example from your page, however, the version in GitHub repo has this bug fixed...

**Comment by ldworkin** [comment]
Hi @alxfed ! Sorry you're having trouble installing our platform. Can you try

`pip3 install git+ssh://git@github.com/facebook/Ax.git#egg=ax-platform` and let me know if that works? It looks like in pip >= 20.3, things will fail if there's name mismatch (see discussion [here](https://github.com/pypa/pip/issues/9217), whereas this wasn't an issue in previous versions. We will update our docs.

For the db.py file bug, are you referring to https://github.com/facebook/Ax/issues/560? We'll get a fix out for that soon. It should still be possible to use much of the library without touching our storage code, though. Out of curiosity, what example was it failing on?

**Comment by alxfed** [comment]
Yes, that is what I meant.
Just of curiosity, I would like to know the name of the hero who did it. Can you let us know?

**Comment by ldworkin** [comment]
Haha, sorry I didn't follow -- the hero who did what?

**Comment by alxfed** [comment]
Who wrote and I quote:
`name_or_url=url`
in the call of SQLAlchemy function/object **create_engine()**
