### ISSUE TITLE
Can not save_experiment with a registered runner to SQA store

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#600]
With ax-platform 0.1.20 I created and registered a 'DummyRunner' exactly as in your example, 
<pre>
class DummyRunner(Runner):
    def run(self, trial):
        return {"name": str(trial.index)}
</pre>
but when I try to save a newly created experiment with this registered runner there is an error message like this:

{SQAEncodeError}"Cannot encode runner to SQLAlchemy because runner's subclass (<class 'abc.ABCMeta'>) is missing from the registry. The runner registry currently contains the following: <class 'ax.runners.synthetic.SyntheticRunner'>,<class 'app.src.runners.DummyRunner'>

So, it obviously is in the registry
If I don't register a runner everything saves like a breeze, which IMHO proves that everything else is working fine.

I'm not sure how to add the 'abc.ABCMeta' class to your registry... Is there a solution to this problem?

**Comment by lena-kashtelyan** [comment]
> Cannot encode runner to SQLAlchemy because runner's subclass (<class 'abc.ABCMeta'>) is missing from the registry

Interesting, let me look into this, something is clearly off. May I ask how you registered the runner? Was it like this?
```
from ax.storage.runner_registry import register_runner

register_runner(DummyRunner)
```

**Comment by alxfed** [comment]
As I said, I did. I created an Experiment, registered the runner (AND AS I SAID IT IS IN THE REGISTRY AS YOU CAN SEE FROM THE ERROR MESSAGE), then tried to save_experiment.

**Comment by lena-kashtelyan** [comment]
> I created an Experiment, registered the runner (AND, AS I SAID, IT IS IN THE REGISTRY AS YOU CAN SEE FROM THE ERROR MESSAGE), then tried to save_experiment.

I understood exactly what you said and read thought your error message. It just helps to know how someone got into a given situation, so I asked.

> It is an obvious bug, I was just being polite not naming it this way, not a 'question'.

It will be labeled accordingly once I had a chance to repro and verify that this is coming from the library and not a user error.

> Should I assign the experiment.runner it BEFORE registering the class? That would be pretty counterintuitive... (btw, just checked - makes no difference whatsoever).

You are right that it should not matter. We will look into this.

**Comment by alxfed** [comment]
ty

**Comment by lena-kashtelyan** [comment]
I think the issue is that you should've been setting `experiment.runner` to a runner _instance_ not a class, i.e. `experiment.runner = DummyRunner()`, ax exemplified here in the tutorial: https://ax.dev/tutorials/building_blocks.html#5.-Define-a-runner.

**Comment by alxfed** [comment]
ty
