### ISSUE TITLE
Is there a complete example of use for Encoder and Decoder?

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#603]
I mean: how to prepare the complete experiment with all bells and whistles, as OptimizationConfig, metrics property etc. with the help of ax.storage.sqa_store.encoder.Encoder then **save_experiment** after that **load_experiment** back with the help of ax.storage.sqa_store.decoder.Decoder?

I can not understand how to use these two classes in practice.

**Comment by ldworkin** [comment]
Hi @alxfed -- you actually shouldn't need to use ax.storage.sqa_store.encoder.Encoder or ax.storage.sqa_store.decoder.Decoder unless you're doing something quite custom. For the vast majority of use cases, just calling `save_experiment` and `load_experiment` should work, as described [here](https://ax.dev/docs/storage.html#sql). Is that not working as expected for you?

**Comment by alxfed** [comment]
Good morning, @ldworkin,
I have a couple of hundred custom metrics and a dozen custom runners. In order to store and retrieve any of them in an instance of an Experiment without an error message I have to register all of them every time I init_engine_and_session_factory (and before save_experiment or load_experiment call of course), so, pretty much after every API call to my microservice...
Tell me that there is a better way... please.

**Comment by lena-kashtelyan** [comment]
You could register them on some import by putting them at the top level in your file? For instance:
```
class MyRunner(Runner):
    ...

register_runner(MyRunner)
```

Would that do it?

**Comment by alxfed** [comment]
That's exactly what I do, but...

**Comment by lena-kashtelyan** [comment]
You could subclass the encoder for this, but you would still register things in the same way, just in the encoder. So I don't think it would make it much better and your current approach is likely the right one. 

There is a question of why you need so many runners and metrics –– perhaps they don't need to each have their own class, but rather could do something different depending on their inputs? But that's a separate issue and totally up to you, just wanted to flag that intuitively that feels confusing.

I'll close this, as I think the answers here are the best we can do for now. We are not planning full examples of encoder/decoder as they should not be necessary for most of our open-source users.

**Comment by alxfed** [comment]
to your question: because those are different ML models which I train and compare along the way too.

Please, let us know, when there will be an example of use for Encoder / Decoder.
