### ISSUE TITLE
documentation for optimize

### ISSUE THREAD

**Issue by kurtosis-dd** [facebook/Ax#604]
The `optimize` example on the main page makes it really easy to get started but I had to hunt around a bit to figure out how to set a parameter to be integer valued ("value_type"). Would be helpful to have a more detailed docstring, say.

**Comment by lena-kashtelyan** [comment]
Hi, @kurtosis-dd! There is actually a whole tutorial on it: https://ax.dev/tutorials/gpei_hartmann_loop.html, does that help? We'll add a link to the tutorial to the docstring of the function in that case.
