### ISSUE TITLE
Request: add `requirement.txt` for conda-forge compatibility

### ISSUE THREAD

**Issue by rpanai** [facebook/Ax#614]
Hi There,
I made a @conda-forge package for this (see [here](https://anaconda.org/conda-forge/ax-platform)). Now I have some problem with dependency in auto updating see [PR](https://github.com/conda-forge/ax-platform-feedstock/pull/1). Do you mind to add a requirement.txt?

**Comment by lena-kashtelyan** [comment]
Hi, @rpanai, we'll look into adding it next week!

**Comment by lena-kashtelyan** [comment]
Wishlisted
