### ISSUE TITLE
Reference to inaccessible page

### ISSUE THREAD

**Issue by alxfedotov** [facebook/Ax#635]
Is there a way to see what is on [this page](https://fburl.com/empirical_bayes) referenced on [this page](https://ax.dev/api/utils.html#ax.utils.stats.statstools.positive_part_james_stein) and in statstools.py ?

**Comment by Balandat** [comment]
Ah, somehow the reference to an internal page slipped in here, thanks for flagging.

No, there is no way to see that page. That said, there is nothing proprietary about the info on that page, so we should probably make that it's own page in the OSS docs and reference that instead.

**Comment by alxfedotov** [comment]
Thank you for the prompt response, Max.

Indeed. I think that would be helpful for many.

**Comment by Balandat** [comment]
Let's leave this open for tracking purposes.

**Comment by lena-kashtelyan** [comment]
Fix for this is now on master; the open-source doc that is an analogue fo the internal one is this: https://ax.dev/versions/latest/docs/models.html#empirical-bayes-and-thompson-sampling.

**Comment by lena-kashtelyan** [comment]
This is now fixed in latest stable version, 0.2.1.
