### ISSUE TITLE
Mistake in API documentation for `save_generation_strategy`

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#645]
There is a misleading phrase in the description of **save_generation_strategy()** function on [this page](https://ax.dev/api/storage.html#ax.storage.sqa_store.save.save_generation_strategy).

Namely, this description and I quote:"Save generation strategy (using default SQAConfig if no config is specified). If the generation strategy has an experiment set, the experiment **will be** saved first." suggests or at least implies that the experiment **will be saved** (without any action of the developer, 'automagically').

In reality (save.py line 125): f"Experiment {...} should be saved before "

I think the word **'must'** (be saved) would be totally appropriate in the description of the function... Just a suggestion.

**Comment by ldworkin** [comment]
Yup, good point! We might have changed the behavior and forgot to update the docstring.

**Comment by alxfed** [comment]
Just noticed, that because of this change in behavior the example on [page](https://ax.dev/tutorials/generation_strategy.html#3B.-SQL-storage) throws an error message.

**Comment by ldworkin** [comment]
Yep, this is fixed locally and will be out in the next release.

**Comment by alxfed** [comment]
I have yet another question here:
Is there any meaningful description of those 'fidelities' that can be used in Data as a str/json column?
Also, I would recommend at least mentioning 'n' somewhere for the people who deal with real samples of items.  If you don't know about its' existence you can not automatically combine the precious (I'm not joking, every new user is worth $100 now) new data with the precious old data. I found it only because Bakshy had this column in his data table on one of the slides during the event in May. In so many words the size of the sample 'n' is worth publicizing. :)

**Comment by lena-kashtelyan** [comment]
This is now fixed in latest stable version, 0.2.1.
