### ISSUE TITLE
Non-existing page referenced on website -> 404

### ISSUE THREAD

**Issue by pboes** [facebook/Ax#668]
Hey, this is just to quickly let you know that on "https://ax.dev/tutorials/" there is a link to the "Building Blocks of Ax" page that produces a 404. The problem is that in Ax/website/pages/tutorials/index.js you reference "building_blocks.html" but that file seems to no longer exist in the repo. Cheers

**Comment by danielcohenlive** [comment]
Thanks for pointing that out @pboes!

**Comment by lena-kashtelyan** [comment]
This has now been fixed on master and will be included in latest stable release (likely this or next week)

**Comment by lena-kashtelyan** [comment]
Stable version 0.2.2 is out now and takes care of this issue.
