### ISSUE TITLE
[Documentation] Link `Building Blocks of Ax` on https://ax.dev/tutorials/ points to 404 page

### ISSUE THREAD

**Issue by aivanou** [facebook/Ax#687]
The link in  `Building Blocks of Ax` (https://ax.dev/tutorials/building_blocks.html) on https://ax.dev/tutorials/ page points to non-existent page.

**Comment by lena-kashtelyan** [comment]
Hello @aivanou, this issue has been reported: https://github.com/facebook/Ax/issues/668 and the fix will be released with the next stable version, closing as duplicate.
