### ISSUE TITLE
Choice parameters fail

### ISSUE THREAD

**Issue by imbalu007** [facebook/Ax#688]
I am trying out Ax with a simple set of 'choice' parameters. Here is my script

```
from ax import optimize
best_parameters, best_values, experiment, model = optimize(
        parameters=[
          {
            "name": "x1",
            "type": "choice",
            "values": [-10, 0, 10],
          },
          {
            "name": "x2",
            "type": "choice",
            "values": [-10, 0, 10],
          },
        ],
        # Booth function
        evaluation_function=lambda p: (p["x1"] + 2*p["x2"] - 7)**2 + (2*p["x1"] + p["x2"] - 5)**2,
        minimize=True,
    )
```
During the 6th trial, I am getting this error
`TypeError: optimize_acqf_discrete() got an unexpected keyword argument 'num_restarts'`

Looks like mk_ehvi_default_optimizer_options() in ax\models\torch\botorch_modular\default_options.py is setting this argument. I am not sure why this error is occurring only in the 6th trial and not before that.

Following is my environment:
1. Python 3.8.11
2. ax-platform==0.2.1
3. botorch==0.5.0
4.  Windows 10

**Comment by Balandat** [comment]
This fails after the 5th trial because the default setting of the `optimize` API is to use 5 Sobol quasi-random points before switching to Bayesian Optimization. It should not fail though, this seems to be a bug on our end - cc @lena-kashtelyan

**Comment by imbalu007** [comment]
Thanks. Please let me know if you need any more info for resolution

**Comment by lena-kashtelyan** [comment]
Hi @imbalu007, this issue is fixed in BoTorch 0.5.1! Let me know if upgrading BoTorch doesn't fix this for you.

**Comment by imbalu007** [comment]
@lena-kashtelyan, thanks. I upgraded to BoTorch 0.5.1 and there are a couple of things
1. I am getting this warning from pip 
`ax-platform 0.2.1 requires botorch==0.5.0, but you have botorch 0.5.1 which is incompatible`
Looks like 0.2.1 is the latest ax-platform version.
2.  When I run the same code as above, I get this error
`ImportError: cannot import name '_set_transformed_inputs' from 'botorch.fit'`

Am I missing something?

**Comment by lena-kashtelyan** [comment]
Ah I see, we need to release a new version of Ax to fully resolve this. We should be able to do that today or tomorrow; our apologies for the inconvenience!

**Comment by imbalu007** [comment]
No problem. Please update when the fix is released and I will give it another try. Thanks!

**Comment by imbalu007** [comment]
@lena-kashtelyan , is there an update on the resolution?

**Comment by lena-kashtelyan** [comment]
We are working on the new release, it should hopefully be out within the next two days.

**Comment by lena-kashtelyan** [comment]
Stable version 0.2.2 is out now and takes care of this issue.
