### ISSUE TITLE
[bug] evaluate_acquisition_function of BoTorchModel incompatible with TorchModelBridge

### ISSUE THREAD

**Issue by alan-tan-wm** [facebook/Ax#692]
Hello,

I'm unable to use evaluate_acquisition_function when using BoTorchModel (botorch_modular) with the TorchModelBridge as described in the tutorials.
BoTorchModel.evaluate_acquisition_function requires arguments such as searchspacedigest, objective_weights, etc. However, TorchModelBridge._model_evaluate_acquisition_function only sends the parameters of the arms to be evaluated. Am I doing something wrong?

Thanks!

**Comment by lena-kashtelyan** [comment]
Hi  @alantan-SQ40, this is a known issue that came up as a result of a recent refactor. It will be fixed soon!

**Comment by alantan-SQ40** [comment]
Got it. Thx!

**Comment by lena-kashtelyan** [comment]
The fix is now part of the latest stable version: 0.2.3.
