### ISSUE TITLE
Feature request: fallback to hit-and-run sampler on rejection sampling errors

### ISSUE THREAD

**Issue by EvgenyZamyatin** [facebook/Ax#694]
It's work with a small(5 for example) number of parameters in the "parameter_constraints" option. But if the number of parameters for example 10, there is the error.
In my case "parameter_constraints" looks like "w_1 + w_2 + ... + w_10 <= 1", where  0 <= w_i <= 1.
The probability to satisfy the condition when we sample n-dimensional vector from U[0, 1] is 1/n!. That is a problem.
Could you please add a support of direct sampling from a simplex?

**Comment by Balandat** [comment]
Could you please provide a full stack trace so we can see exactly where this is happening?

FWIW, we do have a utility for sampling directly from a simplex (used e.g. here: https://github.com/facebook/Ax/blob/3f10ec92381b1f39b6ceae6220512442ad1b7355/ax/models/torch/utils.py#L549). However it doesn't seem to be hooked up to the top-level search space definition  - the challenges here is to infer from the parameter constraints that the feasible set is a simplex, without having another special argument for that. We could instead use a more generic hit-and-run polytope sampler, e.g. https://github.com/pytorch/botorch/blob/fd7bd523741895ba34e8447dad0c5b753bc72231/botorch/utils/sampling.py#L312

**Comment by EvgenyZamyatin** [comment]
> [INFO 09-17 10:04:13] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+GPEI', steps=[Sobol for 10 arms, GPEI for subsequent arms], generated 0 arm(s) so far). Iterations after 10 will take longer to generate due to model-fitting.
[INFO 09-17 10:04:13] ax.service.managed_loop: Started full optimization with 1000 steps.
[INFO 09-17 10:04:13] ax.service.managed_loop: Running optimization trial 1...
Traceback (most recent call last):
  File "/Users/e.zamyatin/vk/scala/feed_xgb/src/main/luigi/main.py", line 45, in <module>
    total_trials=1000)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/service/managed_loop.py", line 224, in optimize
    loop.full_run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/service/managed_loop.py", line 166, in full_run
    self.run_trial()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/service/managed_loop.py", line 145, in run_trial
    experiment=self.experiment
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/modelbridge/generation_strategy.py", line 235, in gen
    gen_run = model.gen(n=n, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/modelbridge/base.py", line 609, in gen
    model_gen_options=model_gen_options,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/modelbridge/random.py", line 92, in _gen
    rounding_func=transform_callback(self.parameters, self.transforms),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/models/random/sobol.py", line 118, in gen
    rounding_func=rounding_func,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/models/random/base.py", line 114, in gen
    existing_points=self.generated_points,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ax/models/model_utils.py", line 108, in rejection_sample
    f"Specified maximum draws ({max_draws}) exhausted, without "
ValueError: Specified maximum draws (10000) exhausted, without finding sufficiently many (1) candidates.

**Comment by Balandat** [comment]
The simplest thing to do would probably be to just catch that error (which should be a more specific error type, also seems like `ValueError` is not the right base error type here...) and retry with the `sample_polytope` hit-and-run sampler.

**Comment by EvgenyZamyatin** [comment]
Got it, thank you!
One more question: why do you use "gen_unconstrained" function which samples points from U[0, 1]xD instead of "sample_polytope" which can already generate "true" points?

**Comment by Balandat** [comment]
Two primary reasons:
(i) Legacy - this is what we started with.
(ii) Speed (in some cases): If the volume of the feasible set is reasonably large relative to the bounding box, then rejection sampling with large batches of uniform samples can be faster than running an iterative hit-and-run sampling algorithm.

**Comment by lena-kashtelyan** [comment]
For posterity, summarizing the solution @Balandat suggested:
1. Make a better more specific exception for the rejection-sampling error, 
2. Catch that exception, 
3. Run the `sample_polytope` function instead.

**Comment by sgbaird** [comment]
@EvgenyZamyatin any luck with a custom generation strategy?

**Comment by lena-kashtelyan** [comment]
@sgbaird, do you need help setting up the custom generation strategy? This comment: https://github.com/facebook/Ax/issues/694#issuecomment-951084270 should have all the information you need to make one, feel free to start a new issue if you are confused about how to make it (please let us know what you tried so far in it).

**Comment by sgbaird** [comment]
Since it's on master, first I [install the latest version](https://ax.dev/docs/installation.html) in a conda environment:
```
pip install 'git+https://github.com/facebook/Ax.git#egg=ax-platform'
```
The relevant imports are:
```python
from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
from ax.modelbridge.registry import Models
```
Then based on [1A. Manually configured generation strategy](https://ax.dev/tutorials/generation_strategy.html#1A.-Manually-configured-generation-strategy), I change the first `GenerationStep` `model_kwargs` from:
```python
model_kwargs={"seed": 999}
```
to
```python
model_kwargs={
    "seed": 999,
    "fallback_to_sample_polytope": True,
}
```
With the full generation strategy (`gs`) given by:
```python
gs = GenerationStrategy(
    steps=[
        # 1. Initialization step (does not require pre-existing data and is well-suited for 
        # initial sampling of the search space)
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3, # How many trials need to be completed to move to next model
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
            model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
        ),
        # 2. Bayesian optimization step (requires data obtained from previous phase and learns
        # from all data available at the time of each new candidate generation call)
        GenerationStep(
            model=Models.GPEI,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            max_parallelism=3,  # Parallelism limit for this step, often lower than for Sobol
            # More on parallelism vs. required samples in BayesOpt:
            # https://ax.dev/docs/bayesopt.html#tradeoff-between-parallelism-and-total-number-of-trials
        ),
    ]
)
```
Finally, in the case of this issue, and as mentioned:
```python
AxClient(generation_strategy=gs)
```
Or in the case of the Loop API:
```python
optimize(..., generation_strategy=gs)
```
Seems to work well for my use-case; thank you! I'll try to update the other relevant issues soon.

**Comment by lena-kashtelyan** [comment]
Fantastic, great to hear this worked for you @sgbaird! Thank you very much for posting this full example here, we really appreciate it!

**Comment by lena-kashtelyan** [comment]
The fix is now part of the latest stable version: 0.2.3.
