### ISSUE TITLE
[Question] Running Trials In Parallel

### ISSUE THREAD

**Issue by charliemarx** [facebook/Ax#695]
What is the recommended way to run trials in parallel? I am running a hyperparameter optimization task on a computing cluster and I want to run a few trials in parallel. It would be nice to be able to submit multiple jobs on different nodes while sharing results in a single database so that each job is aware of results generated from trials completed by the other jobs. Is there a recommended way to parallelize trials across separate jobs using Ax?

**Comment by Balandat** [comment]
@charliemarx Not sure if you mean to close this, but commenting here for posteriority. If you have control over the loop / the scheduling process, check out our `Scheduler` tutorial [here](https://github.com/facebook/Ax/blob/main/tutorials/scheduler.ipynb). If you don't have that control, then you could re-load a shared client from within the individual runs (but you'd have to be a bit careful about race conditions).
