### ISSUE TITLE
Data for Tracking Metrics stored in SQA store but not retrievable

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#696]
The Experiment.lookup_data_for_trial(trial_index=...) returns Data for metrics used in the optimization config only, not the Tracking Metrics even though their Data is being stored in the SQA store (data_v2 table) as a separate row. Is there a way to retrieve it from the SQA store (without a 'brute force' querying of the table of course)?

P.S. Attempts to lookup the Tracking Metrics (that are listed on the Experiment and stored in the database, of course ) for these COMPLETED trials return empty dataframes.

**Comment by lena-kashtelyan** [comment]
Hi @alxfed, would you mind trying `experiment.fetch_data()` and `experiment.fetch_data(tracking_metrics)`?

**Comment by alxfed** [comment]
Doesn't retrieve Tracking Metrics either. That's where I started.

**Comment by ldworkin** [comment]
@alxfed  can you provide a repro? These functions should definitely return data for tracking metrics, and I believe they do in most cases, so it's possible you're running into some edge case here!

**Comment by alxfed** [comment]
I can not jigsaw this from my code.
Also, fetch_data() works perfectly well for all the metrics including the Tracking Metrics while the trial is 'RUNNING' and until the trial is marked as COMPLETED and stored. After that - you can try... you can even provide the names _taken from the experiment metrics list_ in an iterable (to fetch_trials_data) the corresponding df's come empty.

**Comment by ldworkin** [comment]
If you can provide a lightweight repro (doesn't have to be the exact code you're running) we'd be happy to take a look! I know this works correctly for our internal usecases, so there must be some edge case you're hitting in your setup.

**Comment by alxfed** [comment]
fetching returns data from the cache only if the metrics are _not_ 'available while running'. Mine are 'available while running'.

**Comment by lena-kashtelyan** [comment]
Hi @alxfed! We just added a note to our README to clarify that for bug reports, we ask users to provide a minimal code snippet showing the issue. We'll be happy to look into this once we have one! Thank you.

**Comment by lena-kashtelyan** [comment]
We believe the fix for this should now be on master (with https://github.com/facebook/Ax/commit/6ebb79b488f1c253f60535b3dc67f040eb70c60d); we fixed an issue that we think could be resulting in this behavior, but of course cannot be 100% sure without the repro.
