### ISSUE TITLE
Better documentation for `evaluation_function`

### ISSUE THREAD

**Issue by HanGuo97** [facebook/Ax#71]
Thanks to the team for the great work! I would appreciate if documentation for arguments like `evaluation_function` could be provided more explicitly in the tutorials. It took me a while to figure out the function should return a (mean, stderr) tuple when the outcome is a dictionary (`https://github.com/facebook/Ax/blob/master/ax/core/types.py#L25`).

**Comment by kkashin** [comment]
Thanks for the feedback! We can make this more explicit in https://ax.dev/tutorials/gpei_hartmann_loop.html and https://ax.dev/tutorials/gpei_hartmann_service.html within the evaluation function sections. Would this make it clearer?

**Comment by HanGuo97** [comment]
Thanks! This would definitely help.

**Comment by lena-kashtelyan** [comment]
Better documentation is in on master. Please check out [section on evaluation function](https://github.com/facebook/Ax/blob/master/docs/runner.md#evaluation-function), @HanGuo97!
