### ISSUE TITLE
MOO with NaN outcomes

### ISSUE THREAD

**Issue by soerenjalas** [facebook/Ax#713]
Hi,
I have a multi-objective problem where one of the objectives is only defined when the other one is larger than 0. I'm using the service API and noticed that if I don't pass the NaN objective in these cases the model does not complain and in `exp_to_df` they show up as NaN as intended. 
I wanted to make sure that this is causing no unexpected behaviour. How are the NaNs handled in the model? Are they ignored?

Thanks for the great work!

**Comment by lena-kashtelyan** [comment]
cc @sdaulton and @Balandat for this one! 

And just to clarify, in this sentence:
> I'm using the service API and noticed that if I don't pass the NaN objective in these cases the model does not complain and in exp_to_df they show up as NaN as intended.

you meant "if I pass the NaN objective in these cases", correct? Not "if I don't pass..."? Just making sure we understand you fully.

**Comment by sdaulton** [comment]
Hmm having NaNs in the data should certainly cause issues if you are using Bayesian optimization because I do not believe we do any filtering of NaNs. Are you using Sobol search? Can you share an example?

**Comment by Balandat** [comment]
It may also be the case that there is just no data passed and the NaNs simply show up when calling `exp_to_df`. On the modeling end that could just result in a ModelList under the hold with a different number of observations for different objectives.

**Comment by soerenjalas** [comment]
Sorry, I should have given an example to begin with. So here a small reproducer using np.random as objectives

```python
ax_client = AxClient()
ax_client.create_experiment(
        name='test',
        parameters=[
            {
                "name": "x1",
                "type": "range",
                "bounds": [0., 1.],
            },
            {
                "name": "x2",
                "type": "range",
                "bounds": [0., 1.],
            },
        ],
        objectives={
    # `threshold` arguments are optional
    'f1': ObjectiveProperties(minimize=False, threshold=0.5), 
    'f2': ObjectiveProperties(minimize=False, threshold=0.5)
    })

for i in range(10):
    # configurations where f1 and f2 are defined (random for testing)
    para, trial = ax_client.get_next_trial()
    ax_client.complete_trial(trial, {'f1':np.random.rand(), 'f2':np.random.rand()})

# point where only f1 has a defined result
para, trial = ax_client.get_next_trial()
ax_client.complete_trial(trial, {'f1':0})  

# continue with normal results
for i in range(3):
    # configurations where f1 and f2 are defined (random for testing)
    para, trial = ax_client.get_next_trial()
    ax_client.complete_trial(trial, {'f1':np.random.rand(), 'f2':np.random.rand()})
```

For me this runs without causing any obvious errors. The resulting `ax_client.get_trials_data_frame()` then looks like this:

	trial_index	f1	f2	arm_name	x1	x2	trial_status	generation_method
						
	0	0.142490	0.764766	0_0	0.444212	0.750662	COMPLETED	Sobol
	1	0.003357	0.107010	1_0	0.728347	0.381416	COMPLETED	Sobol
	2	0.033787	0.260226	2_0	0.879503	0.681396	COMPLETED	Sobol
	3	0.300835	0.536247	3_0	0.434606	0.935327	COMPLETED	Sobol
	4	0.796099	0.147013	4_0	0.557067	0.284050	COMPLETED	Sobol
	5	0.582075	0.128140	5_0	0.176017	0.642988	COMPLETED	MOO
	6	0.364672	0.392250	6_0	0.231844	0.000000	COMPLETED	MOO
	7	0.610980	0.288289	7_0	0.000000	1.000000	COMPLETED	MOO
	8	0.556442	0.564593	8_0	0.307306	0.275758	COMPLETED	MOO
	9	0.170643	0.114691	9_0	0.384656	0.440409	COMPLETED	MOO
	10	0.000000	NaN	10_0	0.219750	0.214369	COMPLETED	MOO
	11	0.844927	0.667551	11_0	0.469838	0.000000	COMPLETED	MOO
	12	0.676797	0.106539	12_0	0.565742	0.000000	COMPLETED	MOO
	13	0.110780	0.736512	13_0	0.415839	0.000000	COMPLETED	MOO


I looked at the model that is used in this case and I think @Balandat is right: here it ends up using ModelListGP with two SingleTaskGPs. Whereas, when all data is there its just a SingleTaskGP. 
I take it that this is maybe not the behaviour that I hoped for and I'm probably better of setting the undefined objective to some arbitrary (non-optimal) real value, correct? Or how is EHVI dealing with the ModelListGP?

Thanks a lot!

**Comment by Balandat** [comment]
Is the fact that one of the objectives is not defined indicative of some failure / does it mean that you would not consider the associated parameterization viable? If not then I don’t see any issue with the current behavior, seems like this is what you’d want to happen.

**Comment by soerenjalas** [comment]
For my kind of problem you can think of f1 as the integral of some signal and f2 as the width of that signal. Obviously if the function is zero everywhere it does not make sense to define a width (unless its infinity). So yeah the data is consistent in that sense. How can I then image the outcome of the ModelListGP? Does it look the same as the multi-output SingleTaskGP?

**Comment by soerenjalas** [comment]
Okay, thanks for the explanation!
