### ISSUE TITLE
Is there a designed routine for ax to do Bayesian Optimizatio on exists experiment data?

### ISSUE THREAD

**Issue by solensolen** [facebook/Ax#714]
I used the **Service API** 5 times to tune parameters. 
Every time it gen and finish 20 trails.

As I got 5*20=**100 examples**, I want to combine them to make **one Bayesian Optimization process** to see how the parameters go. 
And use ax to plot result to analsis.

Alread get data as ({par:.....}, {'metric':}) pairs.

Through the doc, I haven't  find a routine to go this way. 

I tried **ax_client.attach_trial(),** it seems to add existing data, but still need to run sobol steps to triggle BO.

Is there a designed routine to do it? Or I just have to walk through the **developer api** then find a way?

Any tips? Thx ^_^b

==========================================

And already know that it has N3 complexity.  I think botorch with gpu can handle.

**Comment by lena-kashtelyan** [comment]
Hi, @solensolen! `ax_client.attach_trial` is indeed the way to go in this case, just remember you will also need to do `ax_client.complete_trial` to add data for those trials. 

If you want to skip the Sobol phase, you will need to specify a custom generation strategy, but that's easy to do. Just do this (to learn more about generation strategy and how to construct custom ones, you can read through [this tutorial](https://ax.dev/tutorials/generation_strategy.html):
```
from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
from ax.modelbridge.registry import Models

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.GPEI,
            num_trials=-1,
        ),
    ]
)

ax_client = AxClient(generation_strategy=gs)
ax_client.get_next_trial()  # Must generate a trial for Ax to instantiate the GPEI model which will be used for plotting
# Now you can plot!
```

**Comment by solensolen** [comment]
> Hi, @solensolen! `ax_client.attach_trial` is indeed the way to go in this case, just remember you will also need to do `ax_client.complete_trial` to add data for those trials.
> 
> If you want to skip the Sobol phase, you will need to specify a custom generation strategy, but that's easy to do. Just do this (to learn more about generation strategy and how to construct custom ones, you can read through [this tutorial](https://ax.dev/tutorials/generation_strategy.html):
> 
> ```
> from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
> from ax.modelbridge.registry import Models
> 
> gs = GenerationStrategy(
>     steps=[
>         GenerationStep(
>             model=Models.GPEI,
>             num_trials=-1,
>         ),
>     ]
> )
> 
> ax_client = AxClient(generation_strategy=gs)
> 
> for _ in range(...):  # Attach trials from your previous experiments
>     ax_client.attach_trial(...)
>     ax_client.complete_trial(...)
> 
> ax_client.get_next_trial()  # Must generate a trial for Ax to instantiate the GPEI model which will be used for plotting
> 
> # Now you can plot!
> ```

This is just the solution I want.

Have tried it , and it woks.
4parameters, 100trails, it takes cpu 15s to process,

Thank you for the tip!

================================================================

I compared several opensource hyper tuning tools, as far as I can understand, 
AX is designed for more advanced use. 
Glad it also has so good community support.

After this porject onhand finishes, I will try to deep into developer API.

**Comment by lena-kashtelyan** [comment]
> I compared several opensource hyper tuning tools, as far as I can understand,
AX is designed for more advanced use

We definitely want Ax to serve both the advanced and the simple use –– always feel free to open an issue if it doesn't seem like the simple use-case is supported : )
