### ISSUE TITLE
Limits on number of parameters, metrics, etc

### ISSUE THREAD

**Issue by aaditya8959** [facebook/Ax#715]
Hi. Are there any limits on the number of parameters, metrics, parameter constraints, metric constraints that can be handled by the Bayesian optimization functionality? If so, is there someplace in the docs I can look for this information?

**Comment by lena-kashtelyan** [comment]
Hi @aaditya8959, there is some info on that on this page: https://ax.dev/docs/models.html.

For standard Bayesian optimization (so [GPEI](https://ax.dev/docs/models.html#gaussian-process-with-ei) for single-objective case and [GP+NEHVI](https://ax.dev/tutorials/multiobjective_optimization.html) for multi-objective, which will be performed by Service API, for example):
1. for number of parameters, I believe up to 20 should work,
2. for metrics, it depends on whether they are objective, constraint, or just tracking metrics; for objectives, note that having more than one means we do multi-objective optimization, which has different limitations –– the default implementation can handle up to 5 I believe,
3. for parameter constraints, it's hard to say specifically –– I believe if they are not hard to meet (so if it's not a very small region of the search space that is left to be "feasible" by those constraints –– you can have as many as parameters,
4. for outcome (metric) constraints, I'm not 100% sure.

Tagging @Balandat and @danielrjiang to check me on these and add information on number of outcome constraints we can handle/

**Comment by aaditya8959** [comment]
Thank you. For the number of parameters even though upto 20 is advised in the link, is there functionality for handling more than those many parameters? Similarly for parameter constraints? Mainly, is there a hard limit in the functionality beyond which the number of parameters or constraints cannot be increased, irrespective of the problem?

**Comment by Balandat** [comment]
These are no hard limits in the sense that they don’t raise Exceptions or are explicitly unsupported. It’s just more likely that the model fits will be terrible or that the candidate generation will take forever.  As Lena said, I’d you’re interested in a large number of parameters then SAASBO is a good thing to try. 

For outcome constraints it also depends on how tight they are. If you have lots of tight outcome constraints then you need to model a lot more outputs and optimization gets harder, so things will probably take a really long time to run.

**Comment by lena-kashtelyan** [comment]
@aaditya8959, let us know if this discussion did not fully answer your question! If you do have follow-ups, please reopen this issue to make sure we see your follow-up.
