### ISSUE TITLE
How do I implement python's function based constraints in Ax?

### ISSUE THREAD

**Issue by tousifahmed54** [facebook/Ax#720]
I have an optimization problem formulated using python's scipy.optimize library. Currently using the SLSQP method for the minimization process. I am planning to use AX optimize for the same problem to see if I get better results (i.e., quicker convergence or overall better minimization). One problem I am facing is dealing the function type constraints in AX optimize. Most of my constraints are defined as functions (as can be found [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize)). 

I am not sure what type of constraints can handle functions defining the constraints in AX optimize. My constraints are linear. So, are there any ways I can convert my function constraints in a AX type constraints? One example constraint in my current code is as follows:

`def capacity(x):`
    `DELTA = np.zeros_like(REMELTdummy)`
    `TOT_MELTdummy[:] = TOT_MELT[:]`
    `k = 0`
    `for i in range(Ncast):`
        `TOT_MELTdummy[i] += x[i+k]`
        `for m in range(n_RAS):`
            `for j in range(np.size(IntScrAlloy[m])):`
                `if f_int_list[m][i][j] > 1.:`
                    `k += 1`
                    `TOT_MELTdummy[i] += x[i+k] * (1.0 - melt_loss)`
        `for j in range(np.size(ExtScrAlloy)):`
            `if f_ext[i,j] > 1.:`
                `k += 1`
                `TOT_MELTdummy[i] += x[i+k] * (1.0 - melt_loss)`
        `ind = alloy_desig.index(cast_alloy[i])`
        `DELTA[i] = InputVolMAX[ind] - TOT_MELTdummy[i]`
    `return DELTA`

`con= ({'type': 'ineq',`
           ` 'fun' : capacity})`

Any direction in this matter is greatly appreciated. Thanks

**Comment by lena-kashtelyan** [comment]
Hi, @tousifahmed54! In Ax we support two types of constraints: parameter constraints and outcome constraints. This documentation section describes the parameter constraints we support: https://ax.dev/docs/core.html#search-space-and-parameters, and this one describes the outcome constraints: https://ax.dev/docs/core.html#optimization-config. Then, for passing constraints to `optimize`, see the example in this tutorial: https://ax.dev/tutorials/gpei_hartmann_loop.html#2.-Run-optimization.

If your constraints need to be function-based and cannot be expressed in linear form with parameters or metrics/outcomes, they are not supported by Ax.

**Comment by Balandat** [comment]
Taking a step back, how many function evaluations are you currently running with the SLSQP optimizer? How long does a single evaluation take? If there are many evaluations and they can be performed quickly, then Ax will likely not be a good choice here since its not really designed for that (but if you have costly evaluations and can only make a few then by all means Ax is the right tool).

**Comment by lena-kashtelyan** [comment]
@tousifahmed54, please reopen this issue if you have any follow-up questions!
