### ISSUE TITLE
How to run Ax in Visual Studio Code with plotting

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#726]
After running the `gpei_hartman_loop.py` example, the plotly output seems to go directly to the command terminal (i.e. a very long text-based entry) rather than actual plotting it anywhere. I can use a notebook version, but I was curious if there's a way to run this with plotting in an IDE (specifically VS Code).

**Comment by lena-kashtelyan** [comment]
Hi @sgbaird, that's an interesting question! One solution would be to serialize the plot and save it to file (I believe Plotly has utilities for that), but beyond that I'm not sure; let me see if anyone else on the team has thoughts and get back to you!

**Comment by lena-kashtelyan** [comment]
@bernardbeckerman found a useful pointer for this: https://stackoverflow.com/questions/64849484/display-plotly-plot-inside-vs-code. You might have some luck with this @sgbaird! Alternatively, you can use our APIs in a Jupyter notebook as you mentioned; you will also have a bit more granular control with Service API than with the Loop API, so I recommend checking out this tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html.

Feel free to re-open this if you have follow-up questions or comments!
