### ISSUE TITLE
SAASBO MOO: Unknown solver options: sequential

### ISSUE THREAD

**Issue by hanochk** [facebook/Ax#735]
I was trying to imply my MOO problem over the MOO SAASBO ipynb, though the objective isn't noisy in my case. Getting the following warning about sequential, is it normal? 
from iteration #19 of SOBOL under saasbo_nehvi.ipynb  :

 

Unknown solver options: sequential

[WARNING 11-30 11:04:24] ax.service.utils.report_utils: Ignoring user-specified `deduplicate_on_map_keys = True` since `exp.fetch_data().map_keys` is empty or does not exist. Check that at least one element of `metrics` (or `exp.metrics` if `metrics is None`) inherits from `MapMetric`.
Iteration: 9, HV: 0.0
/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/generation/gen.py:166: OptimizeWarning:

Unknown solver options: sequential

**Comment by lena-kashtelyan** [comment]
cc @dme65 on this one

**Comment by dme65** [comment]
I think we'll need a repro to be able to answer where the `Unknown solver options: sequential` warning comes from since it doesn't seem to be present in the `saasbo_nehvi` tutorial. 

@hanochk, can you provide a minimal repro that produces this warning?

**Comment by hanochk** [comment]
Hi David, since part of the code is proprietary, it is challenging. Not
sure if applicable.

**Comment by lena-kashtelyan** [comment]
@hanochk, this warning does not come up in a run of the tutorial built off of the latest Ax and BoTorch: https://ax.dev/versions/latest/tutorials/saasbo_nehvi.html (this is updated nightly) or in a run built off of the stable Ax (0.2.2) and BoTorch (0.5.1): https://ax.dev/tutorials/saasbo_nehvi.html. My guess is you need to update something about your packages. 

Other than that, we cannot debug this more without a repro; if you are able to make one, please reopen this issue. Until then, I'd recommend ensuring your packages are all up-to-date.

**Comment by hanochk** [comment]
Hi Lena, indeed mine are 0.2.2 and 0.5.1 as well (respectively). I can't
share proprietary code but rather the exp_to_df ( as you mentioned) at the
iteration when the warning comes out.
Hanoch
