### ISSUE TITLE
Attach trials and data in developer API

### ISSUE THREAD

**Issue by paoloBerizzi** [facebook/Ax#737]
Hi, in accordance with the "Fully Bayesian Multi-Objective Optimization using qNEHVI + SAASBO" tutorial I am using the Developer API to develop a SAASBO MOO. I need to attach data to the experiment as it is done with the "attach_trial" and "complete_trial" in the Service API. Given that the evaluation take place remotely I cannot implement a runner to evaluate trials and I would only need to import  data+evaluation that has already happened together with the corresponding results, to then retrieve a new trials that I'm going to evaluate remotely.

I think I could make use of  ["attach_data"](https://ax.dev/api/core.html#ax.core.experiment.Experiment.attach_data) after creating the experiment, though after attaching data to the experiment fetch_data return an empty set.

`

        trial = my_experiment.new_trial().add_arm(Arm(parameters=parameters))
        for objective_name in objective_names:
            data_df = pd.DataFrame([[trial.arm.name, objective_mean_value, objective_name, objective_sem_value, trial.index]],
                        columns=['arm_name', 'mean', 'metric_name', 'sem', 'trial_index'])
            my_experiment.attach_data(ax.core.data.Data(data_df), combine_with_last_data=True)
        print("self.experiment.num_trials ", self.experiment.num_trials)
        print(self.experiment.fetch_data())
`

Any suggestions on how to implement SAASBO MOO with ServiceAPI so that I can use the attach_trial&complete_trial ?
Any idea on how to "fix" the attached data to the experiment inthe Developer API?

Thanks,
Paolo

**Comment by lena-kashtelyan** [comment]
Hi @paoloBerizzi! You could, if you wanted, just use the Service API for this? You'd just need to specify the correct generation strategy. Here is how you would do that using generation strategy ([tutorial](https://ax.dev/tutorials/generation_strategy.html) for reference):
```
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3, # How many trials need to be completed to move to next model
        ),
        GenerationStep(
            model=Models.FULLYBAYESIANMOO,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            max_parallelism=3,  # Parallelism limit for this step, often lower than for Sobol
            # You can configure these however you see fit; 
            # these are arguments to `Models.FULLYBAYESIANMOO` call, so configuring them 
            # like this is analogous to the setup in this section: 
            # https://ax.dev/tutorials/saasbo_nehvi.html#qNEHVI-+-SAASBO
            model_kwargs={
                "num_samples": 256,
                "warmup_steps": 512,
                "disable_progbar": True, # Set to False to print a progress bar from MCMC
            }
        ),
    ]
)

ax_client = AxClient(generation_strategy=gs)
```

To see how to set up `AxClient` for multi-objective optimization, refer to this section of the multi-objective tutorial: https://ax.dev/tutorials/multiobjective_optimization.html#Using-the-Service-API. 

Let us know if this doesn't fully help!

**Comment by lena-kashtelyan** [comment]
Hi again @paoloBerizzi! Closing this issue as inactive, assuming my last comment answered your question. Please reopen if you have any follow-ups (don't comment on closed issue without reopening it as we might not see the comment; please actually reopen if you add comments)!
