### ISSUE TITLE
raise ValueError(f"{p} not RangeParameter") when no RangeParameters are used.

### ISSUE THREAD

**Issue by ovr4** [facebook/Ax#738]
I keep getting this error when running the get_botorch function below:

**Error:** raise ValueError(f"{p} not RangeParameter") 

**Function:**
    model = get_botorch(
        experiment=exp,
        data=exp.eval(),
        search_space=exp.search_space,
        model_constructor=_get_and_fit_simple_custom_gp, transforms=[]
    )

My search space doesn't include any RangeParameters but it keeps checking for RangeParameters. 
ValueError: ChoiceParameter(name='Bridge1', parameter_type=FLOAT, values=[0.0, 1.0, 2.0]) not RangeParameter

Is this an issue with my set up or an issue with get_botorch? Please advise.

**Comment by lena-kashtelyan** [comment]
Hi @ovr4, could you please paste a full snippet of how you are setting up the experiment and also the full stack trace for the error? Without that information, it's tricky to fully understand what is going on. Thank you!

**Comment by ovr4** [comment]
Hello,

Thanks for getting back to me so soon. Thankfully, I just figured out what the issue was. But I appreciate your willingness to assist.

**Comment by lena-kashtelyan** [comment]
Great news, @ovr4! Would you mind briefly stating what the solution was in the end, in case it will help someone else in the community?

**Comment by lena-kashtelyan** [comment]
Closing this, but if you could comment stating what the problem and the solution ended up being, we would really appreciate that.

**Comment by ovr4** [comment]
Sorry for the late reply @lena-kashtelyan! The resolution was quite silly. I had accidentally included an empty list [] for the transforms parameter in the get_botorch function. I'm guessing the function would then require a RangeParameters object with this set up since it expected to perform a transformation of my inputs.

**Comment by lena-kashtelyan** [comment]
@ovr4 I think that's exactly right; usually there are transforms selected by default, but because you manually passed an empty list, that didn't happen and things went wrong. Thank you for letting us know, we really appreciate it!
