### ISSUE TITLE
Can the Loop API be used with an increased number of sampling points for higher-dimensional problems?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#740]
Similar to #694, I'm running into the error:
```python
ax.service.managed_loop: Running optimization trial 1...   [INFO 12-04 17:51:23] ax.service.managed_loop: Stopped 
optimization as the search space is exhaused. Message from generation strategy: Rejection sampling error (specified 
maximum draws (10000) exhausted, without finding sufficiently many (1) candidates). This likely means that there are no 
new points left in the search space..
```
Is there a way to increase this using the Loop API? It seems like the general recommendation based on #694 is as follows:
> The fix for this is now on master; it does require specifying `fallback_to_sample_polytope` argument to model. For Service API (`AxClient`) use cases, that argument can be specified among `model_kwargs` to the Sobol generation step. See [generation strategy tutorial](https://ax.dev/tutorials/generation_strategy.html) for making a custom generation strategy, which can then be passed to `AxClient(generation_strategy=my_generation_strategy)`.
> 
> Falling back to sample polytope will not be the default at least for a while due to additional complications it introduces into the deduplication logic, so it will only be available if `fallback_to_sample_polytope` is specified as `True`.

`ax.service.managed_loop.optimize` also takes a `generation_strategy` argument, so I assume I could apply something similar.

So far I've found the following (`max_rs_draws`):
https://github.com/facebook/Ax/blob/6f2eac0b62b7fa8b701553b890d26e804bfcc5c7/ax/models/tests/test_sobol.py#L202-L216

Related: #727

**Comment by Balandat** [comment]
I'll let @lena-kashtelyan answer the question about the loop API specifically, but can you please provide the constraints that you're using for your problem?

**Comment by lena-kashtelyan** [comment]
@sgbaird, you could configure this through passing a custom generation strategy to `optimize`, as you correctly pointed out. This comment: https://github.com/facebook/Ax/issues/694#issuecomment-951084270 should inform how to do so! One thing I would note is that deduplication of Sobol points might not work with fallback to hit-and-run sampler, so let us know how setting `fallback_to_sample_polytope=True` ends up working out for you –– we can help tweak the setup as necessary.

Enchoing @Balandat's thoughts, I'd also like to see what the constraints are in your case, to understand why you are running into this issue.

**Comment by lena-kashtelyan** [comment]
@sgbaird kindly posted their findings on using `fallback_to_sample_polytope` here: https://github.com/facebook/Ax/issues/694#issuecomment-987353936, linking that comment in this issue as well so folks who need a similar customization find it easily.

**Comment by sgbaird** [comment]
To address @Balandat 's question, the constraint is something to the effect of:
```python
constraint = "A + B + C + ... + S + T <= 1.0"
```
