### ISSUE TITLE
Meaningful warnings in saasbo_nehvi.ipynb ? 

### ISSUE THREAD

**Issue by hanochk** [facebook/Ax#741]
Hi, im getting two types of warnings, the 2nd is probably related to instability avoidance in the Cholesky decomposition ("added jitter"). Are they pointing to an issue that should be concerned?

1. 
This warning also appears in the jupyter :
https://github.com/facebook/Ax/blob/main/tutorials/saasbo_nehvi.ipynb

[WARNING 12-03 11:35:29] ax.service.utils.report_utils: Ignoring user-specified `deduplicate_on_map_keys = True` since `exp.fetch_data().map_keys` is empty or does not exist. Check that at least one element of `metrics` (or `exp.metrics` if `metrics is None`) inherits from `MapMetric`.
<ax.modelbridge.multi_objective_torch.MultiObjectiveTorchModelBridge object at 0x7f03e4d2c3a0> <ax.core.data.Data object at 0x7f03e49ff370>
/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning:

2.

[INFO 11-29 15:02:58] ax.models.torch.fully_bayesian: MCMC elapsed time: 87.58944511413574 
<ax.modelbridge.multi_objective_torch.MultiObjectiveTorchModelBridge object at 0x7f8609433be0> <ax.core.data.Data object at 0x7f8608d9c130> 
/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning: 
 
A not p.d., added jitter of 1.0e-08 to the diagonal 
 
/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning: 
 
A not p.d., added jitter of 1.0e-08 to the diagonal 
 
/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning: 
 
A not p.d., added jitter of 1.0e-08 to the diagonal 
 
[WARNING 11-29 15:04:18] ax.service.utils.report_utils: Ignoring user-specified `deduplicate_on_map_keys = True` since `exp.fetch_data().map_keys` is empty or does not exist. Check that at least one element of `metrics` (or `exp.metrics` if `metrics is None`) inherits from `MapMetric`. 
Iteration: 0, HV: 0.0 
 
Warmup:   0%|          | 0/768 [00:00, ?it/s] 
Warmup:   0%|          | 1/768 [00:03,  3.23s/it, step size=2.14e+00, acc. prob=0.333] 
Warmup:   1%|          | 4/768 [00:03,  1.52it/s, step size=2.17e-01, acc. prob=0.526] 
Warmup:   1%|          | 6/768 [00:03,  2.45it/s, step size=3.52e-01, acc. prob=0.656]

**Comment by lena-kashtelyan** [comment]
For warning #1, we already answered in this issue that this was an unnecessary warning that is going away in next stable version: https://github.com/facebook/Ax/issues/735#issuecomment-983007513.

For warning #2, it's very difficult to understand whether it's meaningful without actually seeing the data you are supplying to our models in the course of the experiment. Usually warnings like that come up when there are a few observations in the data that are either very similar or the same, but we won't be able to say more without seeing your data.

If you are able to make a minimal repro notebook (specifically, we need to see the contents of the `df` objects from this cell of the tutorial: https://ax.dev/tutorials/saasbo_nehvi.html#qNEHVI-+-SAASBO –– obviously feel free to change naming of parameters/outcomes if that helps), please post that and reopen this issue!
