### ISSUE TITLE
How to use Ax with an existing, small dataset of (effectively randomly) sampled points?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#743]
As mentioned in #727, a colleague of mine, @ramseyissa is in the (perhaps common) situation where he has a dataset existing of ~O `100` datapoints which to some extent has been randomly sampled (or sampled using domain knowledge) that he's now taken over for, and for which it's his job to expand the dataset in search of the highest performing (**laboratory chemical synthesis**) experimental parameters.

How would Ax typically be used in this case to "suggest best next experiments" in a sequential learning / adaptive design scheme? Any recommendations for how to go about this or links to example implementations?

I'm thinking mostly in reference to @Balandat 's https://github.com/facebook/Ax/issues/727#issuecomment-986305247:
> ... Ax is typically used is by building its own (typically Gaussian Process) surrogate model internally ...

The [Human-In-The-Loop tutorial](https://ax.dev/tutorials/human_in_the_loop/human_in_the_loop.html) is probably much more relevant than I initially thought.

**Comment by sgbaird** [comment]
I think I've found another example of human-in-the-loop adaptive (laboratory) experimental design here:
https://nextorch.readthedocs.io/en/latest/examples/13_Using_Ax.html

**Comment by sgbaird** [comment]
I think I've got it based on several issues throughout, the clearest (because of the worked example) being https://github.com/facebook/Ax/issues/266#issuecomment-596675083. The implementation is as follows, where a single next set of parameters (`next_experiment`) is suggested:
```python
# %% imports
import numpy as np
import pandas as pd

from ax.modelbridge.generation_strategy import GenerationStrategy, GenerationStep
from ax.modelbridge.registry import Models

from ax.service.ax_client import AxClient
from ax.service.utils.instantiation import ObjectiveProperties

unique_components = ["filler_A", "filler_B", "resin_A", "resin_B", "resin_C"]

X_train = np.array([
       [0.4, 0.4, 0. , 0. , 0.2],
       [0.5, 0. , 0. , 0.5, 0. ],
       [0.5, 0.3, 0. , 0.2, 0. ],
       [0.5, 0. , 0. , 0.5, 0. ],
       [0. , 0.6, 0.4, 0. , 0. ],
       [0.6, 0. , 0.4, 0. , 0. ],
       [0. , 0.6, 0.2, 0.2, 0. ]])

np.random.seed(10)
y_train = 100 * np.random.rand(len(components))

n_train = X_train.shape[0]

# Ax-specific
parameters = [
    {"name": component, "type": "range", "bounds": [0.0, 1.0]}
    for component in unique_components[:-1]
]

separator = " + "
composition_constraint = separator.join(unique_components[:-1]) + " <= 0.5"

# %% optimize
gs = GenerationStrategy(
    steps=[
        # 1. Initialization step (does not require pre-existing data and is well-suited for
        # initial sampling of the search space)
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3,  # How many trials need to be completed to move to next model
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={
                "seed": 999,
                "fallback_to_sample_polytope": True,
            },  # Any kwargs you want passed into the model
            model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
        ),
        # 2. Bayesian optimization step (requires data obtained from previous phase and learns
        # from all data available at the time of each new candidate generation call)
        GenerationStep(
            model=Models.GPEI,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            max_parallelism=3,  # Parallelism limit for this step, often lower than for Sobol
            # More on parallelism vs. required samples in BayesOpt:
            # https://ax.dev/docs/bayesopt.html#tradeoff-between-parallelism-and-total-number-of-trials
        ),
    ]
)

ax_client = AxClient(generation_strategy=gs)
ax_client.create_experiment(
    name="dummy",
    parameters=parameters,
    parameter_constraints=[
        composition_constraint,
    ],
    minimize=True,
)

for i in range(n_train):
    ax_client.attach_trial(X_train.iloc[i, :-1].to_dict())
    ax_client.complete_trial(trial_index=i, raw_data=y_train[i])

next_experiment, trial_index = ax_client.get_next_trial()
print("next suggested experiment: ", next_experiment)

best_parameters, metrics = ax_client.get_best_parameters()
```

**Comment by lena-kashtelyan** [comment]
@sgbaird, I totally missed this issue, but your use of Ax in the last comment looks exactly right!

**Comment by sgbaird** [comment]
Since I'll be pointing some colleagues to this issue, I updated my comment above to fix some errors. I also [put the example up on Colab](https://colab.research.google.com/drive/1NDsKieIVS8qubg9EOkoLBafqygIxVkfa?usp=sharing) to make it easier for people to run and test right away.
