### ISSUE TITLE
`gradf` are NaN while running saasbo_nehvi.ipynb

### ISSUE THREAD

**Issue by hanochk** [facebook/Ax#749]
Hi im implementing my own optimization over the SAASBO.ipynb having the following error, which occurred a few times already, in the BoTorch engine, though I may assume it is hard to restore also due to the stochastic nature of the MC can you help?

Ax (0.2.2) and BoTorch (0.5.1)

 not p.d., added jitter of 1.0e-08 to the diagonal

/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning:

A not p.d., added jitter of 1.0e-07 to the diagonal

/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/utils/cholesky.py:44: NumericalWarning:

A not p.d., added jitter of 1.0e-06 to the diagonal

/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py:1635: NumericalWarning:

Runtime Error when computing Cholesky decomposition: Matrix not positive definite after repeatedly adding jitter up to 1.0e-06.. Using symeig method.

Traceback (most recent call last):
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/HMS/mobo_ANS_saasbo_nehvi.py", line 409, in <module>
    main()
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/HMS/mobo_ANS_saasbo_nehvi.py", line 269, in main
    generator_run = model.gen(BATCH_SIZE)
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/multi_objective_torch.py", line 231, in gen
    return super().gen(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/base.py", line 669, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/array.py", line 274, in _gen
    X, w, gen_metadata, candidate_metadata = self._model_gen(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/multi_objective_torch.py", line 165, in _model_gen
    X, w, gen_metadata, candidate_metadata = self.model.gen(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/models/torch/botorch_moo.py", line 364, in gen
    candidates, expected_acquisition_value = self.acqf_optimizer(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/models/torch/botorch_defaults.py", line 346, in scipy_optimizer
    X, expected_acquisition_value = optimize_acqf(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/optim/optimize.py", line 113, in optimize_acqf
    candidate, acq_value = optimize_acqf(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/optim/optimize.py", line 184, in optimize_acqf
    batch_candidates_curr, batch_acq_values_curr = gen_candidates_scipy(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/generation/gen.py", line 166, in gen_candidates_scipy
    res = minimize(
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 623, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 140, in __init__
    self._update_fun()
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 233, in _update_fun
    self._update_fun_impl()
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/generation/gen.py", line 162, in f
    raise RuntimeError(msg)
RuntimeError: 100 elements of the 100 element gradient array `gradf` are NaN. This often indicates numerical issues.

My code :
#!/usr/bin/env python
# coding: utf-8

# # Fully Bayesian Multi-Objective Optimization using qNEHVI + SAASBO
# 
# ### This Tutorial
# 
import pandas as pd
from ax import *

import torch
import numpy as np

from ax.metrics.noisy_function import GenericNoisyFunctionMetric
from ax.service.utils.report_utils import exp_to_df
from ax.runners.synthetic import SyntheticRunner

# Plotting imports and initialization
from ax.utils.notebook.plotting import render, init_notebook_plotting
from ax.plot.contour import plot_contour
from ax.plot.pareto_utils import compute_posterior_pareto_frontier
from ax.plot.pareto_frontier import plot_pareto_frontier

# init_notebook_plotting()

# Model registry for creating multi-objective optimization models.
from ax.modelbridge.registry import Models

# Analysis utilities, including a method to evaluate hypervolumes
from ax.modelbridge.modelbridge_utils import observed_hypervolume

from pylab import *
import sys
#sys.path.insert(1, '/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/HMS')
import M
import torch as nn
import os
from math import sqrt, log
import time 
from argparse import ArgumentParser
import matplotlib.pyplot as plt
import numpy as np
from bayesian_opt_utils import Cmax_compress_min_err_moo, print_arguments
from matplotlib.cm import ScalarMappable

def main():
    parser = ArgumentParser()

    # parser.add_argument('--random-seed', type=int, default=None, metavar='INT', help="random seed to set")

    parser.add_argument('--gpu-id', type=int, default=3, metavar='INT',
                        help="cuda device id ")

    parser.add_argument('--model-path', type=str, default='ml_video_edit_art_generate.onnx', metavar='PATH',
                        help=" MODEL PATH TO BE OPTIMIZED")

    parser.add_argument('--result-dir', type=str, default=None, metavar='PATH',
                        help="if given, all output of the training will be in this folder. "
                             "The exception is the tensorboard logs.")

    parser.add_argument('--n-batch', type=int, default=20, metavar='INT', help="")

    parser.add_argument('--batch-size', type=int, default=4, metavar='INT', help="")

    parser.add_argument('--lambda-scale-rel-error', type=float, default=1.0, metavar='INT', help="")

    parser.add_argument('--apply-ref-point', action='store_true',
                        help='')

    parser.add_argument('--ans-opt-kernel', type=str, default='python_imp', choices=['c_type', 'python_imp'], metavar='STRING',
                        help='')

    parser.add_argument('--verbose', action='store_true',
                        help='')

    args = parser.parse_args()
    # In[2]:

    print_arguments(args)
    # if args.verbose:
    #     os.system("g++ -DFSE_VERBOSE -Ofast ../cimpl/main.cc -lm  -shared -o ../HMS/ans_cmprs.so") # no verbose

    start = time.time()
    print("SAASBO MOBO")
    clock = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(start))
    print("Time/Date is {}".format(clock))

    if args.ans_opt_kernel == 'python_imp':
        python_imp = True
    elif args.ans_opt_kernel == 'c_type':
        python_imp = False
    else:
        raise ValueError("Wrong kernel type!!!!")

    negate = False #True
    verbose = args.verbose
    compute_hv = False
    args.python_imp = python_imp
    args.negate = negate
    args.algo = "SAASBO"

    N_BATCH = args.n_batch
    BATCH_SIZE = args.batch_size

    unique_run_name = str(int(time.time()))
    print("unique run name : {}".format(unique_run_name))
    args.unique_run_name = unique_run_name

    if not os.path.exists(args.result_dir):
        os.makedirs(args.result_dir)

    M.path_to_error_eval_images = '/mnt/users/sefi/images/**/*.jpg'
    print("Model {}".format(args.model_path))
    reshape_input_image = not (os.path.basename(args.model_path) == 'ml_video_edit_art_generate.onnx' or
                               os.path.basename(args.model_path) == 'ml_video_edit_art_transfer.onnx' )
    images = M.Images(for_judge=reshape_input_image)
    minsize = 10 #1048572 #  HK : only one layer FC 1K
    model_path = args.model_path

    if os.path.basename(args.model_path) == 'ml_video_edit_art_transfer.onnx':
        #run the generate 1st creating inputs to the transfer
        ob = M.OnnxBridge(os.path.join(os.path.dirname(args.model_path), 'ml_video_edit_art_generate.onnx'))
        # images = M.Images()
        original_outs = [ob(i) for i in images]
        ################ original outs are needed to the transfer model, so we generate those inhere as well :o

        ob = M.OnnxBridge(os.path.join(os.getcwd(), 'ml_video_edit_art_transfer.onnx'))
        original_transfer_outs = []

        for i, oo in zip(images, original_outs[-1:] + original_outs[:-1]):
            x = [i, oo[0], oo[1]]
            # original_transfer_outs.append(ob(x)[0])
            original_transfer_outs.append(x) #creating inputs as list
        images = original_transfer_outs

    if python_imp:
        print("python imp!!!")

    # ### Load our sample 2-objective problem

    # ## Define experiment configurations
    if args.gpu_id == -1:
        device = torch.device("cpu")  # Force CPU
    else:
        device = torch.device("cuda:" + str(args.gpu_id) + "" if torch.cuda.is_available() else "cpu")

    tkwargs = {
        "dtype": torch.double,
        "device": device, # HK
    #     "device": torch.device( "cpu"), #Force CPU
    }
    objective_ans = Cmax_compress_min_err_moo(model_path=model_path, images=images, #negate the objectives HK (-compression, rel error)
                                         minsize=minsize, negate=negate,
                                        python_imp=python_imp, verbose=verbose,
                                              lambda_scl_rel_err=args.lambda_scale_rel_error,
                                              apply_ref_point=args.apply_ref_point).to(**tkwargs)
    args.objective_ans_cfg = objective_ans.__dict__.items()

    # ### Search Space

    upper = [0.1 if python_imp==True else 0.1][0] # HK was 0.005 for python 4.12  # to 0.1 for judge
    print("Upper bound of param range ", upper)
    search_space = SearchSpace(
        parameters=[RangeParameter(name=f"x{i}", lower=0, upper=upper, parameter_type=ParameterType.FLOAT) for i in range(objective_ans.dim)],
    )

    # ### MultiObjectiveOptimizationConfig
    #
    # To optimize multiple objective we must create a `MultiObjective` containing the metrics we'll optimize and `MultiObjectiveOptimizationConfig` (which contains `ObjectiveThreshold`s) instead of our more typical `Objective` and `OptimizationConfig`. Additional resources:
    # - To set up a custom metric for your problem, refer to the dedicated section of the Developer API tutorial: https://ax.dev/tutorials/gpei_hartmann_developer.html#8.-Defining-custom-metrics.
    # - To avoid needing to setup up custom metrics by using multi-objective optimization in Ax Service API: https://ax.dev/tutorials/multiobjective_optimization.html#Using-the-Service-API.
    #
    # We define `GenericNoisyFunctionMetric`s to wrap our synthetic Branin-Currin problem's outputs.

    # In[6]:

    param_names = [f"x{i}" for i in range(objective_ans.dim)]

    # In[7]:

    def f1(x) -> float:
            x_sorted = [x[p_name] for p_name in param_names]
            return float(objective_ans(torch.tensor(x_sorted, **tkwargs))[0])

    def f2(x) -> float:
            x_sorted = [x[p_name] for p_name in param_names]
            return float(objective_ans(torch.tensor(x_sorted, **tkwargs))[1])

    metric_a = GenericNoisyFunctionMetric("a", f=f1, noise_sd=0.0, lower_is_better=False)
    metric_b = GenericNoisyFunctionMetric("b", f=f2, noise_sd=0.0, lower_is_better=False)

    # oc = OutcomeConstraint(metric=Metric(name="b"), op = ComparisonOp.LEQ, bound=0.005, relative=False)

    mo = MultiObjective(
        objectives=[Objective(metric=metric_a), Objective(metric=metric_b)],
    )

    objective_thresholds = [
        ObjectiveThreshold(metric=metric, bound=val, relative=False)
        for metric, val in zip(mo.metrics, objective_ans.ref_point)
    ]

    optimization_config = MultiObjectiveOptimizationConfig(
        objective=mo,
        objective_thresholds=objective_thresholds,
    #     outcome_constraints = [oc]   # HK added to focus ROI
    )

    # ## Define experiment creation utilities
    # These construct our experiment, then initialize with Sobol points before we fit a Gaussian Process model to those initial points.

    N_INIT = 2 * (objective_ans.dim + 1) #HK

    def build_experiment():
        experiment = Experiment(
            name="pareto_experiment",
            search_space=search_space,
            optimization_config=optimization_config,
            runner=SyntheticRunner(),
        )
        return experiment

    ## Initialize with Sobol samples

    def initialize_experiment(experiment):
        sobol = Models.SOBOL(search_space=experiment.search_space)

        experiment.new_batch_trial(sobol.gen(N_INIT)).run()

        return experiment.fetch_data()

    # ## qNEHVI + SAASBO
    # Noisy expected hypervolume improvement + fully Bayesian inference with SAAS priors.

    # In[17]:

    print("SOBOL random init HV can be 0") # by FAIR
    experiment = build_experiment()
    data = initialize_experiment(experiment)

    # In[ ]:

    from botorch.utils.multi_objective.box_decompositions.dominated import DominatedPartitioning
    hv_list = []
    model = None
    for i in range(N_BATCH):
        model = Models.FULLYBAYESIANMOO(
            experiment=experiment,
            data=data,
            # use fewer num_samples and warmup_steps to speed up this tutorial
            num_samples=256, #monte carlo MCMC
            warmup_steps=512,
            torch_device=tkwargs["device"],
            verbose=verbose,  # Set to True to print stats from MCMC  gp_kernel="rbf" by defualt
            disable_progbar=False,  # Set to False to print a progress bar from MCMC
        )
        # print(model, data)
        generator_run = model.gen(BATCH_SIZE)
        trial = experiment.new_batch_trial(generator_run=generator_run)
        trial.run()
        data = Data.from_multiple_data([data, trial.fetch_data()])

        exp_df = exp_to_df(experiment)
        outcomes = torch.tensor(exp_df[['a', 'b']].values, **tkwargs)
        partitioning = DominatedPartitioning(ref_point=objective_ans.ref_point, Y=outcomes)
        if compute_hv: # disable increase speed
            try:
                hv = partitioning.compute_hypervolume().item()
            except:
                hv = 0
                print("Failed to compute hv")
            hv_list.append(hv)
            print(f"Iteration: {i}, HV: {hv}")

    df = exp_to_df(experiment).sort_values(by=["trial_index"])
    # Handle scaling the target
    df['b'] = df['b'].apply(lambda x: x / args.lambda_scale_rel_error)

    outcomes = df[["a", "b"]].values
    fig, axes = plt.subplots(1, 1, figsize=(8,6))
    algos = ["qNEHVI"]
    train_obj = outcomes
    cm = plt.cm.get_cmap('viridis')

    # n_results = N_BATCH*BATCH_SIZE + N_INIT

    batch_number = df.trial_index.values
    sc = axes.scatter(train_obj[:, 0], train_obj[:,1], c=batch_number, alpha=0.8)
    axes.grid()
    axes.axhline(y=-0.05)
    axes.set_title(algos[0] + " w/ rel error scaling " + str(args.lambda_scale_rel_error) + " trials" + str(N_BATCH) + "_x_" + str(BATCH_SIZE) + " model:" + os.path.basename(args.model_path))
    axes.set_xlabel("Compression")
    axes.set_ylabel("-rel_error ")
    norm = plt.Normalize(batch_number.min(), batch_number.max())
    sm =  ScalarMappable(norm=norm, cmap=cm)
    sm.set_array([])
    fig.subplots_adjust(right=0.9)
    cbar_ax = fig.add_axes([0.93, 0.15, 0.01, 0.7])
    cbar = fig.colorbar(sm, cax=cbar_ax)
    cbar.ax.set_title("Iteration")

    file_name = 'SAASBO_qNEHVI' + str(unique_run_name)

    fig.savefig(os.path.join(args.result_dir, file_name + ".png"))

    df['-rel_error'] = df['b']
    df['compression_ratio'] = df['a']

    df.to_csv(os.path.join(args.result_dir, file_name + ".csv"))
    end = time.time()
    print("Elapsed time for processing SAASBO",end - start)
    print("unique run name : {}".format(unique_run_name))

    args.process_time = end - start
    df_result = pd.DataFrame.from_dict(list(vars(args).items()))
    df_result.to_csv(os.path.join(args.result_dir, file_name + "_settings.csv"))

    # # Hypervolume statistics
    # The hypervolume of the space dominated by points that dominate the reference point.

    # plt.show()

**Comment by lena-kashtelyan** [comment]
Hi @hanochk, would you be able to add a printout of `exp_to_df` at it looks just before you encounter the error? The numerical instability is likely coming from the data in your experiment, so it would help us to see it.

**Comment by hanochk** [comment]
Hi Lena, you are probably referring to exp_to_df(experiment) which is a
dataframe otherwise it is just a function handler, right ?

**Comment by hanochk** [comment]
Hi Lena,  attached the log + the dataframe hope it helps to resolve the
issue

A not p.d., added jitter of 1.0e-06 to the diagonal

/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/gpytorch/lazy/lazy_tensor.py:1635:
NumericalWarning:

Runtime Error when computing Cholesky decomposition: Matrix not positive
definite after repeatedly adding jitter up to 1.0e-06.. Using symeig method.

Traceback (most recent call last):
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/HMS/mobo_ANS_saasbo_nehvi.py",
line 456, in <module>
    main()
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/HMS/mobo_ANS_saasbo_nehvi.py",
line 305, in main
    generator_run = model.gen(BATCH_SIZE)
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/multi_objective_torch.py",
line 231, in gen
    return super().gen(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/base.py",
line 669, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/array.py",
line 274, in _gen
    X, w, gen_metadata, candidate_metadata = self._model_gen(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/modelbridge/multi_objective_torch.py",
line 165, in _model_gen
    X, w, gen_metadata, candidate_metadata = self.model.gen(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/models/torch/botorch_moo.py",
line 364, in gen
    candidates, expected_acquisition_value = self.acqf_optimizer(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/ax/models/torch/botorch_defaults.py",
line 346, in scipy_optimizer
    X, expected_acquisition_value = optimize_acqf(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/optim/optimize.py",
line 113, in optimize_acqf
    candidate, acq_value = optimize_acqf(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/optim/optimize.py",
line 184, in optimize_acqf
    batch_candidates_curr, batch_acq_values_curr = gen_candidates_scipy(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/generation/gen.py",
line 166, in gen_candidates_scipy
    res = minimize(
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_minimize.py",
line 623, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py",
line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py",
line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py",
line 140, in __init__
    self._update_fun()
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py",
line 233, in _update_fun
    self._update_fun_impl()
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py",
line 137, in update_fun
    self.f = fun_wrapped(self.x)
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py",
line 134, in fun_wrapped
    return fun(np.copy(x), *args)
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py",
line 74, in __call__
    self._compute_if_needed(x, *args)
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/scipy/optimize/optimize.py",
line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File
"/home/hanoch/PycharmProjects/pythonProject/ans_compression_opt/laila/sefi/_skariel/mixed_quant/ans_compression_opt/lib/python3.8/site-packages/botorch/generation/gen.py",
line 162, in f
    raise RuntimeError(msg)
RuntimeError: 20 elements of the 20 element gradient array `gradf` are NaN.
This often indicates numerical issues.


Or copy pasted:



a b trial_index arm_name x0 trial_status generation_method
0 8.068041 -24.6268 0 0_0 0.000796 RUNNING Sobol
1 5.199663 -4.19127 0 0_1 0.000166 RUNNING Sobol
2 5.988303 -7.30463 0 0_2 0.0003 RUNNING Sobol
3 7.609933 -16.6442 0 0_3 0.000677 RUNNING Sobol
4 5.191666 -5.06542 10 10_0 0.000164 RUNNING FullyBayesianMOO
5 5.189671 -4.55445 10 10_1 0.000164 RUNNING FullyBayesianMOO
6 3.716345 -0.85848 10 10_2 2.77E-05 RUNNING FullyBayesianMOO
7 5.603725 -6.10952 10 10_3 0.00023 RUNNING FullyBayesianMOO
8 8.568494 -37.0896 11 11_0 0.000945 RUNNING FullyBayesianMOO
9 8.573934 -35.8411 11 11_1 0.000945 RUNNING FullyBayesianMOO
10 8.572574 -36.1694 11 11_2 0.000945 RUNNING FullyBayesianMOO
11 8.573934 -35.0651 11 11_3 0.000946 RUNNING FullyBayesianMOO
13 8.538693 -30.8884 12 12_0 0.000936 RUNNING FullyBayesianMOO
14 8.519836 -26.4187 12 12_1 0.00093 RUNNING FullyBayesianMOO
15 8.515806 -26.8477 12 12_2 0.000928 RUNNING FullyBayesianMOO
16 8.593032 -31.5655 12 12_3 0.000949 RUNNING FullyBayesianMOO
17 8.699605 -29.01 13 13_0 0.000982 RUNNING FullyBayesianMOO
18 8.489037 -26.8972 13 13_1 0.000921 RUNNING FullyBayesianMOO
19 8.42416 -25.8886 13 13_2 0.000904 RUNNING FullyBayesianMOO
20 8.493042 -25.7067 13 13_3 0.000923 RUNNING FullyBayesianMOO
21 2.643023 -0.04383 14 14_0 1.57E-06 RUNNING FullyBayesianMOO
22 5.990296 -8.38581 14 14_1 0.000301 RUNNING FullyBayesianMOO
23 3.72583 -0.80929 14 14_2 2.82E-05 RUNNING FullyBayesianMOO
24 3.72583 -0.85087 14 14_3 2.81E-05 RUNNING FullyBayesianMOO
25 3.699038 -0.69308 15 15_0 2.69E-05 RUNNING FullyBayesianMOO
26 3.698784 -0.68551 15 15_1 2.69E-05 RUNNING FullyBayesianMOO
27 3.699038 -0.71811 15 15_2 2.69E-05 RUNNING FullyBayesianMOO
28 5.207685 -4.62374 15 15_3 0.000167 RUNNING FullyBayesianMOO
29 3.676127 -0.83659 16 16_0 2.59E-05 RUNNING FullyBayesianMOO
30 3.676377 -0.83315 16 16_1 2.59E-05 RUNNING FullyBayesianMOO
31 3.670132 -0.58616 16 16_2 2.56E-05 RUNNING FullyBayesianMOO
32 3.677128 -0.89461 16 16_3 2.59E-05 RUNNING FullyBayesianMOO
33 5.178724 -4.51121 17 17_0 0.000163 RUNNING FullyBayesianMOO
34 5.178724 -4.51122 17 17_1 0.000163 RUNNING FullyBayesianMOO
35 6.861653 -11.3288 17 17_2 0.00048 RUNNING FullyBayesianMOO
36 6.858168 -10.6527 17 17_3 0.00048 RUNNING FullyBayesianMOO
37 5.168812 -4.8978 18 18_0 0.000161 RUNNING FullyBayesianMOO
38 5.170791 -5.06586 18 18_1 0.000161 RUNNING FullyBayesianMOO
39 5.170296 -4.81449 18 18_2 0.000162 RUNNING FullyBayesianMOO
40 8.260534 -20.8875 18 18_3 0.000849 RUNNING FullyBayesianMOO
41 5.219763 -3.99052 19 19_0 0.000168 RUNNING FullyBayesianMOO
42 8.400575 -21.3234 19 19_1 0.000897 RUNNING FullyBayesianMOO
43 8.374525 -25.244 19 19_2 0.000891 RUNNING FullyBayesianMOO
44 8.396658 -21.6753 19 19_3 0.000896 RUNNING FullyBayesianMOO
12 2.552951 -0.03182 1 1_0 1.00E-06 RUNNING FullyBayesianMOO
45 5.228353 -4.97016 20 20_0 0.000169 RUNNING FullyBayesianMOO
46 5.229365 -4.89913 20 20_1 0.00017 RUNNING FullyBayesianMOO
47 5.229365 -4.98165 20 20_2 0.00017 RUNNING FullyBayesianMOO
48 6.879131 -10.6896 20 20_3 0.000484 RUNNING FullyBayesianMOO
49 3.820442 -0.8488 2 2_0 3.27E-05 RUNNING FullyBayesianMOO
50 3.820172 -0.84357 2 2_1 3.27E-05 RUNNING FullyBayesianMOO
51 3.825854 -0.79946 2 2_2 3.30E-05 RUNNING FullyBayesianMOO
52 3.734848 -0.66818 2 2_3 2.86E-05 RUNNING FullyBayesianMOO
53 8.758858 -31.2492 3 3_0 0.001 RUNNING FullyBayesianMOO
54 6.869507 -10.4942 3 3_1 0.000482 RUNNING FullyBayesianMOO
55 7.877416 -19.3954 4 4_0 0.000744 RUNNING FullyBayesianMOO
56 7.376101 -12.7957 4 4_1 0.000622 RUNNING FullyBayesianMOO
57 6.448749 -12.7827 4 4_2 0.000388 RUNNING FullyBayesianMOO
58 8.451843 -25.8176 4 4_3 0.000912 RUNNING FullyBayesianMOO
59 5.602562 -6.15705 5 5_0 0.000228 RUNNING FullyBayesianMOO
60 5.596757 -5.79174 5 5_1 0.000229 RUNNING FullyBayesianMOO
61 5.596757 -6.01547 5 5_2 0.000229 RUNNING FullyBayesianMOO
62 5.598497 -6.13271 5 5_3 0.000227 RUNNING FullyBayesianMOO
63 5.608962 -5.42298 6 6_0 0.000231 RUNNING FullyBayesianMOO
64 5.609545 -5.57277 6 6_1 0.000232 RUNNING FullyBayesianMOO
65 5.607797 -5.51083 6 6_2 0.000231 RUNNING FullyBayesianMOO
66 5.608962 -5.48389 6 6_3 0.000231 RUNNING FullyBayesianMOO
67 8.684219 -25.7495 7 7_0 0.000977 RUNNING FullyBayesianMOO
68 8.687012 -27.0697 7 7_1 0.000977 RUNNING FullyBayesianMOO
69 8.661936 -27.0806 7 7_2 0.000968 RUNNING FullyBayesianMOO
70 8.719267 -27.9501 7 7_3 0.000988 RUNNING FullyBayesianMOO
71 3.764261 -1.02164 8 8_0 3.00E-05 RUNNING FullyBayesianMOO
72 3.766624 -0.73326 8 8_1 3.01E-05 RUNNING FullyBayesianMOO
73 3.7682 -0.81367 8 8_2 3.01E-05 RUNNING FullyBayesianMOO
74 3.765573 -0.89762 8 8_3 3.00E-05 RUNNING FullyBayesianMOO
75 8.637003 -34.3312 9 9_0 0.00096 RUNNING FullyBayesianMOO
76 8.630103 -34.884 9 9_1 0.000959 RUNNING FullyBayesianMOO
77 8.603982 -31.7533 9 9_2 0.000953 RUNNING FullyBayesianMOO
78 8.741847 -25.423 9 9_3 0.000994 RUNNING FullyBayesianMOO

**Comment by lena-kashtelyan** [comment]
Thank you for this data, @hanochk, we'll look into it shortly!

**Comment by lena-kashtelyan** [comment]
Marking this one as "in progress" for while we investigate this internally. @hanochk, just letting you know that this is a busy time for us and the holidays are coming up, so we will likely get to this at the beginning of January and will update you then!

**Comment by hanochk** [comment]
Thanks for the update keep me posted.

**Comment by lena-kashtelyan** [comment]
Not currently sure when we will be able to look into this, so I'll put this investigation onto our wishlist for now
