### ISSUE TITLE
Do you support discrete/mixed multi-objective optimization?

### ISSUE THREAD

**Issue by fipeop** [facebook/Ax#765]
I saw this [docstring](https://github.com/facebook/Ax/blob/543a58302c4e10a51f0edddcd283ced812615112/ax/modelbridge/dispatch_utils.py#L116) that is referenced on issue #711.

Does this mean that multi-objective optimization does not support mixed (or purely discrete) search spaces?

**Comment by Balandat** [comment]
Looking through the `_suggest_gp_model` function it seems that this is indeed currently the case. However, there isn't really a good reason for this - the BO_MIXED model should be easily adaptable to the MOO case. In fact, one thing that has made this unnecessarily hard is that under the hood we currently use different `Modelbridge` classes for MOO and standard (single objective, possibly constrained) problems. But I know that @EugenHotaj and @lena-kashtelyan are working on cleaning this up, so hopefully we can enable this soon.

**Comment by fipeop** [comment]
I tried [this example](https://ax.dev/tutorials/multiobjective_optimization.html) of multi-objective optimization, changing one of the range parameters to an ordered choice parameter. It seems it is working well. 

Referring back to `_suggest_gp_model `, we choose 'MOO' as the model. How is 'MOO' managing the mixed space? 
My modified example below:

```

from ax.service.ax_client import AxClient
from ax.service.utils.instantiation import ObjectiveProperties

import torch

# Plotting imports and initialization
from ax.utils.notebook.plotting import render, init_notebook_plotting
from ax.plot.pareto_utils import compute_posterior_pareto_frontier
from ax.plot.pareto_frontier import plot_pareto_frontier
init_notebook_plotting()

# Load our sample 2-objective problem
from botorch.test_functions.multi_objective import BraninCurrin
branin_currin = BraninCurrin(negate=True).to(
    dtype=torch.double, 
    device= torch.device("cuda" if torch.cuda.is_available() else "cpu"),
)

ax_client = AxClient()
ax_client.create_experiment(
    name="moo_experiment",
    parameters=[
        {
            "name": f"x1",
            "type": "range",
            "bounds": [0.0, 1.0],
        },
        {
            "name": f"x2", # modified parameter
            "type": "choice",
            "values": [0.0, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
            "is_ordered": True
        }
    ],
    objectives={
        # `threshold` arguments are optional
        "a": ObjectiveProperties(minimize=False, threshold=branin_currin.ref_point[0]), 
        "b": ObjectiveProperties(minimize=False, threshold=branin_currin.ref_point[1])
    },
    overwrite_existing_experiment=True,
    is_test=True,
)

def evaluate(parameters):
    evaluation = branin_currin(torch.tensor([parameters.get("x1"), parameters.get("x2")]))
    return {"a": (evaluation[0].item(), 0.0), "b": (evaluation[1].item(), 0.0)}

for i in range(50):
    parameters, trial_index = ax_client.get_next_trial()
    # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=evaluate(parameters))

```

**Comment by Balandat** [comment]
The basic MOO model will use a one-hot encoding of the discrete parameters. This model will be chosen as long as there are [more ordered than categorical parameters](https://github.com/facebook/Ax/blob/543a58302c4e10a51f0edddcd283ced812615112/ax/modelbridge/dispatch_utils.py#L179).

It should generally work quite well, but there are some potential issues with this approach that can lead the acquisition optimization to repeatedly suggest the same point, which can be inefficient and cause numerical issues. Once we've cleaned up the modelbridge setup (as mentioned above) we can avoid this by using mixed optimization and properly representing the discrete choices as such.

**Comment by EugenHotaj** [comment]
> Once we've cleaned up the modelbridge setup (as mentioned above)

This should hopefully happen pretty soon. The PRs are already in progress (#764), there's just a couple of failing tests that need to be updated + some minor clean up.

**Comment by fipeop** [comment]
Thank you @EugenHotaj  and @Balandat. Hope we can close this issue when the PR is done, for future reference.

**Comment by fipeop** [comment]
@Balandat I tried MOO with current one-hot encoding and unfortunately is suggesting the same point multiple times, as you mentioned in your previous [comment.](https://github.com/facebook/Ax/issues/765#issuecomment-1001232602)

I am considering forking and making the necessary modification myself. @EugenHotaj  @Balandat I was looking at [#764 ](https://github.com/facebook/Ax/pull/764). After it is completed, how would you choose BO_MIXED as the model for multi-objective optimization? I think we will still need to change the policy in dispatch_utils.py?

**Comment by EugenHotaj** [comment]
@fipeop thanks for the patience on this as people were out for holidays and last week was generally a slow week for Meta.

Yes, I believe `dispatch_utils.py` (and possibly other places) would need to be updated after the PR stack to get rid of `MultiObjectiveTorchModelBridge` lands. I think @Balandat's point was that adding `BO_MIXED` support for MOO will be a lot easier (under the hood) once the mentioned PRs land. This is because currently `BO_MIXED` uses a [`TorchModelBridge`](https://github.com/facebook/Ax/blob/c3cf7f44aa18b2f6f391db301ae7799bf4a0e740/ax/modelbridge/registry.py#L246) while for MOO problems we expect that a [`MultiObjectiveTorchModelBridge`](https://github.com/facebook/Ax/blob/c3cf7f44aa18b2f6f391db301ae7799bf4a0e740/ax/modelbridge/registry.py#L258) will be used.

**Comment by EugenHotaj** [comment]
@fipeop just added support for this in 2562c386fc154b58f6b97c522699bfcf0ca9ba88. Please give it a shot and lmk if you have any comments!
