### ISSUE TITLE
Incorporate domain knowledge in categorial parameters

### ISSUE THREAD

**Issue by Stefan2016** [facebook/Ax#772]
Hi there,

I am thinking about an application where I would like to use Ax to optimize the outcome of chemical reactions by choosing different chemicals within the reaction design. 

At this point I can represent the chemicals to choose from as categorical variables (e.g. by names) similar like this:

`choice_param = ChoiceParameter(name="y", parameter_type=ParameterType.STRING, values=["chemical A", "chemical B"])`

The `values` are given as strings, one for each name. And based on the documentation this parameter design will lead to an one hot encoding schema within Ax.

Question:
As the chemicals are known to me I also have a huge set of descriptors for each of them. Can this domain knowledge be incorporated within Ax?

E. g. I can describe the chemicals by using continuous and discrete variables like "molecular weight", "polar (yes/no)" and "density".

When I think about incorporating this know how I think of something similar like this:

`choice_param = ChoiceParameter(name="y", parameter_type=ParameterType.???, values=["(99.5,1,850.0)", "(87.2,0,990.0)"])`

The name of `Chemical A` is substituted by the descriptors "molecular weight", "polar (yes/no)" and "density": `"(99.5,1,850.0)"`

And ideally the parameters should probably not be handled as strings anymore (e.g. no more one hot encoding).

Is there a way to do this in Ax? If it makes sense?

Thanks and cheers,
Stefan

**Comment by Balandat** [comment]
Hi Stefan, 

How many descriptors do you have for each chemical? If it's of limited size (maybe up to a couple of dozen) then our standard models should be able to manage it. If there are a lot more, then it could make sense to take a fancier approach and try to use some kind of latent embedding of the properties and perform the optimization in that latent space. How many observations do you have? 

If the size is manageable, then @sgbaird's [excellent response](https://github.com/facebook/Ax/issues/706#issuecomment-1007204572) should mostly answer this question. Indeed, you'd encode each descriptor separately as a parameter of the right (numerical or categorical) type, manually add the observations for all the chemicals you have, and then evaluate the acquisition value for each element in the finite set of possible combinations you're interested in trying.

**Comment by lena-kashtelyan** [comment]
Closing this issue as inactive; @Stefan2016, please feel free to reopen if you do have a follow-up! To make sure we see your subsequent comments, make sure the issue is open, as it might take us a bit to see comments on closed issues.

**Comment by sgbaird** [comment]
@Balandat would love to get some additional insight on what you mentioned about the latent embedding. I take it the latent embedding would happen in PyTorch, similar to the example in https://botorch.org/v/0.1.0/tutorials/vae_mnist, correct? Is that a good place to start for what you're describing? I have some basic understanding of (at least the behavior of) generative models like VAEs, GANs, and advection-diffusion models, though maybe VAEs are the most relevant in this context based on my limited understanding of the mechanics of each.

The idea of pairing Ax's strength of "continuous search" with domain knowledge for categorical parameters has come to my mind quite a few times. Aside from a latent space embedding, I'm wondering if there's some notion of extended features in Bayesian optimization - i.e. the model benefits from additional features (appended, not replacing), but only optimizes over the the original features. The [`FixedParameter` class](https://ax.dev/api/core.html#ax.core.parameter.FixedParameter) comes to mind, but I don't think the intention was for a `FixedParameter` to *vary* for every datapoint. The discussion in https://github.com/facebook/Ax/issues/773 related to sequential search spaces also comes to mind. Is it totally nonsensical to try to specify separate `FixedParameter` classes for each of the data points (by e.g. creating a new search space for each datapoint)?

**Comment by Balandat** [comment]
@sgbaird Yeah. There have been a number of papers on this recently, see e.g. https://arxiv.org/pdf/1709.05501.pdf and citations therein and thereof. It would be relatively straightforward to hook something like this up with BoTorch (we should probably put together a tutorial...); unfortunately getting that all integrated with Ax would require some more thinking / work.
