### ISSUE TITLE
Add commonly used plots to `__init__.py`, so they can be available with just `import ax`

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#774]
Here is a minimal reproducer:
```python
import ax
print(ax.__version__)
print(dir(ax.plot))
ax.plot.marginal_effects
```
> ```python
> '0.2.3'
> ['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'base', 'color', 
> 'feature_importances', 'helper', 'pareto_frontier', 'pareto_utils', 'render', 'trace']
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> AttributeError: module 'ax.plot' has no attribute 'plot_marginal_effects'
> ```

When I "go to definition" for `ax.plot` it takes me to a blank `__init__.py`.

Running in VS Code on Windows inside a `conda` environment.

**Comment by sgbaird** [comment]
Digging a bit further, I get a syntax error from trying to import the function directly:
```python
from ax.plot.marginal_effects import plot_marginal_effect
```

> ```bash
> Traceback (most recent call last):
>   File "c:\Users\sterg\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 420, in evaluate_expression
>     compiled = compile_as_eval(expression)
>   File "c:\Users\sterg\.vscode\extensions\ms-python.python-2021.12.1559732655\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_vars.py", line 374, in compile_as_eval
>     return compile(_expression_to_evaluate(expression), '<string>', 'eval')
>   File "<string>", line 1
>     from ax.plot.marginal_effects import plot_marginal_effect
>     ^
> SyntaxError: invalid syntax
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ImportError: cannot import name 'plot_marginal_effect' from 'ax.plot.marginal_effects' (C:\Users\sterg\Miniconda3\envs\crabnet-hyperparameter\lib\site-packages\ax\plot\marginal_effects.py)
> ```

Oddly enough the following works fine despite being `diagnostic` being one of the missing modules:
```python
from ax.plot.diagnostic import interact_cross_validation_plotly
```

**Comment by Balandat** [comment]
Yeah just a question of what we want to surface as `__all__` in the module's `__init__.py`. It probably makes sense to collect a few commonly used top-level functions in there.

**Comment by lena-kashtelyan** [comment]
Merging this into the wishlist for now, but it should be fairly straightforward, so we should be able to attend to this soon! In the meantime, we suggest folks just import the functions they need directly, as @sgbaird suggests above.
