### ISSUE TITLE
Understanding warning: expected argument transform_configs to be of type typing

### ISSUE THREAD

**Issue by xxxkkkccc** [facebook/Ax#781]
Hello! I am trying to use Ax for MOO (following the tutorial) and parallel evaluation of batches. 

I am getting the following warning which I am not understanding, could you please help?

_ax.utils.common.kwargs: `<class 'ax.modelbridge.multi_objective_torch.MultiObjectiveTorchModelBridge'>` expected argument `transform_configs` to be of type typing.Optional[typing.Dict[str, typing.Dict[str, typing.Union[int, float, str, botorch.acquisition.acquisition.AcquisitionFunction, typing.Dict[str, typing.Any], NoneType]]]]. Got {'Winsorize': {'optimization_config': MultiObjectiveOptimizationConfig(objective=MultiObjective(objectives=[Objective(metric_name="displacement", minimize=True), Objective(metric_name="weight_savings", minimize=False)]), outcome_constraints=[OutcomeConstraint(stress <= 12.0)], objective_thresholds=[])}} (type: <class 'dict'>)._

**Comment by bernardbeckerman** [comment]
@xxxkkkccc thanks for reporting this! It looks like a bug - would you please post the entire stacktrace to help me fix?

**Comment by bernardbeckerman** [comment]
@xxxkkkccc It looks like this is part of a [previously reported issue](https://github.com/facebook/Ax/issues/770) so i'm marking this as a duplicate and  #closing. Please follow up on that issue with more questions. Thanks a lot!
