### ISSUE TITLE
Fully Bayesian Modular Botorch Model  (SAASBO in MBM)

### ISSUE THREAD

**Issue by polivucci** [facebook/Ax#795]
Dear developers,

I am deeply appreciating the great work you've done on BOTorch and Ax.

As far as I understand, Fully Bayesian BO is for now restricted to the `qNEI` acquisition and the `SingleTaskGP` surrogate.
What would be the best approach to access the entire BOTorch modelling kit using Fully Bayesian estimation?
Are you plannning anything in this direction?

I thought it would be great to have a Fully Bayesian option within `botorch_modular`,  something along the lines of:
```
class ax.modelbridge.registry.Models(value)
...
FULLYBAYESIAN_MODULAR = 'FullyBayesianBotorchModel'
```
With `FullyBayesianBotorchModel` defined as:
```
from ax.models.torch.botorch_modular.model import BotorchModel
....
class FullyBayesianBotorchModel(FullyBayesianBotorchModelMixin, BotorchModel):
```
which would then allow fully flexible use of the BOTorch components.
Of course I'd be happy to help out on this,
Thank again for the great work!

Paolo

**Comment by Balandat** [comment]
That is correct, unfortunately making the fully Bayesian model fully modular is not straightforward - there are some performance issues with running NUTS on top of standard GPyTorch models, so what we currently do to circumvent those is to do this on a custom reimplementation of the model in pure PyTorch  and then loading samples from the hyper parameter posterior into a batched BoTorch model. This make it quite hard to do this for general kernels / likelihoods. Modularizing the acquisition function should be easier, however. 

We have some work planned to allow setting up a fully Bayesian model via the modular BoTorch model set up as well (under the aforementioned limitations on the models we can use for this). 

More long term we hope to be able to eliminate the performance issues I mentioned (though that will require more work also on the GPyTorch and PyTorch end).

**Comment by polivucci** [comment]
Hi @EugenHotaj, @Balandat,

Thank you for the very helpful replies!

I'm glad to hear you have some work planned on modularising fully bayesian inference.
I think many people like me working on low-dimensional, sparse-data problems, would find such functionality worth a try.

If I understand correctly, at the moment the standard way to make a botorch gp model fully bayesian entails rewriting and "hard-coding" it as done [here](https://github.com/facebook/Ax/blob/e4a94e2461e69de096756dd69a7f7db3b97a4d78/ax/models/torch/fully_bayesian.py),  (which I believe is what you were mentioning). If I may ask, for how many botorch gp models are you planning to do this? Are also multi-task or multi-fidelity botorch models in the works? 

Thank you

**Comment by Balandat** [comment]
> If I understand correctly, at the moment the standard way to make a botorch gp model fully bayesian entails rewriting and "hard-coding" it as done [here](https://github.com/facebook/Ax/blob/e4a94e2461e69de096756dd69a7f7db3b97a4d78/ax/models/torch/fully_bayesian.py), (which I believe is what you were mentioning). If I may ask, for how many botorch gp models are you planning to do this? Are also multi-task or multi-fidelity botorch models in the works?

That is correct. We don't have plans to go down a laundry list of models and convert them one by one (too much manual work), but we have have implemented a multi-task version that currently lives in our internal codebase. 

@dme65 and @qingfeng10, are there any blockers keeping us from moving the multi-task SAASBO model into OSS?

**Comment by lena-kashtelyan** [comment]
This functionality is now on latest! To set up the generation strategy:

```
from botorch.models import SaasFullyBayesianSingleTaskGP
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models

GenerationStrategy(
    steps=[
        # Quasi-random initialization step
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
        ),
        # Bayesian optimization step using the custom acquisition function
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            # For `BOTORCH_MODULAR`, we pass in kwargs to specify what surrogate or acquisition function to use.
            model_kwargs={
                "surrogate": Surrogate(SaasFullyBayesianSingleTaskGP),
            },
        ),
    ]
)
```

This will also be included in the next stable release of Ax.

**Comment by lena-kashtelyan** [comment]
This is now on latest stable: 0.2.5.1 : )
