### ISSUE TITLE
One error about human_in_the_loop.ipynb

### ISSUE THREAD

**Issue by yuanquan010** [facebook/Ax#798]
Hello, for the file human_in_the_loop.ipynb in the tutorials of Ax, there is an error on importing DEPRECATED_DECODER_REGISTRY.  How can we correct it?
![image](https://user-images.githubusercontent.com/54976645/152710475-0256a220-e25b-4b24-8367-bd129e1ba4e6.png)

**Comment by EugenHotaj** [comment]
@mpolson64 do you mind taking a look? Not sure if this was recently fixed with #797 or if it's a new issue.

**Comment by mpolson64** [comment]
Ah, sorry for the confusion! At any given moment there are a many changes going on in the Ax codebase, and it looks like what has happened is you've found the human-in-the-loop tutorial from our main branch but I suspect you're running Ax's last stable release. There are two solutions you could move forward with to run the tutorial: downloading the tutorial from the latest stable release v0.2.3 (which we would recommend) or building Ax from the main branch (which I would advise against). Let us know if you have any trouble with this or if you have any other questions.
