### ISSUE TITLE
Incomplete dependencies when installing Ax with notebook option

### ISSUE THREAD

**Issue by robertocalandra** [facebook/Ax#80]
When installing Ax with notebook options (via pip3 install git+ssh://git@github.com/facebook/Ax.git#egg=Ax[notebook]), Cython needs to be installed manually (or otherwise the installation throw an error). 
Would it be possible to either include it in the setup or add this bit of info into the documentation?

**Comment by kkashin** [comment]
Thanks for raising this @robertocalandra - we're going to restructure the installation page in the next few days to make this more explicit and to also more clearly differentiate between the stable version of the library and the latest master version.

**Comment by kkashin** [comment]
@robertocalandra - this has been updated on the [latest version of the site ](https://ax.dev/versions/latest/docs/installation.html)(and will roll out to stable once we push a new release).

It's also been updated in the [repo README](https://github.com/facebook/Ax).
