### ISSUE TITLE
Troubleshooting MOO points focused in small region of search space (via looking at acquisition function values)

### ISSUE THREAD

**Issue by du-210** [facebook/Ax#800]
I'm working on a multi-objective problem and I'd like to render acquisition plots in each iteration. I looked at available plotting utils but doesnt seem there is any for my purpose. Is there an easy way to implement these plots or is it something that will be released in the next versions?

**Comment by lena-kashtelyan** [comment]
Hi @du-210! Could you provide a bit more detail for the type of plot you are looking for? What would be the data being visualized?

**Comment by du-210** [comment]
Hi @lena-kashtelyan, I am trying to optimise a function that I know roughly how the optimal pareto front should look like. But when I run MOO, after the first few optimisation iterations, nearly all generated points concentrated on a small region of the optimal pareto front. I need to understand why this happens. I am able to diagnose my surrogate models using Ax plotting utils but I'm in dark when it comes to acquisition function. Note that I am quite new to the world of MOO so if you think the ACF plot is not what I need to look into, please advice me to a right direction. Thanks

**Comment by lena-kashtelyan** [comment]
Hi @du-210, sorry for the delay on this. My understanding was that you would like to know how to approach the fact that the first few trials in your MOO optimization end up concentrated in a small region of the search space, correct?

I think looking into model fit (which you've already been doing with the help of the plot) and into the values of the acquisition function for the generated trials seems reasonable. Unfortunately, doing the latter is a bit non-trivial currently, but next stable version release of Ax will have a more convenient interface for it. When that version is released (which should be towards the end of this week), we'll provide you with an example!

However, I think also just looking at the acquisition function values might not be enough –– if Ax is picking those points in the small region, likely you will just see that those points have high acquisition function values, but it won't necessarily be clear why that is, I think? To that effect, I suggest you provide a more detailed repro so we can look into this for you. For a full repro:
- Please show how you are setting up your experiment, what the search space is, and approximately what values your metrics take on. 
- Also paste the dataframe for your experiment (output of `ax.service.utils.report_utils.exp_to_df(ax_client.experiment)` too.

**Comment by eytan** [comment]
cc @sdaulton

**Comment by sdaulton** [comment]
Hmm it kind of looks like Ax is minimizing both objectives in the later iterations.

What are the inferred objective thresholds? Do these seem reasonable.

What does the cross validation for each model look like? Is the model for one objective much more accurate than the model for the other? If one model is better than the other, then the candidates may be biased toward a region with more certainty about improvement.

How far off is this PF from the true PF? Mostly wondering if this is already nearly converged

**Comment by lena-kashtelyan** [comment]
@du-210, do you have any thoughts on @sdaulton's comment above?

**Comment by du-210** [comment]
Hi @sdaulton, sorry for the late reply.

- The inferred thresholds seem reasonable. I have also tried setting them to fixed values [69, 5] but the optimal PF is still localised to a corner. However, by setting the thresholds to [85, 5], I get better diversity and convergence to the true PF. 
- Both objective models are quite accurate. 
- The PF converges to the true PF after ~30 iterations but it doesn't diversify over the entire true PF.

**Comment by lena-kashtelyan** [comment]
Sorry for delay @du-210, @sdaulton do you have thoughts on how to proceed with figuring this out?

**Comment by sdaulton** [comment]
Has this been resolved? My hunch is that that the PF is nearly converged and the model believes that the greatest potential improvements in hypervolume will come from the left bottom corner.

The coverage also looks pretty good along the identified PF. What does the true PF look like? 

It is surprising that 85,5 works better than 69, 5, since the former would give no hypervolume to observed points with f0 <= 85. The former reference point could be useful for targeting the optimization towards the upper right corner in the later iterations.

What does the leave-one-out cross validation look like for each model? What is the noise level (inferred by the model or supplied to the model)?

A repro, if possible, would be very helpful. Thanks!

Can you provide

**Comment by lena-kashtelyan** [comment]
cc @du-210

**Comment by lena-kashtelyan** [comment]
Closing as inactive. Please reopen if following up.
