### ISSUE TITLE
Can anybody offer more detail about the interface of the runner?

### ISSUE THREAD

**Issue by yuanquan010** [facebook/Ax#801]
Hello, thanks a lot for this great project, I am new to Bayesian optimization.
I want to use Bayesian optimization to optimize some parameters of an Abaqus simulation model and in my understanding, the simulation model should be considered as a Runner for the trial. However, the examples about the runner in the tutorial are very brief. Can anyone tell me how to define the runner? Such as how to use the design parameters (arm), and the form of the simulation results to be returned.
 
![image](https://user-images.githubusercontent.com/54976645/152944422-59d5028c-dcbb-46cf-bf05-b686cc15d754.png)
What'more, the parameters can be transferred into the simulation model by command line, and the simulation results can be written in a CSV or txt file.

**Comment by lena-kashtelyan** [comment]
Hello @yuanquan010! You could consider using the Service API (tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html), in which case you will not need to implement your own runner. Does that work for your use case do you think? If not, let me know why, and I'll be happy to help out with setting up a runner!

**Comment by yuanquan010** [comment]
> Hello @yuanquan010! You could consider using the Service API (tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html), in which case you will not need to implement your own runner. Does that work for your use case do you think? If not, let me know why, and I'll be happy to help out with setting up a runner!
 
Thanks for your reply, the service API can work for my case.   An additional question is how to get the value of acquisition function. I want to visualize it to show the optimization process.

**Comment by yuanquan010** [comment]
Hello， now I am using service API to optimize the simulation. But there were two problems that I can not understand, and maybe they are related.
This first problem is some warning appears. I am trying to optimize a 20-dimensional problem and hope to do 60 trials and the generation strategy steps are 40 for Sobol sampling and 10 For GPEI. However, at the 39th trial, a Warning appears and I can not understand its meaning, can anyone explain it to me?
![image](https://user-images.githubusercontent.com/54976645/153829650-657ea158-2c9c-4a03-aec9-c18718bc63ce.png)
And the second problem is that when the optimization is over, I draw the optimization trace and get the model predictions, however, the actual prediction results are not consistent with the results shown in the trace plot.  
The following is the optimization trace.
![image](https://user-images.githubusercontent.com/54976645/153830239-5a0e12f0-be27-4a7d-9fb5-f5de830cf22b.png)
We can find the value of ETC from 10th to 20th iterations is smaller than 0.13, however, in the actual prediction results, only the value of the 19th iteration is smaller than 0.13.
The following is the figure of actual prediction results.
![image](https://user-images.githubusercontent.com/54976645/153830723-9475cca3-307f-47b5-b108-dccf41e3f2f1.png)
![image](https://user-images.githubusercontent.com/54976645/153830761-591f7f65-3e5a-4b1f-a999-161268318d7f.png)
![image](https://user-images.githubusercontent.com/54976645/153830815-ae858874-4f98-43e9-b4fe-bb1c7c6a40d8.png)
![image](https://user-images.githubusercontent.com/54976645/153830901-14e7bc3d-8030-4068-b433-38308c030671.png)

And for the trace plot, if we use the Sobol sampling, why does the value decline gradually. It's said that the Sobol sampling is a quasi-random process, why aren't there any fluctuations?

**Comment by lena-kashtelyan** [comment]
> However, at the 39th trial, a Warning appears and I can not understand its meaning, can anyone explain it to me?

Are you referring to the warning that comes from `ax.utils.common.kwargs` in your screenshot? If so, see this issue: https://github.com/facebook/Ax/issues/770. The fix for this is now on master and will be part of the next stable version release.

> the second problem is that when the optimization is over, I draw the optimization trace and get the model predictions, however, the actual prediction results are not consistent with the results shown in the trace plot.

Would you mind opening a separate issue about this, since this is not really related to your previous question, so we can keep the discussion organized? You can just copy the information in your comment in this issue there. Thank you!

>  I am trying to optimize a 20-dimensional problem and hope to do 60 trials and the generation strategy steps are 40 for Sobol sampling and 10 For GPEI.

It seems like you are doing a lot of Sobol trials, you could do more GPEI trials instead. We can discuss this on the separate issue you open about predictions not matching the values you see in the plot. Thank you!

**Comment by lena-kashtelyan** [comment]
> And for the trace plot, if we use the Sobol sampling, why does the value decline gradually. It's said that the Sobol sampling is a quasi-random process, why aren't there any fluctuations?

The answer to this is that the plot shows the "best objective found by Nth trial", if that makes sense. So it doesn't show all points that were found, just the best cumulative value found. To see all points that were tried and their objectives, you can do this to see all trials in a convenient dataframe:

```
from ax.service.utils.report_utils import exp_to_df
exp_to_df(ax_client.experiment)
```
Here are the API docs for `exp_to_df` and the inputs that it takes: https://ax.dev/api/service.html#ax.service.utils.report_utils.exp_to_df

**Comment by lena-kashtelyan** [comment]
I will close this issue as it was answered with switching to the Service API; for you question about the model predictions and plots mismatch, we'll expect a new issue from you, @yuanquan010!

**Comment by yuanquan010** [comment]
> 

Thanks for your reply, you have answered all my questions. Do you still hope I open a separate case to ask the same question? If you want I can do it. Sorry for I asked unrelated questions in one case.
