### ISSUE TITLE
Bayesian optimization with zero gradient zones

### ISSUE THREAD

**Issue by Kh-im** [facebook/Ax#806]
Hello,

I use Ax for an optimization problem with two variables (maximization). The problem is there are zones within the search space where the objective function has always the same value, for example : for a search space x : [0.0, 10.0] and a "zone" x : [2.0, 5.0], f(x)=4.0. 

Is this something difficult for the algorithm ? Is there a strategy that is recommended  for this kind of space ?

Regards

**Comment by eytan** [comment]
This shouldn't be inherently problematic, especially if the flat space doesn't constitute a majority of your search space, and there isn't a sudden transition from 4.0 to whatever other values.  It's possible that [input warping](https://arxiv.org/pdf/1402.0929.pdf) could help here.  This is supported in Ax but it isn't well documented.  Perhaps @sdaulton could give you pointers if you wanted to try this out.

**Comment by Balandat** [comment]
Closing this out since this doesn't actually seem to be an issue. Feel free to reopen if you're running into problems.
