### ISSUE TITLE
Allow users to easily choose to run optimization on GPU in Service API

### ISSUE THREAD

**Issue by Balandat** [facebook/Ax#811]
Currently that only seems possible by passing in a custom Generation Strategy with the appropriate kwargs. We don't want users to have to dig into the details of this if they want to run the optimization on a GPU (which is going to be a lot faster especially for our MOO algorithms).

**Comment by sgbaird** [comment]
For visibility, to specify `torch_device` in a custom generation strategy:
```python
gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,
        ),
        GenerationStep(
            model=Models.GPEI,
            num_trials=-1,  
            model_kwargs = {"torch_device": torch.device("cuda")},
        ),
    ]
)

exp = AxClient(generation_strategy = gs)
```
https://github.com/facebook/Ax/issues/678#issue-979292175

Cross-posting this in https://github.com/facebook/Ax/pull/821
