### ISSUE TITLE
Can we use the Sum constraint in service API, and how can we set the runner in the developer API?

### ISSUE THREAD

**Issue by yuanquan010** [facebook/Ax#817]
Hello, thanks for the great project.
I want to set a sum constraint of parameters in ax_client.create_experiment, but it seems not supported. How can I solve this problem?
The following is the codes:
```
# Set up experiment
import numpy as np 
L = 3.96 # The size of RVE
P = 0.2 # The porosity of air
w = 0.3 # The smallest printing wall thickness
upper_a = (L**2)*P/(0.15*np.pi)
lower_a = (L**2)*P*2/((L-0.3)*np.pi)

ax_client.create_experiment(
    name="ETC_optimization",
    parameters = [
        {
            "name": "a",
            "type": "range",
            "bounds":[0.15, (L-0.3)/2],
            "value_type": "float",
            "log_scale": False,
        },
        {
            "name": "theta",
            "type": "range",
            "bounds":[0, np.pi],
            "value_type": "float",
        },
    ],
    objective_name="ETC",
    minimize=True, # Optional, defaults to False.
    parameter_constraints=["a >= lower_a","a <= upper_a"]
)
```
The error is like that:
![image](https://user-images.githubusercontent.com/54976645/155269214-64505e78-0611-406e-94e6-5bd259c355f9.png)
![image](https://user-images.githubusercontent.com/54976645/155269240-4a70e2c4-1bff-4832-83d0-bb95d61e3eb9.png)
![image](https://user-images.githubusercontent.com/54976645/155269268-2e07d743-b6ba-44ec-81b7-ce7682726527.png)
So can we can a bound by using an outside variable?

The questions is that I solve the above by using develop API, but I do not know how to set the runner, and there is no more detail about runner in the tutorial. I guess the evaluate function in service API should be included in the custom metric, is it right?
The following are the relative codes:
```
# Create Search Space
import numpy as np 
L = 3.96 # The size of RVE
P = 0.2 # The porosity of air
w = 0.3 # The smallest printing wall thickness

from ax import ParameterConstraint
param_a = RangeParameter(name=f"a", parameter_type=ParameterType.FLOAT, lower=0.15, upper= (L-w)/2)
param_theta = RangeParameter(name=f"theta", parameter_type=ParameterType.FLOAT, lower=0, upper= np.pi)

upper_a = (L**2)*P/(0.15*np.pi)
lower_a = (L**2)*P*2/((L-0.3)*np.pi)
con_1 = SumConstraint(parameters=[param_a], is_upper_bound=False, bound=lower_a)
con_2 = SumConstraint(parameters=[param_a], is_upper_bound=True, bound=upper_a)
search_space = SearchSpace(
    parameters=[param_a, param_theta], parameter_constraints=[con_1,con_2]
)
```
And the custom metric is like that：

```
# Defining custom metrics
from typing import Any, List, Optional, Callable
from ax.metrics.noisy_function import NoisyFunctionMetric
from ax.utils.common.typeutils import checked_cast
from ax.core.types import TParameterization
import os
class ETCMetric(NoisyFunctionMetric):
    def __init__(
        self,
        name: str,
        param_names: List[str],
        noise_sd: Optional[float] = 0.0,
        lower_is_better: Optional[bool] = None,
    ) -> None:

        self.noise_sd = noise_sd
        super().__init__(name=name,param_names = param_names, lower_is_better=lower_is_better)
    def _evaluate(self, params: TParameterization) -> float:
        x = np.array([params[p] for p in self.param_names])
        np.savetxt('parameter.csv', x, delimiter=',')   
        run_filename = 'Ellipsoid_2d.py'
        command = 'abaqus cae noGUI' + '=%s' % run_filename
        os.system(command)
        xx = np.loadtxt('ETC.csv') 
        # In our case, standard error is 0, since we are computing a synthetic function
        return xx[5]
```
Here, the simulation software is the external system to get the parameters (arm) and calculate the ETC (outputs).
Would you like to help me to build a Runner? I just use the following runner,
```
from ax import Runner

class MyRunner(Runner):
    def run(self, trial):
        trial_metadata = {"name": str(trial.index)}
        return trial_metadata
```
And it seems that the parameters are not transported into the simulation software.

**Comment by danielcohenlive** [comment]
Thanks again for the question, @yuanquan010!  You can still use the service API.  The function that evaluates the param constraint string does not have a reference to outside variables, but `upper_a` and `lower_a` do seem to be constants, so you could just rewrite the line as 
```python
    parameter_constraints=[f"a >= {lower_a}", f"a <= {upper_a}"]
```
or
```python
    parameter_constraints=['a >= 0.5455309629704624', 'a <= 6.655477748239643']
```
To step up a level though, you shouldn't have to do that.  These constraints are basically functioning as a separate set of "bounds", so you should just be able to determine the actual bounds you want for the parameter "a" as an intersection of the bounds you already have and those constraints, which turns out to be `[0.5455309629704624, 1.83]`.

> And it seems that the parameters are not transported into the simulation software.

By this do you mean that `ETCMetric._evaluate` is not being called?  I'm not seeing a `Metric. _evaluate` in our code.  You want to define `fetch_trial_data` like in the [tutorial](https://ax.dev/tutorials/gpei_hartmann_developer.html#8.-Defining-custom-metrics) if you do use the Developer API.
