### ISSUE TITLE
Using ax.early_stopping with the Loop API

### ISSUE THREAD

**Issue by adwaykanhere** [facebook/Ax#824]
Hi,

I'm new to Ax and I'm following your [tune_cnn](https://ax.dev/tutorials/tune_cnn.html) tutorial. I would like to implement [early stopping](https://ax.dev/api/early_stopping.html) during training but couldn't seem to find any documentation for the same. 

Please advise on how to implement this.

Thanks!

**Comment by Balandat** [comment]
I don't think we currently support early stopping as part of the loop API. We do, however, as part of the service API. For a general service API example see https://ax.dev/tutorials/gpei_hartmann_service.html. For the early stopping part, you'd use https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L1007-L1028. (note that this will require running the most recent dev version, as the latest stable release does not yet have this functionality). 

I believe @danielrjiang is working on putting together a tutorial for early stopping, maybe he has some preliminary version that he could share.

**Comment by adwaykanhere** [comment]
Thank you! Looking forward to checking out the Service API in the stable version.

**Comment by lena-kashtelyan** [comment]
The new table version is now released, so the link @Balandat added above: https://github.com/facebook/Ax/blob/main/ax/service/ax_client.py#L1017 shows the method that will be useful for leveraging early-stopping in the Service API. I opened a separate issue for adding a tutorial for the early-stopping functionality to our website: https://github.com/facebook/Ax/issues/851; feel free to ask any questions you have in that issue while the work on the tutorial is in progress @adwaykanhere!

**Comment by adwaykanhere** [comment]
Thanks, @lena-kashtelyan, and @Balandat!
