### ISSUE TITLE
No module named ax

### ISSUE THREAD

**Issue by hbrachemi** [facebook/Ax#837]
I'm currently trying to tune my hyperparametters using scripts and procedure calls, I made sure the package is installed, the same code works fine in the colab notebook but generates a "No module named 'ax' " ImportError when calling it from a .py file

**Comment by EugenHotaj** [comment]
Hey @hbrachemi, could you provide more details on your setup? How did you install Ax locally? What is the code that you're trying to run which works on Colab but not locally?

**Comment by Balandat** [comment]
Are you sure you're calling the .py script in the same python environment that you installed Ax into? Sounds like that might not be the case here.

**Comment by lena-kashtelyan** [comment]
Hi @hbrachemi, do you think you could post a printout of your dev environment, within which you are running colab? We are not sure how to reproduce the issue you are facing.

**Comment by EugenHotaj** [comment]
@hbrachemi haven't heard from you in a while so going to assume this is no longer and issue and close this out. Please feel free to reopen or create a new task if necessary.
