### ISSUE TITLE
`plot_marginal_effects` not functional for SAASBO model

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#846]
@dme65 @lena-kashtelyan IIRC, `plot_marginal_effects` produces the appropriate plot skeleton but without any data from what I can tell.

Happy to provide a reproducer if desired. This is non-blocking for me, but I figured it's always better to post about things like this if I come across them.

**Comment by dme65** [comment]
I took a look and I don't think this is an issue with SAASBO. `plot_objective_vs_constraints` works as expected, but I assume you got that one to work given that you removed it from the title. `plot_marginal_effects` also seems to work, but it places all plots in one row which makes them very hard to read even for the 10-dimensional toy problem I'm using. I'm assuming you have even more parameters than that which may result in the plot being unreadable.  

cc: @bernardbeckerman, @lena-kashtelyan as they likely know more about `plot_marginal_effects` than I do.

**Comment by lena-kashtelyan** [comment]
Hi @sgbaird, could you post a repro actually here? Not sure what the status of this issue is, and it might be tough to debug without having the repro.

**Comment by sgbaird** [comment]
@lena-kashtelyan ok!

**Comment by lena-kashtelyan** [comment]
Going to close this one as inactive for now; please reopen when you have a repro, @sgbaird! : )
