### ISSUE TITLE
SAASBO set a new state-of-the-art benchmark for a materials science problem via hyperparameter optimization

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#847]
@dme65 @lena-kashtelyan @Balandat See [`matbench_expt_gap` leaderboard](https://matbench.materialsproject.org/Leaderboards%20Per-Task/matbench_v0.1_matbench_expt_gap/) (experimental band gap measurements). Ax/SAASBO optimization of 23 hyperparameters of an attention-network transformer materials informatics model (CrabNet) in 100 iterations without prior assumptions (except for constraints on the search space) set a new state-of-the-art benchmark. Writing up a manuscript over the weekend before moving to bigger fish 🎣, and will post it here when it's up on a preprint server. Feel free to close, but wanted to share the news. Thank you for all the help in working on this! This is the first of several manuscripts I'm hoping to write related to Ax and SAASBO applied to materials informatics problems.

**Comment by Balandat** [comment]
This is great news, thank you for sharing! I'll close out the issue to keep GitHub tidy, but I'm very much looking forward to learning more about the details in the manuscript and future bigger fish!
