### ISSUE TITLE
Support `botorch_modular.BoTorchModel.feature_importances`

### ISSUE THREAD

**Issue by yuanquan010** [facebook/Ax#850]
Hello, thanks for the previous help. Now I face a new problem.
I am trying to use a new generation strategy. However, the feature importance plot can not be drawn.
The following is the code of the generation strategy.
```
gs = GenerationStrategy(
    steps=[
        # Quasi-random initialization step
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
        ),
        # Bayesian optimization step using the custom acquisition function
        GenerationStep(
            model=Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            # For `BOTORCH_MODULAR`, we pass in kwargs to specify what surrogate or acquisition function to use.
            model_kwargs={
                "surrogate": Surrogate(SingleTaskGP),
                "botorch_acqf_class": qNoisyExpectedImprovement
            },
        ),
    ]
)
```
The following figure is the error:
![image](https://user-images.githubusercontent.com/54976645/158173674-56550556-cdb7-43e0-9cf3-eff7f2ce8ad7.png)
Here, the singleTaskGp is used as the surrogate model, is it not a Gaussian process?

**Comment by yuanquan010** [comment]
> 
Actually, I used 100 trials. The following figure shows the code.
![image](https://user-images.githubusercontent.com/54976645/158381729-f7424f71-0b17-4b94-b078-327a93768000.png)
Based on the Cross-validation plot, it looks okay.
![image](https://user-images.githubusercontent.com/54976645/158382173-ce5316ae-16c1-4b3c-b0dc-b3fb16e16130.png)

**Comment by yuanquan010** [comment]
> > 
> 
> Actually, I used 100 trials. The following figure shows the code. ![image](https://user-images.githubusercontent.com/54976645/158381729-f7424f71-0b17-4b94-b078-327a93768000.png) Based on the Cross-validation plot, it looks okay. ![image](https://user-images.githubusercontent.com/54976645/158382173-ce5316ae-16c1-4b3c-b0dc-b3fb16e16130.png)

Another thing worth mentioning is that when I come back to use models.GPEI in the generation strategy, as shown in the following figure.
![image](https://user-images.githubusercontent.com/54976645/158382652-71c14e24-f65e-49c7-a7d0-40b764032717.png)

I can get the feature importance,  but the GP model can not fit well.
![image](https://user-images.githubusercontent.com/54976645/158382867-3812f2f3-1d41-46eb-8913-920b015f8ea2.png)
![image](https://user-images.githubusercontent.com/54976645/158382911-642bdbfc-e95f-4e0f-bf7c-205ed62533df.png)
In the above two experiments, only the generation strategy is changed. Is there some internal connection in these errors?

**Comment by yuanquan010** [comment]
> Could you trigger the "Show CI" selector on the plot as well? It would be good to also understand how well calibrated these models are.
Here are the above CV plots with CI
![image](https://user-images.githubusercontent.com/54976645/158496218-381583ea-5881-4e85-9291-a9136e4c2888.png)
![image](https://user-images.githubusercontent.com/54976645/158496248-5b3a96e8-b7fa-45a2-830a-621fd1689995.png)

**Comment by yuanquan010** [comment]
> From a chat with @lena-kashtelyan: "I think the user is seeing this issue because the modular BotAx model doesn't implement `feature_importances` method, so it's falling back to the one in base Model class," which just produces a [`NotImplementedError`](https://github.com/facebook/Ax/blob/c5466712e246ef78981c385e852aedfe02bd397e/ax/models/base.py#L54-L57). Accordingly, I'm turning this into a feature request. Thanks so much for reporting, and please let me know if you have any more questions!

Yep, thank you. But why the GP model does not fit well in the second experiment?

**Comment by Balandat** [comment]
Not sure. This is not on the same data, right? But it is using the same data generating process?

**Comment by yuanquan010** [comment]
> Not sure. This is not on the same data, right? But it is using the same data generating process?

Yes, they are from the same simulation program, but the not the same data

**Comment by Balandat** [comment]
Is the simulation program noisy in the sense that evaluating the same configuration can yield different results? If so, are you passing in either a known SEM value for the observation or a NaN (which means that the noise level is inferred)?

If the observations are noisy, then one possible reason for the second run to result in a bad model fit is that you got really unlucky with the noise realizations and the noise is drowning out the signal. Another one is that the marginal log likelihood (the loss we're optimizing to fit the model) is multimodal and the optimization got stuck in a local minimum. It could be enough to re-fit the model. You could also try using the SAASBO model (see https://ax.dev/tutorials/saasbo.html) that should be a lot more robust to these kind of issues.

**Comment by bernardbeckerman** [comment]
Closing this out since it's been a while but @yuanquan010 please feel free to re-open if you're still having issues.

**Comment by lena-kashtelyan** [comment]
This will remain open for now as a feature request to support `botorch_modular.BoTorchModel.feature_importances`

**Comment by dme65** [comment]
Closing as this functionality was added by https://github.com/facebook/Ax/pull/1551!
