### ISSUE TITLE
Is there a way to calculate the expected hypervolume improvement for a certain point in the search space?

### ISSUE THREAD

**Issue by EvanClaes** [facebook/Ax#854]
Hi all,

I'm currently testing the service API for multi-objective optimization.

After an iteration, I would like to calculate the expected hypervolume improvement for a certain point in the search space (specified by me). Is this possible? Or do I need to use Botorch for this?

Thanks!

**Comment by bernardbeckerman** [comment]
Hi @EvanClaes, let me take a look and get back to you!

**Comment by bernardbeckerman** [comment]
The function you want is [`ModelBridge.evaluate_acquisition_function`](https://github.com/facebook/Ax/blob/main/ax/modelbridge/base.py#L825-L836). Let me know if that answers your question!

**Comment by EvanClaes** [comment]
Hello Bernard,

Thanks a lot for your reply. I tried your function on the model fitted according to this tutorial: [](https://ax.dev/tutorials/multiobjective_optimization.html)

I'm trying:

`ehvi_model.evaluate_acquisition_function(np.array([1,1]))`

The error I get is the following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_26972/3581126695.py in <module>
----> 1 ehvi_model.evaluate_acquisition_function(np.array([1,1]))

TypeError: evaluate_acquisition_function() missing 2 required positional arguments: 'search_space_digest' and 'objective_weights'

Although the documentation seems to suggest that evaluate_acquisition_function() only requires one argument, with the rest being optimal...

Has it something to do with the type of ehvi_model? This is:

<ax.modelbridge.multi_objective_torch.MultiObjectiveTorchModelBridge

**Comment by Balandat** [comment]
@EvanClaes looks like you're on an older version of Ax? We actually changed this interface recently to make it easier to use, the current release 0.2.4 should have the new API: https://github.com/facebook/Ax/blob/0.2.4/ax/modelbridge/base.py#L825-L836

**Comment by bernardbeckerman** [comment]
@Balandat I may be missing something but it seems like `search_space_digest` and `objective_weights` args are required by [`ax.models.torch.botorch_modular.model.BoTorchModel.evaluate_acquisition_function`]. I'll make a task so that the behaviors of `botorch_modular` and `base` modelbridges are more consistent.

**Comment by Balandat** [comment]
@bernardbeckerman you are correct that these are required on the level of the model API, but they are not require on the level of the modelbridge API. The conversion / extraction of the appropriate containers is happening here as this is being called from within the modelbridge: https://github.com/facebook/Ax/blob/0.2.4/ax/modelbridge/array.py#L483-L511

**Comment by bernardbeckerman** [comment]
Ah, thank you! Ok @EvanClaes lmk if upgrading to the current release fixes your problem : )

**Comment by EvanClaes** [comment]
Hello Max, Bernard,

Thanks for the feedback. I will try this in the coming days and let you know...

**Comment by EvanClaes** [comment]
Hello Bernard,

I got a little further but still getting an error... Below you can find my 'minimal' example (mostly taken from one of the tutorials). I guess I'm not making the observationfeatures object correctly?

`import pandas as pd
from ax import *

import numpy as np

from ax.metrics.noisy_function import NoisyFunctionMetric
from ax.service.utils.report_utils import exp_to_df
from ax.runners.synthetic import SyntheticRunner

# Factory methods for creating multi-objective optimization modesl.
from ax.modelbridge.factory import get_MOO_EHVI, get_MOO_PAREGO

# Analysis utilities, including a method to evaluate hypervolumes
from ax.modelbridge.modelbridge_utils import observed_hypervolume

# Load our sample 2-objective problem
import torch
from botorch.test_functions.multi_objective import BraninCurrin
branin_currin = BraninCurrin(negate=True).to(
    dtype=torch.double, 
    device= torch.device("cuda" if torch.cuda.is_available() else "cpu"),
)

x1 = RangeParameter(name="x1", lower=0, upper=1, parameter_type=ParameterType.FLOAT)
x2 = RangeParameter(name="x2", lower=0, upper=1, parameter_type=ParameterType.FLOAT)

search_space = SearchSpace(
    parameters=[x1, x2],
)

class MetricA(NoisyFunctionMetric):
    def f(self, x: np.ndarray) -> float:
        return float(branin_currin(torch.tensor(x))[0])
    
class MetricB(NoisyFunctionMetric):
    def f(self, x: np.ndarray) -> float:
        return float(branin_currin(torch.tensor(x))[1])

metric_a = MetricA("a", ["x1", "x2"], noise_sd=0.0, lower_is_better=False)
metric_b = MetricB("b", ["x1", "x2"], noise_sd=0.0, lower_is_better=False)

mo = MultiObjective(
    objectives=[Objective(metric=metric_a), Objective(metric=metric_b)],
)

objective_thresholds = [
    ObjectiveThreshold(metric=metric, bound=val, relative=False)
    for metric, val in zip(mo.metrics, branin_currin.ref_point)
]

optimization_config = MultiObjectiveOptimizationConfig(
    objective=mo,
    objective_thresholds=objective_thresholds,
)

# Reasonable defaults for number of quasi-random initialization points and for subsequent model-generated trials.
N_INIT = 6
N_BATCH = 2

def build_experiment():
    experiment = Experiment(
        name="pareto_experiment",
        search_space=search_space,
        optimization_config=optimization_config,
        runner=SyntheticRunner(),
    )
    return experiment

## Initialize with Sobol samples

def initialize_experiment(experiment):
    sobol = Models.SOBOL(search_space=experiment.search_space, seed=1234)

    for _ in range(N_INIT):
        experiment.new_trial(sobol.gen(1)).run()

    return experiment.fetch_data()

ehvi_experiment = build_experiment()
ehvi_data = initialize_experiment(ehvi_experiment)

ehvi_hv_list = []
ehvi_model = None
for i in range(N_BATCH):   
    ehvi_model = get_MOO_EHVI(
        experiment=ehvi_experiment, 
        data=ehvi_data,
    )
    generator_run = ehvi_model.gen(1)
    trial = ehvi_experiment.new_trial(generator_run=generator_run)
    trial.run()
    ehvi_data = Data.from_multiple_data([ehvi_data, trial.fetch_data()])
    
    exp_df = exp_to_df(ehvi_experiment)
    outcomes = np.array(exp_df[['a', 'b']], dtype=np.double)
    try:
        hv = observed_hypervolume(modelbridge=ehvi_model)
    except:
        hv = 0
        print("Failed to compute hv")
    ehvi_hv_list.append(hv)
    print(f"Iteration: {i}, HV: {hv}")

ehvi_outcomes = np.array(exp_to_df(ehvi_experiment)[['a', 'b']], dtype=np.double)


#try evaluate_acquisition_function
x = np.array([0.20314397, 0.42122987])
param_dict = {
    pname: x[i]
    for i, pname in enumerate(ehvi_experiment.search_space.parameters.keys())
}
obsf = ObservationFeatures(parameters=param_dict)  

ehvi_model.evaluate_acquisition_function(obsf)`

**Comment by bernardbeckerman** [comment]
Hi @EvanClaes, I believe one issue is that `ehvi_model.evaluate_acquisition_function` takes a list of `ObservationFeatures` as an argument, so that the input should be `[obsf]` rather than bare `obsf`. It seems though that `evaluate_acquisition_function` is not implemented for the model type you're using (`MultiObjectiveBotorchModel`, obtained via `get_MOO_EHVI()`), so even fixing that issue won't get you all the way there. I'll turn this issue into an `enhancement` and hopefully we can get to it soon!

cc @Balandat in case there are any workarounds for the time being that I'm unaware of.

**Comment by Balandat** [comment]
So we're planning to move to the modular botorch model setup and deprecate older model APIs such as `MultiObjectiveBotorchModel`, so ideally we wouldn't work on adding new features to it. The modular botorch model already implements `evaluate_acquisition_function` and so using that instead should work. 

@EvanClaes could you use the new modular botorch model setup instead? Here is a tutorial to get you started: https://ax.dev/tutorials/modular_botax.html

**Comment by EvanClaes** [comment]
Hello Max, Bernard,

Thanks for the feedback. I will try to make it work with the modular botorch setup.

I will open a new issue if I have any questions with regards to that (which is likely). You can close this one.

Thanks!
