### ISSUE TITLE
Missing SimpleExperiment

### ISSUE THREAD

**Issue by parkerwray** [facebook/Ax#858]
Hello, 

I have been using the SimpleExperiment module for some time, though this seems to no longer be supported. Can you help provide a solution such that old data can be re-evaluated  that was pickled as a SimpleExperiment? Also, can you advise on an alternative to the SimpleExperiment framework?

**Comment by bernardbeckerman** [comment]
Hi @parkerwray! `SimpleExperiment` was [recently deprecated](https://github.com/facebook/Ax/pull/766) - please use the [`Experiment`](https://ax.dev/api/core.html#experiment) abstraction from now on. There are a few different APIs for setting up and executing experiments ([loop](https://ax.dev/tutorials/gpei_hartmann_loop.html), [service](https://ax.dev/tutorials/gpei_hartmann_service.html, and [developer](https://ax.dev/tutorials/gpei_hartmann_developer.html), ordered from easiest to use to most granular control - my guess is that you might find the service API most useful).

As for un-pickling a `SimpleExperiment`, the only option I can think of is rewinding your local Ax fork to before the deprecation and building locally. I'll ask around internally in case there is a better way.

**Comment by lena-kashtelyan** [comment]
@parkerwray, we'll close this issue as inactive, but @bernardbeckerman's response above should take care of it. To reiterate, if you actually pickled your experiment, you might have to downgrade Ax to unpickle it. From there on, we suggest using our JSON storage (feel free to open a new issue if you still need help with it or if it doesn't work for your `SimpleExperiment`).

**Comment by shijiale0609** [comment]
Here is how the old version SimpleExperiment write.
from ax import SimpleExperiment

exp = SimpleExperiment(
    name="test_branin",
    search_space=search_space,
    evaluation_function=branin,
    objective_name="branin",
    minimize=True,
)
Now transfer to Experiment,
since evaluation_function and minimize are missing. 

How to write
exp = Experiment(

)

**Comment by Balandat** [comment]
@shijiale0609 if your use case is relatively straightforward (and could have been achieved with `SimpleExperiment `), I recommend you try the service API as described in this tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html

**Comment by shijiale0609** [comment]
> @shijiale0609 if your use case is relatively straightforward (and could have been achieved with `SimpleExperiment `), I recommend you try the service API as described in this tutorial: https://ax.dev/tutorials/gpei_hartmann_service.html


The problem is that SimpleExperiment function has been deleted from the current version.

**Comment by Balandat** [comment]
Indeed, that's why I'm suggesting to use the Service API instead.
