### ISSUE TITLE
Request for a feature. Please introduce the TrialStatus.PAUSED

### ISSUE THREAD

**Issue by alxfed** [facebook/Ax#862]
In many cases when the trial data are collected from an online log (or a sequence of events coming in real time) and metrics are calculated over the periods of time of a different duration (like Retention D1 and Conversion D2 with 2 days for the first and 3 days for the second necessary for calculation) it is advantageous to collect data related to _the same_ daily cohorts _only_. This can be done by starting a trial for a day, then pausing it until the metric with the longest duration can be calculated, then, after the intermediate evaluation - restarting the _same_ trial.
It can also be used for collecting small samples from a large stream of data periodically, let's say once a day for 5 minutes, then assessing the resulting data together, as a single Trial.

Subclassing works of course, but it is just logical to have it in the framework itself.

**Comment by alxfed** [comment]
The simplest way right now is to assign a property "Paused" to the Trial, if you want my take on this subject, 
...but I was just saying that you equipped the preparatory stage of the experiment with very useful states CANDIDATE and STAGED but didn't do similar job with the actual run in anticipation that somebody will be using your framework for real-time online experiments and will need this. That's all. I'm not seeking advice. Thank you.

**Comment by Balandat** [comment]
> This can be done by starting a trial for a day, then pausing it until the metric with the longest duration can be calculated, then, after the intermediate evaluation - restarting the same trial.

Is there a reason you want to restart the same *trial* rather than run another trial of the same *arm*? In Ax, the concept of a particular configuration to evaluate is linked to an arm, rather than a trial. In particular, the same arm can be evaluated in different trials. Doing this could simplify your setup. Do you think this would work for you?

**Comment by alxfed** [comment]
Max, yes, there _is_ a reason. The optimization config has multiple metrics with _different durations_ and individual weights. I'm optimizing this aggregate as a whole.

**Comment by lena-kashtelyan** [comment]
Hi @alxfed, thank you for the useful suggestion! We'll put it on our wishlist for now, but in the meantime it seems you have a simple workaround of writing to trial properties, so that's great.
