### ISSUE TITLE
define step-size for parameter range

### ISSUE THREAD

**Issue by hududed** [facebook/Ax#866]
When creating experiment, how do I go about creating a parameter with a range but with discrete intervals / step-size?
```
ax_client.create_experiment(
    name="hartmann_test_experiment",
    parameters=[
        {
            "name": "x1",
            "type": "range",
            "bounds": [10, 1000], # with step size 10
            "value_type": "int",
            "log_scale": False,
        },
       {
            "name": "x2",
            "type": "range",
            "bounds": [0, 1000], # with step size 20
            "value_type": "int",
            "log_scale": False,
        },
        ...
```

**Comment by danielcohenlive** [comment]
Thanks for the question, @hududed!  It looks like we don't have that feature currently, but I can offer 2 workarounds:
1) Use an integer range parameter and multiply the value by a constant on evaluation
2) Use a choice parameter and set `is_ordered` to True

**Comment by hududed** [comment]
I see - will this work for `np.arange` for floats too?

**Comment by danielcohenlive** [comment]
> Ok, where do I setup range parameter and where do I set the choice parameter?
 

It would look like:
```python
ax_client.create_experiment(
    name="hartmann_test_experiment",
    parameters=[
        # option 1
        {
            "name": "x1",
            "type": "range",
            "bounds": [1, 100], # with step size 10, multiply `x1` by 10 before evaluating
            "value_type": "int",
            "log_scale": False,
        },
        # option 2
        {
            "name": "x2",
            "type": "choice",
            "values": [10 * i for i in range(101)], # with step size 10, multiply `x1` by 10 before evaluating
            "is_ordered": True,
        },
        ...
```
>Will this work for np.arange for floats too?

Not quite sure what you mean by this, but I think you could accomplish this by assigning "values" to `[some_constant * i for i in range(N)]` with a choice param or `np.arange` (maybe with some type casting necessary).

**Comment by danielcohenlive** [comment]
I'm going to close this.  If you have any further questions please feel free to reopen it or create a new issue.

**Comment by Balandat** [comment]
> Use a choice parameter and set is_ordered to True

I would only recommend this if there are relatively few values and if the values are unevenly spaced. In all other cases you should use an integer parameter and scale things up to the right multiple on your end of the code. This will make it easier for Ax to build a good surrogate and optimize the problem well.
