### ISSUE TITLE
Pandas frame.append method being deprecated

### ISSUE THREAD

**Issue by farrokhsiar** [facebook/Ax#874]
Recently started to receive this warning:
`/lib/python3.8/site-packages/ax/service/utils/report_utils.py:440: FutureWarning:
The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.`

**Comment by danielcohenlive** [comment]
Thanks for pointing this out! https://github.com/facebook/Ax/pull/876
