### ISSUE TITLE
`InstantiationBase.make_objectives` does not set `metric.lower_is_better` correctly

### ISSUE THREAD

**Issue by lyhyl** [facebook/Ax#882]
`InstantiationBase.make_objectives` does not set `lower_is_better`, which causes https://github.com/facebook/Ax/issues/869.

`make_objective`:
https://github.com/facebook/Ax/blob/3f99a1a7857e72ed67f3bb1bfc09595a094cdf52/ax/service/utils/instantiation.py#L438-L441

`compute_posterior_pareto_frontier`:
https://github.com/facebook/Ax/blob/3f99a1a7857e72ed67f3bb1bfc09595a094cdf52/ax/plot/pareto_utils.py#L375-L378

A [PR ](https://github.com/facebook/Ax/pull/881) is made.

A temporary workaround:
```python
ax_client.experiment.optimization_config.objective.objectives[0].metric.lower_is_better = True
ax_client.experiment.optimization_config.objective.objectives[1].metric.lower_is_better = True
...
```

**Comment by lena-kashtelyan** [comment]
I believe we merged the PR for this, so marking as fixready. This will be part of the next stable release, too!
