### ISSUE TITLE
Allow for plotly>=3.9.0 dependency

### ISSUE THREAD

**Issue by OleMussmann** [facebook/Ax#89]
The installation of ax-platform breaks other installed packages like `plotly-express` that rely on `plotly>=3.9.0`.

During installation of `ax-platform`:
```
ERROR: plotly-express 0.2.0 has requirement plotly>=3.9.0, but you'll have plotly 2.7.0 which is incompatible.
```

**Comment by ldworkin** [comment]
Hi @OleMussmann -- this is currently in the works! Should be ready shortly.

**Comment by ldworkin** [comment]
Hi @OleMussmann -- this is in master now, and will be in our next release :)

**Comment by ldworkin** [comment]
Closing, since this should be in our current release (0.1.2)!
