### ISSUE TITLE
Are there asynchronous parallel examples?

### ISSUE THREAD

**Issue by deng-cy** [facebook/Ax#896]
I have a function that needs to be evaluate remotely
```
evaluate(parameter, server_id):
    # send `parameter` to server based on `server_id`
    return {'metric': (res, 0)}
```

For instance, I have 5 servers and want to optimize the metric in parallel. Currently the only way I could think of is to run the following :
```
import multiprocessing as mp
ps=[]
for i in range(5):
    parameters, trial_index = ax_client.get_next_trial()
    p = mp.Process(target=evaluate, args=(parameters, i))
    p.start()
    ps.append(p)
for i in range(5):
    ps[i].join()
    # retrieve data 
    ax_client.complete_trial(trial_index=trial_index, raw_data=retrieved_data)
```

This is actually synchronous, which is less efficient. Is there a way to construct an asynchronous parallel evaluation?

**Comment by sgbaird** [comment]
@deng-cy Have you taken a look at https://ax.dev/tutorials/raytune_pytorch_cnn.html?

**Comment by deng-cy** [comment]
Thanks for your reply. Yes I did, but I feel it is just a black box without telling how to assign `server_id`

**Comment by mpolson64** [comment]
Hi @deng-cy thank you for reaching out! Your use case may be a good candidate for our Scheduler API, which has a tutorial [here](https://ax.dev/tutorials/scheduler.html).

It involved a little more overhead to set up compared to the Service API, you will define a Runner object to send trials to your external system and Metric objects to retrieve the data once the trial has been run, but it gives you the ability to set maximum parallelism (among other settings) and allow Ax to handle scheduling, new point generation, and trial deployment and polling for you automatically.  Personally this is my favorite way of using Ax as it allows the user to "set it and forget it", which I find more than worth the effort in setting the Scheduler up for most experiments.

If you need any assistance setting this up or any other questions with your specific use case please feel free to continue to respond to this thread!

**Comment by deng-cy** [comment]
Thanks for your reply! I think Scheduler should work. But I felt it was too complicated since I need to write the whole class even if I only need to customize a little bit. I solved the issue by multiprocessing in Python with Server API.  

```
evaluate(parameter, server_id):
    # send `parameter` to server based on `server_id`
    q.put({'idx': trial_index, 'res': (metric, 0))}


n_result = 0
q = mp.Queue()
ps = []

for i in range(len(servers_id)):
    parameters, trial_index = ax_client.get_next_trial()
    p = mp.Process(target=evaluate, args=(parameters, servers_id[i], q, trial_index))
    p.start()
    ps.append(p)
while n_result < n_trials:
    res = q.get(block=True)
    n_result += 1
    ax_client.complete_trial(trial_index=res['idx'], raw_data=res['res'])

    for i in range(len(servers_id)):
        if ps[i].is_alive() == False:
            parameters, trial_index = ax_client.get_next_trial()
            p = mp.Process(target=evaluate, args=(parameters, servers_id[i], q, trial_index))
            p.start()
            ps[i] = p

```

**Comment by sgbaird** [comment]
@deng-cy nice job! I'll keep this in mind. I take it you meant Service API (not Server API), correct? Thanks for including a code snippet.

**Comment by deng-cy** [comment]
@sgbaird Yeah Service API, I corrected it.

**Comment by bernardo-suez** [comment]
This is great and I'm trying to use the code but have two questions:
1. Where the `server_id` list comes from?
2. Inside `evaluate`, how to I send the function evaluation to a server (I'm assuming the server can run on a core, no?) based on its `server_id`?
