### ISSUE TITLE
Reparameterizing compositional linear equality constraints as linear inequality constraints introduces Sobol sampling bias

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#903]
I've been struggling with this concept for a week or two and decided to surface this to the Ax devs in a fresh issue to get some suggestions and as a sanity check.

@bernardbeckerman offered [a very useful comment](https://github.com/facebook/Ax/issues/727#issuecomment-975644304) related to removing degenerate search space dimensions that I've been implementing:
> Brief drive-by comment regarding the constraints in this problem: @sgbaird correct me if i'm wrong, but you really only have 4 free parameters in this case, since the requirement that they sum to 1 removes a degree of freedom. For this reason, it might be useful for you to set a constraint:
> 
> ```
> "filler_A + filler_B + resin_A + resin_B <= 1"
> ```
> 
> and then for each parameterization `resin_C = 1 - (filler_A + filler_B + resin_A + resin_B)`.

I described the issue related to a bias in Sobol sampling in https://github.com/facebook/Ax/issues/727#issuecomment-1081315512:
> I realized that there is an issue with using Sobol sampling and the one-fewer-degrees-of-freedom style compositional constraint, and wanted to make a record of it in this issue.
> ##
> Take the case of:
> ```python
> x1+x2+x3 == 1
> ```
> reparameterized to:
> ```python
> x1+x2 <= 1
> ```
> where `x3 == 1 - x1 - x2`. When the Sobol candidates are generated, it is completely unaware of the original representation involving `x3` during the sampling. If the bounds on `x1` and `x2` are `[0,1]`, then it will preferentially favor the exploration of higher values of `x1` and `x2` than that of the unseen `x3`, if I'm not mistaken.

To illustrate, the bias in Sobol sampling towards the first two parameters might look something like the following, made-up data:
```
0.60, 0.30, 0.10
0.30, 0.60, 0.10
0.40, 0.40, 0.20
...
```

In https://github.com/facebook/Ax/issues/727#issuecomment-1086561847, I mentioned that retaining the original linear equality parameterization is probably the only way to prevent a bias in the Sobol sampling (and to some extent, possibly in the Bayesian iterations); however, this requires passing directly to BoTorch and manually implementing the underlying transforms https://github.com/facebook/Ax/issues/769#issuecomment-1024826291 @dme65.

For simple use-cases where anything/everything is allowed to range from `[0, 1]`, it might be OK to ignore the transforms. For more complicated cases that I'm dealing with where I have different bounds for parameters (e.g. `[0.1, 0.25]`) or the constraint isn't relative to `1.0` (e.g. `x_1 + x_2 <= 0.25 && x_1 + x2 >= 0.15`), I wonder if this will start causing issues.

**Comment by sgbaird** [comment]
xref: https://github.com/facebook/Ax/issues/786

**Comment by sgbaird** [comment]
@Balandat This is really helpful, thank you! [`sample_simplex`](https://github.com/pytorch/botorch/blob/ab04dd39a2d4c7734e41c5f26eb2dbba5b0e1771/botorch/utils/sampling.py#L270-L309) looks like it will help. I think one clarification is that I'm trying to sample from a simplex embedded in one higher dimension (in the case of 3 components as in the example, this means a triangle embedded in 3D space). I've dealt with PCA transformations and the like before (albeit in a different language), so I should be able to find the transformation from the vertices of the `d-1` simplex (i.e. hyperplane) embedded in `d` to the vertices of the *simplex* in `d-1` getting sampled via `sample_simplex`, and map the sampled points onto the hyperplane embedded in `d`. (where `d` and `d-1` referring to dimensions).

It's nice to see [`sample_polytope`](https://github.com/pytorch/botorch/blob/ab04dd39a2d4c7734e41c5f26eb2dbba5b0e1771/botorch/utils/sampling.py#L312) as well, thank you for linking to this. Let me know if there is an easier way than what I described above.

There are cases in materials science where it may not necessarily be a unit simplex (e.g. application of domain knowledge that `x1` should have tighter/different bounds than `x2`), at which point I imagine I would convert the vertices to matrix-form inequality constraints and pass them to `sample_polytope`.

**Comment by Balandat** [comment]
You can also give [DelaunayPolytopeSampler]9https://github.com/pytorch/botorch/blob/21ce6c7fa9fa907674c37b849e2e5dc683ca2682/botorch/utils/sampling.py#L697-L715) a try - This does uses a pretty cool algorithm to uniformly sample from a general Polytope (it supports equality constraints as well) by subdividing the whole polytope into primitive shapes and then uses their volume to build a two-stage sample process. There is some expensive upfront computation (the computation of the convex hull) but if you need lots of samples this can be worth it. Note though that the complexity grows quickly here so if you are in higher dimensions or have lots of complex constraints this can quickly get intractable.

**Comment by lena-kashtelyan** [comment]
Closing this issue as inactive; @sgbaird, please reopen it if you do follow up!

**Comment by sgbaird** [comment]
@Balandat quick follow-up. Any recommendations for if there are categorical parameters in the search space? Draw randomly? Convert to some numerical representation with equal distance between choices?

**Comment by Balandat** [comment]
Hmm good question. Sobol (and QMC methods in general) don't really play well with non-box bounds and non-continuous parameters. I would recommend just drawing those parameters independently at random and then stitch those together with the sobol samples of the rest of the space (or just do everything uniformly normal if you don't care too much about the low-discrepancy space filling properties of Sobol). 

You can also map the categoricals to integers and then use the approach from https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.integers.html#scipy.stats.qmc.Sobol.integers to get qMC-ish integer draws and then map those back to the categorical parameters.

**Comment by sgbaird** [comment]
@Balandat thanks! I wasn't aware of the integers method from `scipy.stats`. After looking at [the source code](https://github.com/scipy/scipy/blob/v1.10.1/scipy/stats/_qmc.py#L770-L850), it seems to just be an `np.floor(...)` method. In terms of setting up the search space and using existing machinery in Ax:
- specify the numerical type as `integer` within the search space
- use [`sklearn.preprocessing.OrdinalEncoder`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html) to do the mapping

**Comment by sgbaird** [comment]
> if you define the parameter as an integer in Ax itself, we'll try to model it as a numerical parameter; i.e. we'll assume that distance in the parameter values is related to distance in function values. Which is probably not what you want want for the modeling if your parameter are truly categorical (and unordered).

Good catch, thanks!

> So you could generate your custom initial random arms externally that doesn't involve the surrogate modeling, and then go from there in Ax. Or you could alternatively just use random sampling rather than Sobol sampling if the parameter constraints bias the sampling otherwise.

One clarification: Is it possible for the parameter constraints to bias the Sobol sampling because Sobol points are generated within the unconstrained design space and then limited to points within the feasible design space via a rejection strategy? (meaning you might get large, systematic gaps along certain "edges")
