### ISSUE TITLE
Invalid choice parameter example in the core.md file

### ISSUE THREAD

**Issue by Irynei** [facebook/Ax#91]
There is a small typo in the example of choice parameters in the [core.md](https://github.com/facebook/Ax/blob/master/docs/core.md) document. ChoiceParameter didn't have `value` param, instead, it is called `values`.

Currently:

```python
choice_param = ChoiceParameter(name="y", parameter_type=ParameterType.STRING, value=["foo", "bar"])
```

Should be:
```python
choice_param = ChoiceParameter(name="y", parameter_type=ParameterType.STRING, values=["foo", "bar"])

```

**Comment by kkashin** [comment]
Thanks for identifying that - will be fixed shortly: https://github.com/facebook/Ax/pull/92

**Comment by ldworkin** [comment]
Closing, since this should be in our current release (0.1.2)
