### ISSUE TITLE
Hypervolume Statistics in Service API

### ISSUE THREAD

**Issue by IgorKuszczak** [facebook/Ax#942]
Hello, 

I am working on a Multiobjective Optimisation using the Service API. It has been serving me well and I was wondering: is it possible to extract the hypervolume statistics within the API to track the convergence? I have seen how this can be done with the Developer API. However, I would prefer to keep my work within the simpler Service API.

**Comment by mpolson64** [comment]
Hi Igor-

As of our latest version you can retrieve the latest maximum hypervolume found with `AxClient.get_hypervolume`. Using this method you may specify an optimization config (if none is specified the config attached the the experiment will be used), trials to consider (if none are specified we will consider all trials), and whether or not to use the model predicted hypervolume (by default we do).

Let me know if this is what you were looking for or if you have any other questions.

**Comment by IgorKuszczak** [comment]
Hi @mpolson64, I have just tried applying this to a constrained MOO optimisation (simply using AxClient.get_hypervoluem()) and have encountered the following error:
```
[INFO 05-03 22:50:43] ax.modelbridge.base: Leaving out out-of-design observations for arms: 35_0, 57_0, 74_0, 49_0, 54_0, 14_0, 50_0
Traceback (most recent call last):
  File "C:/Users/igork/4YP/bayes-opt-for-ntopology/main.py", line 211, in <module>
    print(ax_client.get_hypervolume())
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\ax\service\ax_client.py", line 1398, in get_hypervolume
    use_model_predictions=use_model_predictions,
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\ax\service\utils\best_point_mixin.py", line 269, in _get_hypervolume
    modelbridge=model, optimization_config=optimization_config
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\ax\modelbridge\modelbridge_utils.py", line 1081, in predicted_hypervolume
    selected_metrics=selected_metrics,
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\ax\modelbridge\modelbridge_utils.py", line 1004, in hypervolume
    f_t = obj(f)
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\botorch\acquisition\objective.py", line 285, in __call__
    output = super().__call__(samples=samples, X=X, *args, **kwargs)
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\botorch\acquisition\multi_objective\objective.py", line 145, in forward
    samples = super().forward(samples=samples)
  File "C:\Users\igork\anaconda3\envs\bayes-opt-for-ntop\lib\site-packages\botorch\acquisition\multi_objective\objective.py", line 104, in forward
    return samples.index_select(-1, self.outcomes.to(device=samples.device))
IndexError: index out of range in self

Process finished with exit code 1
```

**Comment by lena-kashtelyan** [comment]
Hi @IgorKuszczak, which version of Ax are you on? If it's not the last one, would you mind updating it?

**Comment by IgorKuszczak** [comment]
Hi @lena-kashtelyan, it is the newest version. I have upgraded right before running the trials.

**Comment by lena-kashtelyan** [comment]
@IgorKuszczak, gotcha, seems like a bug. @mpolson64, is this the one you recently fixed? We might need to release a new minor version of Ax with the fix in that case!

**Comment by IgorKuszczak** [comment]
Hi @mpolson64, here is my attempt at a repro. For my use case, I am generating trials sequentially and running the simulations in parallel using concurrent.futures as shown below. I am also using a constraint metric. In the below code, I am taking most of the values from a configuration YAML file (`opt_config` in the code). Let me know if you need any of the specific entries from the configuration.
```
  ## Bayesian Optimization in Service API

  NUM_OF_ITERS = opt_config['num_of_iters']
  NUM_SOBOL_STEPS = opt_config['num_sobol_steps']

  BATCH_SIZE = opt_config['batch_size']

  # Generation strategy
  gs = GenerationStrategy(steps=
                          [GenerationStep(model=Models.SOBOL, num_trials=NUM_SOBOL_STEPS),
                           GenerationStep(model=Models[opt_config['model']],num_trials=-1,max_parallelism=3)])

  # Initialize the ax client
  ax_client = AxClient(generation_strategy=gs, random_seed=12345,
                       torch_device=torch.device("cuda"),
                       enforce_sequential_optimization=False, 
                       verbose_logging=True)

  # Define parameters
     params = opt_config['parameters']

 # Creating an experiment

    ax_client.create_experiment(
        name=opt_config['experiment_name'],
        parameters=params,
        objectives={i['name']: ObjectiveProperties(minimize=i['minimize'], threshold=i['threshold']) for i in
                    objective_config['objective_metrics']},
        outcome_constraints=opt_config['outcome_constraints'],
        parameter_constraints=opt_config['parameter_constraints'])

  # Initializing variables used in the iteration loop

  abandoned_trials_count = 0 # counter for abandoned trials
  
  # list containing batch sizes for each trial
  # Below variables represent tuples of quotients and remainders
  SoB = divmod(NUM_SOBOL_STEPS,BATCH_SIZE) # sobol steps / batch size
  ToB = divmod(NUM_OF_ITERS-NUM_SOBOL_STEPS,BATCH_SIZE) # remaining iters/ batch size
  
  batch_size_list  = (SoB[0])*[BATCH_SIZE] + [SoB[1]] + (ToB[0])*[BATCH_SIZE] + [ToB[1]]
  
  # removing entries equal to 0
  batch_size_list = [i for i in batch_size_list if i!=0]
   
  NUM_OF_BATCHES  = len(batch_size_list)

  for i in range(NUM_OF_BATCHES):
      try:
          results = {}
          trials_to_evaluate = {}

          # Sequentially generate the batch
          for j in range(batch_size_list[i]):
              parameterization, trial_index = ax_client.get_next_trial()
              trials_to_evaluate[trial_index] = parameterization

          # Evaluate the results in parallel and append results to a dictionary
          with concurrent.futures.ProcessPoolExecutor(max_workers=None) as executor:
              futures_to_idx = {executor.submit(sim.get_results, parametrization,trial_index):trial_index for trial_index,
                                parametrization in trials_to_evaluate.items()}
                                   
                          
              # go through completed trials and update the results dictionary          
              for future in concurrent.futures.as_completed(futures_to_idx):
                  trial_index = futures_to_idx[future]
                  try:
                      results.update({trial_index: future.result()})
                  except Exception as e:
                      ax_client.abandon_trial(trial_index=trial_index)
                      abandoned_trials_count += 1
                      print(f'[WARNING] Abandoning trial {trial_index} due to processing errors.')
                      print(e)
                      if abandoned_trials_count > 0.1 * NUM_OF_ITERS:
                          print(
                              f'[WARNING] Abandoned {abandoned_trials_count} trials. Consider improving the '
                              f'parametrization.')                       
          
          # update the ax_client with results
          for trial_index in results:
              ax_client.complete_trial(trial_index, results.get(trial_index))

      except KeyboardInterrupt:
          print('Program interrupted by user')
          break
```
The final step is of course `ax_client.get_hypervolume()`.

**Comment by mpolson64** [comment]
Thanks for posting this. I'm going to ask @sdaulton and @dme65 to take a look at this as well.

The general setup looks exactly right to me, though it would be helpful to know the values of opt_config['model'], opt_config['num_of_iters'], opt_config['num_sobol_steps'], and opt_config['batch_size']

**Comment by IgorKuszczak** [comment]
I was running trials with the MOO model for 100 iterations, with 10 Sobol steps, and an intended batch size of 3.

**Comment by sdaulton** [comment]
My hunch is that there are no designs that satisfy the outcome constraints and are better than the objective thresholds. This would lead to `f` being an empty tensor in `f_t = obj(f)` in ax\modelbridge\modelbridge_utils.py", line 1004, in hypervolume.

**Comment by mpolson64** [comment]
Great intuition Sam! This reproduced the issue on my end perfectly.
Igor, we will look into adding some more descriptive error messages in the next release. In the mean time it may be best to see if you can relax your outcome constraints at all OR you may use `ax_client.get_hypervolume(use_model_predictions=False)` which will not run into the same issues, though you will still have the problem of your outcome constraint being violated by the pareto optimal points.
Does this answer your question?

**Comment by mpolson64** [comment]
While you could use repeated calls to `get_hypervolume` to do this you could also use the newly implemented `get_trace` as defined here. Given an experiment and MOO experiment this will give you a List where the element at i is the hypervolume after i trials. You may plot this with whatever python plotting framework you would like.

**Comment by IgorKuszczak** [comment]
Yes, thank you for the help.
