### ISSUE TITLE
How to extract Pareto optimal parameters in constrained MOO?

### ISSUE THREAD

**Issue by IgorKuszczak** [facebook/Ax#949]
Hello, 
I am using Ax's Service API for constrained multiobjective optimisation. I have recently run into a problem where applying `get_pareto_optimal_parameters()`  returns an error message stating that this functionality is still under development for the constrained optimisation. I was wondering if there are any workarounds which  I could use to at least approximate the optimal point in the optimisation. I was considering applying the simple TOPSIS algorithm to points generated with the `compute_posterior_pareto_frontier` (excluding the out-of-design points) to find the best point in two objectives and then extracting the correspondent parameterisation. Is this a feasible approach? If so, how could I associate a point in the frontier with a parametrisation?

**Comment by lena-kashtelyan** [comment]
@IgorKuszczak, if you wanted to just grab contents of this function: https://github.com/facebook/Ax/blob/main/ax/service/utils/best_point.py#L466 and remove the check about outcome constraints: https://github.com/facebook/Ax/blob/main/ax/service/utils/best_point.py#L522 and seeing what happens?
For inputs to that function, you can just do this: `get_pareto_optimal_parameters(ax_client.experiment, ax_client.generation_strategy)`.

Let me know whether that works for your use case and feel free to put up a PR removing that error if things do look good!

**Comment by lena-kashtelyan** [comment]
Also cc @sdaulton on this

**Comment by IgorKuszczak** [comment]
@lena-kashtelyan, I removed the outcome constraints check and it resulted in an empty dictionary as an output with no extra errors. Is this the expected behaviour here?

**Comment by bernardbeckerman** [comment]
@IgorKuszczak are you using objective thresholds in your multi-objective optimization config? If so, do any of your experiment's arms exceed all objectives? If no arms exceed the thresholds for all objectives, there might be zero points on the Pareto curve. Please let me know if it looks like this may be the case.

**Comment by IgorKuszczak** [comment]
Hi @bernardbeckerman, I am using thresholds in both objectives:  0.9 for the 'displacement' (minimized) and 30 for the 'weight_savings' (maximized). As you can see on the below picture where consecutive evaluations are plotted, there are multiple arms which exceed all objectives.
![image](https://user-images.githubusercontent.com/41329306/166800309-31ec8d42-ded5-458b-afed-b4d827c49cbc.png)

**Comment by IgorKuszczak** [comment]
Interestingly, I am able to get soem results with the same code when I set `use_model_predictions` to False.

**Comment by bernardbeckerman** [comment]
That's interesting that the code returns all arms when `use_model_predictions=False`! Can you include the cross-validation plot for each variable? (see example 4 [here](https://ax.dev/tutorials/visualizations.html).) Also the `interact_fitted` plot (example 6 from that tutorial) might be useful here as well.

**Comment by lena-kashtelyan** [comment]
I believe this is waiting on a repro, @IgorKuszczak. Is this still an active issue or can we close it?

**Comment by lena-kashtelyan** [comment]
Gonna close this one for now as inactive; please reopen if you follow up, @IgorKuszczak!
