### ISSUE TITLE
Custom Runner in Scheduler API with using __init__ to provide additional arguments for deployment

### ISSUE THREAD

**Issue by mango-picket** [facebook/Ax#952]
Hi, 

Is it possible to see an example for defining custom Runner in Scheduler API with using __init__ to provide additional arguments for deployment. Currently the example provided at https://ax.dev/versions/0.1.1/docs/runner.html (for the asynchronous case) is not correct I think since it doesnt call self.foo_param during deployment call. I raise this as a question because the scheduler API seems to work buggily (at least in my implementation) if I follow the example and add self.foo_param myself. Therefore, I wanted to see a better example before I attribute it as an issue

**Comment by bernardbeckerman** [comment]
Hi @mango-picket, thanks for raising this here! I think you're right - it should be 

```
        run_metadata = deploy_to_foo(self.foo_param, name_to_params)
```

instead of 

```
        run_metadata = deploy_to_foo(foo_param, name_to_params)

```

Is that what you meant?

Also, I believe you mentioned that even after you make this change, the runner works buggily - can you tell me more about that?

**Comment by mango-picket** [comment]
Hi Bernard,
1) Yes this is what i was referring to in the documentation.
2) The bug that I am observing is that the scheduler API passes the same parameters to deployment for each trial when I pass additional arguments for deployment by defining the __init__ function. If I manually (without defining the Runner __init__) pass the additional arguments, then the scheduler API works perfectly and passes a new set of parameters for deployment at each trial. 

For eg. Assume a generation strategy of 5 SOBOL trials followed by many GPEI trials. The following code results in the scheduler to suggests the same point for deployment for all trials 1-5 (even though it generates new points for each trial).

```
def runner(Runner):
        def __init__(self, foo_params):
               self.foo_params = foo_params

        def run(self, trial):
               foo_params = self.foo_params # dictionary of additional arguments required for deployment
               job_queue = get_job_queue()
               job_id = job_queue.schedule_job_with_config(
                             config=foo_params.update(trial.arm.parameters)
               )
```

The same code where I manually provide foo_params dictionary and do not pass it via with the __init__ works correctly wherein the scheduler passes unique points for each trial to deploy.

**Comment by bernardbeckerman** [comment]
@mango-picket thanks for the added detail. I'll recreate locally tomorrow morning to investigate.

**Comment by bernardbeckerman** [comment]
@mango-picket I just noticed that the docs you're linking are from an old version of Ax (0.1.1). I would recommend using [this updated example](https://ax.dev/docs/trial-evaluation.html) and updating your Ax version if necessary. Please let me know if that helps.

**Comment by bernardbeckerman** [comment]
@mango-picket I'm closing this out since it's been a few days but please feel free to re-open if you have any further issues!

**Comment by mango-picket** [comment]
Hi Bernard, Sorry for the late reply. Thanks for guiding me to the updated documentation, however I already tried attempting the method described there. Kindly see this colab notebook to reproduce the bug: https://colab.research.google.com/drive/1TWnIeO-T9KLoATP-F_5lYfX30hfcJSTa#scrollTo=ejLUPExD62IK

**Comment by bernardbeckerman** [comment]
Thanks for this example! Reopening this issue now and looking into it.

**Comment by mango-picket** [comment]
oh wow, that indeed did the trick, thanks for your quick response. Is it also possible to know how I can receive the model for visualization from the scheduler API? and the experiment object if I am using model resumption? this could be a new cell at the end of the notebook and will help me immensely since I am unable to find the documentation on

**Comment by bernardbeckerman** [comment]
Closing this out since it seems like the main issue has been addressed but please comment if anything still seems wrong!
