### ISSUE TITLE
[Question] UCB acquisition function

### ISSUE THREAD

**Issue by farrokhsiar** [facebook/Ax#955]
Looking at the on the ready to use methods in AX, without the need to create BoTorch models, I can't find the UCB acquisition function. Any replacement for UCB? if not, how should I import it from BoTorch?

**Comment by lena-kashtelyan** [comment]
Hi @farrokhsiar, to use UCB you'd use the modular `BoTorchModel` (aka MBM) setup we provide (see a quick-start example here: https://ax.dev/tutorials/modular_botax.html#1.-Quick-start-example). To use it as part of a generation strategy (if looking to configure the model used by Ax Service API), refer to this section of the MBM tutorial https://ax.dev/tutorials/modular_botax.html#5.-Utilizing-BoTorchModel-in-generation-strategies. You should be able to use the generation strategy specified in that section pretty much verbatim, just replace `qNoisyExpectedImprovement` with `qUpperConfidenceBound` (imported from `botorch`).

Then, you can pass the generation strategy to `AxClient` like so: `ax_client = AxClient(generation_strategy=my_custom_ucb_gs)` (also suggested here: https://ax.dev/tutorials/gpei_hartmann_service.html#4.-Run-optimization-loop).

I realize this is not exactly "without the need to create BoTorch models", but I hope that helps : )

**Comment by farrokhsiar** [comment]
Thanks, Lena. This was very helpful.
