### ISSUE TITLE
Re-Open Custom Runner in Scheduler API deploys same arms for multiple trials when passing additional arguments via __init__

### ISSUE THREAD

**Issue by mango-picket** [facebook/Ax#974]
Hi Bernard, Sorry for the late reply. Thanks for guiding me to the updated documentation, however I already tried attempting the method described there. Kindly see this colab notebook to reproduce the bug (I use the  Branin experiment provided in the scheduler API guide for this): https://drive.google.com/file/d/1Yha7rvM2bz9gjlexy5RVB2d1VfB5Tapg/view?usp=sharing

My observations: The scheduler deploys same arms for first few trials (probably for SOBOL generation strategy)
I currently worked around the bug by passing constant variables from the global scope however my solution will not be able to scale for the intended functionality of the scheduler API

_Originally posted by @mango-picket in https://github.com/facebook/Ax/issues/952#issuecomment-1131257247_

**Comment by bernardbeckerman** [comment]
Thanks for your reply! I've reopened the original issue - let's please continue the discussion there : )
