### ISSUE TITLE
Can't install latest from git

### ISSUE THREAD

**Issue by crasanders** [facebook/Ax#984]
When I run the command from the readme to install the latest version, `pip3 install git+ssh://git@github.com/facebook/Ax.git#egg=ax-platform`,  I get the error 

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by danielcohenlive** [comment]
@crasanders thanks for the question.  Do you currently have [github ssh authentication](https://docs.github.com/en/authentication/connecting-to-github-with-ssh) set up?  I think that may be necessary even though its not in our docs.  Also, can you pip install from other OSS git repos?

**Comment by Balandat** [comment]
You should also be able to just use https instead of ssh to grab this from github: 
```
pip install git+https://github.com/facebook/Ax.git#egg=ax-platform
```
@danielcohenlive we should probably update the readme with that

**Comment by crasanders** [comment]
> ```
> You should also be able to just use https instead of ssh to grab this from github:
> ```
This worked; thank you!
